### ISSUE TITLE
Ajouter la recherche des types de POIs

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#103]
je relaye la demande d'un utilisateur :

> Merci mais du coup les categories qui sont dans le menu de gauche ne correspondent pas notamment pour les plombiers, cordonniers etc... est-il possible d'envisager une recherche textuelle ?

**Comment by PanierAvide** [comment]
Cf aussi #117

**Comment by PanierAvide** [comment]
Au final on en a beaucoup parlé de cette histoire de recherche de POIs, mais rien n'a été implémenté. De souvenir la dernière solution évoquée c'était d'afficher des badges une fois qu'une catégorie a été sélectionnée. On part là-dessus ? On affiche où ces badges (par dessus la carte, ailleurs) ?

**Comment by caugner** [comment]
Here's a simple solution:

1. When a category is selected, show a "category" line below with all the icons belonging to the subcategories (horizontally scrollable, if necessary).
2. Optional: When a subcategory is selected, show the icon and title of the subcategory in that line.
3. Optional: When a selected subcategory is selected again, show all the subcategory icons again.

**Comment by wadouk** [comment]
Instead of subcategory, i will speak directly about "main tag" shop=bakery shop=butcher ... 
should display it as cloud tag like opening the category will show all tags that include

**Comment by caugner** [comment]
Just to check: You suggest to display a tag cloud with the *technical* tags of the subcategories? For a user without OSM background, this might be confusing.

On the other hand, `categories.json` already defines subcategories, and we have both icons and translated descriptions for these.

**Comment by PanierAvide** [comment]
Yes I think we should keep concept of subcategories, as we group together different OSM tags (tobacco = shop=tobacco + tobacco=yes + shop=tobacco;newsagent...).

**Comment by wadouk** [comment]
Of course making some translation between OSM language and human language.
Not displaying tag directly but something that exactly match the same cardinality. Sub-category and tags are too different things in categories.json. I don't see/understand the need of that. Making the difference between post office and vending machine is not mandatory and could be great to understand what the POI you are looking for, what could be expected when going to this place (between a machine and an office).

**Comment by overflorian** [comment]
I don't think we'll spend more time to fix the search result, will we? We should close this issue.
