### ISSUE TITLE
Expand "Ca reste ouvert" outside France

### ISSUE THREAD

**Issue by vdct** [osmontrouge/caresteouvert#106]
Enable selected coverage

- [x] load the planet on the server **in progress**
- [x] Add the country code to each POI
- [x] Update the update script to have a whitelist of countries
- [x] Insert only POI from the whitelist 
- [ ] Adapt the frontend to load the categories depending of the country displayed
- [x] Adapt geocoder results

**Comment by overflorian** [comment]
(@vdct comment elle claque ta request ^^)

**Comment by PanierAvide** [comment]
Voir #107

**Comment by francois2metz** [comment]
La base est en ligne. Je clos et crée un nouveau ticket pour les catégories coté client.
