### ISSUE TITLE
Attribution sur la version responsive

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#109]
En version mobile, on a le petit i qui cache l'attribution osm, je pense qu'il faut l'avoir en mode déployé.

![Screenshot_20200401-093925](https://user-images.githubusercontent.com/890869/78113250-be03db80-73ff-11ea-9c12-6186628e9c1d.jpg)

**Comment by francois2metz** [comment]
Il me semblait que c'était acceptable de de le présenter comme cela. Mais je n'ai pas retrouvé cela dans la licence.

**Comment by vinber** [comment]
Les discussions qu'il peut y avoir en particulier avec MapBox, Facebook et d'autres utilisateurs d'OSM porte souvent sur cela. Pourquoi y-t-il la place pour le logo de la structure dans les versions mobiles mais pas pour la mentions @contributeurs opensreetmap en mode dépliée ?

Concernant l'aspect légal, je ne suis pas juriste donc acceptable peut-être (mais même sur cela il ne semble pas y avoir un consensus de lecture de la licence) mais faisons d'autant plus la promotion :) et je sais que nous souhaitons tous faire la promotion d'OSM.

**Comment by francois2metz** [comment]
Fait dans dde34cddb670f5fcae7e2bc16df2c4078f4cd696.
