### ISSUE TITLE
La sidebar est pas claire / trop longue

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/caresteouvert#112]
Ceci est une issue un peu générale pour discuter des évolutions a apporter a la sidebar.

Actuellement la sidebar ressemble a cela:
![Screenshot_2020-04-01 Ça reste ouvert(1)](https://user-images.githubusercontent.com/86659/78127070-cf56e300-7413-11ea-9416-2debed38669e.png)

Voici quelques idées que j'ai en tête:

Logo:
- réduire le logo en hauteur pour utiliser la version large (et dans le futur le rendre localisable)

Catégories:
- Comprendre le point de #103 
- Ajouter un filtre pour la livraison #92 
- Déplacer les services funéraires dans Autre Établissement

Liens:
Pas très clair pour moi encore.  Je supprimerai bien le lien Mairies pas très compréhensible.
On pourrait aussi réduire sensiblement la hauteur de chaque lien.

**Comment by PanierAvide** [comment]
Idée pour les liens : dans la sidebar, juste un bouton "à propos" qui affiche une boîte de dialogue avec une phrase courte de ce qu'est le site + les liens divers qu'on a actuellement

**Comment by francois2metz** [comment]
On garde "A propos" et "Changer la langue" du coup ? Ca me parait bien. On pourra structurer un peu mieux cette boite avec une partie contribution (#15 ?) et ce qui touche au site en lui même.

**Comment by francois2metz** [comment]
On pourrait enlever le bandeau d'alerte aussi. C'est un peu anxiogène.

**Comment by PanierAvide** [comment]
Le bandeau j'aurais tendance à laisser, c'est la garantie qu'on est pas là pour inciter à sortir inutilement. Anxiogène mais on montre patte blanche
