### ISSUE TITLE
Jours d'ouverture : raccourcis (Lun-Ven, Lun-Sam, Lun-Dim)

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#115]
Beaucoup de magasins ont le même horaire pour plusieurs jours. Jusqu'ici, il faut cocher tout les jours l'un après l'autre. Il serait donc util de proposer quelques raccourcis, notamment :

* Lundi à Vendredi
* Lundi à Samedi
* Lundi à Dimanche

**Update**: Sinon on pourrait aussi supporter utiliser <kbd>Shift</kbd> pour selectionner plusieurs jours en un clique, mais les raccourcis visibles seraient plus facils à découvrir (et marchent sur mobile !).

**Comment by overflorian** [comment]
Autre suggestion liée : factoriser également les jours pour mettre à jour les horaires déjà existants.

**Use case :** une boutique est marquée ouverte du lundi au vendredi de 7h30 à 20h.
De nouveaux horaires sont mis en place : 8h à 20H du lundi au vendredi.
Comportement actuel : supprimer un à un tous les jours créés, puis recréer les jours.
Comportement possible : sélectionner la planche horaire applicable à tous ces jours, ne changer que l'horaire de début, l'appliquer à tous les jours d'un coup. Ux précise à réfléchir

PS : cette suggestion n'est à prioriser que si les MAJ de données sont importantes. A vérifier dans les stats

**Comment by caugner** [comment]
D'un part, oui, ce serait utile, surtout par rapport au horaires des jours fériés qui ne sont normalement pas affichées.

D'autre part, cela risque que l'utilisateur mélange les anciennes données avec les nouvelles. Sauf si on a une workflow où on montre le dialog avec les jours déjà coché

À mon expérience, beaucoup de lieux n'ont pas actuellement des horaires. Pour eux, les raccourcis aident énormément et je pourrait quasiment enregistrer touts les lieux que je passe sans m'arrêter.

**Comment by caugner** [comment]
Au lieu de montrer les jours directement, on pourrait aussi montrer d'abord les raccourcis et une option "Autre" qui fait apparaître les checkboxes.
