### ISSUE TITLE
Gérer les catégories en base de données

### ISSUE THREAD

**Issue by PanierAvide** [osmontrouge/caresteouvert#117]
Je lance le sujet : comment gérer de manière centralisée et efficace les catégories de points que l'on affiche. Actuellement, les catégories sont mobilisées dans :
* Les filtres de la carte et la base de données : catégories _normalisées_
* Les symboles sur la carte + nom de catégorie dans le panneau de droite : _catégories issues d'OSM_ (amenity, shop, office, craft)

Je pars du principe qu'on doit garder les deux : dans la rubrique "alimentation", on a envie de distinguer le supermarché du magasin à la ferme, dans "tabac" le magasin de e-liquides du bar/tabac. On peut désormais parler de __catégories__ et __sous-catégories__.

Pour assurer leur centralisation, les catégories et sous-catégories sont à gérer côté serveur : on doit pouvoir décliner une seule source en plusieurs fichiers/mécanismes.
* Table dans PostgreSQL pour faire le lien OSM -> nos catégories/sous-catégories
* Fichier JSON pour l'interface web
* Fichier JSON pour la traduction des libellés
* Fichier YAML pour Imposm
* ... et sûrement autre chose

Idéalement, on a envie que la modification d'un seul fichier se répercute automatiquement partout, sinon ça va être à terme un enfer à gérer. La question est donc : où placer le fichier de référence ? Dans PostgreSQL ? Sous forme d'un fichier JSON ? Ou un CSV ? Question ouverte, pas sûr de la réponse à apporter.

Autres aspects à gérer plus tard :
* Déclinaisons des règles par pays (statut par défaut, afficher ou pas les lieux...)

**Comment by francois2metz** [comment]
J'ai commencé a y réfléchir, surtout du point de vue de l'internationalisation.

- Je propose un format pivot autour d'un YAML (ou whatever) similaire a cela: https://github.com/osmontrouge/caresteouvert/commit/2be4fe10dad2e8e000f3d2c59bb311bed131080e
- ce format pivot permet de générer la fonction postgres (code à écrire)
- ce fichier yaml est directement chargeable par l'interface web
- pour imposm, comme on ne filtrer quasiment rien, j'ai l'impression qu'on a rien a faire
- pour les libellé dans l'interface, on peut écrire un moulinette pour les synchro avec le yaml

**Comment by PanierAvide** [comment]
J'étais en train de partir sur un modèle en JSON (mais ça peut être YAML, peu importe), avec quelques détails en plus pour chaque entrée

```json
{
	"healthcare": {
		"name": { "en": "Healthcare", "fr": "Santé" },
		"subcategories": {
			"pharmacy": {
				"name": { "en": "Pharmacy", "fr": "Pharmacie" },
				"osm_tags": [ { "amenity": "pharmacy" } ],
				"countries": [ "FR", "GB" ]
			},
			"clinic": {
				"name": { "en": "Clinic", "fr": "Clinique" },
				"osm_tags": [ { "amenity": "clinic" }, { "healthcare": "clinic" } ],
				"countries": [ "FR" ]
			}
		}
	},
	"food": {...},
	"shop": {...},
	"amenity": {...},
	"transport": {..}
}
```

Ça rend possible l'internationalisation, le choix des tags +/- variés, les conditions d'affichage par pays...

**Comment by francois2metz** [comment]
On mettrait tout dans un seul fichier ? pourquoi pas. j'éviterais de mettre les traductions dedans pour utiliser la même mécanique qu'actuellement.

**Comment by PanierAvide** [comment]
Après comment on refait le lien entres les catégories et les traductions ? Une approche que j'avais utilisé c'était un script maison qui sort les chaînes à traduire pour en faire un fichier pour Transifex, et inversement une moulinette pour réintégrer dans le fichier commun. Cf https://framagit.org/PanierAvide/osminedit/-/blob/master/presets_extract_labels.js et https://framagit.org/PanierAvide/osminedit/-/blob/master/presets_merge_labels.js

**Comment by francois2metz** [comment]
oui on sort les clefs à traduire du fichier json et on les réinjecte dans le fichier json des locales (la version `en` du coup).

**Comment by PanierAvide** [comment]
Ça peut être ça oui, je vais m'en occuper

**Comment by PanierAvide** [comment]
Du coup en base de données, pour chaque POI, on lui associe juste sa sous-catégorie, ou catégorie + sous-catégorie ? C'est selon ce qu'on prévoit pour le client : ce sera lui qui refera le lien entre chaque sous-catégorie et la catégorie parente (sur la base de `categories.json`), ou on veut que ce soit en dur en base (pour les tuiles vectorielles notamment ?).

**Comment by francois2metz** [comment]
Je me disais qu'on allais traiter les POIs avec leur catégorie par pays. Et donc on ne traite que les POIs FR avec leur catégorie grâce au fichier FR, puis on traite les POIs de ES, puis .... De cette façon on n'est pas obligé de trouver une intersection dans les catégories, chacun fait sa vie.

**Comment by francois2metz** [comment]
Je pense que l'on a besoin de discuter ;)

**Comment by PanierAvide** [comment]
Après discussion, on part donc sur :
- Liste `all` des pays en mode liste blanche
- Traductions à peut-être que sortir de categories.json et pas réinjecter

**Comment by PanierAvide** [comment]
Solved by #124
