### ISSUE TITLE
Intégrer les données de livraison pour Paris

### ISSUE THREAD

**Issue by wadouk** [osmontrouge/caresteouvert#120]
La [mairie de Paris](https://www.paris.fr/pages/livraison-alimentaire-a-domicile-les-commercants-parisiens-mobilises-7685) propose aux commerçants de renseigner s'ils livrent.

C'est aussi dispo en [open data](https://www.data.gouv.fr/fr/datasets/coronavirus-commercants-parisiens-livraison-a-domicile/)

Ça ajouterais de la donnée pour https://github.com/osmontrouge/caresteouvert/issues/92

**Comment by caugner** [comment]
La liste comprend aussi des restaurants.
Pourtant les restaurant ne sont actuellement pas affichés sur la carte.

**Comment by wadouk** [comment]
sur le site de paris ? y a une option restaurant et traiteur

**Comment by caugner** [comment]
> Pourtant les restaurant ne sont actuellement pas affichés sur la carte.

Sur https://www.caresteouvert.fr/

**Comment by wadouk** [comment]
Oups, ah oui j'ai vu un traiteur qui marque sur son site qu'il n'accueil plus de publique mais qui est sur epicery donc qui a l'air de faire juste des livraisons. c'est un moyen de garder une activité en limitant le nombre de personnes au point de vente.

**Comment by francois2metz** [comment]
On prend on prend ! Pour les restaurant on peut mettre `takeway:covid19=only`, et on pourra toujours les traiter a part.

**Comment by PanierAvide** [comment]
Si on a un `opening_hours:covid19` de renseigné sur un resto, il ressort sur ça reste ouvert. À nous d'améliorer l'affichage pour que ce soit clair qu'il n'est qu'en livraison avec le tag `takeaway:covid19=only`, cf #92

**Comment by caugner** [comment]
> Pour les restaurant on peut mettre `takeway:covid19=only`, et on pourra toujours les traiter a part.

Pour l'instant, on ne peut ajouter cette info que directement dans OSM, c'est ca ? Une meilleure auto-complétion qui propose aussi les restaurants (non-affichés) pourrait aider à cet effet.

**Comment by caugner** [comment]
@wadouk As-tu pensé plutôt à une import automatisée ou à les intégrer manuellement ?

**Comment by wadouk** [comment]
plutôt quelque chose de récurent et automatique parce que ça peut changer régulièrement mais peut être une validation humaine type osmose ou maproulette parce que les imports dans OSM sans donnée qualifié/validé c'est mal ?

**Comment by wadouk** [comment]
Pour m'aider j'ai [fais ça](https://github.com/wadouk/opendata-paris-commerces-ouvert-covid19-vers-osm/blob/master/out.geojson) avec le petit bout de [nodejs](https://github.com/wadouk/opendata-paris-commerces-ouvert-covid19-vers-osm/blob/master/in.js) à partir de la version json (qui contient des IDs et des dates, que j'imagine utiliser pour faire des diffs plus tard)

**Comment by wadouk** [comment]
Mais me rends compte que j'ai pas mis de `takeaway:covid19` ou de `delivery:covid19`, juste `opening_hours:covid19` ce qui est pourtant le sens du jeu de données.
Me tâte à faire un mailing au commerçant pour les prévenir de la réutilisation.

**Comment by pyrog** [comment]
Pas `contact:mail` mais `contact:email`, et aussi `email`(plus utilisé)
Pas `contact:tel` mais `contact:phone`, et aussi `phone`(plus utilisé)

` source` à mettre dans le changeset plutôt qu'à chaque objet.
`source:last-modification`, `source:id` je ne vois pas l'intérêt de stocker ça dans OSM ?
Tu peux garder ça dans ton serveur et indiquer l'ID de l'objet OSM si tu en as besoin ?

`opening_hours:covid19=same` le fichier ne le précise pas 😉

**Comment by wadouk** [comment]
@pyrog le `opening_hours:covid19=same` c'était pour préciser au moins une info covid. 
Sur la pharmacie faite, je ne trouve aucune info de livraison sur internet, va falloir que je les contacts si je veux faire ça bien.
les deux infos source, c'est pour un détail pour plus tard mais plus tard, donc je shoot.
les 2 contacts, corrigés, merci l’œil du tigre

**Comment by pyrog** [comment]
🐯 😆 

> `opening_hours:covid19=same` c'était pour préciser au moins une info covid

Je comprend ton idée 😄, mais c'est au contributeur/intégrateur de définir sa valeur.
A moins que tu arrives à le préciser (je ne me rappel plus du détail des données).

**Comment by francois2metz** [comment]
Sans détails sur les heures, la façon actuelle est de mettre `opening_hours:covid19=open`

**Comment by wadouk** [comment]
Mailing fait


------
Bonjour,

J'ai trouvé votre adresse de courrier électronique dans le fichier mis à disposition par la mairie de Paris des commerçants faisant des livraisons pendant le confinement https://opendata.paris.fr/explore/dataset/coronavirus-commercants-parisiens-livraison-a-domicile.
Je vous contact au titre de contributions pour OpenStreetMap. OpenStreetMap est une base de données géolocalisée collaborative mondiale et surtout libre. Une des utilisations est "comme google maps" une carte sur https://www.openstreetmap.org/. Une autre utilisation mets en valeur les commerçants toujours ouvert https://www.caresteouvert.fr.

Je vous contact afin de mettre à jour cette base de données avec les informations mises en à disposition par la Mairie de Paris.

Pourriez-vous me confirmer si :
 - vous êtes toujours ouvert
 - vous pratiquez des livraisons
 - vous pratiquer de la vente à apporter
Éventuellement
 - vos horaires habituels
 - vos horaires éventuellement adapté à cette période de confinement
 - téléphone
 - site web
 - mail j'ai déjà

Il n'y a aucune obligations à tout ça.

Ces questions ne sont pas forcément exclusives : vous pouvez livrer sans être ouvert.
Votre commerce est peut être déjà dans OpenStreetMap. Vous pourrez si vous le souhaitez compléter, corriger, effacer ces données. Je pourrais vous y aider tout comme le reste de la communauté OpenStreetMap http://www.openstreetmap.fr/.

Merci d'avance pour votre aide.
Salutations

**Comment by pyrog** [comment]
> vous pratiquer de la vente à apporter

vous **pratiquez** de la vente à **emporter** 😉 😄 

> site web

Je cherche à chaque intégration, mais si tu en as beaucoup, le mél est peut-être plus rapide 😄

**Comment by wadouk** [comment]
j'ai relu mais j'ai laissé passer des trucs effectivement. Il y en a un qui vient de mettre un point d'interrogation à cette question, les autres sont plus indulgents. quinzaine de réponse en une heure sur 188. 362 au total.

**Comment by pyrog** [comment]
> Il y en a un qui vient de mettre un point d'interrogation à cette question

Tu parles d'un commerçant qui ne comprends pas l'objet de ton mél ?
Ou qui ne sait pas y répondre ?

> quinzaine de réponse en une heure
C'est un bon début 😄 

Les autres vont peut-être répondre d'ici quelques heures.

**Comment by wadouk** [comment]
> Tu parles d'un commerçant qui ne comprends pas l'objet de ton mél ?
entre le _apporté_ au lieu de _emporté_

**Comment by pyrog** [comment]
il chinoise😆 

 (blague à 2 balles en lien avec notre pandémie)

**Comment by wadouk** [comment]
37 réponses, j'ai modifié mon script pour prendre en compte les réponses
j'ai ajouté un tableur pour gérer un peu ça.
j'ai commencé à ajouter dans OSM https://www.openstreetmap.org/user/Nicolas Bétheuil/history

c'est fastidieux, entre les commerces inexistants, fusionner sans écraser une donnée OSM potentiellement de meilleur qualité ...
si quelqu'un veut participer/aider, c'est open

**Comment by PanierAvide** [comment]
Comme c'est géré par ailleurs ( https://github.com/wadouk/od2osm ), je ferme le ticket.
