### ISSUE TITLE
Nouveau visuel haut du site mobile

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#121]
pour remplacer cette mention sur mobile :
![image](https://user-images.githubusercontent.com/11553211/78167297-8cfec780-744e-11ea-8656-1d70828a0d63.png)
 
le graphiste propose :
![logo-site-new-version](https://user-images.githubusercontent.com/11553211/78167377-ac95f000-744e-11ea-8b93-c92a8bc755a1.png)

ça permet de ne plus avoir le logo flottant en bas à gauche de l'écran. Recommandation de graphiste / ux designer pro ;)

**Comment by PanierAvide** [comment]
Intégré

**Comment by ossiannroux** [comment]
Hello, petite rectification pour le logo sur mobile afin qu'il occupe mieux l'espace et soit plus lisible.
![logo-site-mobile-(modif)](https://user-images.githubusercontent.com/63117361/78385177-c0229180-75db-11ea-9337-1493fd72e5a9.png)

**Comment by PanierAvide** [comment]
C'est fait, merci :+1:
