### ISSUE TITLE
proposer une option : commerce n'existant plus / changement d'enseigne

### ISSUE THREAD

**Issue by JLZIMMERMANN** [osmontrouge/caresteouvert#125]
Exemple concret : 
il y avait encore quelques semaines une enseigne d'alimentation intitulée La vie claire. Elle a été remplacée par une activité tertiaire de services. Ce n'est plus de l'alimentation.

En revanche il peut aussi y avoir le cas du local vacant ou du changement d'enseigne.
![image](https://user-images.githubusercontent.com/4929752/78193216-4b841180-747a-11ea-86bc-aa7413b0f907.png)

**Comment by vinber** [comment]
faire un renvoi vers l'article de contribution ?
Je crains que "fermé" fasse doublon avec la fermeture pendant la crise ?
Peut-être un article spécifique "L'activité d'un commerce a changé, le local commercial est vacant, Que faire ?"

**Comment by PanierAvide** [comment]
Dans la pratique, les fermetures définitives sont souvent notées dans la partie "détails" en fin de formulaire, ce qui créé une note et permet une vérification par la communauté. Est-ce qu'on veut aller plus loin pour gérer ces cas ?

**Comment by vinber** [comment]
à mon avis on laisse pour l'instant soit par note, soit par renvoie sur la contribution avec son compte. Mon point de vue / On évite la contribution directe qui peut effacer des données ou modifier trop de données hors :covid19 -> on laisse cela à des gens ayant des comptes en propre !
À voir plus tard, peut-être une authentification ouvrant d'autres possibilités, mais cela voudra dire que les gens ont au moins créé un compte ! Voir que seuls les comptes ayant X modifications pourront s'en servir !!

**Comment by francois2metz** [comment]
Si on a un article sur comment traiter les changements de POI, je propose de rajouter un choix:
Oui / Non / Le commerce a changer ou fermer. Et on pousse l'article dans ce cas la directement.
