### ISSUE TITLE
Mentions légales : Utilisation de get.gauges.es

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#126]
Je viens de remarquer que vous utilisez sur le site un tracker de https://get.gaug.es/. Cependant, l'autorisation de l'utilisateur n'est pas obtenue (selon le RGPD) et le tracker n'est pas mentionné dans les mentions légales non plus. Est-ce intentionnel ?

https://github.com/osmontrouge/caresteouvert/blob/62bcbd7762ad046928da3d7425e6726522c6f612/index.html#L12-L25

L'entrée de blog suivante suggère d'ailleurs que le site est conforme au RGPD (meme s'il parle d'OpenStreetMap en general et pas de CaResteOuvert en particulier) : https://blog.caresteouvert.fr/un-outil-de-communication-des-mairies/

**Comment by overflorian** [comment]
Bonjour, merci pour cette remarque. En effet c'est un oubli non-intentionnel de notre part.
Je vais rajouter la mention dans les conditions d'utilisation.

@francois2metz je suggère d'ajouter un bandeau en haut à l'ouverture du site (au dessus de l'interface, il ne faut pas qu'elle la recouvre). il ne faut pas que ce bandeau s'affiche sur les applis. Je vais écrire le wording.

**Comment by overflorian** [comment]
j'ai mis à jour les conditions d'utilisation

**Comment by overflorian** [comment]
Je propose le wording :

Nous respectons votre vie privée. Nous utilisons juste un tout petit cookie pour mesurer le nombre de visiteurs pour améliorer notre site. J'ACCEPTE / NON MERCI

NON MERCI : désactive le suivi analytics

**Comment by caugner** [comment]
> Ces cookies permettent d’obtenir des statistiques de fréquentation anonymes
> (Source: https://blog.caresteouvert.fr/mentions-legales/)

Cela veut dire que les addresses IP ne sont pas enregistrer, c'est ca ? Sinon, ce n'est pas anonyme à mon avis.

> Nous utilisons juste un tout petit cookie pour mesurer le nombre de visiteurs pour améliorer notre site.

Est-ce que ce suivi analytics est vraiment necessaire ou pourriez-vous mesurer le nombre de visiteurs également à partir des fichiers journaux du serveur ?  Firefox et uBlock Origin le blocke de toute facon et alors les fichiers journaux seraient plus fiables.

Corrigez-moi si je me trompe.
