### ISSUE TITLE
Rajouter une couleur pour les lieux fermés mais qui fonctionnent encore ?

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#127]
je relaye la demande reçue sur le blog

> Bonjour,
> Nous allons travailler à l’alimentation de cette carte pour la Ville de Chelles. Comment me conseillez-vous de renseigner les structures municipales fermées physiquement mais pour lesquelles nous avons mis en place un standard téléphonique ? (ex : Hôtel de Ville, Police municipale, etc.). Ne faudrait-il pas une catégorie intermédiaire (orange ?).
> Bravo pour votre initiative ! C’est top !
> MCJ
> (Innovation & SIG – Ville de Chelles 77500 )

**Comment by PanierAvide** [comment]
Je dirais : `opening_hours:covid19=<horaires> + description:covid19=Permanence téléphonique` mais à valider plus largement.

**Comment by PanierAvide** [comment]
Pas plus de retours, je ferme le ticket.

**Comment by jibix2256** [comment]
Deux suggestions qui me passent par la tête:
- "description:covid19=Permanence téléphonique" -> "description:covid19=phone_only" ou quelquechose du genre?
- "catégorie intermédiaire (orange ?)" -> orange ou (/et?) chager la forme du marqueur sur la carte, au lieu que ce soit un cercle, mettre une forme de téléphone? Avantage: plus visuel; inconvénients: peut-être pas approprié quand les points sont un peu tassés. La couleur orange peut couvrir un spectre plus large de situations, une chose n'empêche pas l'autre.

**Comment by vinber** [comment]
je n'avais pas vu, oui pour opening_hours:covid19=* et le description:covid19 et peut-être un phone:covid19=+33XXXX car il arrive qu'un numéro unique est mis en place. Il y a quelques (36) phone:covid19.

**Comment by vdct** [comment]
>     * "description:covid19=phone_only

J'ai plusieurs cas aussi donc pourquoi pas ce tag, à défaut. On pourra toujours le changer/l'affiner, mais au moins ça permet une suggestion pour les contributeurs rencontrant le cas

**Comment by vinber** [comment]
oui seulement le "description:covid19=phone_only" laisse supposer une possibilité de traitement automatique, alors que jusqu'à maintenant c'est un champs texte "libre" plutôt.
Oui pour le renseignement dans le description:covid19= mais je pense que cela doit rester en mode texte compréhensible dans la langue du pays.
