### ISSUE TITLE
Demander la source : client VS owner (+ url)

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#128]
Il serait bien d'enregistrer d'ou vient les informations :

* "Je suis particulier." (`opening_hours:covid19:source=client`)
* "J'agis au nom de l'entroit." (`opening_hours:covid19:source=owner`)

On pourrait ajouter cela dans la troisième étape ("Details") avec un champ de saisie URL optionnel. (Montrer cette URL facilite aux utilisateurs de verifier si les infos sont à jour.)

**Comment by PanierAvide** [comment]
C'est plutôt dans l'autre sens les tags source d'habitude : `source:opening_hours:covid19=*` (sur le modèle de `source:geometry` ou `source:addr`.

**Comment by vinber** [comment]
est-ce vraiment nécessaire ? Cela laisse supposer que l'un pourrait avoir priorité sur l'autre ?

**Comment by caugner** [comment]
À mon avis, les informations des établissements eux-même sont plus fiable que les autres. En plus, cette information pourrait donner un indice sur l'acceptation par les commerces.

En tout cas, cette information me semblet utile, bien qu'elle ne soit pas absolument nécessaire.

**Comment by francois2metz** [comment]
On pourrait rajouter une case a cocher, 'je suis le propriétaire de cet établissement', mais il faudrait maintenir cette information au fur et a mesure des changements potentiels. 
Comme la plupart des objets avec un tag source, celui ci sera obsolète rapidement.

Je ne suis pas pour l'ajout de ça.

**Comment by caugner** [comment]
> Comme la plupart des objets avec un tag source, celui ci sera obsolète rapidement.

Je n'ai pas penser à cela, donc je fais fermer cet issue.
