### ISSUE TITLE
Créditer OSM dans le volet POI

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#129]
Je propose de créditer OpenStreetMap dans le volet ouvert pour chaque POI.
Ma proposition : fixé en bas de page, sur un fond de couleur différente (gris clair ?), l'exacte même mention que sur qwant maps :
![image](https://user-images.githubusercontent.com/11553211/78238280-b108ea00-74dc-11ea-96f5-6643a350a13b.png)

exemple : https://www.qwant.com/maps/place/osm:node:2322905385@Franprix

**Comment by vinber** [comment]
Oui je pense que c'est une erreur d'enthousiasme :) et/ou de précipitation :)

**Comment by francois2metz** [comment]
Cela peut permettre de traiter #130 et #86 d'un coup. Je regarde.
