### ISSUE TITLE
Formulaire de contribution

### ISSUE THREAD

**Issue by PanierAvide** [osmontrouge/caresteouvert#13]
Je créé un ticket ici pour reprendre les différents éléments de discussion.

* On veut permettre une contribution simple et directe à OSM via le site caresteouvert.fr
* Sur le modèle de WheelMap, on peut créer un compte unique, celui-ci enregistrera dans OSM les tags opening_hours:covid19 et note:covid19
* Pour ce compte, on doit suivre les contraintes d'édition coordonnée (de source OSMF) : https://wiki.openstreetmap.org/wiki/Organised_Editing
* On veut permettre aussi la contribution avec les comptes persos des contributeurs OSM ?

**Comment by overflorian** [comment]
> On veut permettre aussi la contribution avec les comptes persos des contributeurs OSM ?
Je pense que ça rajoutera de la complexité à l'interface. Les contributeurs OSM disposent déjà d'outils par ailleurs.

OK pour tout le reste

**Comment by Marc-marc-marc** [comment]
vu la noyade (on se dirige vers plus de 1000 notes sur la matinée), il serrait plus modeste de couper la contribution par note en attendant la maturité à une contribution directe.
Pour l'instant l'interface est très simple, c'est "yaka" que d'autres fassent la modif osm".

**Comment by francois2metz** [comment]
Cela me parait raisonnable de couper et d'afficher un message en indiquant quelque chose comme "Nous sommes en train d'intéger une première vague de contribution. La modification est pour le moment coupée. Elle reviendra dès demain."
Un avis ?

**Comment by PanierAvide** [comment]
Je trouve dommage de vouloir stopper les notes : on crée de la donnée, les notes sont très pertinentes, et remontent même des infos de commerces fermés définitivement... Une fois la contribution directe intégrée, on aura tout le temps d'aller intégrer ces notes. Personne n'est forcé de traiter ces notes, l'appel sur talk-fr était pour demander un coup de main et nullement forcer la main.

**Comment by PanierAvide** [comment]
Bon j'ai ouvert le dépôt pour le back-end ici : https://github.com/osmontrouge/caresteouvert_backend

Et ça dépend d'une modification de la bibliothèque osm-request pour permettre les appels API en authentification basique : https://github.com/osmlab/osm-request/pull/13

Prochaine étape : valider le format des données envoyées par le formulaire du site web pour que je puisse transformer en format opening_hours

**Comment by francois2metz** [comment]
Je ne pense pas que j'aurais le temps aujourd'hui de finir cet éditeur. Du coup pour arrêter le flux des notes je propose une solution intermédiaire temporaire dans laquelle on modifie OSM sans cet éditeur.

L'info d'ouverture serait traduite au mieux en fonction de la présence d'opening hours dans les tags, et la note irait dans le champ note (ou description ?). Ce week end je pourrais finir l'éditeur et brancher ce dernier point.
Qu'en pensez vous ?

**Comment by PanierAvide** [comment]
Pas sûr d'avoir compris, tu proposes donc :
* Un formulaire simplifié sur le site (le même qu'actuellement ?)
* Qui communique avec l'API sur laquelle je travaille
* Et qui remplit les tags `opening_hours:covid19` et `note:covid19` ou `description:covid19` directement dans OSM ?
Au final on aura plus les notes, mais des données moyennement bien détaillées directement dans OSM. Dans ce cas là, autant garder les notes, ça fait tampon et on peut nettoyer avant de mettre dans OSM...

**Comment by francois2metz** [comment]
Il est vrai que ce sera moins détaillé, mais combien de personnes vont vraiment remplir des horaires d'ouvertures ?
J'ai conscience que ce n'est pas idéal, mais ça avance dans la bonne direction a mon avis.

**Comment by PanierAvide** [comment]
C'est sûr, mais on va se retrouver avec un fourre-tout dans le champ qui accueillera le texte libre : horaires, livraison, fermetures définitives... L'avantage des notes est de pouvoir gérer le côté brouillon de l'info et de structurer en différents tags avant ajout en base. Là si ça va direct dans OSM, le suivi et modification va être plus complexe.

Ou alors il faut gérer un système édition + notes : si pas d'infos en texte libre, on modifie OSM directement, sinon on créé une note. Ça réduira le nombre de notes à modification "évidente", tout en gardant la richesse du texte libre et en mettant pas la zone dans OSM.

**Comment by francois2metz** [comment]
Cela me parait une bonne idée !

**Comment by PanierAvide** [comment]
Pour les horaires d'ouverture, il faudrait que le formulaire renvoie à terme des infos sous cette structure :
* Un tableau qui contient plusieurs objets
* Chaque objet avec les propriétés : jour de début (dayStart), heure de début (minStart), jour de fin (dayEnd), heure de fin (dayEnd). Chacun de ces créneaux est continu : du lundi 23h au mardi 3h. Pour dupliquer un créneau, il faut deux objets, exemple ouvert lundi et mardi de 8h à 15h = deux objets (lundi-lundi 8h-15h, mardi-mardi 8h-15h)
* dayStart/dayEnd sont l'identifiant du jour de la semaine (0=lundi, 1=mardi, 2=mercredi...)
* minStart/minEnd sont le nombre de minutes écoulées depuis minuit (600=10h, 1200=20h).

Un exemple en JSON

```json
[
   { "dayStart": 0, "dayEnd": 0, "minStart": 600, "minEnd": 1200 },
   { "dayStart": 1, "dayEnd": 1, "minStart": 600, "minEnd": 1200 },
   { "dayStart": 3, "dayEnd": 3, "minStart": 30, "minEnd": 90 }
]
```

Équivaut à `Mo,Tu 10:00-20:00, Th 00:30-01:30`

C'est le formalisme déjà utilisé par YoHours, donc on pourra reprendre ces données directement et intégrer ça côté back plus rapidement.

**Comment by overflorian** [comment]
> Cela me parait une bonne idée !

+1

**Comment by francois2metz** [comment]
> Pour les horaires d'ouverture, il faudrait que le formulaire renvoie à terme des infos sous cette structure :
> 
>     * Un tableau qui contient plusieurs objets
> 
>     * Chaque objet avec les propriétés : jour de début (dayStart), heure de début (minStart), jour de fin (dayEnd), heure de fin (dayEnd). Chacun de ces créneaux est continu : du lundi 23h au mardi 3h. Pour dupliquer un créneau, il faut deux objets, exemple ouvert lundi et mardi de 8h à 15h = deux objets (lundi-lundi 8h-15h, mardi-mardi 8h-15h)
> 
>     * dayStart/dayEnd sont l'identifiant du jour de la semaine (0=lundi, 1=mardi, 2=mercredi...)
> 
>     * minStart/minEnd sont le nombre de minutes écoulées depuis minuit (600=10h, 1200=20h).
> 
> 
> Un exemple en JSON
> 
> ```json
> [
>    { "dayStart": 0, "dayEnd": 0, "minStart": 600, "minEnd": 1200 },
>    { "dayStart": 1, "dayEnd": 1, "minStart": 600, "minEnd": 1200 },
>    { "dayStart": 3, "dayEnd": 3, "minStart": 30, "minEnd": 90 }
> ]
> ```
> 
> Équivaut à `Mo,Tu 10:00-20:00, Th 00:30-01:30`
> 
> C'est le formalisme déjà utilisé par YoHours, donc on pourra reprendre ces données directement et intégrer ça côté back plus rapidement.

Ok ca va changer pas mal ce que javais commencé a faire, mais au moins j'ai une idée clair de ce qu'il faut faire.

**Comment by PanierAvide** [comment]
Après si tu avais une autre idée en tête, je peux me baser sur un format que tu me précises et faire la transformation côté back, à toi de voir selon comment tu le sens.

**Comment by Phyks** [comment]
Une idée rapide vue sur IRC (`#osm-fr-tech`). Pour réduire le nombre de notes, peut-être envisager une approche plus simple :

Information incorrecte ? Avec 3 possibilités (liste déroulante) : "magasin ouvert - horaires habituels" / "magasin ouvert - horaires adaptés" / "magasin fermé".

Pour horaires habituels / fermés, édition directe dans OSM (facile, pas trop de doutes sur la donnée) avec un champ supplémentaire "complément d'information" qui va dans "description:covid19".

Pour "horaires adaptés", passage par une création de note comme actuellement.

My 2 cents, de loin et sans possibilité de contribuer dans l'immédiat… soyez libres de me dire que c'est une mauvaise idée :)

**Comment by PanierAvide** [comment]
C'est à peu près le modèle retenu en attendant un formulaire complet avec saisie des horaires. Pour l'instant on part sur :
- Si aucune info saisie dans le champ de texte libre -> on modifie OSM `opening_hours:covid19=same/off`
- Si des détails sont saisis dans le champ de texte libre -> note telle qu'on a jusqu'à présent

Avec pour esprit de ne plus avoir de notes "clic bouton" à résolution évidente, mais de garder les notes avec des infos supplémentaires et faire confiance à la communauté pour les indiquer dans les tags appropriés (note:covid19, description:covid19, opening_hours:covid19, fixme...). Le temps bien sûr qu'on finalise le formulaire de saisie d'horaires et qu'on voit comment faire un suivi correct des infos saisies en texte libre (pour ne pas polluer la base).

**Comment by francois2metz** [comment]
Nous avons fermé à moitié le robinet à notes. Si aucun détails n'est précisé, alors on modifie directement dans OSM. Sinon ca crée une note comme avant.

**Comment by vinber** [comment]
Test 1 : changement d'un point en same : https://www.openstreetmap.org/way/154884797#map=19/44.83713/-0.59815
Super cela fonctionne

Test 2 : ajout d'information supplémentaire en utilisant le champ de signalement depuis caresteouvert, les 2 notes ont été créées :
-  https://www.openstreetmap.org/way/154884797#map=19/44.83713/-0.59815 sur le même point avec une précision sur les horaires de confinement
- sur un autre point en précisant les horaires également 

Cela fonctionne super bien, encore merci (je vais corriger mes notes hein :) )

Impression d'un lag (2-3 minutes) au niveau du temps apparition de la modif et des notes (est-ce des "contrôles" de votre coté, une lenteur de mon coté, une fausse impression ?).

**Comment by PanierAvide** [comment]
Cool ;-)

Le lag c'est voulu, c'est pour regrouper les modifications des objets dans des changesets. On est à des envois ~ toutes les 5 minutes.

**Comment by vinber** [comment]
Ok, tellement mal habitué à "l'instantanéité" d'OSM !!!

**Comment by PanierAvide** [comment]
On se rapproche du formulaire complet : https://github.com/osmontrouge/caresteouvert_backend/pull/1

**Comment by vinber** [comment]
Carte à jour, le cycle de 1 heure est ok :)

**Comment by PanierAvide** [comment]
Tu veilles à la minute près, ça c'est de l'implication :smile:

**Comment by vinber** [comment]
c'est pour s'assurer que cela tourne, l'intérêt va être gandissant dans les 15 jours qui viennent pour la france et selon les cas pour d'autres pays à venir

**Comment by PanierAvide** [comment]
C'est en prod, je ferme le ticket.

**Comment by francois2metz** [comment]
Je vrai créer un ticker pour gérer les delivery/takeway.

**Comment by zorun** [comment]
Génial, bravo, on voit déjà apparaître plein de contributions, le formulaire a l'air facilement utilisable !

Par contre, dans le cas où l'utilisateur précise « ce sont les mêmes horaires hors confinement », il ne faudrait pas plutôt mettre `opening_hours:covid19=same` plutôt que de dupliquer l'information dans `opening_hours` et `opening_hours:covid19` ?

Par exemple ici : https://www.openstreetmap.org/node/3196907457

**Comment by PanierAvide** [comment]
Merci de ton retour, comme on a l'ambiguïté sur la valeur de `same` suite à nos premiers choix, on préfère dupliquer les valeurs pour assurer que ce sont bien les horaires en pratique et pas un résidu de contributions incertaines. Mais c'est à discuter

**Comment by zorun** [comment]
Ok, ça fait sens, merci
