### ISSUE TITLE
Focus barre de recherche

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#132]
Lorsqu'un utilisateur sur mobile/appli mobile clique sur la barre de recherche, je propose qu'un focus "recherche" soit mis en place.
Le principe :
-le clavier s'ouvre (ce n'est pas le cas actuellement)
-la barre de recherche prend toute la largeur (les autres logos disparaissent) et est plus grande en hauteur.
-Le texte tapé apparaît en plus gros caractère qu'actuellement
-et pourquoi pas aussi ajouter le logo "MICRO" comme dans l'appli Netflix :
![image](https://user-images.githubusercontent.com/11553211/78239013-810e1680-74dd-11ea-8b39-40f6d067b6ab.png)

**Comment by PanierAvide** [comment]
J'ai ajouté le focus sur la barre de recherche. Quand tu dis plus grand, ce serait quelle hauteur ?

**Comment by overflorian** [comment]
cool, ça fait le taff, merci. Pour la hauteur je ne me rend pas vraiment compte, peut-être jusqu'à 50% plus grand ? Faut faire un test car si le texte est trop grand, taper une longue adresse peut devenir pénible. Peut-être regarder les stats de recherche pour identifier la longueur moyenne (ou encore mieux médiane) des chaînes de caractères tapées.
Si tu penses que je vais trop loin dans le trip d'optimisation, t'as qu'à augmenter la taille de 20% et on verra les retours utilisateurs.

Nouvelle évolution : lorsque l'on perd le focus de la barre de recherche, le clavier disparaît bien, mais la barre de recherche reste affichée. Possible de la refaire disparaître pour remette le logo à ce moment là ? Ou alors, on rajoute un bouton BACK comme ça :
![image](https://user-images.githubusercontent.com/11553211/78340170-e8879d00-7595-11ea-8a01-242b40e521a1.png)
Je n'ai pas d'avis tranché sur la question.

je propose aussi de changer le wording : "Rechercher" -> "Saisissez votre recherche"
