### ISSUE TITLE
Ajouter les cliniques vétérinaire

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/caresteouvert#134]

**Comment by PanierAvide** [comment]
On en a 15/2300 avec l'info covid19, et pas de retour en plus depuis 19 jours. Je ferme le ticket.

**Comment by OcelotNat** [comment]
Euh 15 notés :covid19 **avant** que ça ne soit dispo dans CRO, c'est un retour, non ? ;)
19 aujourd'hui : y'a incontestablement des pingouins mappeurs.

**Comment by PanierAvide** [comment]
C'est sûr que c'est intéressant, mais ça fait pas un bon ratio 19/2300. On va afficher beaucoup de cliniques pour lesquelles l'info n'est pas connue, donc potentiellement du bruit. Et la difficulté c'est que seul un travail de fourmi permet ici d'augmenter les infos connues, à moins qu'il y ait des réseaux / "marques" de cliniques qui permettent d'avoir un peu d'info rapidement sur le territoire.
