### ISSUE TITLE
rendre le bouton GEOLOC flottant

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#136]
le détacher de la barre du haut et le mettre à coté des boutons de zoom

**Comment by francois2metz** [comment]
Il était comme cela au début, et je crois que tu ne l'a jamais vu.

**Comment by sygour** [comment]
l'idee serait de le coller aux boutons de zoom ? (ex. comme [OSM](https://www.openstreetmap.org)
Ou bien on pourrait le mettre dans le coin en bas a droite pour le detacher reelement des boutons de zoom.

**Comment by overflorian** [comment]
je n'ai pas d'avis tranché sur le sujet mais ma préférence va à un bouton détaché. Par contre je pense qu'il faut qu'il reste en haut à droite pour ne pas parasiter la future barre du bas : https://github.com/osmontrouge/caresteouvert/issues/144

**Comment by PanierAvide** [comment]
C'est intégré, sous la forme d'un bouton détaché en dessous des boutons de zoom.
