### ISSUE TITLE
Ajouter les restaurants qui font de la livraison ou à emporter

### ISSUE THREAD

**Issue by fbroussais** [osmontrouge/caresteouvert#138]
Les restaurants sont fermés, mais certains proposent un service de livraison.

En lien avec https://github.com/osmontrouge/caresteouvert/issues/92

**Comment by frodrigo** [comment]
Il manque notamment les pizzerias à emporter.

**Comment by francois2metz** [comment]
Si le restaurant et en `opening_hours:covid19=open` et `takeway:covid19=only` ça s'affiche.

J'imagine que vous voulez ajouter tout les restaurant en affichage inconnu ? et qu'on compléterait ?

**Comment by frodrigo** [comment]
Il n'y sont pas, donc on ne peut pas les completer.

**Comment by fbroussais** [comment]
Si j'ai bien compris, une enseigne qui n'est pas catégorisée sur la carte, sera quand même affichée lorsqu'on utilise(ra) l'option "afficher les commerce qui ont un service de livraison" ?

**Comment by frodrigo** [comment]
Mon cas d'usage à moi:
- la pizzeria du coin de la rue ne fait que à emporter
- elle est toujours ouverte
- je ne peux pas dire qu'elle est ouverte : car elle n'est pas sur la carte

**Comment by francois2metz** [comment]
Les commerces hors catégories sont de même affiché si ils ont un tag `opening_hours:covid19=open`. 

On peut tenter de traiter les restaurants qui ont un tag `takaway`. C'est bien le cas pour ta pizzéria @frodrigo ?

**Comment by fbroussais** [comment]
Le tag takeway est utilisé pour les plats à emporter.
Est-ce que le tag `delivery:covid19=yes` serait utilisé ?
Ex. pour les Domino's sur Nancy qui sont fermé au public, mais assurent les commandes par téléphone et la livraison.

**Comment by frodrigo** [comment]
https://www.openstreetmap.org/node/1754966942
`takeaway=only`


https://www.openstreetmap.org/node/1754966936
`delivery=yes`
`takeaway=yes`

**Comment by francois2metz** [comment]
@fbroussais c'est ok si `delivery:covid19=only` mais faut `opening_hours:covid19=*` tout de même.

@frodrigo ok !

J'ai renommé l'issue pour essayer de clarifier le besoin: Afficher les restaurants qui font de la livraison ou a emporter (et faut rajouter le champ de formulaire pour le takeaway).

**Comment by fbroussais** [comment]
Merci !

**Comment by deuzeffe** [comment]
Et ceux qui font ça mais uniquement sur commande ? Est-ce que reservation:covid19=required est approprié ? Pas forcément à mettre dans le formulaire, mais à prendre en compte dans l'affichage ("Sur commande uniquement" par exemple) ?

**Comment by vinber** [comment]
À mon avis, l'affichage des restaurants (fermés par défaut) est intéressant pour pouvoir faire contribuer à  l'information, en particulier livraison et à emporter. Lien avec #120

**Comment by fbroussais** [comment]
Bonjour,
En fait, mon exemple (Domino's), c'est bien "uniquemement sur commande.", ou en d'autre termes, fermé (physiquement) au public mais assurant les commandes au téléphone ou internet. Ou alors il y a un cas de figure qui m'échappe ?
Du coup quelle différence entre `reservation:covid19=required` et `reservation:covid19=only` ?

**Comment by PanierAvide** [comment]
À noter que les POIs s'affichent tant qu'ils ont un `opening_hours:covid19=*` (que ce soit open, off ou autre). Donc un resto dans lequel on ne peut pas manger sera en `opening_hours:covid19=off`. Après on complète avec delivery/takeaway:covid19 selon les cas.

**Comment by vinber** [comment]
Complexe car opening_hours:covid19=off ne permet pas d'avoir les horaires d'ouvertures pour le "drive" ou la livraison.
Est-ce que l'on rentre trop dans des détails ?

**Comment by PanierAvide** [comment]
Je viens de réaliser la modification suivante :
- Sont concernés restaurants, fast food et glacier
- S'ils disposent d'au moins un tag delivery, takeaway, delivery:covid19, takeaway:covid19 on les affiche sur la carte
