### ISSUE TITLE
Faire diparaitre l'interface par un clic sur la carte

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#143]
pour web mobile et appli mobile, un tap sur la carte devrait faire complètement disparaître l'interface hors carte : boutons de zoom, barre du haut, menu de gauche.
un tap supplémentaire fait réapparaître tous ces élements

inspiration : appli mobile google maps

**Comment by francois2metz** [comment]
A l'usage je ne trouve pas cela essentiel.
