### ISSUE TITLE
Proposition d'évolution d'interface

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#144]
Notre graphiste Ossiann et moi-même proposons de faire évoluer l'interface web mobile / appli mobile :
[proposition app ça reste ouvert.pdf](https://github.com/osmontrouge/caresteouvert/files/4422670/proposition.app.ca.reste.ouvert.pdf)

Use case : l'utilisateur cherche une pharmacie. 
**Actuellement :** dans le volet de gauche, il décoche TOUTES les cases qui ne sont pas des pharmacies.
**Nouvelle interface :** il ouvre le volet du bas et clique sur "pharmacie"

Cette proposition résout l'issue https://github.com/osmontrouge/caresteouvert/issues/112 et permet d'envisager l'ajout de nombreuses nouvelles catégories de POI (par exemple celles déjà demandées https://github.com/osmontrouge/caresteouvert/issues/95 https://github.com/osmontrouge/caresteouvert/issues/66 https://github.com/osmontrouge/caresteouvert/issues/60)

j'ai déjà décomposé cette proposition en plusieurs demandes distinctes : https://github.com/osmontrouge/caresteouvert/issues/143 https://github.com/osmontrouge/caresteouvert/issues/136 https://github.com/osmontrouge/caresteouvert/issues/132 https://github.com/osmontrouge/caresteouvert/issues/121, ce à quoi on peut ajouter :
-implémenter le bandeau du bas
-supprimer le bouton sandwich dans la barre du haut

Par la suite cette nouvelle interface nous permettra d'aller beaucoup plus loin dans l'UX liée aux POIs mais aussi le reste.
On espère que vous aimez ! Challengez-nous pour aboutir à la meilleure solution

**Comment by francois2metz** [comment]
J'aime bien l'idée globalement. Je trouve que dans la partie menu, tout ce qui n'est pas du choix de POI est beaucoup trop gros (A propos, Presse, etc ...) alors que c'est vraiment le truc le moins intéressant.

**Comment by overflorian** [comment]
je suis d'accord avec toi : c'est une suggestion du graphiste mais ma vision est quelque chose de beaucoup plus sobre et long : on a une page avec un scroll infini : autant en profiter sans entasser des blocs les uns à côté des autres. Tout ce qui est en dessous du choix des POIs sera, de toute manière, intégré tel quel dans un premier temps puis sera discuté par la suite.

**Comment by wadouk** [comment]
Ça fait bizarre d'avoir un bouton recherché en haut, mais les catégories de POI en bas.
Sur l'idée de passer des cases à cocher à des boutons : effectivement chercher à la fois l'alimentation et la mairie n'a que peu d’intérêt
Je verrais plus un wizard:
 - d'abord l'adresse
 - puis la catégorie

Les 2 notions dans le même volet. Mais il faut pouvoir zapper la sélection de l'adresse si l'emprise de la carte est déjà bonne.

Me demande sur la cohérence du scroll infini avec un entassement de blocs. Quelle cohérence dans l'ordre des catégories ? Pourquoi police avant commerce (simple exemple pour la discussion). Une vue arborescente peut être ? Ex: boulangeries dans commerces. Plus un système de tag ? dans une première partie commerces, services ... qui filtrerais une sous partie où apparaîtrait les différentes catégories shop=whatever ? La toponymie OSM est suffisamment robuste/clair pour dire en premier on choisit shop/amenity ... et après shop=bakery ?

Et sur le contenu du volet du bas, une simple liste de liens ... ou des grosses images pourquoi pas.

Mais la question aussi que je me pose est de comment décliner tout ça en responsive pour pouvoir faire la transition avec l'existant. Champs de recherche toujours visible ? La sélection en wizard n'est pas nécessaire, on la place pour tout mettre.

**Comment by francois2metz** [comment]
Je vais essayer de découper ça en problèmes à résoudre et je m'attaque a la sélection des POIs.

**Comment by overflorian** [comment]
+1 @francois2metz 
@wadouk parlons plus spécifiquement du contenu de la barre infinie ici : https://github.com/osmontrouge/caresteouvert/issues/146

**Comment by overflorian** [comment]
Autre conséquence du nouveau bandeau : celui-ci doit apparaître comme une page référencée par les moteurs de recherche (niveau 1 dans l'arborescence) et ses titres, sous-titres et contenu bien interprétés pour le SEO

**Comment by wadouk** [comment]
SEO ? oulah, autre sujet ... pour l'instant la page est blanche sans JS ...

**Comment by wadouk** [comment]
> Et on part du principe qu'affiché plusieurs types de POI est peu pertinente.

Bah ça dépends, si on affiche dans "Hoptial" aussi les cliniques ?
Dans "Alimentation" les supermarchés, primeurs, superettes ...

**Comment by pyrog** [comment]
Quand on clique sur un POI, le bandeau du bas (OSM) est un peu trop "épais" .
C'est aussi valable sur PC.

Le libellé _« Ça reste ouvert » utilise les données d'OpenStreetMap._ est trop long.
Les boutons VOIR et MODIFIER sont trop gros (une petite icône serait bien).

Enfin, le choix de l'éditeur devrait être paramétrable.
