### ISSUE TITLE
Réorganiser les types de POIs affichés

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#146]
@wadouk a posé des questions liées à l'implémentation d'une nouvelle interface https://github.com/osmontrouge/caresteouvert/issues/144
Ses questions :

> Quelle cohérence dans l'ordre des catégories ? Pourquoi police avant commerce (simple exemple pour la discussion). Une vue arborescente peut être ? Ex: boulangeries dans commerces. Plus un système de tag ? dans une première partie commerces, services ... qui filtrerais une sous partie où apparaîtrait les différentes catégories shop=whatever ? La toponymie OSM est suffisamment robuste/clair pour dire en premier on choisit shop/amenity ... et après shop=bakery ?

Je pense que nous pouvons reposer à plat tous les types de POs affichés et repartir de zéro en partant du principe que nous ne serons plus limités par le nombre : nous pouvons afficher autant de catégories que l'on veut !

Tout d'abord, gardons en tête l'objectif principal : informer au mieux les personnes confinées. Ensuite, il semble important d'informer les 40% de la population qui continue de bosser. Enfin, il me paraît important d'ajouter des informations d'urgence.

Voici la liste que je propose, inspiré des points déjà affichés cf. https://wiki.openstreetmap.org/wiki/France/Covid-19
Les informations entre parenthèse sont juste pour information, mais le reste est le wording exact que je propose d'afficher sur l'interface.

- CATEGORIE "je suis confiné" :

Boulangeries
Tabac
Cigarettes électroniques
Pharmacies
Marchés
Supermarchés (regroupe supermarchés, supérettes et convenience)
Fruits et légumes
Presse
Laveries
Boucheries
Charcuteries
Produits de la mer
Surgelés
Alcool (caviste)
Chocolatiers
Fromagers
Téléphonie
Bricolage
Quincailleries
Papeteries
Hôtels
Opticiens
Vétérinaires
Animaleries
Services funéraires
Banques
Assureurs
(il faudra réfléchir à ajouter les artisans à un moment : plombiers, chauffagistes ...)

- CATEGORIE "je dois bosser" :

Garderies
Stations essence
Garages automobile
Pièces auto
Vélos
Location de voiture
Vente de produits agricoles
Vente de matériel médical
Vente d’électronique
Matériel informatique (regroupe vente et réparation)
Travail temporaire

- CATEGORIE "urgence" :

Police
Centres de soin
Hopital (inclu cliniques)

J'ai trié ces éléments du plus important au moins important de mon point de vue, mais peut-être mieux vaut-il les classer par ordre alphabétique ?

**Comment by gendy54** [comment]
Je doublonnerais bien Pharmacie et Matériel médical dans Urgence.
mais sinon excellente idée.

**Comment by wadouk** [comment]
Pareil, les listes sont trop grandes, sans ordre évident. Il faudrait un critère plus discriminant pour diviser les listes plus facilement (question d'UX). 
J'aime bien l'idée à regrouper par usage mais un peu peur "ah oui, oups, oublié une catégorie, faudrait rajouter ..." et la liste continue de grossir sans cohérence.

**Comment by wadouk** [comment]
Ça me parait rejoindre cette discussion ? https://github.com/osmontrouge/caresteouvert/issues/112

**Comment by PanierAvide** [comment]
Lié à #117 et surtout #124

**Comment by ViolaineDo** [comment]
je doublonnerais aussi dans la catégorie "je dois bosser" :

- les hôtels / hébergements(pour les soignants qui aimeraient se loger proche de leur lieu de travail sans contaminer la famille.., ici à Tahiti celà implique contaminer les parents, grands parents, qui sont à risques)
- les magasins alimentaires qui font de la livraison
Et ajouterais :
- les restos/snack/pizzeria qui font de la livraison
- les coursiers / livreurs 

Dans la catégorie "je suis confiné" :
- ajout des coursiers / livreurs : pour faire les courses des "anciens"
- ajout des restos avec livraison

Je ne sais pas comment gérer l'attribut en plus "qui fait la livraison" ou si faudrait pas un filtre global en plus "livraison/pas livraison".
@+

**Comment by francois2metz** [comment]
Nous avons une réflexion sur continuer a ré-organiser les catégories, pour ensuite avoir des sous-catégories disponible pour filtrer en plus.

Nous aimerions déjà réduire le nombre de catégories disponibles. Actuellement:

- police
- pharmacies
- bureaux de poste
- alimentation
- boulangerie
- restauration
- tabac
- boutiques
- services financier
- mobilité
- pompes funèbres
- autres établissement

Comment pourrait-on réduire cette liste ?

**Comment by PanierAvide** [comment]
* pompes funèbres + pharmacie + autres services de santé à venir -> santé
* boulangerie -> alimentation
* supprimer police
* bureaux de poste -> boutiques

**Comment by wadouk** [comment]
Il y a quoi derrière chaque catégorie actuellement ?

Je viens de voir qu'un fast food, shop=tea ou shop=coffee n'est pas dans alimentation mais dans autre établissements
tabac -> autre boutiques (mais je suis pas fumeur) ou alimentation peut être ?

pompe funèbre dans santé ? j'ai un doute qu'on y pense

boutiques vs autres établissements ? j'ai du mal à faire la différence

police, postes -> services "publiques" ?

Je poserais bien la question avec les tags osm et voir comment on peut les regrouper.

**Comment by wadouk** [comment]
J'ai ma réponse, https://github.com/osmontrouge/caresteouvert/blob/b24a158ebac031e75165f6b4e1fe26d0b53940bb/categories.json je vais proposer une liste de catégories et un sondage pour avoir quelque chose de représentatif. OK ?

**Comment by wadouk** [comment]
Pas de sondage : il y a 45 tags, ça fait un sondage trop long je crains.

Pas tant d'option au final 7+1 catégories vs 11+1 actuellement.
On peut réduire à 5+1

```
Services
  {"amenity": "police"},
  {"amenity": "post_office"},
  {"office": "employment_agency"},
  {"amenity": "bank"},
  {"office": "financial"},
  {"shop": "money_lender"},
  {"office": "insurance"},
  
Santé / Health
  {"amenity": "pharmacy"},
  {"shop": "medical_supply"},
  {"shop": "optician"},
  {"craft": "optician"},
  {"shop": "funeral_directors"}
  
Alimentation
  {"shop": "frozen_food|supermarket"},
  {"shop": "butcher"},
  {"shop": "cheese|coffee|tea"},
  {"shop": "convenience"},
  {"shop": "seafood"},
  {"shop": "greengrocer"},
  {"shop": "deli|farm|chocolate"},
  {"amenity": "marketplace"},

Food / Eat
  {"shop": "bakery|pastry"},
  {"amenity": "vending_machine", "vending": "bread|pizza"},
  {"amenity": "restaurant"},
  {"amenity": "fast_food"},

Drugs
  {"shop": "alcohol|beverages|wine"},
  {"shop": "tobacco"},
  {"tobacco": "yes|only"},
  {"shop": "e-cigarette"},

Commerces
  {"shop": "doityourself|hardware"},
  {"shop": "mobile_phone"},
  {"shop": "electronics"},
  {"craft": "electronics_repair"},
  {"shop": "dry_cleaning|laundry"},
  {"shop": "stationery"},
  {"shop": "kiosk|newsagent"},
  {"shop": "pet"},
  {"shop": "agrarian"},
  {"shop": "garden_centre"},

Mobility
  {"amenity": "fuel"},
  {"shop": "gas"},
  {"amenity": "car_rental"},
  {"shop": "bicycle"},
  {"shop": "car_parts|car_repair"},
```

Éventuellement mettre ensemble Alimentation / Mangé / Drugs parce qu'entre Alimentation et Mangé c'est plutôt une question de `takeaway`/`delivery` vs commerce de bouche
Peut être diviser les commerces ? Mais en fait je commence à me dire que chaque tag serait une sous catégorie à part entière pour juste trouver juste les `shop=pet` par exemple

Il y aurait du coup juste 2 niveaux, les catégories et les tags. Sur grand écran on verrait les 2 et sur mobile juste le premier, mais pourtant c'est éventuellement sur mobile qu'on aurait besoin de filtrer.

**Comment by PanierAvide** [comment]
J'ai fait un remaniement sur la base de la proposition de @wadouk, ça sera bientôt visible en ligne.
