### ISSUE TITLE
Mobile : pas d'affichage avec Firefox

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#148]
J'ai un écran tout blanc 😞 
Si je coche sur "voir la version pour ordinateur" : idem

Android 8.0.0
Firefox 68.6.0 version du 10 mars 2020

**Comment by overflorian** [comment]
Tu as mis ce screenshot :
![image](https://user-images.githubusercontent.com/11553211/78352072-0e1da200-75a8-11ea-9ae6-ac1c72e7faf8.png)
Je ne comprends pas ce qui ne s'affiche pas. J'ai l'impression que tout est parfait au contraire. Peux-tu stp préciser le problème ?

**Comment by francois2metz** [comment]
Ca ressemble plus a chrome sous Android

**Comment by caugner** [comment]
Pour moi, le site marche sans aucun problème sous Android 9 dans Firefox 68.6.0, Firefox 76.0a1 et Firefox Focus 8.1.0.

**Comment by caugner** [comment]
@overflorian @francois2metz Pourrait-on ajouter un label "need repro` ou similaire ?

**Comment by caugner** [comment]
En fait, j'ai réussi à reproduire le bug: Après avoir ouvert caresteouvert.fr dans Firefox, change l'application d'abord et change vers Firefox encore. Résultat : la carte n'est plus affichée (seulement le header).

@pyrog Un workaround est de bouger la carte un peu et la carte apparaît à nouveau.

**Comment by Bibi56** [comment]
@caugner même pas. Ça dépend peut-être si tu permets à FF de rester en arrière plan. Pour moi la carte est réapparue au bout de quelques temps, comme s'il rechargeait les tuiles.

@pyrog bouge <strike>ton c., </strike> ta carte ;-).

**Comment by pyrog** [comment]
@overflorian la copie d'écran était bien sous Chrome pour montrer la barre du navigateur qui mangeait le haut de l'écran.

Je n'ai pas osé fair une copie d'écran blanc 😆 

@caugner Bouger l'écran fait bien réapparaître la carte 😄 

@Bibi56 😝

**Comment by francois2metz** [comment]
@pyrog On est d'accord que ce bug n'apparait que lorsque quitte puis revient dans firefox ?

**Comment by francois2metz** [comment]
@pyrog up ^^ !

**Comment by pyrog** [comment]
@francois2metz je n'arrive pas à le reproduire.

De mémoire, c'est arrivé la première fois que je me suis connecté avec Firefox (je n'ai jamais vu la carte avant de suivre le conseil de @caugner )

**Comment by francois2metz** [comment]
Merci du retour. Je ferme. Possible que cela ait été un bug temporaire.

**Comment by caugner** [comment]
@francois2metz Je peux encore le reproduire:

1. Ouvre le site dans Firefox Android.
2. Change le contexte (par exemple ouvrir les préferences systeme).
3. Ouvre Firefox à noveau (sans l'avoir fermé, bien sur).
4. Resultat : la carte est toute grise.

**Comment by francois2metz** [comment]
@caugner Tu peux ouvrir un bug sur https://bugzilla.mozilla.org/ ? Je n'ai rien trouvé qui correspondrait a cela.

**Comment by caugner** [comment]
> Tu peux ouvrir un bug sur https://bugzilla.mozilla.org/ ? Je n'ai rien trouvé qui correspondrait a cela.

Bonne idée, je vais le faire ici : https://github.com/mozilla-mobile/fenix/issues

**Comment by pyrog** [comment]
@caugner je n'arrive pas à le reproduire avec ta procédure.
J'ai redémarré mon tél. et recommencer, pas mieux.

**Comment by caugner** [comment]
@pyrog C'est bizarre, le redamarrage a en effet résolu le problème. 🙄

**Comment by Bibi56** [comment]
Je pense avoir un cas reproductible : prendre une url avec élément sélectionné comme [ici](https://www.caresteouvert.fr/@47,-3,10/place/n344445884). Fermer la fenêtre. Oh, la belle blanche^^.

**Comment by caugner** [comment]
Someone reported something similar on Twitter yesterday: https://twitter.com/OSM_Pontarlier/status/1249694694596136961
