### ISSUE TITLE
Avoir un guide de contribution

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/caresteouvert#15]
Pour guider les personnes a contribuer et a améliorer OpenStreetMap, ce serait pas mal d'avoir un guide sur comment faire pour rajouter les informations directement.

Pour les contributr·ices·eurs chevronné·e·s  on peut aussi décrire la procédure avec NoteReview pour mettre à jour en masse les infos.

Également une foire aux questions sur que faire si le commerce a un mauvais nom, ou manquant.

**Comment by PanierAvide** [comment]
C'est un peu ce que l'on a commencé à faire sur https://wiki.openstreetmap.org/wiki/France/Covid-19

@vinber tu aurais envie de nous aider là-dessus ?

**Comment by francois2metz** [comment]
Mon but final serait de l'intégrer au site. On pourra aller récupérer la page wiki en live si il faut.

**Comment by vinber** [comment]
je suis ce qui se passe et si je peux je vais faire, mais disons que j'ai aussi plusieurs trucs en cours ! mais vu oui :)

**Comment by PanierAvide** [comment]
J'ai pas suivi dans le flux d'articles du blog, mais c'est OK pour ce guide de contribution ?
