### ISSUE TITLE
Intégrer les données des partenaires du gouv pour les petits commerces ?

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#151]
https://www.economie.gouv.fr/coronavirus-e-commerce-offres-preferentielles-commercants

Stuart m'a contacté à ce sujet, je vais voir ce que ça donne mais pour les autres je n'ai pas regardé s'il y a des données intéressantes pour nous

**Comment by PanierAvide** [comment]
Pas de retour, je ferme le ticket.
