### ISSUE TITLE
Define open place types per country

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#152]
**Is your feature request related to a problem? Please describe.**

This is about defining what types of places (e.g. `shop=supermarket`) are allowed to be opened where.

So far, this information seems to be specific to France. Now, we're gathering data about Spain (#94) and Germany (#149).

**Describe the solution you'd like**
It would be great to have a common format to describe what types places are allowed to open in whatc country. Possible formats could be JSON or CSV.

**Describe alternatives you've considered**
Alternatively, we could come up with a common format later.

**Additional context**
* https://github.com/osmontrouge/caresteouvert/issues/94#issuecomment-607418246
* https://github.com/osmontrouge/caresteouvert/issues/149

**Comment by PanierAvide** [comment]
Related to #124

**Comment by caugner** [comment]
Fixed by #124.
