### ISSUE TITLE
Rework title of CaResteOuvert_visitor changesets

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#160]
**Is your feature request related to a problem? Please describe.**
User feedback is automatically submitted to OSM using the [CaResteOuvert_visitor](https://www.openstreetmap.org/user/CaResteOuvert_visitor).

Currently the changesets are titled as follows:

```
Ajout d'informations liées au confinement #covid19 #caresteouvert
```

**Describe the solution you'd like**
With the upcoming launch in other countries, I would suggest to translate and shorten that title, e.g.:

```
Update #covid19 info via caresteouvert.fr
```

* Using a short title (i.e. one line instead of two) reduces the vertical space the changesets take on the History page: https://www.openstreetmap.org/history#map=11/48.8875/2.5832
* Using a URL rather than `#caresteouvert` allows OSM users to discover the app more easily (without searching for it or navigating to the user first).
* As soon as there is an international domain name, that should be used instead.

**Describe alternatives you've considered**
An alternative would be to just translate it:

```
Add information related to lockdown #covid19 #caresteouvert
```

**Additional context**
See: https://www.openstreetmap.org/user/CaResteOuvert_visitor/history

**Comment by PanierAvide** [comment]
This has been implemented on backend side, so I close the issue, thanks for reporting :+1:
