### ISSUE TITLE
Facebook : icône et lien

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#161]
L'icône n'est pas celle de FB. Le texte est moche et inutile ?
Quand au lien, il n'est pas cliquable (probablement si ce n'est pas une URL complete).

Exemple:
https://www.caresteouvert.fr/@46.576246,5.750155,19.18/place/n5655907241

**Comment by PanierAvide** [comment]
Normalement le tag `facebook=*` doit contenir l'URL complète vers la page (voir wiki), c'est ça qui est normalement affiché. On pourrait ceci dit mettre un texte type "Page facebook" à la place.

**Comment by pyrog** [comment]
[Wiki](https://wiki.openstreetmap.org/wiki/Key:contact:facebook) dit : _"In most cases, the full URL is used as value. It is also possible to add the user name or page name only (the part after the last '/')."_ 😉 

>  On pourrait ceci dit mettre un texte type "Page facebook" à la place.

Je n'ai pas testé, mais pour un POI qui a un site facebook, twitter… c'est peut-être plus lisible de coller les icônes côte à côte et sans texte ?

![](https://createandcode.com/wp-content/uploads/2018/02/social-share-links-post.jpg)

**Comment by pyrog** [comment]
ça fonctionne même sans URL complète 😄 

[n7358801986](https://www.caresteouvert.fr/@48.601648,5.666831,16.98/place/n7358801986)
[n6133515392](https://www.caresteouvert.fr/@48.576421,-3.825952,21.95/place/n6133515392)

**Comment by pyrog** [comment]
Icônes réseaux sociaux : https://www.glyphicons.com/tools/social/
