### ISSUE TITLE
Regrouper le lien web avec les autres liens

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#162]
Mettre ce lien avant les horaires (avec téléphone, Facebook…) ?

**Comment by francois2metz** [comment]
J'ai déplacé le lien vers facebook au même endroit que le site web, au dessous de tout. C'est une tentative de séparer contact direct / horaires d'ouvertures / liens externes.

**Comment by pyrog** [comment]
Exemple : [n4685425730](https://www.caresteouvert.fr/@45.777029,3.085522,17.89/place/n4685425730)

Ok. 😄 

Le texte après les icône est toujours [moche et inutile](https://github.com/osmontrouge/caresteouvert/issues/161#issue-593781574) 😉
