### ISSUE TITLE
Add tooltip to explain "Shops" (Commerces) and "Other places" (Autres établissements)

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#163]
**Is your feature request related to a problem? Please describe.**
The map contains the categories "Shops" (Commerces) and "Other places" (Autres établissements).

However, it does not explain what types of shops or places are displayed, which is especially important regarding the "Report a missing shop" feature (because a missing shop might just qualify for display).

**Describe the solution you'd like**
Add an info icon (like after the "Follow government restrictions" message) after those two categories with a tooltip listing what types of shops/places are included in this category.

**Describe alternatives you've considered**
I can't think of any alternatives.

**Additional context**
(None.)

**Comment by francois2metz** [comment]
May be fixed by #146
