### ISSUE TITLE
Where to publish blog posts in other languages?

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#166]
**Is your feature request related to a problem? Please describe.**
We have translated the blog posts for the launch in Germany: https://github.com/caugner/caresteouvert-de/issues/2

**Describe the solution you'd like**
* We need instructions on where to publish the translated posts.
* Also: How do they get referenced in the frontend?

**Describe alternatives you've considered**
(Not applicable.)

**Additional context**
(Not applicable.)

**Comment by overflorian** [comment]
Hi, thank you very much for your contribution. I will create the pages myself. But first I need to setup WordPress with a multilanguage add-on. Any advice of the best one to use?

**Comment by caugner** [comment]
> Hi, thank you very much for your contribution.

It's a team effort. :wink: 

> I will create the pages myself.

Alternatively, I could offer to create them myself. I guess there's a WordPress role that allows creating content without actually publishing it. If that would help? (Like this I could also update the German content afterwards if required.)

> But first I need to setup WordPress with a multilanguage add-on. Any advice of the best one to use?

Good question! A workaround could probably be to use tags and some clever URL patterns?

**Comment by pyrog** [comment]
> A workaround could probably be to use tags and some clever URL patterns?

fr|de
--|--
https://blog.caresteouvert.fr | https://blog.caresteouvert.fr/de/
https://blog.caresteouvert.fr/presse/| https://blog.caresteouvert.fr/de/pressen/
https://blog.caresteouvert.fr/mentions-legales/  | https://blog.caresteouvert.fr/de/impressum/

or ?

fr|de
--|--
https://www.caresteouvert.fr/blog/ | https://www.caresteouvert.fr/de/blog/
https://www.caresteouvert.fr/presse/| https://www.caresteouvert.fr/de/pressen/
https://www.caresteouvert.fr/mentions-legales/  | https://www.caresteouvert.fr/de/impressum/

or ?

fr|de
--|--
https://www.caresteouvert.fr/blog/ | https://www.bleibtoffen.de/blog/
https://www.caresteouvert.fr/presse/| https://www.bleibtoffen.de/pressen/
https://www.caresteouvert.fr/mentions-legales/  | https://www.bleibtoffen.de/impressum/

**Comment by pyrog** [comment]
> But first I need to setup WordPress with a multilanguage add-on

Could be "simply" two instances of wordpress with the good URL settings ?
(see above)

PS: in practice, one "multi-sites" wordpress installation 😉

**Comment by caugner** [comment]
Now that you mention WordPress MU, it's probably a good solution, and it has domain mapping as a native feature. Each language would be a site, which would allow adding the users for that language directly rather than have to make changes through somebody from the CRO core team.

**Comment by pyrog** [comment]
Yes 😄
So you don't need to have a "sync" between french and german blogs.

**Comment by pyrog** [comment]
[How to install and set up a wordpress multisite](https://multilingualpress.org/docs/how-to-install-wordpress-multisite/)

**Comment by francois2metz** [comment]
Here is the repository to create the blog posts: https://github.com/osmontrouge/caresteouvert_blog

**Comment by pyrog** [comment]
Fine 😄
But I thought that it was a wordpress site ?

images should be renamed : [Capture-d%E2%80%99%C3%A9cran-de-2020-03-28-08-20-57.png](https://github.com/osmontrouge/caresteouvert_blog/blob/master/images/Capture-d%25E2%2580%2599%25C3%25A9cran-de-2020-03-28-08-20-57.png)

And may be localised (in this example, the map is in France, with french roads names).

**Comment by pyrog** [comment]
@francois2metz does file names should be translated ?
(And config.json should be updated too)

mentions-legales.md → Impressum.md

```son
  "de": {
    "brand": "bleibtoffen",
    "brand_text": "Bleibt offen",
…
    "disclaimer": "https://blog.caresteouvert.fr/impressum/"
  }
```
