### ISSUE TITLE
Changer "Ajouter des détails si nécessaire"

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#167]
Dans la troisième étape il y a "Ajouter des détails si nécessaire" / on se retrouve avec des commentaires sans intérêts qui tranforment en note, ce qui pourrait être une contribution directe.

Peut-être "Ajouter des détails nécessaire au confinement" pour réduire encore les notes.

Éviter au max les notes avec les horaires et ceci "Des jeunes très agréables et une très bonne viande", donc derrière nécessité d'une contribution humaine.

**Comment by francois2metz** [comment]
Ok on tente ça.
