### ISSUE TITLE
Le passage de toute la partie report et discussion en anglais peut avoir des freins pour les communautés non informaticiennes

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#170]
Je ne sais pas comment faire, mais est-ce qu'il existe des moyens pour classer aussi la langue.
J'imagine des gens qui ne viendront pas signaler quoi que ce soit car en anglais !

**Comment by francois2metz** [comment]
On a toujours des issues en Français qui arrivent. Donc pour le moment ce n'a pas l'air d'être un problème.
