### ISSUE TITLE
Séparer la contribution opening_hours:covid19 et la note ?

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#171]
Si j'ai tout suivi (et si ce n'est pas le cas, désolé du bruit) :

1. je vais sur Ca reste ouvert,
2. je sélectionne un point
3. je dis qu'il est ouvert, je donne des horaires, puis livraison,
4 "Ajouter des détails nécessaire au confinement "

Le point 4, aujourd'hui quand il est rempli, fait que tout part dans une note.

Ne peut-on envoyer 1, 2, 3 dans OSM et seulement 4 dans une note et/ou description:covid19 (mais moins fan car suivi plus complexe) ?

**Comment by pyrog** [comment]
Idem si le lieux est fermé. 

@vinber c'est probablement un choix pour éviter 2 éditions successives du POI ?

**Comment by PanierAvide** [comment]
C'est bien ça, peu importe ce qui est saisi aux étapes 1/2/3, si en 4 on ajoute des détails, ça devient une note. Plusieurs raisons à ça :
- Éviter la double modification d'un POI
- Ne pas remplir le champ description:covid19 avec n'importe quoi sans vérification (on ne peut pas prédire la qualité du texte saisi et on a pas envie d'être responsable d'éventuelles dérives)
- Gérer les cas de fermetures définitives manuellement (éviter les actes de malveillance)

**Comment by pyrog** [comment]
Merci Adrien pour les précisions 😄 

Ce qui est un peu "troublant", c'est qu'on ne sais pas si la m.-à-j. se fait directement ou si une note est crée.

**Comment by vinber** [comment]
pour moi, cela permettait lorsque les commentaires sont "inutiles-sans intérêt-" de juste fermer la note et de ne pas demander à un contributeur de faire la modif des horaires par exemple.

Mais j'entends, bien que je ne comprenne pas l'enjeu d'éviter une double modification d'un POI ? Quel est l'impact ?

**Comment by PanierAvide** [comment]
C'est peut-être pas l'argument principal d'éviter la double édition, c'est pour "économiser" des groupes de modifications côté OSM.
