### ISSUE TITLE
Disparition de la sélection multiple

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#172]
Dans l'interface, je ne peux avoir qu'une catégorie.

Je trouve la sélection multiple intéressante pour optimiser une sortie (tabac, à emporter, et primeurs).
Dans la version cases à cocher, il manquait peut-être "tout sélectionner, Tout désélectionner, inverser"

**Comment by caugner** [comment]
Pour afficher toutes les catégories, tu peux simplement cliquer encore une fois sur la catégorie sélectionné.

**Comment by vinber** [comment]
merci @caugner j'avais pas compris effectivement.

Donc une ou toutes ok, je ferme
