### ISSUE TITLE
Show places selling ice cream

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#174]
**Is your feature request related to a problem? Please describe.**
* Shops selling ice cream ([`shop=ice_cream`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dice_cream), e.g. Amorino) are apparently allowed to open for takeway.
* However, they are not shown on the map yet.

**Describe the solution you'd like**
Show `shop=ice_cream` as part of the "Shops" category.

**Describe alternatives you've considered**
Alternatively, it would suffice to show those with `takeaway=true`.

**Additional context**
(None for now.)

**Comment by vinber** [comment]
> **Describe alternatives you've considered**
> Alternatively, it would suffice to show those with `takeaway=true`.

Okay, if it's only to show the shop=ice_cream with takeway=yes/only

Like you, i prefer showing all the shop=ice_cream, to encourage people to contribute

**Comment by caugner** [comment]
Once #85 is resolved, it would be possible to give feedback about `takeaway` options.

**Comment by PanierAvide** [comment]
Done
