### ISSUE TITLE
Permettre de modifier les infos de contact des POIs

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#18]
Ajouter un bouton d'édition pour permettre de changer les infos de contact d'un POI : téléphone, site internet
Je pense qu'il ne devrait pas être possible de changer opening_hours car ça ferrait doublon avec opening_hours:covid19 et pourrait porter à confusion

**Comment by vinber** [comment]
idem #19 , à mon avis pas avec un compte unique, le périmètre de modification des données devient trop important pour un compte générique #13

**Comment by PanierAvide** [comment]
On peut pas plutôt ajouter un lien d'édition vers iD ou pointer sur l'objet dans OSM ?

**Comment by overflorian** [comment]
Je comprend l'argument d'éviter l'édition depuis un compte générique : c'est en effet une situation à éviter dans la mesure du possible.
Mais malheureusement je pense qu'avec une solution qui requiert de créer un compte OSM on perd 90% des contributeurs.

Je préférerai que ces infos ne soient pas éditables plutôt que de mettre un lien direct vers iD. Une solution intermédiaire avec un message explicatif avant de renvoyer vers iD me paraît envisageable.

**Comment by francois2metz** [comment]
Est ce qu'on abandonne cette idée ? Rajouter dans le guide de contribution comment faire pour ajouter téléphone/site web/email via OSM directement ?

**Comment by PanierAvide** [comment]
On a un lien d'édition vers OSM, ça résoud le problème.
