### ISSUE TITLE
Make search results more distinguishable

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#183]
**Describe the bug**
The search results sometimes seem to contain several instances of the same item. However, these are just different places that cannot be easily distinguished.

**To Reproduce**
1. Open site.
2. Search for "Mons".
3. See many instances of "Mons, France".

**Expected behavior**
Multiple places with the same name should be distinguishable, e.g. by accompanying the names with the region (e.g. Ile-de-France), the postal code or the full address.

**Screenshots**
![image](https://user-images.githubusercontent.com/495429/78504381-1ffc7200-776d-11ea-9a83-01525dfb3234.png)

**Desktop (please complete the following information):**
(Not applicable)

**Smartphone (please complete the following information):**
(Not applicable)

**Additional context**
(Not applicable)

**Comment by caugner** [comment]
I just checked the result:

```
{
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          0.95976,
          45.74589
        ]
      },
      "properties": {
        "id": "1360314737",
        "gid": "whosonfirst:locality:1360314737",
        "layer": "locality",
        "source": "whosonfirst",
        "source_id": "1360314737",
        "name": "Mons",
        "confidence": 1,
        "match_type": "exact",
        "accuracy": "centroid",
        "country": "France",
        "country_gid": "whosonfirst:country:85633147",
        "country_a": "FRA",
        "macroregion": "New Aquitaine",
        "macroregion_gid": "whosonfirst:macroregion:1108826385",
        "macroregion_a": "AC",
        "region": "Haute-Vienne",
        "region_gid": "whosonfirst:region:85683531",
        "region_a": "HV",
        "macrocounty": "Rochechouart",
        "macrocounty_gid": "whosonfirst:macrocounty:404228177",
        "county": "Saint-Laurent-sur-Gorre",
        "county_gid": "whosonfirst:county:102069037",
        "localadmin": "Saint-Laurent-Sur-Gorre",
        "localadmin_gid": "whosonfirst:localadmin:404358299",
        "locality": "Mons",
        "locality_gid": "whosonfirst:locality:1360314737",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "Mons, France"
      },
      "bbox": [
        0.95976,
        45.74589,
        0.95976,
        45.74589
      ]
    },
```

Maybe `county` ("Saint-Laurent-sur-Gorre" in this example) and `region` ("Haute-Vienne" in this example) could be shown in grey-ish text, if the label doesn't include them.

**Comment by francois2metz** [comment]
I tried something. Tell me if it's works for you.

**Comment by caugner** [comment]
Exactly what I was thinking of, much better now, thanks a lot!
