### ISSUE TITLE
Ajouter les pépiniéristes, jardineries et autres producteurs de plants  ?

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#191]
Bonjour,
Désolé si ce n'est pas au bon endroit 

Depuis mercredi dernier (1er avril) les plants et semences à vocation alimentaire sont considérés comme de « première nécessité » pendant le confinement.
Source : https://www.ouest-france.fr/sante/virus/coronavirus/coronavirus-nantes-les-jardineries-rouvrent-pour-le-potager-6800819
Il faudrait donc peut-être ajouter les pépiniéristes, jardineries, etc.

**Comment by caugner** [comment]
Merci pour cette info, c'est tout à fait le bon endroit.

Est-ce que tu pourrais regarder dans les listes suivantes à quelles étiquettes correspondent ces magasins, par exemple `shop=garden_centre` ?

* https://wiki.openstreetmap.org/wiki/FR:Key:shop
* https://wiki.openstreetmap.org/wiki/FR:Key:amenity

Sinon, est-ce que tu pourrais trouver un établissement particulier en utilisant la recherche sur https://www.openstreetmap.org/?

**Comment by caugner** [comment]
Au fait, c'est `shop=garden_centre`, par exemple Truffaut à Paris:

* https://www.openstreetmap.org/node/1407040563
* https://www.caresteouvert.fr/@48.836942,2.373848,19.00

**Comment by caugner** [comment]
@Cybereric Merci encore une fois ! Les pépiniéristes, jardineries, etc. sont désormais affichés sur la carte.
