### ISSUE TITLE
Mention caresteouvert_backend in README

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#193]
**Is your feature request related to a problem? Please describe.**
* There is a second important repository: https://github.com/osmontrouge/caresteouvert_backend
* It is not yet mentioned in this repository, so hard to discover.

**Describe the solution you'd like**
The README should contain an overview of the project, including a link to the backend repository.

**Describe alternatives you've considered**
(Not applicable)

**Additional context**
(Not applicable)

**Comment by PanierAvide** [comment]
Right, thanks I added this to readme.

**Comment by caugner** [comment]
Thank you! And sorry for all these issues, I tend to write down everything I stumbled upon.

**Comment by PanierAvide** [comment]
No worries, it's the best way to keep track of things to do ;-)
