### ISSUE TITLE
Add issue template for "Report a missing shop category"

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#194]
**Is your feature request related to a problem? Please describe.**
If a place is missing, there are two possible explanations:

1. The place is not recorded in OSM.
2. The place is recorded in OSM, but the place type is not included in the categories.

Currently, the "Report a missing shop" link assumes 1., whereas 2. can be valid, especially when extending the map beyond France.

**Describe the solution you'd like**
1. The link should be replaced by a dialog, similar to "Learn more".
2. The dialog should explain the two possible explanations.
3. Apart from the link to the blog post, there should also be a link to a (new) issue template in this repository.
4. The issue template should ask for all required information such as:
   a. Which country?
   b. What kind of shop?
   c. URL to examplary shop on openstreetmap.org (via search result, right-click on result item).
   d. URL of caresteouvert.fr showing the area including that exemplary shop.
   e. URL to official government document explaining that the shop can be opened (optional?).

**Describe alternatives you've considered**
(None.)

**Additional context**
* Examples: #174, #191
* Related to #163

**Comment by caugner** [comment]
Once done, I will try out the issue template to request `shop=chemist` (for Germany, where they are very popular and mostly still open).

**Comment by francois2metz** [comment]
That sounds like a good idea. I'll work on it.

**Comment by caugner** [comment]
Would make sense to also mention the icon workflow: https://github.com/osmontrouge/caresteouvert/issues/240#issuecomment-610890471

**Comment by caugner** [comment]
> That sounds like a good idea. I'll work on it.

I'll submit a PR with this shortly.
