### ISSUE TITLE
Erreur d'icone et catégorie pour les garages

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#195]
**Describe the bug**
L'icone affichée pour les garages est un panier

**To Reproduce**

https://www.caresteouvert.fr/@44.836763,-0.601411,20.79/place/w156051379

**Expected behavior**

un icone "garage" : https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/car_repair.svg

**Comment by vinber** [comment]
Les garages apparaissent dans shop https://www.caresteouvert.fr/shop@44.836950,-0.599905,14.15/place/w156051379

à mon avis une catégorie station essence/ garage?

**Comment by PanierAvide** [comment]
C'est fait, j'ai créé une catégorie "mobilité" qui regroupe stations-service, boutique vélos, garages, et associé les icônes qui vont bien.
