### ISSUE TITLE
Intégrer un lien vers le générateur d'attestation numérique

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#197]
publié par le gouv le 6 avril : https://media.interieur.gouv.fr/deplacement-covid-19

Suggestion : ajouter un lien dans le menu en bas, sous "commerce manquant" avec la mention "Attestation de sortie"

**Comment by PanierAvide** [comment]
Quelle est la valeur ajouté d'ajouter ce lien ? Tu penses que beaucoup de visiteurs vont l'utiliser, et pas directement chercher sur un moteur de recherche (ou continuer avec la version papier pour ne pas être fliqué) ?

**Comment by francois2metz** [comment]
Pareil je ne vois pas l'intérêt.

**Comment by PanierAvide** [comment]
On ferme le ticket du coup ?

**Comment by overflorian** [comment]
Ok
