### ISSUE TITLE
Intégrer un lien vers les infos de santé publique

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#198]
https://www.santepubliquefrance.fr/l-info-accessible-a-tous/coronavirus
Réfléchir où intégrer ce lien ...

**Comment by PanierAvide** [comment]
On a déjà le lien vers https://www.gouvernement.fr/info-coronavirus dans le bandeau orange, ce n'est pas suffisant ?

**Comment by overflorian** [comment]
Peut-être que oui ... pour l'instant je n'ai créé cette suggestion que comme reminder ;)

**Comment by PanierAvide** [comment]
Pas d'autres retours, et pas hyper convaincu, je ferme le ticket.
