### ISSUE TITLE
No icon and label for healthcare=nurse

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#199]
* https://www.caresteouvert.fr/@46.576228,5.750187,18.51/place/n7369048286
* https://www.caresteouvert.fr/@46.572562,5.746374,17.24/place/n7369048285
* https://www.caresteouvert.fr/@43.966443,6.667435,18.26/place/n7356489007

Nothing displayed in right panel (not yet any `*:covid19` tags)
* https://www.caresteouvert.fr/@44.042351,0.137283,16.12/place/n5773243745
* https://www.caresteouvert.fr/@44.042351,0.137283,16.12/place/n5795318342

304 POI https://overpass-turbo.eu/s/Ssf

**Comment by PanierAvide** [comment]
Lié au ticket #12, sera résolu en même temps. Je me permet de fermer comme ça fait doublon.h
