### ISSUE TITLE
Intégrer les horaires de la Poste

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#20]
Depuis les données dispo ici : https://datanova.laposte.fr/explore/dataset/laposte_ouvertur/information/

**Comment by PanierAvide** [comment]
Ce sont les horaires habituels dans le fichier, pas les horaires de confinement ?

**Comment by overflorian** [comment]
Le message _" De nouveaux enregistrements sont actuellement en cours d'ajout sur ce jeu de données. Pendant la durée du traitement, les visualisations peuvent afficher des données incomplètes. N’hésitez pas à rafraîchir votre page régulièrement ! "_ qui s'affiche depuis ce matin me laisse perplexe. Revenons demain pour voir.

**Comment by PanierAvide** [comment]
Rien de nouveau de leur côté, je ferme le ticket.
