### ISSUE TITLE
Afficher tous les objets où description:covid19 est renseigné 

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#205]
Fonctionne avec `opening_hours:covid19=*` mais `description:covid19` à été oublié 😉
cf. #27

Exemple : [n7371393103](https://www.caresteouvert.fr/@46.186155,6.236906,18.66/place/n7371393103) [osm](https://www.openstreetmap.org/node/7371393103)

**Comment by PanierAvide** [comment]
Je serais quand même tenté d'ajouter systématiquement le `opening_hours:covid19=open`.

**Comment by pyrog** [comment]
Dans cet exemple j'ai la réponse, mais il existe peut être des cas où on ne sait pas ?
Ça ne mange pas de pain si tu traites aussi `description:covid19` pour afficher le POI ?

**Comment by PanierAvide** [comment]
En pratique si, on est parti sur une base monde et cette colonne n'est pas intégrée, ça va poser des questions de performance assez rapidement. Tu as une idée du volume de points concernés ?

**Comment by pyrog** [comment]
Ok 😄 

Est-ce qu'il est possible à l'intégration de mettre une valeur dans `opening_hours:covid19` ?
C'est peut-être ce que tu voulais dire en mettant `on` ?

**Comment by PanierAvide** [comment]
Dans OSM oui c'est possible ;-) Côté base de données ça va poser ces fameux soucis de performance, que ce soit fait avant ou après import/mise à jour.

**Comment by pyrog** [comment]
Je pensais que la "moulinette" qui importe les données OSM, n'ajoute pas le champ `description:covid19` dans PostgresQL, mais une valeur `"open"`, `"unknown"` ou `""` dans le champs `opening_hours:covid19` (si celui-ci est vide).

**Comment by PanierAvide** [comment]
La moulinette c'est en fait directement ImpOSM, et je ne suis pas sûr qu'on puisse lui dire ça (@vdct peux-tu confirmer ?).

Et en vrai on parle de ~70 points, qui mériteraient pour la plupart d'avoir un `opening_hours=open/same/restricted/...` en complément du champ de description.

**Comment by vdct** [comment]
On ne peut pas remplir des champs en fallback dans imposm autant que je sache. Reste le champ tags qui stocke tout, si vraiment on a besoin... mais le plus on pourra faire converger les valeurs vers un remplissage de    opening_hours:covid19 directement dans OSM, le mieux ce sera. On risque de ne pas pouvoir s'amuser souvent à recharger une base Monde

**Comment by pyrog** [comment]
> Et en vrai on parle de ~70 points

On peut effectivement les traiter manuellement. Pour le reste, il faut bien dire dans la "doc" ce qui fait apparaitre un POI sur cette carte.

Je pensais qu'un tag `*:covid19` suffisait, mais en pratique c'est plus subtil : https://github.com/osmontrouge/caresteouvert/issues/138#issuecomment-609722757

**Comment by vdct** [comment]
Désormais (depuis #497 ) la présence d'au moins un tag parmi: 
- opening_hours:covid19
- delivery:covid19
- description:covid19
- takeaway:covid19
- drive_through:covid19
- access:covid19
rend l'objet disponible
