### ISSUE TITLE
Ajout des contours Suisse & Autriche

### ISSUE THREAD

**Issue by vdct** [osmontrouge/caresteouvert#209]
@caugner : est-ce que la réglementation des ouvertures/fermetures dans ces pays se fixe au niveau du pays entier, ou par Canton/Kreis etc ? Pour savoir quel détail de limites on doit considérer

**Comment by caugner** [comment]
@datendelphin Can you tell if the rules for open shops in Switzerland are national or differ between cantons?

**Comment by caugner** [comment]
Pour l'Autriche, je viens de demander sur Twitter : https://twitter.com/ClaasAug/status/1247143579002208256

**Comment by caugner** [comment]
@vdct Pour l'Allemagne, considérez-vous le pays ou les regions (Bundesland) ?

**Comment by vdct** [comment]
@caugner for Germany we have already both country as a whole and Bundesländer

**Comment by caugner** [comment]
Perfect.

For Austria, there are national rules ([Source](https://twitter.com/viennageomeetup/status/1247154175017750533)).

**Comment by datendelphin** [comment]
For Switzerland, there are national rules with exceptions (stricter) for Ticino, where for example building sites and some factories are closed as well.

**Comment by PanierAvide** [comment]
Closing the issue as it seems to be solved by now.
