### ISSUE TITLE
Intégrer les lieux de don de sang EFS

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#21]
données sources : https://www.data.gouv.fr/fr/datasets/dates-et-lieux-des-collectes-de-don-du-sang/

Je propose de créer un nouveau type de lieu "Don de sang" en bas de liste après "services funéraires"

**Comment by krichtof** [comment]
J'ai l'impression pour arriver à intégrer les lieux de de don de sang EFS qu'on pourrait procéder comme suit :

- interroger l'api opendatabaseevent sur les 7 jours à venir : http://api.openeventdatabase.org/event/?what=health.blood.collect&when=nextweek&limit=1000

- transformer le json récupéré en csv avec ces colonnes :

nom | latitude | longitude | start | stop | where
-------|-----------|--------------|-------|--------|---------

- importer le csv en base et updater les poi

- afficher les collectes de dons de sang

Je débute en carto. Est-ce que ce plan vous parait correct ?

Est-ce que ça vous dit si je transforme le json en csv ?

**Comment by francois2metz** [comment]
Ca parait être un bon début !

**Comment by krichtof** [comment]
Le csv est par ici : https://github.com/krichtof/events-don-du-sang/blob/master/don-du-sang.csv

Si le format vous convient, je le génererai 1 fois par jour.

**Comment by francois2metz** [comment]
Ca me parait bien @krichtof 

Je propose pour avancer sur le sujet:

- ajouter l'import de ce fichier dans le cron dans une nouvelle table
- installer [Tegola](https://github.com/go-spatial/tegola) pour avoir des tuiles avec plusieurs layers 
- Afficher ca sur la carte

Mon parti pris est de mettre ça dans 2 layers, en grand partie parce que mixer les 2 données me parait bizarre et que cela me prendrais trop de temps avec mes talents ;).

**Comment by overflorian** [comment]
J'ai essayé de prendre rdv pour donner mon sang mais sur le site de l'EFS l'événement apparaît bien sur la carte mais impossible de prendre rdv.
Est-ce que quelqu'un pourrait jeter un œil sur la qualité/crédibilité de la donnée ?

**Comment by vinber** [comment]
j'étais en train d'aller voir les données, pas de réponse de data.gouv (error 500 ?)

**Comment by vinber** [comment]
> J'ai essayé de prendre rdv pour donner mon sang mais sur le site de l'EFS l'événement apparaît bien sur la carte mais impossible de prendre rdv.
> Est-ce que quelqu'un pourrait jeter un œil sur la qualité/crédibilité de la donnée ?

impossible pourquoi ? le téléphone ne marche pas, pas de réponse ?

**Comment by francois2metz** [comment]
J'ai vu un événement avec une URL de réservation. Il y a avait des créneaux d'occuper mais en scrollant un peu il y en avait de libres. Ca m'a l'air pas mal comme données.

**Comment by overflorian** [comment]
@vinber le serveur téléphonique vocal ne trouvait pas le lieu en donnant mon CP. Et idem sur la page de prise de rdv sur le site https://mon-rdv-dondesang.efs.sante.fr/collecte/liste?q=1&d=&r=3&l=&n=
Alors que sur la carte où se trouvent les lieux s'affiche bien le lieu en question (situé à Bagneux 9220) https://dondesang.efs.sante.fr/trouver-une-collecte
Et je crois que c'est ce dernier jeu de données qui est publié sur data.gouv.fr
Mais je ne suis pas allé plus loin, donc si @francois2metz pense que la qualité est suffisante alors je lui fait confiance > go

**Comment by krichtof** [comment]
Pas certain non plus de la fiabilité du jeu de données data.gouv.fr
Il est indiqué une url de l'api openeventdatabase, et je ne retrouve pas des collectes indiqués sur https://dondesang.efs.sante.fr/

https://github.com/krichtof/events-don-du-sang/issues/1

**Comment by francois2metz** [comment]
Ce fichier ne traite que de la collecte mobile. J'ai regardé les points fixe sur Paris, ce n'est pas complet http://overpass-turbo.eu/s/S6x

**Comment by pyrog** [comment]
Ne devrait-on pas intégrer manuellement ces lieux dans OSM ?

La géolocalisation sur le site de l'EFS n'est pas très précise: https://dondesang.efs.sante.fr/trouver-une-collecte

**Comment by pyrog** [comment]
Certaines données sont manquantes :

- Site **fixe** ou collecte **mobile** (pas de tag pour le préciser dans OSM)
- **Type de don** (cf. wiki : [Which components of your blood can be donated](https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dblood_donation#Which_components_of_your_blood_can_be_donated))

**Comment by pyrog** [comment]
Les données sont disponibles directement en son :

**Comment by pyrog** [comment]
@krichtof je viens de voir comment est "nourrie" l'API OpenEventDatabase pour les [données de l'EFS](https://github.com/openeventdatabase/datasources/blob/master/fr.efs/efs.py).

Il s'agit de moissonner une ["vieille" carte](https://carte.dondusang.com/#) google map qui fournit moins de détails:

```json
{
  "0": {
    "c_date": 1589234400, 
    "c_hdebutaprem": "17:00:00", 
    "c_hfin": "20:00:00", 
    "c_id": "541225", 
    "c_type": "S", 
    "div": "<p class=\"aff_ville\" style=\"background:url('https://carte.dondusang.com/imgs/markers2/rou2_ico.png') no-repeat center left;\"><a href=\"#\" onclick=\"seeBuble(0);\">12 mai. - Pagnoz</a></p>", 
    "icon": "rou2", 
    "lat": "46.97040939", 
    "lon": "5.81758118", 
    "lp_libconv": "Salle des f\u00eates", 
    "region": "015", 
    "text": "<div><div><span style=\"color:#C62B2B\">Collecte de sang total</span><br /><b>mardi 12 mai 2020</b><br /> de 17h00 \u00e0 20h00<br /></div><div id=\"gbitineraire\"><img onclick=\"javascript:iti()\" src=\"https://carte.dondusang.com/imgs/voiture.png\" alt=\"Itin\u00e9raire\" /></div><div id=\"gbadresse\">Salle des f&ecirc;tes<br />39330 PAGNOZ</div><div class=\"clear\"></div></div>", 
    "ville": "PAGNOZ"
  }, 
  "delay": 3628800, 
  "icot": 0, 
  "num_results": 1, 
  "num_sitefx": 0, 
  "t1": 0, 
  "t2": 6
}
```

On peut mettre à jour OpenEventDatabase pour obtenir ces nouveaux champs ?
Voir https://github.com/openeventdatabase/datasources/issues/10

**Comment by PanierAvide** [comment]
Ticket inactif, problème de qualité de données, l'approche serait d'améliorer les points de collectes permanents dans OSM et fiabiliser les collectes mobiles. Je ferme le ticket.

**Comment by pyrog** [comment]
Je peux exporter les lieux fixes et on peut vérifier à plusieurs leur intégration/validité ?

**Comment by PanierAvide** [comment]
En tout cas tu peux lancer le sujet sur talk-fr, voir les tags + s'il n'y a pas de soucis de licence, méthodo, ...

**Comment by pyrog** [comment]
@krichtof > transformer le json récupéré en csv avec ces colonnes
CRO peut probablement utilisé directement du JSON ?
Et plutôt que de passer par un service intermédiaire, autant modifier directement OpenEventDatabase 😉 

Cf. https://github.com/openeventdatabase/datasources/issues/10

**Comment by gendy54** [comment]
L'EFS nous renvoit vers le fichier data.gouv...
https://twitter.com/EFS_dondesang/status/1256543283179814912

**Comment by pyrog** [comment]
> L'EFS nous renvoit vers le fichier data.gouv...

On y trouve :openEventDatabase 
https://www.data.gouv.fr/fr/datasets/don-du-sang-lieux-et-horaires-des-collectes/

**Comment by pyrog** [comment]
Le fichier de Lou Dupont donne les détails manquants :
* giveBlood : Si vrai, il est possible de donner son sang dans ce lieu.
* givePlasma : Si vrai, il est possible de donner son plasma dans ce lieu.
* givePlatelet : Si vrai, il est possible de donner ses plaquettes dans ce lieu.
* groupCode : Code de groupement du lieu de prélèvement (SITEFX ou code de mobilité).

**Comment by overflorian** [comment]
Merci @pyrog pour ces infos. Je ne suis pas assez technique, j'ai donc du mal à évaluer le potentiel d'intégration des données. Quel est ton avis ?

**Comment by pyrog** [comment]
La lecture d'un fichier CSV est simple 😉 
La lecture du GeoJSON aussi 😃


`location_groupCode` et/ou `collection_groupCode` semblent être un identifiant unique du lieu de prélèvement.

Pour localiser un lieu de prélèvement, on utilise :
* soit les coordonnées du fichier.
* soit les coordonnées d'un objet OSM ayant un tag `ref:FR:EFS` avec l'identifiant du lieu de prélèvement.

Exemples :
* `A04019` — [Mairie Salle des GAVOTS](https://www.openstreetmap.org/node/2279256339?mlat=44.09299850463867&mlon=6.236283779144287#map=19/44.09325/6.23608) — 1 Boulevard Martin Bret 04000 DIGNE LES BAINS
* `P34AA1` — [TAURUS (SALLE DU TEMPS LIBRE)](https://www.openstreetmap.org/node/7474194984?mlat=43.42246627807617&mlon=3.603074550628662#map=17/43.42136/3.60305) — 15 RUE DE LA MÉDITERRANÉE 34140 MEZE
