### ISSUE TITLE
Some restaurant are displayed as "Other places"

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#216]
id | tags | display
--|--|--
[n7357761822](https://www.openstreetmap.org/node/7357761822) | amenity=restaurant<br/>cuisine=pizza<br/>**takeaway=yes** | [Restaurant](https://www.caresteouvert.fr/@46.575454,5.749831,17.45/place/n7357761822)
[n5663129779](https://www.openstreetmap.org/node/5663129779) | amenity=restaurant<br/>cuisine=pizza;burger;regional;french;sandwich<br/>delivery=no | [Other places](https://www.caresteouvert.fr/@46.576072,5.750484,17.45/place/n5663129779)
[n6567612574](https://www.openstreetmap.org/node/6567612574#map=19/46.57589/5.75052) | amenity=restaurant<br>cuisine=italian;pizza | [Other places](https://www.caresteouvert.fr/@46.576173,5.750179,18.34/place/n6567612574)
[n6204275582](https://www.openstreetmap.org/node/6204275582) | amenity=fast_food | [Other places](https://www.caresteouvert.fr/other@48.872921,2.368648,13.20/place/n6204275582)

It seem that `amenity=restaurant` + `takeaway=yes` is displayed as restaurant 😢

Issue related to #138 ?

**Comment by PanierAvide** [comment]
Exactly, only amenity=restaurant/fast_food/ice_cream + delivery or takeaway (covid19 or not) is shown in restaurant. This is too avoid showing too many restaurants which might be closed, as they should not be opened to eat-in. So we rely on delivery/takeaway tags, which may be improved on OSM as they are not so often set. Maybe we can also improve our support of tags to better handle those cases.

**Comment by pyrog** [comment]
New contributors couldn't find easily restaurant to add delivery or takeaway ?
So, I suggest to display them at least with the restaurant filter.

**Comment by wadouk** [comment]
@pyrog maybe have you not read all the answer ? Because I was like you, doesn't understand why there is so few restaurant.
>  This is too avoid showing too many restaurants which might be closed, as they should not be opened to eat-in.

**Comment by pyrog** [comment]
@wadouk I read all the answer 😉

If the map is too crowd, add an option to hide closed or unknown shop.

He plussoie 😁 
Un resto reste un resto. Ni le libellé,  ni l'icône ne doivent changer.

**Comment by PanierAvide** [comment]
So I fixed this issue by defining a new mechanism in `categories.json` : `osm_filter_tags` for tags which are not defining a category but are used to filter in a category (like delivery/takeaway for restaurants). They are handled differently, so anything having a `amenity=restaurant` tag will be marked as restaurant, but only the ones having either `opening_hours:covid19` or `delivery/takeaway/...` tags are kept.

This will be visible on website after next DB update (~1 hour).

**Comment by pyrog** [comment]
Thanks, I will try to understand the subtlety 😄

**Comment by PanierAvide** [comment]
Short version : we only keep a few restaurants (having takeaway/delivery or opening_hours:covid19), but all restaurants will have the correct category + icon as now ;-)

**Comment by pyrog** [comment]
![Restauration](https://user-images.githubusercontent.com/2158081/78912015-66144700-7a87-11ea-9b5a-81c37ce93530.jpeg)

All restaurants are visible. Thanks 😄
