### ISSUE TITLE
shop=newsagent;tobacco displayed as "Other places"

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#218]
Multivalued `shop=tobacco`, `shop=e-cigarette` or `shop=kiosk`should be displayed as "Tobbacco".

`shop=kiosk` is displayed as "Newsagent" but also [sell cigarettes](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dkiosk). (It's category is "Shops")

Examples:
tag | object
--|--
 `shop=newsagent;tobacco` | [n533515466](https://www.caresteouvert.fr/other@45.759690,4.842160,19.00/place/n533515466)
`shop=kiosk` | [n1988351351](https://www.caresteouvert.fr/shop@43.628640,3.861060,18.00/place/n1988351351)
`shop=e-cigarette`| [n5779515403](https://www.caresteouvert.fr/tobacco@48.822007,2.415346,16.63/place/n5779515403)

See #70

[Several values that should be displayed as Tobbaco](https://taginfo.openstreetmap.org/keys/shop#values)
```
tobacco
e-cigarette
kiosk
newsagent;tobacco
tobacco;newsagent;lottery
e-cigarette;tobacco
e-cigarette;mobile_phone
bag;tobacco
beverages,tobacco,alcohol
kiosk;lottery;newsagent;tobacco
lottery;weapons;tobacco
…
```

**Comment by PanierAvide** [comment]
Well support of multiple values in main tags is a pain :baguette_bread:, can't we use a single main tag (shop=kiosk or newsagent or ...) + `tobacco=yes` (2549 uses worldwide) ? This approach is already supported by our backend also.

**Comment by pyrog** [comment]
> Well support of multiple values in main tags is a pain

Welcome to OSM 😉

> can't we use a single main tag (shop=kiosk or newsagent or ...) + tobacco=yes (2549 uses worldwide) ?

Mass edit ??

**Comment by PanierAvide** [comment]
I'm not saying we should do mass edit, I just say that we only support single tag values + tobacco=yes as now. So if you are doing some edits, you might want to change on your own tags to be more reusable :grin:  Or offer a PR for handling those tricky tags :wink:

**Comment by PanierAvide** [comment]
We will not push forward support of this, as other software of OSM ecosystem don't support really well main tags with multiple values either. Best solution is still to use a single value for `shop` and complete with other tags like `tobacco=yes`.
