### ISSUE TITLE
Expand "Ça reste ouvert" data to Philippines

### ISSUE THREAD

**Issue by govvin** [osmontrouge/caresteouvert#219]
Please check the following requirements:
- [x] You are a team of at least 2 people experienced with OpenStreetMap
- [x] Translate the app via transifex with your country languages. [Filpino already merged](https://github.com/osmontrouge/caresteouvert/pull/145)
- [x] Translate some content of the blog to help newcomers (how to create a new shop, the about page, ...)
- [x] Start gathering data about shop open or closed nation wide in https://github.com/PanierAvide/Covid_enseignes/
- [ ] Once everything has been done and the data have been loaded, you should be busy getting media coverage. So the map will have a lot of contribution and be quickly useful.

Others questions:

- if you want a localized domain name, please tell us which one
- Each lockdown is different, what shops are open or closed in your country? What should be done in the category list?
  - [x] **Compiled category list from our initial [idea pad](https://hackmd.io/mbQ7Im8XRH-sFHfZT5jUoQ)**: 
[caresteouvert-ph.csv.txt](https://github.com/osmontrouge/caresteouvert/files/4443078/caresteouvert-ph.csv.txt)

## Team
- `GOwin`
- `DearPaul24`
- `Mapbeks`

**Comment by francois2metz** [comment]
Hi @govvin. I hope you are safe! 

Thanks for your interest!

About the localized domain name, we may be cancel this part, as it's complicated to manage on our side. But we'll have an international name.

**Comment by francois2metz** [comment]
@vdct Do we have the philippines boundary yet?

**Comment by govvin** [comment]
Have you seen the OSM Community index [repo](https://github.com/osmlab/osm-community-index/tree/master/resources) ? You might find it interesting for simple,  un-official boundaries, and side step the question of whether this or that boundary is "official" or not.

If that doesn't work, I'll get you another.

**Comment by vdct** [comment]
Thank you @govvin

**Comment by caugner** [comment]
@vdct Is there anything blocking the addition of `PH` to the categories? I keep forgetting all the steps.

**Comment by vdct** [comment]
@caugner my commits only take care of the geo boundaries of PH in order to flag all OSM objects with country code in our database. This part is now merged into master branch.
Other matters to enable PH including categories should be discussed with @PanierAvide and @francois2metz

**Comment by govvin** [comment]
Thank you for the update.

@PanierAvide  and @francois2metz, kindly let me know what else is needed from our end to get this moving forward.

**Comment by PanierAvide** [comment]
Can you complete https://github.com/PanierAvide/Covid_enseignes to add major brands and their opening state ?

**Comment by francois2metz** [comment]
@govvin Could you send me an email to francois [at] 2metz [dot] fr or a tweet to twitter.com/francois2metz/ so I can send you an invite team a private discussion forum.

**Comment by francois2metz** [comment]
@govvin Where you could we find the localized blogs posts? Could you create them in the repository under the `~/articles/tl`.

**Comment by govvin** [comment]
@francois2metz , i have a [PR](https://github.com/osmontrouge/caresteouvert/pull/415) for the localized how-to, including a generic English guide.

**Comment by francois2metz** [comment]
@govvin good job!

**Comment by govvin** [comment]
> @govvin good job!

Thank you! By the way, do you know when the data in the Philippines will be made active? We'd like to make plans to promote it.

**Comment by PanierAvide** [comment]
So database is being updated, normally this will be live in ~1h.

**Comment by PanierAvide** [comment]
Closing the issue as it is live and working.

**Comment by govvin** [comment]
Thank you!
