### ISSUE TITLE
Orthographe  et texte barre latérale

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#222]
Une correction à faire dans la barre latérale gauche : « Services financier »  s'écrit avec un **s** (il y a plusieurs services).
Donc « Services financier**s** »

Sinon une précision s'impose je crois à propos de la restauration.
Il faudrait ajouter  le mot **emport** je pense sinon on risque de penser les restaurants ouverts.
Donc quelque chose comme « **Restauration (emport)** » serait pas mal je trouve.

**Comment by PanierAvide** [comment]
Bonjour,

Pour l'orthographe ça avait déjà été corrigé sur Transifex, et c'est bien visible sur le site. Peut-être vider le cache pour que ça soit mis à jour de votre côté ?

Pour le nommage des catégories, il me semble qu'un travail est en cours ici #146 je vous invite à vous joindre à la conversation entamée.

Cordialement.
