### ISSUE TITLE
drive adossé à un commerce

### ISSUE THREAD

**Issue by Al-Hun** [osmontrouge/caresteouvert#223]
Certains drive sont totalement autonomes (aucun commerce dans lequel on pénètre), mais certains fonctionnent en complément d'un commerce : ils ont parfois des horaires propres.
Comment les saisir sans devoir créer un nouveau pseudo-commerce ? Si le commerce a le tag drive_through=yes on aurait alors un doublon. 

- Un tag opening_hours:drive_through:covid19 sera-t-il pris en compte ? A doubler d'un drive_through:covid19=yes (une seule utilisation actuellement sur taginfo) pour indiquer un drive spécifique à la période de confinement ?
- A intégrer dans l'interface d'édition de la carte ?

**Comment by francois2metz** [comment]
Bonjour !

Pour avoir regardé un peu l'usage des tags [delivery](https://wiki.openstreetmap.org/wiki/Key:delivery) et [takeaway](https://wiki.openstreetmap.org/wiki/Key:takeaway) pour le formulaire de contribution, je proposerai de tagger avec  `drive_through:covid19` et comme valeur les horaires d'ouverture. Cela reste des valeurs très minoritaires mais intéressantes.

A voir en terme d'usage si on veut pousser ce tag ou non. Je ne connais pas ce type de magasins, peux tu donner des exemples pour nous guider ?

**Comment by PanierAvide** [comment]
+1 pour `drive_through:covid19`. Quelques exemples de drives adossés à un commerce :
- Drive ajouté à un petit supermarché (coin de parking réservé, les salariés prennent les produits dans les rayons comme les clients)
- Pharmacies
- Boulangeries
- Restauration rapide (horaires drive étendus par rapport à la restauration en salle)
- ...

**Comment by PanierAvide** [comment]
L'affichage des infos de `drive_through:covid19` est désormais pris en compte (visible sur le site d'ici quelques minutes), et pour les tags bien suivre la recommandation décrite ici : https://wiki.openstreetmap.org/wiki/FR:Key:opening_hours:covid19#Livraison.2C_vente_.C3.A0_emporter.2C_drive
