### ISSUE TITLE
shop=pasta et shop=cannery dans "Autres établissements" au lieu d' "Alimentation"

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#224]
[shop=pasta]  et [shop=cannery]  apparaissent dans la rubrique "Autres établissements" au lieu d' "Alimentation"

[shop=pasta] avec filtre "Autres établissements"
https://www.caresteouvert.fr/other@47.221381,-1.558451,19.41

[shop=cannery] avec filtre "Autres établissements"
https://www.caresteouvert.fr/other@47.213705,-1.558937,19.45

**Comment by PanierAvide** [comment]
Ajouté, ce sera visible d'ici ~1h
