### ISSUE TITLE
Avoir une barre latérale multi-catégories ?

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#225]
Tout est dans le titre.
Je crois que cela pourrait être utile non ?

![barre laterale multi criteres](https://user-images.githubusercontent.com/7645549/78653282-34eb1980-78c3-11ea-8bf2-4b21efaaefea.png)

**Comment by wadouk** [comment]
Ça été fait exprès, avant y avait des cases à cochées https://github.com/osmontrouge/caresteouvert/issues/112

**Comment by Cybereric** [comment]
Euh oui je sais pour les "cases à cocher"...ça fait plus de 15 jours que je suis ça **;-)**

Je trouve qu'il serait pratique de pouvoir sélectionner plusieurs catégories en même temps.

Imaginons que je je doive aller à la pharmacie, au bureau de tabac et aussi acheter à manger.

Je ne sais pas où se trouvent les pharmacies les plus proches ni quels sont les bureaux de tabac ouverts (on suppose que je sais où aller faire mes courses alimentaires) 
Dans ce cas j'aimerais bien pouvoir afficher "ensemble" les catégories qui m'intéressent et de cette manière pouvoir trouver dans les environs de ma supérette, un bureau de tabac et une pharmacie.
Si je suis sans arrêt à basculer d'une catégorie à l'autre ce n'est pas pratique pour chercher des choses.

Les exemples choisis correspondent à l'image postée ci-dessus.

**Comment by overflorian** [comment]
Following https://github.com/osmontrouge/caresteouvert/issues/316 @sfkeller proposal:

I think we should first ask ourselves "**what are we trying to solve ?**".
I agree that "It's inevitable that more and more categories (and subcategories) are coming up (see e.g. #315)" and that we need to find a way for the user to a more way to filter the categories.

In my point of view, selecting multiple categories doesn't solve this in any way.

**I propose a use case: "a smoker needs to find tobacco".**
-Currently: select "tobacco" displays shop=tobacco and shop=e-cigarette 
-What we need: an extra filter to split the tobacco/e-cigarette, displayed ONLY when the main "tobacco" category is selected.

I made a small benchamarck for the record:

1. [Rue du commerce](https://www.rueducommerce.fr/rayon/ordinateurs-64/pc-portable-gamer-8032)

![image](https://user-images.githubusercontent.com/11553211/79325561-a6554880-7f11-11ea-81c4-3139c3575882.png)

Only 1 main category is selectable at the time, multiple sub-categories are selectable (with a tick-box)

2. [LDLC](https://www.ldlc.com/informatique/pieces-informatique/disque-dur-interne/c4697/+fp-l413h775+fv32-10306+fv892-5091.html)
Mix a drop-down menu AND tick-boxes :
![image](https://user-images.githubusercontent.com/11553211/79326036-79556580-7f12-11ea-9966-6010d9b2c193.png)

3. Qwant Maps
![image](https://user-images.githubusercontent.com/11553211/79325817-1e237300-7f12-11ea-9a84-34e1b728d0bf.png)

While selecting a main categorie, the filters disapear for a detailled list of close POIs
![image](https://user-images.githubusercontent.com/11553211/79325907-4a3ef400-7f12-11ea-987f-bfac9450be78.png)

4. Google Maps
![image](https://user-images.githubusercontent.com/11553211/79326155-b0c41200-7f12-11ea-886b-79af09d2be39.png)
A very limited amount of categories is displayed; This forces the user to use the search bar.
While a category is searched, a list of POIs is displayed, like Qwant Maps.
An extra "filter" button is sometimes available (depending on the category):
![image](https://user-images.githubusercontent.com/11553211/79326276-dfda8380-7f12-11ea-81cf-d46304e1fb4d.png)

### My proposal ([in complement to a previous one](https://github.com/osmontrouge/caresteouvert/issues/144))
1. Keep the limited amount of categories as it is
2. Allow POI search in the search bar https://github.com/osmontrouge/caresteouvert/issues/103
3. While a category is selected (from the search bar of from the categories list), it appears as searched in the search bar, and the other categories disappear, like on Gmaps: 
![Screenshot_20200415-122115](https://user-images.githubusercontent.com/11553211/79327063-2086cc80-7f14-11ea-8d9a-3dc7632ae504.jpg)

At the top, sub-categories appear. 
For our use-case: it would be "tobacco" and "e-cigarette".
We should display them as "floating button, like that:
![image](https://user-images.githubusercontent.com/11553211/79328007-ae16ec00-7f15-11ea-997c-4b8b48862458.png)


An "advanced filters" button allow the user to search for specific options, like on Gmaps:
![Screenshot_20200415-122125](https://user-images.githubusercontent.com/11553211/79327192-4f9d3e00-7f14-11ea-9612-caa7cab53736.jpg)
Options could be specific to POI types: delivery only, currently open, less than 1km away from me, contact-less payment...

PS: for the record I don't think Github is a good place to discuss UI evolution. This tool is not adapted for UI design work. Do you guys use any wireframe tool that we could use?

**Comment by sfkeller** [comment]
My main point of #316 was the counter-intuitive way in the current UI to reset the filter.
Having a button "X" to reset could be a solution.

**Comment by francois2metz** [comment]
I added a smal icon to make the reset filter clearer. Not sure it will stay with subcategories, but that's a start.

![Screenshot_2020-04-15 Ça reste ouvert](https://user-images.githubusercontent.com/86659/79335585-8aa66e00-7f22-11ea-8107-3b085e41ec49.png)

**Comment by wadouk** [comment]
Have a text field that handle addresses and categories looks me complicated.
+1 for subcategories like discussed in #103 should maybe do the job.

The cross that switching off the categorie should be moved to the selected sub category.

Categories re-order to the top should be a "nice to have" but work well on desktop screen but could be disturbing on mobile. It's usefull with long lists on e-commerce site but is it the case here ?

**Comment by francois2metz** [comment]
Here is 3 propositions to manage the categories and subcategories. They are not finished. It's only to test the interactions.

1. Only category can be selected at a time with the subcategories that appear to filter down the POIs

![subcategories](https://user-images.githubusercontent.com/86659/79364293-73c74200-7f49-11ea-9e7f-a58616de09e4.gif)

2. You can have multiple categories/sub categories selected. A click select the category and display the subcategories. A click on the subcategories will filter down the POIs

![subcategories2](https://user-images.githubusercontent.com/86659/79364652-f223e400-7f49-11ea-9a82-2032d9ae0b0d.gif)

3. You can have multiple categories/sub categories selected. The categories/sub categories selected appears on top. Only one category is displayed to keep the list manageable.

![subcategories3](https://user-images.githubusercontent.com/86659/79364847-2e574480-7f4a-11ea-94a9-a6f3ba80faa5.gif)

Search is not handled there.

**Comment by wadouk** [comment]
Need to be tested on mobile but that's just awesome, a-ma-zing like someones says !

I will vote for 2

**Comment by Cybereric** [comment]
J'ai fait ça il y a deux jours. 
C'est l'idée que j'avais lorsque j'ai lancé le sujet.  Cela rejoint l'animation n°2 précédente.

![menu lateral multi selection](https://user-images.githubusercontent.com/7645549/79397905-98d6a780-7f7f-11ea-843a-d238c0dbd9ef.png)

**Comment by francois2metz** [comment]
I have something working on https://covid19-fr-map-pr385.osc-fr1.scalingo.io/

Frankly, I'm not a big fan of it (only works well on desktop for now)

**Comment by wadouk** [comment]
just tried on mobile. expecting to keep the side bar open but reclick on it
and it do the job : only view the filtered points and like it.

why are you not a big fan ?

Le jeu. 16 avr. 2020 à 15:33, François de Metz <notifications@github.com> a
écrit :

**Comment by francois2metz** [comment]
To lower the complexity, I implemented a single selectable category with subcategory here: https://covid19-fr-map-pr391.osc-fr1.scalingo.io/@48.814775,2.320768,16.37

**Comment by wadouk** [comment]
on mobile sliding seems to me less friendly to use. maybe if the labels
should be bigger it should be easier to click. or buttons to move left /
right.
but I like the surprise to see sub categories directly visible on map.
but definetivly it's easier to me to click in the sidebar.

in first version, only sidebar, later direct access by categories bubble ?
maybe only displaying icons ?
I try to prevent sliding. to have a sliding usable maybe it should have
some inertia ?




Le jeu. 16 avr. 2020 à 19:38, François de Metz <notifications@github.com> a
écrit :

**Comment by wadouk** [comment]
for the first test app, doesn't see the use case to have multiple
subcategories not in same category selected. is it what you call more
complicated ?
