### ISSUE TITLE
Rephrase "Place allowed to open during lockdown." more carefully

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#230]
Right now, the website is very confident when claiming

> Place allowed to open during lockdown. Open or closed ? Let us know 

There are two main reasons why this statement can be misleading or wrong:

1. Our rules could be wrong or outdated.
2. Our rules could be not specific enough, e.g. a place could only allowed to open under certain constraints (e.g. takeaway/delivery only, for professionals only).

**Solution**: Rephrase the statement more carefully, for example:

> We think that this place is allowed to open during lockdown. Restrictions may apply.
> Can you tell us more?

**Comment by PanierAvide** [comment]
This has been changed

**Comment by caugner** [comment]
Hm, I find that "legal right" is a strong statement. That's why I preferred to use the friendly version "We think that this placed is allowed to open...". :/

**Comment by caugner** [comment]
Also it's not really correct for restaurants. Restaurants are not allowed to open, they are just allowed to provide delivery and takeaway services. That's not the same.
