### ISSUE TITLE
Display categories and governement info depending of the current country

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/caresteouvert#231]

**Comment by PanierAvide** [comment]
Implementation of finding country in API done https://github.com/osmontrouge/caresteouvert_backend/commit/35ab09c1a3083701fc378b11ae207ca442016e19

**Comment by PanierAvide** [comment]
Logique d'implémentation d'un mécanisme similaire dans Gribrouillon :
- On demande le pays à l'API + stocke la position initiale = filterPosition
- À chaque mouvement de carte, on vérifie la distance du centre de la carte  par rapport à filterPosition
- Si la distance est supérieur à n kilomètres, on redemande à l'API le pays, et met à jour filterPosition

Cf https://framagit.org/PanierAvide/gribrouillon/-/blob/master/src/website/index.js#L652
