### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#234]
**Is your feature request related to a problem? Please describe.**
The map shows icons in three colors: green, grey, red.
However, it doesn't explain though what they stand for.

**Describe the solution you'd like**
It would be nice to have a legend shortly describing the colors.

**Describe alternatives you've considered**
The map icons could have a tooltip that explains it.

**Additional context**
(This came up in a user feedback discussion.)

**Comment by PanierAvide** [comment]
@overflorian where can we display the legend ? Only on desktop or also on mobile ?

**Comment by overflorian** [comment]
For mobile I think we should display it in the infinite bar, as suggested https://github.com/osmontrouge/caresteouvert/issues/444
For desktop I guess we should display it directly on the "about" popup but I'm not that convince myself.

**Comment by francois2metz** [comment]
I'm not really convinced that we need a legend.

**Comment by PanierAvide** [comment]
When showing a map (either paper or web), it's a good practice to have a legend somewhere, especially if we display color-based categorization like we do.

**Comment by PanierAvide** [comment]
With recent changes of POI list shown on left sidebar, it is clear enough what colours mean so we can consider it as a legend. Closing the issue.
