### ISSUE TITLE
Ajouter des balises SEO / social media sur la homepage

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#236]
Lorsque l'on partage l'URL du site, aucune info autre que le titre n'est ajoutée.
C'est parce qu'il manque les balises dans le header pour 1. le SEO (texte seul) 2. le partage sur les réseaux sociaux (dont visuel).

Concrètement le code ressemble à ça (mais il faut le tweeker) :

```
<meta property="og:url"                content="http://www.nytimes.com/2015/02/19/arts/international/when-great-minds-dont-think-alike.html" />
<meta property="og:type"               content="article" />
<meta property="og:title"              content="When Great Minds Don’t Think Alike" />
<meta property="og:description"        content="How much does culture influence creative thinking?" />
<meta property="og:image"              content="http://static01.nyt.com/images/2015/02/19/arts/international/19iht-btnumbers19A/19iht-btnumbers19A-facebookJumbo-v2.jpg" />
```

Les guides développeurs complets :
https://support.google.com/webmasters/answer/35624
https://developers.facebook.com/docs/sharing/webmasters
https://developer.twitter.com/en/docs/twitter-for-websites/overview

Ossiann a produit les images de partage aux bonnes dimensions :
- Facebook
![partage-web-facebook](https://user-images.githubusercontent.com/11553211/78662760-4e935d80-78d1-11ea-8228-6660eccbab36.jpg)

- Twitter
![partage-web-twitter](https://user-images.githubusercontent.com/11553211/78662762-4f2bf400-78d1-11ea-9775-ce4f7435e091.jpg)

Je pourrai produire le code entier mais quelqu'un de plus technique sera sûrement plus rapide que moi.
Wording proposé (en suivant le guide https://www.wearethewords.com/conseils-seo-meta-description) :
TITLE : Ça reste ouvert - Les lieux ouverts durant le confinement
DESCRIPTION : La carte collaborative des lieux ouverts durant le confinement. "Ça reste ouvert" est l'outil indispensable pour vous éviter tout déplacement infructueux.

**Comment by wadouk** [comment]
On est d'accord que si la page est blanche sans javascript derrière, en terme de SEO, ça pue ? En terme de partage social c'est moins pire ?

**Comment by overflorian** [comment]
Je ne suis pas certain de comprendre ta question. Sur la home on peut mettre le header sans que l'activation / désactivation du javascript sur la page n'ai la moindre conséquence.

**Comment by wadouk** [comment]
Je pense que c'est parce que je pinaille sur le terme de SEO ... Ou que je n'ai pas la même/bonne définition. Pour moi le Search Engine Optimisation est de comment un robot d'un moteur de recherche indexe une page. Dans cette optique, on m'avait appris que bourrer les balises meta avec des infos sans présence dans la page n'allait pas favoriser le ranking, au contraire. 

Là tu parles des balises OpenGraph ou social sharing qui sont visible lors d'un partage (point 2), du coup pour moi ça s'apparente au bourrage du header évoqué ici ce qui pourra donc nuire au ranking (SEO) du site.

Du coup je me posais la question, vu qu'on est sur une single page application entièrement cliente (SPA) sans aucun rendu serveur (sans JS) si le faite du contenu à destination des partages des réseaux sociaux, si ça allait pas induire un effet négatif sur le référencement du site (qui actuellement n'est basé que sur les liens externe) donc en fait j'en arrive à la conclusion que le référencement en terme de SEO ne doit pas être terrible de toute façon, qu'on est encore loin du Optimisation. Je suis bien en train de faire de la sodomisation de diptère.

**Comment by wadouk** [comment]
Tu dois pouvoir traiter le truc sans dev en faisant une PR en modifiant ce fichier (petit crayon en haut à droite)
https://github.com/osmontrouge/caresteouvert/blob/master/index.html

**Comment by PanierAvide** [comment]
C'est intégré
