### ISSUE TITLE
Ajouter un rayon d'1km autour de l'utilisateur

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#24]

**Comment by francois2metz** [comment]
Dans le cadre de recherche de commerces, ce rayon de 1km n'est pas utile. Est ce qu'on veut tout de même faire ça ?

**Comment by PanierAvide** [comment]
Pareil, aucun intérêt en péri-urbain ou campagne pour la recherche de commerces/services où le rayon de 1km est insuffisant

**Comment by vdct** [comment]
D'accord pour ne pas l'ajouter si ça entretient la confusion entre rayon autorisé *pour l'exercice physique* et sortie à des fins utilitaires

**Comment by overflorian** [comment]
et si on avait un rayon plus précis ? ce projet open source me paraît très cool https://observablehq.com/@pierreleripoll/bulle-de-confinement on pourrait imaginer un bouton ad-hoc pour activer cette fonctionnalité

**Comment by PanierAvide** [comment]
Le projet indiqué ne fonctionne que dans un ensemble de grandes villes.

**Comment by overflorian** [comment]
ok ok, j'avoue c'est un peu expérimental encore. Mais le dev a l'air motivé, est-ce qu'on lui demande une couverture de la France ou est-ce qu'on abandonne la feature ?

**Comment by PanierAvide** [comment]
Perso je suis pas convaincu, mais à voir avec d'autres.

**Comment by overflorian** [comment]
ok abandonnons alors
