### ISSUE TITLE
Missing category: Chemist (de: Drogerie)

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#240]
**Is your feature request related to a problem? Please describe.**
In Austria, Germany and Switzerland, we have so-called "Drogerien" ([`shop=chemist`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dchemist)) as an important category of shops still open during lockdown. 

`shop=chemist` is also used in France and Spain, see examples below.

Note: In France ([Example](https://www.openstreetmap.org/node/2498267590)) and Spain ([Example](https://www.openstreetmap.org/node/3011015936)), some places are tagged as `shop=chemist` **and** `amenity=pharmacy`!

**Describe the solution you'd like**
All `shop=chemist` places should also be displayed in the map, ideally as an independent category (for German-speaking countries).

**Describe alternatives you've considered**
For now, we could add them to "Pharmacy" or "Shops", and create a category later for German-speaking countries only.

**Additional context**
* Icon: https://wiki.openstreetmap.org/wiki/File:Chemist-14.svg
* Wikipedia: https://de.wikipedia.org/wiki/Drogerie
* Examples:
  * Austria: https://www.openstreetmap.org/node/1326672630
  * Germany: https://www.openstreetmap.org/way/503037489
  * Switzerland: https://www.openstreetmap.org/node/4486137538
  * France: https://www.openstreetmap.org/node/916979673
  * Spain: https://www.openstreetmap.org/node/3794003908

**Comment by caugner** [comment]
@francois2metz 

* What happens if a place falls into two categories, which category is taken?
* Would `amenity=pharmacy` win over `shop=chemist`?
* Does it depend on the order in the `categories.json`?

**Comment by francois2metz** [comment]
> @francois2metz
> 
>     * What happens if a place falls into two categories, which category is taken?
>     * Would `amenity=pharmacy` win over `shop=chemist`?
>     * Does it depend on the order in the `categories.json`?

As the SQL is generated from the `categories.json` file, the POI with the first winning condition will have that category.

> All shop=chemist places should also be displayed in the map, ideally as an independent category (for German-speaking countries).

We can do this.

**Comment by caugner** [comment]
@francois2metz Where exactly do you look for the grayscale icons and how to you convert them to the desired size?

Example: https://github.com/osmontrouge/caresteouvert/commit/2bdc4ab0dddc66b84bc93206616ba16d40e93fbe#diff-fc23fe7e0bd5dda9c38b9bb1ac3de2f9

**Comment by francois2metz** [comment]
Most of them come from https://github.com/gravitystorm/openstreetmap-carto. And use inkscape to resize them (and save them as optimized svg).

> All shop=chemist places should also be displayed in the map, ideally as an independent category (for German-speaking countries).

Should we really add them as a top level category?

**Comment by caugner** [comment]
> Most of them come from https://github.com/gravitystorm/openstreetmap-carto. And use inkscape to resize them (and save them as optimized svg).

Perfect, thank you!

> Should we really add them as a top level category?

For AT/DE/CH yes, it's really a *very* important category there. We almost have as much "Drogerien" as bakeries.

But for now we can add it to "shops", and adjust the categories for AT/DE/CH later.

**Comment by francois2metz** [comment]
> For AT/DE/CH yes, it's really a _very_ important category there. We almost have as much "Drogerien" as bakeries.

:open_mouth:
