### ISSUE TITLE
Improve zoom-in chip

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#242]
**Is your feature request related to a problem? Please describe.**
* We show a chip titled `Zoom in to display opened places` since #156.
* Unfortunately the chip is currently hidden by the cookie warning.

**Describe the solution you'd like**
1. Could we show the chip  at the top of the map OR at the center of the map OR above the cookie warning?
2. Could the chip be clickable, setting the zoom level to the minimal required zoom level to show POIs?

**Describe alternatives you've considered**
See above.

**Additional context**
(None.)

**Comment by francois2metz** [comment]
Not sure I want to put it in another place. But I implemented the click on it, it's a nice addition.

**Comment by caugner** [comment]
Could maybe the cookie banner "consume" the space so that the chip would automatically be shown above?

**Comment by francois2metz** [comment]
> Could the cookie banner "consume" the space so that the chip would automatically be shown above?

I would love if you could do that.

**Comment by caugner** [comment]
> Not sure I want to put it in another place.

Just saying: `margin-bottom: 50vw` would basically center it.
