### ISSUE TITLE
Define language by URL

### ISSUE THREAD

**Issue by jmontane** [osmontrouge/caresteouvert#243]
AFAIK, « Ça reste ouvert » uses:
1.- If cookie exists, use lang defined.
2.- If supported, uses web browser's declared language

I request to add a feature to define/force IU language via URL. It  would be useful when « Ça reste ouvert » will be used worlwide.

Thanks

**Comment by francois2metz** [comment]
Hi, thanks for your suggestion.

What problems does it solves?

**Comment by jmontane** [comment]
Not all users have accept-lang properly configured, or they have an unsupported language. But If I can send https://www.caresteouvert.fr/?lang=xx (or whatever URL forcing UI language) to my friend or community, then a better first experience is achieved.

**Comment by francois2metz** [comment]
We now have something similar in production based on the domain. 

- caresteouvert.fr for french
- www.bleibtoffen.de for de
- sigueabierto.openstreetmap.es for es
- ...

See the `config.json` file.
