### ISSUE TITLE
Intégrer la vidéo de présentation

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#246]
avec un iframe :
`<iframe width="560" height="315" sandbox="allow-same-origin allow-scripts" src="https://peertube.openstreetmap.fr/videos/embed/8aaf2c5e-4fc4-4303-bd26-901e159259a0" frameborder="0" allowfullscreen></iframe>`

Suggestion : dans la fenêtre "en savoir plus"
je l'ai déjà rajouté sur la page /à propos

**Comment by Cybereric** [comment]
Bonjour 

Il faut juste corriger un petit quelque chose dans la vidéo ;-)

![ortho vidéo](https://user-images.githubusercontent.com/7645549/78888728-7f56cc80-7a62-11ea-8c32-e36db46a86dc.png)

Autre remarque :
l'écran **"où et quand"** passe beaucoup trop vite on a pas vraiment le temps de lire !

**Comment by PanierAvide** [comment]
Je crois que l'idée d'intégrer dans le à propos avait été écartée lors des discussions, je ferme le ticket.
