### ISSUE TITLE
Intégration bureaux de poste ouvert (FR)

### ISSUE THREAD

**Issue by Bibi56** [osmontrouge/caresteouvert#248]
**Is your feature request related to a problem? Please describe.**
La Poste diffuse les données d'ouverture sous deux formats
Un [format](https://www.laposte.fr/particulier/outils/trouver-un-bureau-de-poste) orienté utilisateur (si j'ose dire) pour trouver les bureaux ouverts mais sans licence claire.
Un format API qui semble utilisable avec un [jeu de données](https://datanova.legroupe.laposte.fr/explore/dataset/laposte_ouvertur/information/?sort=-date_calendrier&lang=fr&q=10177A&rows=1&dataChart=eyJ0aW1lc2NhbGUiOiIiLCJxdWVyaWVzIjpbeyJ4QXhpcyI6ImpvdXIiLCJzb3J0IjoiIiwibWF4cG9pbnRzIjo1MCwiY2hhcnRzIjpbeyJ5QXhpcyI6IiIsImZ1bmMiOiJDT1VOVCIsImNvbG9yIjoiIzJmN2VkOCIsInR5cGUiOiJjb2x1bW4iLCJzY2llbnRpZmljRGlzcGxheSI6dHJ1ZX1dLCJjb25maWciOnsiZGF0YXNldCI6ImxhcG9zdGVfb3V2ZXJ0dXIiLCJvcHRpb25zIjp7fX19XSwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZX0%3D) actualisé et en ODbL.

**Describe the solution you'd like**
Récupérer les données soit à la volée, soit en les cachant, sachant que les données varient rapidement cache du jour courant maxi ?

**Describe alternatives you've considered**
Utilisation de la version citée par @pyrog sur talk-fr.

**Additional context**
Soit le bureau de la poste de Guidel, identifiant [ref:FR:LaPoste](https://wiki.openstreetmap.org/wiki/Key:ref:FR:LaPoste?uselang=en)=10115A dans [OSM](https://www.openstreetmap.org/node/1371288111).
Nous sommes mercredi soit le troisième jour de la semaine. Prenons donc le premier élément en décalant de 2 (3-1) jours.
Ce qui donne l'url :
https://datanova.legroupe.laposte.fr/api/records/1.0/search/?dataset=laposte_ouvertur&q=10115A&lang=fr&rows=1&start=2&sort=-date_calendrier
On obtient : 
clé | valeur
--|--
date_calendrier|"2020-04-09"
bp_plage_horaire_1|"FERME"
plage_horaire_1|"FERME"

La date permet de vérifier qu'on ne s'est pas trompé et qu'on a récupéré le bon élément.

Même topo avec La Poste de Plœmeur :
https://datanova.legroupe.laposte.fr/api/records/1.0/search/?dataset=laposte_ouvertur&q=10177A&lang=fr&rows=1&start=&sort=-date_calendrier
On obtient : 
clé | valeur
--|--
plage_horaire_1|"09:00-12:30"
bp_plage_horaire_1|"09:00-12:30"
plage_horaire_2|"13:30-17:00"
bp_plage_horaire_2"| "13:30-17:30"

(les plages horaires vont de 1 à 7 maximum)

@pyrog, je répnds à ta question sur Disqus : oui, la preuve.

**Comment by pyrog** [comment]
What mean data integration ?
*Just displaying opening hours in CRO ?
*Update OSM database ?

**Comment by Bibi56** [comment]
Updating the database would mean potentially updating daily for the next 7 days to have a meaningful date range.
I think we can spit into 2 parts:
- offices closed during the 7 first days (as of today) => opening_hours:covid19=off. Could be some false positive due to work but if the office is temporary closed for renovation, it will stay closed during the next days too!
- office not closed during the 7 first days (as of today): here 2 possibilities, do it likewise or "just" in CRO. As next Monday is Easter Monday, we would create wrong weekly dates.
For CRO the request would be (in pseudo code):
https://datanova.legroupe.laposte.fr/api/records/1.0/search/?dataset=laposte_ouvertur&q= **{{ref:FR:LaPoste}}**&lang=fr&rows=**7**&start=**zero_based_weekday**&sort=-date_calendrier

**Comment by pyrog** [comment]
> Updating the database

Which one ? CRO or OSM ? :wink:

**Comment by Bibi56** [comment]
> Which one ? CRO or OSM ? wink

OSM of course.

**Comment by PanierAvide** [comment]
No more feedback, closing the issue.
