### ISSUE TITLE
Chaine de traduction de contact sur les assurances

### ISSUE THREAD

**Issue by QuentinS33** [osmontrouge/caresteouvert#255]
Bonjour,
En m'amusant un peu en changeant les langues de l'application, j'ai remarqué que pour les assurances, une mention informe que : "Contact par téléphone possible"
J'ai changé la langue en mettant "Espagnol" et j'ai toujours cette chaine de caractères qui s'affichent.
En allant sur Transifex, la page espagnol indique que 100% des chaînes ont été traduites.
Je pense donc à un oubli dans le code d'appeler la fonction "translate" envers toutes les langues afin que cette chaine puisse être traduite

Quentin

**Comment by PanierAvide** [comment]
Si c'est dans l'encart bleu du bandeau de droite, ce sont des textes qui viennent soit de https://github.com/PanierAvide/Covid_enseignes soit directement de l'objet en lui même (tag OSM `description:covid19`). Ces textes sont exprimés dans la langue locale du pays. Pour traduire côté OSM il faudrait ajouter les déclinaisons type `description:covid19:es` et autres, ça devient vite complexe à gérer.

**Comment by QuentinS33** [comment]
Il n'y a aucune description sur l'objet OSM en lui-même. Cela vient de Covid-enseignes.
Sachant que c'est du texte générique (= pas de présence de tag description covid19), une traduction serait-il envisageable ?

**Comment by PanierAvide** [comment]
Comme côté covid_enseignes on est sur un fichier CSV, ça va nécessiter une machinerie assez lourde pour extraire les libellés, les envoyer sur Transifex, récupérer les traductions et les ré-insérer dans le CSV. J'ai l'impression que l'énergie à déployer est assez considérable pour une valeur ajoutée relativement faible. Mais si quelqu'un propose une pull request, je ne suis pas contre l'intégration.

**Comment by QuentinS33** [comment]
Je comprends, surtout que c'est pour un cas français. Que se passerait-il pour la même marque mais présente dans un pays étranger non francophone. Verrait-on cette bande bleue écrite en français ?

**Comment by PanierAvide** [comment]
Les règles dans covid_enseignes sont décrites pays par pays, donc si une enseigne française est présente en espagne, le descriptif sera écrit en espagnol pour la branche espagnole. Voir https://github.com/PanierAvide/Covid_enseignes/blob/master/rules.csv

**Comment by QuentinS33** [comment]
D'accord, je ne connais pas les règles dans les autres pays. Mais merci pour l'information.
Désolé pour ma réponse tardive
