### ISSUE TITLE
Display source of opening hours during lockdown

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#261]
**Is your feature request related to a problem? Please describe.**
* We use [brand data rules](https://github.com/PanierAvide/Covid_enseignes/blob/master/rules.csv) to show meaningful statuses for many places that haven't been tagged individually yet.
* However, this is not clear to users, and especially OSM users wonder where this data comes from and how it can be updated.

**Describe the solution you'd like**
* We should have a separate note for places affected by rules that explains where this data comes from and how it can be updated. (Note that we collect data for AT/CH/DE [separately here](https://github.com/bleibtoffen/caresteouvert-de#handelsketten) and transfer the data regular to reduce workload for @PanierAvide!).
* Ideally there would also be a note for places *not* affected by any rule to explain that a rule can be added if this place belongs to a brand/chain.

**Describe alternatives you've considered**
See above.

**Additional context**
Example (de): https://lists.openstreetmap.org/pipermail/talk-de/2020-April/116723.html

**Comment by PanierAvide** [comment]
I added a bit of documentation in README to make things clearer.

**Comment by caugner** [comment]
@PanierAvide Sorry, I wasn't being clear, I meant the frontend/website. When OSM users see that a place is open and view the object, but don't see any tags, that's surprising.

**Comment by PanierAvide** [comment]
We might broaden this issue as being "show source of opening hours during lockdown".

**Comment by PanierAvide** [comment]
Now, source of status is kept in database (see 95cb1e5).

@overflorian where can we show information of used data source ? (either OSM or brand rules from covid_enseignes)

**Comment by PanierAvide** [comment]
No feedback = no interest ? Closing the issue, feel free to reopen if necessary.
