### ISSUE TITLE
Plusieurs shop=* alimentaires + 1 "électronique" non visibles

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#263]
Bonjour,
Plusieurs magasins alimentaires ne sont pas visibles :

- **shop=tea**  alors qu'on voit _shop=coffee_
- **shop=confectionery** (c'est bientôt Pâques ;-)) alors qu'on voit _shop=pastry_ et _shop=chocolate_
- **shop=dairy**
- **shop=spices**
- **shop=honey**
- **shop=health_food**

Et sinon **shop=computer** est lui aussi invisible

**Comment by PanierAvide** [comment]
Merci du retour, ça a été intégré et ce sera visible avec les données à jour d'ici ~1h.
