### ISSUE TITLE
Make link previews use brand (and description?) from config

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#265]
**Is your feature request related to a problem? Please describe.**
When I type `https://www.bleibtoffen.de/` into a social network or a messenger, I'm getting the French preview.

**Describe the solution you'd like**
It would be great to adapt this per country.

**Describe alternatives you've considered**
Not sure.

**Additional context**
Screenshot:
![grafik](https://user-images.githubusercontent.com/495429/78890161-6ac80380-7a65-11ea-9390-a1f9d156d4b2.png)

**Comment by caugner** [comment]
Is there any solution in sight?

This issue is kind of a blocker for us, because anybody sharing our German site will get a French preview in messengers. :disappointed:

Also, I fear we won't get a good SEO ranking with a French description:

![image](https://user-images.githubusercontent.com/495429/79015962-2aa07800-7b6e-11ea-8160-903544a9bbbe.png)

**Comment by caugner** [comment]
The French version seems to have a similar issue in Google:
![image](https://user-images.githubusercontent.com/495429/79016043-502d8180-7b6e-11ea-888b-d322e520c3d5.png)

**Comment by PanierAvide** [comment]
Related to #301

**Comment by francois2metz** [comment]
Fixed by #301
