### ISSUE TITLE
Chemist doesn't show up (DE)

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#269]
**Describe the bug**
Chemists in Germany don't show up.

**To Reproduce**
1. Go to https://www.bleibtoffen.de/chemist@52.521365,13.411447,17.79
2. Compare with https://www.openstreetmap.org/way/503037489
3. Chemist is not shown on the app.

**Expected behavior**
Chemist should show up in the map.

**Screenshots**
Empty overview of chemists in Berlin:
![grafik](https://user-images.githubusercontent.com/495429/78894522-78818700-7a6d-11ea-9d0d-ba914fd3f264.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by caugner** [comment]
@francois2metz Would you have an idea why this is so?

Also, the link doesn't work, i.e. the "chemist" parameter gets removed: https://www.bleibtoffen.de/chemist@52.521365,13.411447,17.79

**Comment by francois2metz** [comment]
We seems to have a bug on the DB side. We are looking into it.

**Comment by PanierAvide** [comment]
Should be solved by at least fb58ec6, updating the database.

**Comment by PanierAvide** [comment]
Plus missing chemist name in category, see 9ad3c73

**Comment by caugner** [comment]
Thanks a lot, I can confirm it's working now.
