### ISSUE TITLE
Add target="_blank" and rel="nofollow" to external links

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#272]
**Is your feature request related to a problem? Please describe.**
Two aspects:

* The external links don't include `rel="nofollow"`, which affects search engines (if they can access those links) and poses a theoretical privacy/security issue, because it gives the opening site access to the current page, see: https://developer.mozilla.org/de/docs/Web/HTML/Link_types
* The external links open in the current tab, which means users easily leave the site *by accident*.

**Describe the solution you'd like**
Add target="_blank" and rel="nofollow" to all external links.

**Describe alternatives you've considered**
None.

**Additional context**
Background: https://github.com/bleibtoffen/caresteouvert-de/issues/47

**Comment by francois2metz** [comment]
`rel="nofollow"` will not do anything (as no spiders will access them, for now). We may use `rel="noopener"` instead.

**Comment by francois2metz** [comment]
Also not sure about adding `target="_blank"`. I know that a lot of website use it, but I prefer managing tabs myself (and thus no need to use any rel="noopener").

**Comment by PanierAvide** [comment]
Well on mobile I find it quite convenient to have new tabs being open directly instead of long-clicking on links.

**Comment by caugner** [comment]
Yes, I was hesitating at first thinking about desktop, but it's definitely an issue on mobile.

Also, many people still don't know how to open a link in a new window.
