### ISSUE TITLE
Add amenity=cafe with delivery=yes|only or takeaway=yes|only (AT/CH/DE)

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#274]
**Is your feature request related to a problem? Please describe.**
In Germany, we have some cafes that are very similar to restaurants and offer delivery or takeaway.

**Describe the solution you'd like**

**Describe alternatives you've considered**
None.

**Additional context**
https://github.com/bleibtoffen/caresteouvert-de/issues/48

**Comment by PanierAvide** [comment]
I added cafés in all countries, as it seems to be same logic at least here in France. It follows same rules as restaurants (only with delivery or takeaway). Will be visible at next DB update, in ~1 hour.

**Comment by caugner** [comment]
Perfect, thanks!
