### ISSUE TITLE
Différence d'affichage des horaires sur deux POIs de même type

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#280]
En voyant ce qui suit je m'interroge sur les affichages des horaires

Soit deux POIs. Deux banques en l'occurence.

**Crédit Agricole**
-----------------------------
**Dans OSM =>** https://www.openstreetmap.org/node/6051458184#map=19/47.22120/-1.55576

**Dans Ça reste ouvert** => https://www.caresteouvert.fr/@47.220990,-1.555780,18.69/place/n6051458184

Il est écrit « _Lieu ouvert durant le confinement avec des horaires adaptés_ » 
Puis « _Horaires d'ouverture hors-confinement_ »

**Caisse d'Épargne**
-----------------------------
**Dans OSM** => https://www.openstreetmap.org/node/5257785281#map=19/47.22066/-1.55514

**Dans Ça reste ouvert** => https://www.caresteouvert.fr/@47.220653,-1.555465,18.69/place/n5257785281

Il est écrit « _Lieu ouvert durant le confinement_ »
Ensuite il y a juste le titre « _Horaires_ »

-----------------------------
Dans les deux cas on a juste un **tag "opening_hours" « classique »** pas de "opening_hours:covid19"

Alors pourquoi cette différence d'affichage des horaires ? 
Est-ce "normal" ou un bug ?

**Comment by PanierAvide** [comment]
La différence vient de la règle définie dans la liste covid_enseignes : https://github.com/PanierAvide/Covid_enseignes/blob/master/rules.csv

Crédit Agricole : open_adapted = ouvert avec des horaires susceptibles de changer

Caisse d'épargne : open = ouvert aux horaires classiques

D'où l'affichage différencié.
