### ISSUE TITLE
Add compass to mapa

### ISSUE THREAD

**Issue by jmontane** [osmontrouge/caresteouvert#283]
Currently, It's easy to change map orientation/angle, but it's hard to restore North pointing up. With "compass" icon it would be easiest.

Thanks

**Comment by overflorian** [comment]
I propose to hide the orientation icon when the map is oriented north. On desktop for example, as it's not possible to move with 2 fingers but only with the mouse, this extra button is useless.
The button should appear automatically when the map's orientation is changed

**Comment by PanierAvide** [comment]
Implemented

**Comment by overflorian** [comment]
Tellement le genre de détail d'UX qui montre qu'on aime l'utilisateur <3
