### ISSUE TITLE
Categories sometimes don't load (Console shows 'TypeError: "this.mapCenter is null"')

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#284]
**Describe the bug**
Sometimes when I visit the site, the categories don't load. I already had this yesterday and now again.

**To Reproduce**
Hard to reproduce.
1. Visit site.
2. Categories don't load.
3. Console shows follow error `TypeError: "this.mapCenter is null"`

**Expected behavior**
The categories should always load.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/495429/78930863-16447880-7aa5-11ea-9228-ce766b735c04.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 77.0a1

**Additional context**
None.

**Comment by francois2metz** [comment]
Good catch!
