### ISSUE TITLE
La mise en page de "à propos" est cassée

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#288]
https://blog.caresteouvert.fr/about/

Les boites avec les photos se décalent 😞 
<img width="800" alt="Capture d’écran 2020-04-10 à 00 44 17" src="https://user-images.githubusercontent.com/2158081/78947000-7dbdf080-7ac4-11ea-8e9d-f22088dbb18f.png">
<img width="785" alt="Capture d’écran 2020-04-10 à 00 43 57" src="https://user-images.githubusercontent.com/2158081/78947002-7eef1d80-7ac4-11ea-9c54-182280547fe6.png">

**Comment by francois2metz** [comment]
J'ai corrigé. Merci du signalement

**Comment by pyrog** [comment]
Mieux, merci 😄 

Les photos sont a peine trop grandes et mangent les puces 😉
