### ISSUE TITLE
Add a Local producers category

### ISSUE THREAD

**Issue by pierzen** [osmontrouge/caresteouvert#289]
Support of local producers is even more a concern with the economic shutdown.  They often organize pick-up or deliveries and need to have more visibility.

**Comment by PanierAvide** [comment]
Thanks for your feedback, what tag should be added for local producers ? Note that we already support `shop=farm`.

**Comment by pierzen** [comment]
Yes shop=farm. A distinct category would make it easier to find them. If amenity=marketplace become open with some restrictions, to could be added to the list.

**Comment by PanierAvide** [comment]
See also #103 and #146, as we try to reduce main categories, we will solve this issue by implementing category search.
