### ISSUE TITLE
Ajouter un indicateur visuel sur la carte adapté aux daltoniens

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#290]
Il est impossible pour les daltoniens de distinguer le vert du rouge.
> 4 % de la population française souffre de daltonisme : 8 % des hommes et seulement 0,5 % des femmes

Quel indicateur pourrions-nous trouver sur nos POIs (qui reste élégant à regarder) pour résoudre ce problème ?

**Comment by PanierAvide** [comment]
On pourrait garder les couleurs, mais changer le cercle des commerces fermés pour leur donner une forme proche d'un panneau "interdit de stationner" (à la place du fond bleu, fond blanc + symbole du POI)
![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/France_road_sign_B6a1.svg/200px-France_road_sign_B6a1.svg.png)

**Comment by francois2metz** [comment]
On pourrait avoir un hachurage différent pour faire la distinction entre le rouge et le vert.

**Comment by overflorian** [comment]
les deux options me conviennent.
on pourrait aussi inverser les couleurs :
-rouge à l'extérieur avec blanc à l'intérieur
-vers à l'intérieur avec un liseret blanc à l'extérieur

ou alors faire varier la taille des POIs : plus gros quand ils sont verts.

ou combiner plusieurs options :
-points gris de couleur à l'extérieur et à l'intérieur, petit marqueur
-points rouges avec petit marqueur
-points verts avec gros marqueur

quelle que soit la solution je pense qu'il faut la tester en pre-prod pour se rendre compte du rendu.

**Comment by Bibi56** [comment]
On peut aussi changer la forme (carré : fermé, rond : ouvert, triangle : inconnu). C'est le plus sûr.
Sinon pour des couleurs [ColorBrewer](https://colorbrewer2.org/?type=sequential&scheme=OrRd&n=4#type=diverging&scheme=PuOr&n=3) est une bonne option (ici 3 couleurs, compatible daltoniens, impression N/B et photocopie).

Je peux être bêta testeur sachant que la confusion rouge/vert n'est qu'une des possibilités.
Vous pouvez simuler à partir de copies d'écran avec [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/)
Pour rester en rouge/vert, mettre un rouge foncé et un vert clair est une possibilité : les daltoniens repèrent les différences de luminosité mieux que les non daltoniens.

Pour voir la page en direct, voir https://www.toptal.com/designers/colorfilter/

**Comment by PanierAvide** [comment]
Carré + rond + losange pourrait aussi aller niveau forme ? Je pense que le triangle va nous poser des soucis de dimensions pour les icônes. On devrait aussi faire en même temps #234 pour que la signification des formes soit claire.

**Comment by Bibi56** [comment]
Tu as raison. Sinon laisser des ronds, simplement mettre un liseré rouge pour les lieux fermés, blanc pour les lieux fermés et avec un pointillé rouge/blanc (par exemple) pour ceux au statut incertain.

**Comment by francois2metz** [comment]
@Bibi56 que ferais tu pour les lieux ouverts ? Avec des outils pour simuler des problèmes de couleurs, je trouve que la différence rouge et verte est pas terrible.

**Comment by francois2metz** [comment]
J'ai essayé d'appliquer des patterns sur les points pour faire des différences. Sans succès pour le moment.

**Comment by Bibi56** [comment]
@francois2metz, si les cartouches étaient rectangulaires ce serait sans doute plus facile.
Je corrige mon texte je voulais dire blanc pour les ouverts.

> la différence rouge et verte est pas terrible.

Maintenant tu comprends pourquoi ça embête les daltoniens. D'où ma demande d'un vert clair et d'un rouge foncé.

**Comment by Kolia31** [comment]
Bonjour, 
Je suis le daltonien qui a suggéré à Flo les icônes en plus des couleurs car la différenciation est difficile sur l'écran (je vois actuellement tous les commerces ouvert de mon village en rouge!)
 

> 
> 
> On peut aussi changer la forme (carré : fermé, rond : ouvert, triangle : inconnu). C'est le plus sûr.

Pour moi, c'est une bonne idée,

> Sinon pour des couleurs [ColorBrewer](https://colorbrewer2.org/?type=sequential&scheme=OrRd&n=4#type=diverging&scheme=PuOr&n=3) est une bonne option (ici 3 couleurs, compatible daltoniens, impression N/B et photocopie).

Je vois bien les différences sur color brewer mais est-ce que le rendu sera le même avec des petites icônes?

> 
> Je peux être bêta testeur sachant que la confusion rouge/vert n'est qu'une des possibilités.

Je confirme!

> Vous pouvez simuler à partir de copies d'écran avec [Coblis](https://www.color-blindness.com/coblis-color-blindness-simulator/)
> Pour rester en rouge/vert, mettre un rouge foncé et un vert clair est une possibilité : les daltoniens repèrent les différences de luminosité mieux que les non daltoniens.

euh, je ne sais pas mais je veux bien servir de testeur pour le coup!

> 
> Pour voir la page en direct, voir https://www.toptal.com/designers/colorfilter/

En tout cas merci à vous tous, de prendre ce problème en compte.

**Comment by francois2metz** [comment]
j'ai déployé une version de test, tiré de #457 visible la: https://covid19-fr-map-pr457.osc-fr1.scalingo.io/

Un bouton en bas de la sidebar permet de changer le jeux de couleur utilisé sur la carte et dans l'appli.

C'est une version de test, le but est ici de valider que l'idée peut fonctionner. 

Ensuite on se concentrera sur les couleurs a mettre, et ensuite l'UX du bouton.

**Comment by Kolia31** [comment]
c'est bien ça, je vois toutes les différences, 

du coup, c'est quoi le nouveau code couleur ?
- Bleu ==> ouvert
- gris ==> on ne sait pas
- vert ou jaune ==> fermé

vous confirmez?

**Comment by PanierAvide** [comment]
C'est bien ça pour les couleurs oui

**Comment by Kolia31** [comment]
pour moi en tout cas, je vois tout.
par contre pourquoi les icones reste toujours à la même taille malgré le fait que l'on zoome sur la carte?

**Comment by PanierAvide** [comment]
Pas sûr de comprendre (la taille augmente avec le zoom en pratique), on travaille sur un affichage amélioré niveau taille/visibilité (hormis couleurs) : https://covid19-fr-map-pr456.osc-fr1.scalingo.io/
Si tu as des retours, tu peux les partager sur #456

**Comment by francois2metz** [comment]
Cela a été mergé. Nhésitez pas faire des retours sur la production.
