### ISSUE TITLE
Bug: Rule "CH;supermarket;Migros" is applied to "shop=electronics"

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#292]
**Describe the bug**
In Switzerland, [melectronics](https://www.bleibtoffen.ch/@47.191919,8.477930,17.75/place/w737021556) is a `shop=electronics` with `operator=Migros` and appears as open, even though it is [not tagged as open](https://www.openstreetmap.org/way/737021556) and the [Migros rule](https://github.com/PanierAvide/Covid_enseignes/blob/8317d227e3d6b576dbe79b380fcfd5c497d4353f/rules.csv#L54) should only apply to `shop=supermarket`.

**To Reproduce**
1. Go to: https://www.bleibtoffen.ch/@47.191919,8.477930,17.75/place/w737021556
2. See that the shop appears as "Place open during lockdown".

**Expected behavior**
The shop's state should show up as "undetermined" (i.e. grey).

**Screenshots**
![image](https://user-images.githubusercontent.com/495429/78983820-3ca9f880-7b25-11ea-8bd8-8f5e4c2831e4.png)
![image](https://user-images.githubusercontent.com/495429/78983868-56e3d680-7b25-11ea-8567-883b3081ab56.png)
![image](https://user-images.githubusercontent.com/495429/78984020-a32f1680-7b25-11ea-8bb0-ff70441ca443.png)

**Additional context**
* Background: https://github.com/bleibtoffen/caresteouvert-de/issues/30#issuecomment-611952063
* #291 would allow us to workaround this issue by marking `shop=electronics` as (currently) closed in Switzerland (instead of removing them from the map).

**Comment by PanierAvide** [comment]
Is melectronics a national brand ? If so, well adding it to Covid_enseigne (preferably with Wikidata ID) should be sufficient to solve the issue.

Alternative is to work on categories, but is not so simple : "Carrefour" brand in France could be applied on fuel/supermarket/mall/convenience/bank/gas/travel agency... Oppositely, "Brioche Dorée" is always same kind of shop but not always tagged in a single way in OSM : cafe/fast_food/bakery/pastry... So if problem only occurs punctually on certain brands, we could find simpler workarounds as now.

**Comment by caugner** [comment]
Thanks for the explanation, that makes sense.

Just to verify if I understand this correctly, the "category" column in the `rules.csv` is essentially ignored when applying rules, it mainly servers as a way to keep the `rules.csv` tidy. Is that correct?

**Comment by PanierAvide** [comment]
Yes, as now it is just as an information in `rules.csv`, and is also used by third parties which reuses directly this file, for example : https://cms.geobretagne.fr/content/commerces-de-premiere-necessite-ouverts

**Comment by caugner** [comment]
Thanks, I'll close this issue then.
