### ISSUE TITLE
Migrate old `opening_hours:covid19=same` objects to `opening_hours:covid19=open`

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#300]
**Is your feature request related to a problem? Please describe.**
Right now, CRO doesn't set `opening_hours:covid19=same` if users click "same hours", because `same`

> *was at start mistakenly used for either a shop which is open with same opening hours, or shop open during lockdown but with unknown usual opening hours* (https://github.com/osmontrouge/caresteouvert/issues/259#issuecomment-611358021)

This is a pity, because it is noisy and redundant, and because CRO [sometimes copies the `opening_hours` incompletely](https://github.com/osmontrouge/caresteouvert/issues/259#issuecomment-611463425).

**Describe the solution you'd like**
It would be good to

* determine which changesets are affected exactly (i.e. prior to what timestamp)
* migrate the objects in those changesets from `opening_hours:covid19=same` to `opening_hours:covid19=open` (except if they have been changed in the meantime)

**Describe alternatives you've considered**
None. (We don't have the last modified timestamp in the DB, otherwise we could distinguish that case.)

**Additional context**
None.

**Comment by PanierAvide** [comment]
Switch to value `open` was done on 2020-03-30 @ 11:30 (Paris time). So everything done by API before that date is having value `same`. Also, it was a tag usage recommendation to use `same` value, so this also concerns edits done by a part of contributors.

At least a part of cases is easy to find :
- `opening_hours:covid19=same` without `opening_hours=*` -> should be `open`
- `opening_hours:covid19=same` done by CaResteOuvert_visitors -> should be `open`

**Comment by PanierAvide** [comment]
Part of clean-up has been done in France métropolitaine

**Comment by PanierAvide** [comment]
Worldwide clean-up should be OK now, we can't check for sure data made by OSM contributors when it was recommended to use `same` value. We have ~1800 `opening_hours:covid19=same` left in database. Are we confident enough to use again `same` value on our side when it makes sense ?

**Comment by PanierAvide** [comment]
To be precise, 850 features are still in OSM and were edited before switch on our API : http://overpass-turbo.eu/s/SGN
