### ISSUE TITLE
webgl on firefox no more work

### ISSUE THREAD

**Issue by wadouk** [osmontrouge/caresteouvert#302]
**Describe the bug**
This morning, webgl doesn't work

**To Reproduce**
1. Go to 'caresteouvert.fr'
4. No map display

**Expected behavior**
View the map

**Screenshots**
![image](https://user-images.githubusercontent.com/787448/79039047-c1a51880-7bde-11ea-8a52-5d43f93a32ac.png)

**Desktop (please complete the following information):**
 - OS: linux manjaro (archlinux)
 - Browser: firefox
 - Version : 75

**Additional context**
OK on chrome same OS
OK on firefox on MacOS 74 & 75

OK on mappy.fr (that display vector tiles)
Get same warning in the console but the map load

KO on https://get.webgl.org/

Seems more an issue with some system update Grrrr
Update: Test with the master that works yesterday full local and no more working

**Comment by francois2metz** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1623885 the workaround.

**Comment by wadouk** [comment]
downgrading libdrm & lib32-libdrm works great, thanks.
have broken my X11 trying to update the graphic card drivers. 5~6 hours that i fight, just apply the doc to fix it.
