### ISSUE TITLE
Twitter Card doesn't include logo anymore

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#305]
**Describe the bug**
Twitter Cards for CRO currently don't show a logo anymore.

**To Reproduce**
1. Go to https://cards-dev.twitter.com/validator (and login with any Twitter account)
2. Type in `https://www.caresteouvert.fr/`
3. See card without logo.

**Expected behavior**
Twitter Card should include CRO logo.

**Screenshots**
![image](https://user-images.githubusercontent.com/495429/79044690-c4b3ff00-7c06-11ea-819b-a0cea85db953.png)

**Additional context**
Possibly caused by 191842d5cb876f1cfd22188c2aa45751b24db115.

**Comment by caugner** [comment]
@PanierAvide Unfortunately the missing meta tags were not the problem. The format was:

![image](https://user-images.githubusercontent.com/495429/79049117-cf2fc200-7c21-11ea-9113-52b43fe69578.png)

We could use this image for now (and [make it configurable](#306)): https://www.caresteouvert.fr/opengraph.jpg

How can I access the `config.json` values from Nuxt.js? (Then I can open a PR.)

**Comment by PanierAvide** [comment]
Maybe by an `import` or `require` of the JSON file ?

**Comment by caugner** [comment]
> Maybe by an `import` or `require` of the JSON file ?

Ah, I thought it was maybe already imported into the `Nuxt` context.

**Comment by sfkeller** [comment]
Don't forget to adapt/localize the value which references the country specific Twitter handle:

`<meta data-n-head="ssr" data-hid="twittersite" name="twitter:site" content="@caresteouvert">
`

**Comment by francois2metz** [comment]
Fixed.
