### ISSUE TITLE
Make og:image configurable per brand

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#306]
**Is your feature request related to a problem? Please describe.**
We would ilke to use our German `og:image`: https://www.bleibtoffen.org/opengraph.jpg

**Describe the solution you'd like**
Make `og:image` configurable.

**Describe alternatives you've considered**
None.

**Additional context**
Add `opengraph_image` to `config.json` and use it here:
https://github.com/osmontrouge/caresteouvert/blob/191842d5cb876f1cfd22188c2aa45751b24db115/pages/index.vue#L43

**Comment by francois2metz** [comment]
https://www.bleibtoffen.org/opengraph.jpg is returning a 404. Could you give me the link to a image?

**Comment by PanierAvide** [comment]
It's here : https://github.com/bleibtoffen/bleibtoffen/blob/master/docs/assets/images/opengraph.jpg

**Comment by caugner** [comment]
Sorry, I moved it for consistency: https://www.bleibtoffen.org/assets/images/opengraph.jpg

**Comment by francois2metz** [comment]
Fixed.
