### ISSUE TITLE
Add amenity=ice_cream

### ISSUE THREAD

**Issue by Matthias84** [osmontrouge/caresteouvert#308]
**Describe the bug**
In Germany there are ice cream shops open to take away. Many POIs I see are tagged as amenity=ice_cream, similar

**Expected behavior**
See all POIs not only shop=icecream,. but also amenity=ice_cream. One example at Rostock https://www.openstreetmap.org/node/3728272000

**Comment by PanierAvide** [comment]
Thanks, this has been implemented, and will be visible on website in ~1h.
