### ISSUE TITLE
Add shop=fabric

### ISSUE THREAD

**Issue by Matthias84** [osmontrouge/caresteouvert#309]
**Is your feature request related to a problem? Please describe.**
A lot of people use the pandemic to DIY and hobbies like knitting. Usually all related local stores are closed, but some offer city wide delivery.

**Describe the solution you'd like**
I want to see also POIs with shop=fabric e.g. at Rostock https://www.openstreetmap.org/node/1130917772

**Comment by PanierAvide** [comment]
Thanks, this has been implemented, and will be visible on website in ~1h.
