### ISSUE TITLE
Add any kind of vending machines

### ISSUE THREAD

**Issue by Matthias84** [osmontrouge/caresteouvert#310]
**Is your feature request related to a problem? Please describe.**
A lot of shops are closed, but the vending machines are operational. As they offer a big spectrum of products and services (bicycle tubes ... parcel pick in ... public bookcases), it might be worth to show users this machines as a possible alternative?

**Describe the solution you'd like**
It would be nice to show a generic icon with subicons for different kind of [amenity=vending_machine](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dvending_machine) but also for [amenity=public_bookcase](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dpublic_bookcase), ...

**Comment by PanierAvide** [comment]
Hello, thanks for your feedback. According to existing categories and subcategories we have in `categories.json`, would it be possible for you to list for every of them which values of `vending=*` tag can be associated ?

**Comment by Matthias84** [comment]
I try to create a listing, but I don't wanted to mess up with the syntax without validation. I hope it dosesn't make to much troubles to integrate this list anyway?
*(plz. keep in mind, that this is from a very german perspective on the local data)*

```javascript
"pharmacy"
"vending": "condoms"

"mobility"
"vending": "bicycle_tube"
"vending": "tickets"

"Restaurant & take-away",
"vending": "coffee"
"vending": "drinks"
"vending": "water"
"vending": "sweets"

"eat"
"vending": "milk"

"post_office"
"vending": "parcel_mail_in|parcel_mail_in"
"vending": "stamps"

"shops" or misc.?
"vending": "books"
"amenity": "photo_booth"
"amenity": "public_bookcase"
```

**Comment by vinber** [comment]
for french :D in eat we have
"vending": "bread"

**Comment by PanierAvide** [comment]
@Matthias84 don't worry, I will mess up with the syntax ;-) Thanks for your list, I will work on integrating this soon.

**Comment by PanierAvide** [comment]
This is integrated, thanks ! Will be visible on website in a few minutes.
