### ISSUE TITLE
Expand to 🇮🇹 Italy

### ISSUE THREAD

**Issue by alesarrett** [osmontrouge/caresteouvert#311]
Thanks for your interest ! We hope you are safe during this lockdown. 

We are working hard to be able to expand operations outside of France. But first, a little disclaimer.
The first days of "Ça reste ouvert" the app created **thousands of notes** via the contribute form. We have since worked to make automatic edits, but some notes are still created. You need to keep up with theses.
 
Except this, you can expect thousands of contributions quickly and improve the coverage of shops in your country in OSM, so this is pretty cool!

Please check the following requirements:

- [x] You are a team of at least 2 people experienced with OpenStreetMap
- [x] Translate the app via transifex with your country languages
- [ ] Translate some content of the blog to help newcomers (how to create a new shop, the about page, ...)
- [x] Start gathering data about shop open or closed nation wide in https://github.com/PanierAvide/Covid_enseignes/
- [ ] Once everything has been done and the data have been loaded, you should be busy getting media coverage. So the map will have a lot of contribution and be quickly useful.

Others questions:

- if you want a localized domain name, please tell us which one: not yet
- Each lockdown is different, what shops are open or closed in your country? What should be done in the category list?

**Comment by caugner** [comment]
>  Translate some content of the blog to help newcomers

This is mainly about the "Maggiori informazioni" dialog which contains:

* A link to an article *What to do if a shop is missing in CRO?*
* A link to an article "A communication tool for townhalls"
* A link to a blog
* A link to an about page.
* A link to a press page.
* A link to an imprint.

These links can be customised by adding a `it` section to the [config.json](https://github.com/osmontrouge/caresteouvert/blob/master/config.json) in this repository.

**Comment by vdct** [comment]
Welcome @alesarrett !
Regarding italian rules for open & closed shop and other legal stuff, are there specific rules at the "region" level ?

**Comment by naposm** [comment]
@vdct Hi, I'm from Italy. I've collected some information from the official website for covid in Italy.

In Italy the following shops are closed:
- barber shops
- beauty centres
- hairdressers
- cafès
- restaurants
- ice cream shops (gelateria)
- bakeries (shop=pastry)
- pubs
- cinema
- theatres 
- games rooms
- betting (shop=bookmaker)
- discos
- gyms 
- museums

The following applies to the "campania" region, I don't know if they are applied also in other Italian regions:

In the "Campania" region it is not possible for cafès, restaurants (pizzerias and fast food restaurants included), ice cream shops, bakeries (cake shops) and pubs to make deliveries.

It is possible, for kids clothing shops, to stay open from Tuesday to Friday from 8:00 to 14:00.

Thank you very much for this project, I hope to be helpful!

**Comment by caugner** [comment]
For Germany, we created a CSV file [laender.csv](https://github.com/bleibtoffen/bleibtoffen/blob/master/laender.csv) with
* one column per region ("Bundesland"),
* one row per type of place, and
* each cell recording which term in the legislation for that region maps to the type of place (to make it traceable).

In doing so, we found out that most regions have the same rules and the few differences are not worth incorporating into the map (for now).

Maybe this approach could also help?

@naposm Most of the shops you mention are also closed in all the other countries already available (or at least not yet shown on the map). Hiding cafes, restaurants, ice cream shops and bakeries for Italy is no problem at all.

For example, to hide restaurants in Italy, all we need to do is to list all other countries in the `areas` key here:
https://github.com/osmontrouge/caresteouvert/blob/694af1c5a8959f0c5d453c3c22e5b6d6bd84d8c4/categories.json#L180-L186

Actually, I would very much recommend you going through that [categories.json](https://github.com/osmontrouge/caresteouvert/blob/master/categories.json) file to get a clear overview of what kind of places are currently shown in other countries.

**Comment by naposm** [comment]
@caugner The CSV file is a very good idea, I think I'll take some time in the next days to make one similar to the ones you used just to see if various regions have different rules (for example in Campania we have also some cities which have different rules, but it's more a "strict" rule applied to avoid the spread in the most infected cities).
I've seen the file, so in order to add Italy we should change "all" to "DE", "FR", "ES", "AD", "CH", "AT" in the categories which are not closed in Italy, am I right?

**Comment by caugner** [comment]
> I've seen the file, so in order to add Italy we should change "all" to "DE. FR. ES, AD, CH, AT" in the categories which are not closed in Italy, am I right?

Since the file changes regularly, I wouldn't recommend opening a PR in advance. Instead I would recommend to compile a list of categories/subcategories that you would like to hide.

In the following example, you could hide the (main) category `health` or the *sub*category `pharmacy` separately:

https://github.com/osmontrouge/caresteouvert/blob/694af1c5a8959f0c5d453c3c22e5b6d6bd84d8c4/categories.json#L60-L70

But the idea is correct, yes, the following change would be correct for the `restaurant` subcategory:

```diff
  "restaurant": { 
    "name": "Restaurant", 
    "osm_tags": [ 
      { "amenity": "restaurant" } 
    ], 
-   "areas": "all" 
+   "areas": ["DE", "FR", "ES", "AD", "CH", "AT"]
  }, 
```

**Comment by naposm** [comment]
Yes, I completely agree with you, indeed I would have never done that, because I'd like to wait for the community (which has people way more experienced than me) to check everything. I think the list you did is very good and I think we should do the same in Italy (in my opinion). Thank you very much for the tip!

Your example was very clear, thank you very much for everything you are doing!

**Comment by PanierAvide** [comment]
Note that if you want to exclude a subcategory for a restricted list of countries, you can use instead `"-areas": [ "IT" ]`, example here : https://github.com/osmontrouge/caresteouvert/blob/master/categories.json#L326

**Comment by naposm** [comment]
@PanierAvide That's very handy, thanks! Also love your profile picture 😂

**Comment by PanierAvide** [comment]
How things are going on your side ? Don't hesitate to send us your questions if you have any :wink:

**Comment by naposm** [comment]
We're discussing on making a list of the businesses which are closed in Italy (the whole area), then maybe we'll see for the various regions. We are still organizing it at the moment. I'll let you know if there's any news!

**Comment by podiego** [comment]
After an internet search, I've found latest govenative official document [Gazzetta Ufficiale 2020-04-27](https://www.gazzettaufficiale.it/eli/id/2020/04/27/20A02352/sg), which in annex no.1 lists businesses that can operate.


Ipermercati 
  Supermercati 
  Discount di alimentari 
  Minimercati ed altri esercizi non specializzati di alimentari vari 
  Commercio al dettaglio di prodotti surgelati 
  Commercio al dettaglio in esercizi non specializzati  di  computer,
periferiche, attrezzature per le  telecomunicazioni,  elettronica  di
consumo audio e video, elettrodomestici 
  Commercio al dettaglio di prodotti alimentari, bevande e tabacco in
esercizi specializzati (codici ateco: 47.2) 
  Commercio al dettaglio di carburante per autotrazione  in  esercizi
specializzati 
  Commercio  al  dettaglio  apparecchiature  informatiche  e  per  le
telecomunicazioni (ICT)  in  esercizi  specializzati  (codice  ateco:
47.4) 
  Commercio al  dettaglio  di  ferramenta,  vernici,  vetro  piano  e
materiale elettrico e termoidraulico 
  Commercio al dettaglio di articoli igienico-sanitari 
  Commercio al dettaglio di articoli per l'illuminazione 
  Commercio al dettaglio di giornali, riviste e periodici 
  Farmacie 
  Commercio  al  dettaglio  in  altri   esercizi   specializzati   di
medicinali non soggetti a prescrizione medica 
  Commercio  al  dettaglio  di  articoli  medicali  e  ortopedici  in
esercizi specializzati 
  Commercio al dettaglio di  articoli  di  profumeria,  prodotti  per
toletta e per l'igiene personale 
  Commercio al dettaglio di piccoli animali domestici 
  Commercio al dettaglio di materiale per ottica e fotografia 
  Commercio al dettaglio di combustibile  per  uso  domestico  e  per
riscaldamento 
  Commercio al  dettaglio  di  saponi,  detersivi,  prodotti  per  la
lucidatura e affini 
  Commercio al dettaglio di qualsiasi tipo di prodotto effettuato via
internet 
  Commercio al dettaglio di qualsiasi tipo di prodotto effettuato per
televisione 
  Commercio  al  dettaglio  di  qualsiasi  tipo   di   prodotto   per
corrispondenza, radio, telefono 
  Commercio effettuato per mezzo di distributori automatici 
  Commercio di carta, cartone e articoli di cartoleria 
  Commercio al dettaglio di libri 
  Commercio al dettaglio di vestiti per bambini e neonati 
  Commercio al dettaglio di fiori, piante, semi e fertilizzanti 

I'm consider to extract a [Geofabrik taginfo](https://taginfo.geofabrik.de/europe/italy) set for italian POIs amenity and shop; Don't know if any other key like craft would be useful.

**Comment by PanierAvide** [comment]
If you look at current [categories](https://github.com/osmontrouge/caresteouvert/blob/master/categories.json), we have some `craft=*` tags used.

**Comment by fansanelli** [comment]
> After an internet search, I've found latest govenative official document [Gazzetta Ufficiale 2020-04-27](https://www.gazzettaufficiale.it/eli/id/2020/04/27/20A02352/sg), which in annex no.1 lists businesses that can operate.
> 
> Ipermercati
> Supermercati
> Discount di alimentari
> Minimercati ed altri esercizi non specializzati di alimentari vari
> Commercio al dettaglio di prodotti surgelati
> Commercio al dettaglio in esercizi non specializzati di computer,
> periferiche, attrezzature per le telecomunicazioni, elettronica di
> consumo audio e video, elettrodomestici
> Commercio al dettaglio di prodotti alimentari, bevande e tabacco in
> esercizi specializzati (codici ateco: 47.2)
> Commercio al dettaglio di carburante per autotrazione in esercizi
> specializzati
> Commercio al dettaglio apparecchiature informatiche e per le
> telecomunicazioni (ICT) in esercizi specializzati (codice ateco:
> 47.4)
> Commercio al dettaglio di ferramenta, vernici, vetro piano e
> materiale elettrico e termoidraulico
> Commercio al dettaglio di articoli igienico-sanitari
> Commercio al dettaglio di articoli per l'illuminazione
> Commercio al dettaglio di giornali, riviste e periodici
> Farmacie
> Commercio al dettaglio in altri esercizi specializzati di
> medicinali non soggetti a prescrizione medica
> Commercio al dettaglio di articoli medicali e ortopedici in
> esercizi specializzati
> Commercio al dettaglio di articoli di profumeria, prodotti per
> toletta e per l'igiene personale
> Commercio al dettaglio di piccoli animali domestici
> Commercio al dettaglio di materiale per ottica e fotografia
> Commercio al dettaglio di combustibile per uso domestico e per
> riscaldamento
> Commercio al dettaglio di saponi, detersivi, prodotti per la
> lucidatura e affini
> Commercio al dettaglio di qualsiasi tipo di prodotto effettuato via
> internet
> Commercio al dettaglio di qualsiasi tipo di prodotto effettuato per
> televisione
> Commercio al dettaglio di qualsiasi tipo di prodotto per
> corrispondenza, radio, telefono
> Commercio effettuato per mezzo di distributori automatici
> Commercio di carta, cartone e articoli di cartoleria
> Commercio al dettaglio di libri
> Commercio al dettaglio di vestiti per bambini e neonati
> Commercio al dettaglio di fiori, piante, semi e fertilizzanti
> 
> I'm consider to extract a [Geofabrik taginfo](https://taginfo.geofabrik.de/europe/italy) set for italian POIs amenity and shop; Don't know if any other key like craft would be useful.

Ciao,

ho pensato di prendere l'elenco ed iniziare a buttare giù qualche tag:

https://docs.google.com/spreadsheets/d/16sjnVrZHkXzKwIQVTNATTHdG5V1C42x3qrDsLTCXUm4/edit?usp=sharing

dobbiamo cercare di capire se va bene per tutte le regioni!
Francesco

**Comment by fansanelli** [comment]
@caugner @PanierAvide @podiego 
Do you think this file:
https://docs.google.com/spreadsheets/d/16sjnVrZHkXzKwIQVTNATTHdG5V1C42x3qrDsLTCXUm4/edit?usp=sharing
is enough to start?
Bars, restaurant, pubs are "takeaway" or "delivery", but still open..
Should be indicated somehow in the file too?
If we will have future regional restriction to implement can be this be done later or we should somehow add every Italian region in file?

@naposm will provide soon some blog translation soon...

**Comment by PanierAvide** [comment]
Note that general rules and chain stores rules have to be defined in [Covid enseignes](https://github.com/PanierAvide/Covid_enseignes) repository.

**Comment by fansanelli** [comment]
> Note that general rules and chain stores rules have to be defined in [Covid enseignes](https://github.com/PanierAvide/Covid_enseignes) repository.

https://github.com/PanierAvide/Covid_enseignes/pull/165

it's almost what we already did...
We're asking for some chain, but can we go with this?
Cheers
Francesco

**Comment by naposm** [comment]
Hi! We're working on chains, I'm getting a list of the opened ones. 🙂

**Comment by PanierAvide** [comment]
I merged legal rules, and sure keep working on chains, that's the most efficient way to display accurate information on a wide range of shops.

**Comment by fansanelli** [comment]
Hello,

Can you please enable Italy in Google play store? Currently is not available... Translations should be over

Thanks
Francesco

**Comment by fansanelli** [comment]
Dear @PanierAvide 

we took restiamoaperti.it and did redirect to 5.104.101.30

Thanks
Francesco

**Comment by PanierAvide** [comment]
I added restiamoaperti.it in our server configuration. I think domain still need to be propagated through DNS servers though.

**Comment by fansanelli** [comment]
> Hello,
> 
> Can you please enable Italy in Google play store? Currently is not available... Translations should be over
> 
> Thanks
> Francesco

Any news about this? Should be asked in another project?

**Comment by PanierAvide** [comment]
Maybe you can ping the Android dev team here : https://github.com/osmontrouge/caresteouvert_android/

**Comment by francois2metz** [comment]
The data has been loaded. Closing
