### ISSUE TITLE
Plus de mise à jour de la carte depuis 11/04 ~17h/20h

### ISSUE THREAD

**Issue by OcelotNat** [osmontrouge/caresteouvert#312]
Les informations ":covid19" saisies dans OSM ne semblent plus mises à jour sur la carte.
Un changement fait hier 11/04 à 17h est passé, les suivants à 20h et après non.

Le problème m'a été signalé ce matin par py_berrard.

**Comment by PanierAvide** [comment]
Bonjour, il y a un souci plus général sur la mise à jour de bases OSM avec l'outil Osmosis, cf https://twitter.com/sp8962/status/1249245664111984640

François est dessus, ce sera bientôt de retour.

**Comment by francois2metz** [comment]
C'est revenu. Dernier timestamp `2020-04-12T09\:34\:02Z`. Merci du signalement.
