### ISSUE TITLE
Inapropriate titles for shop=farm (fr,es,en,de, probably more)

### ISSUE THREAD

**Issue by jibix2256** [osmontrouge/caresteouvert#313]
The title for shop=farm in French is "épicerie", which looks wrong to me. Indeed, though the scope for this key slightly differs between the English [[1]](https://wiki.openstreetmap.org/wiki/Tag:shop=farm) and French [[2]](https://wiki.openstreetmap.org/wiki/FR:Tag:shop%3Dfarm) wikis, there should be a better title for that. As an alternative, I propose to use the one used in iD ("Magasin de producteurs"), which looks fine with respect to both wikis.

Exemple:
![https://www.caresteouvert.fr/@48.513670,5.507090,16.85/place/n7354895877](https://framapic.org/2Yr9Y5SkMpxk/3pJp0QhmKqOh)

Also, it seems that "épicerie" was taken as baseline for the translation in other languages, for which I find the corresponding title look consistently inapropriate. Namely: "Ultramarinos" (Spanish), "lebensmittel" (littéralement "nourriture") in German, "Grocery" in English. For these, I propose the same as for the French version: the titles in iD look all OK, that is:
- Spanish: "Tienda de productos agricolas" (the ending in -as is not a <edit>grammar</edit> mistake, it's correct),
- Germen: "Hofladen",
- English: "Farm shop" (logically).
I can't speak the other languages of the website myself, but it looks like something similar occures there as well - hints anyone?

Wiki
[1] https://wiki.openstreetmap.org/wiki/Tag:shop=farm
[2] https://wiki.openstreetmap.org/wiki/FR:Tag:shop%3Dfarm

Bests
-JB

**Comment by caugner** [comment]
The explanation for this is that several shops have been combined to reduce the number of categories:

https://github.com/osmontrouge/caresteouvert/blob/874920e83014a34972361d9103fd11b11c3abe60/categories.json#L106-L114

That's why I translated it more generally with "Lebensmittel" in German.

**Comment by jibix2256** [comment]
OK, I understand the trade-off, fine with me not to go too deep into such details indeed. In that case, Grocery and Lebensmittel look fine to me for the scope in line 110 above.

However, for that scope, I beleive "épicerie"(/"ultramarinos") are improvable. I'd suggest, as in the German case, using the same as the search-menu entry for French and Spanish, as that's the best way I can see to encompass the whole corresponding scope. That would be, namely, "Alimentation" and "Alimentación".

**Comment by PanierAvide** [comment]
Thanks for your feedback, a dedicated subcategory + icon has been created for shop=farm. It will be visible on website in ~1h.

**Comment by jibix2256** [comment]
Thanks. Just seen that indeed. shop=farm is now perfect for French and for English.
For Spanish and German, it apparently falls in the fallback "others" category, which is acceptable. This could be upgraded to "Tienda de productos agricolas" and "Hofladen", but I understand this is probably not a priority. (But maybe still to be considered by whom prefers dedicating effort to small structures).

Also, in the meantime, feedback from the spanish community confirmed that the title for the scope above should be "Alimentación" rather than "Ultramarinos", and excluding farm shop does not change this conclusion. Is it possible to change it? (btw: imo, this applies to French as well)

**Comment by jibix2256** [comment]
In any case, thank you for the great job.

**Comment by PanierAvide** [comment]
I think it's just a matter of translation : translations should be updated in Transifex in all languages in order to display properly.

**Comment by jibix2256** [comment]
I've been pointed to transifex by another contributer in the spanish OSM chat indeed... Sorry for the bother as I'm catching up with how things work here.
Thanks again
-JB
