### ISSUE TITLE
GUI currently counter-intuitive to select/unselect categories

### ISSUE THREAD

**Issue by sfkeller** [osmontrouge/caresteouvert#316]
**Is your feature request related to a problem? Please describe.**
* Current GUI is counter-intuitive the way a category is being unselected.
* Currently, to unselect and return to showing "All" categories, one has to click on a specificly selected categorie another time. 
* And after all, why only select one category at a time?

![Clipboard01](https://user-images.githubusercontent.com/43340/79069838-ab2bb980-7cd1-11ea-97bb-ea8b74fa1b4c.jpg)

**Describe the solution you'd like**
Add at least an "X" to clear the current filter.

If possible, allow to choose more than one category as filter.

![Clipboard01b](https://user-images.githubusercontent.com/43340/79069886-14abc800-7cd2-11ea-81d4-cf884de35af7.jpg)

**Describe alternatives you've considered**
See e.g. "Interface if there is a lot of categories"
https://ux.stackexchange.com/questions/101961/interface-if-there-is-a-lot-of-categories

**Additional context**
It's inevitable that more and more categories (and subcategories) are coming up (see e.g. #315).
So, this issue is becoming more and more evident.

**Comment by francois2metz** [comment]
Let's merge this issue with #316 that have similar points.

**Comment by sfkeller** [comment]
You merged 316 with itself (#316)?

**Comment by francois2metz** [comment]
> You merged 316 with itself (#316)?

Why not :joy:.

Seems to be the right one #225
