### ISSUE TITLE
Prise en compte "Sur commande", "Sur rendez-vous" ?

### ISSUE THREAD

**Issue by deuzeffe** [osmontrouge/caresteouvert#317]
Bonjour,

Nombreux sont les lieux ouverts "sur rendez-vous" (banques, assurances, par ex.) ou qui livrent/délivrent "sur commande" (restau, magasin de producteur, per ex.).
Une partie de ma question a déjà été traitée en #138 (merci !).

Reste à prendre en compte d'autres situations (les banques, ou les shop=farm) qui ne reçoivent ou ne délivrent que sur RdV/commande (pas comme La Poste ou un supermarché, quoi). Est-ce que cette info. peut-être affichée dans la boîte de dialogue en haut dans le cartouche ? (je n'arrive pas à comprendre sur quoi est basé ce qui s'affiche sur fond bleu :/)
Donc, quel tag/champ : reservation:covid19=* ? required/only ? description:covid19 ? Présenté comment ?

Merci pour vos réponses, quelles qu'elles soient.

**Comment by pyrog** [comment]
Le code est ici : [components/detail.vue#L218](https://github.com/osmontrouge/caresteouvert/blob/master/components/detail.vue#L218)

**Comment by deuzeffe** [comment]
@pyrog donc à mettre entre " dans la valeur du champ (donc via osm et pas CRO) ?
(non, lire le code ne m'avance pas plus :P)

**Comment by vinber** [comment]
Pour que cela reste accessible à des contributeurs non avancés en édition OSM, ne pas oublire de le préciser dans le champ description:covid19=* qui est également affiché.
Pour les shop=farm pour moi c'est un takeway=only (seulment à emporter, cela veut dire que tu commande). Si il y a aussi un magasin alors c'est takeway=yes (tu peux venir choisir tes produits ou commander par téléphone et venir la chercher).

la question me semble surtout concerner les rendez vous pour les banques -> pour l'instant j'utilise description:covid19 en complément de opening_hours:covid19=*

**Comment by deuzeffe** [comment]
@vinber ce que tu appelles le champ description:covid19, c'est là où tu rajoutes des précisions (ça ne fait donc plus une note donne une valeur au dit champ ?). 

Dans mon coin, il y a les 2 types de shop=farm, sur commande uniquement ou "comme dans un magasin normal". Oui, c'est surtout le pb des banques, assurances, qq magasins qui ne font que sur commande aussi. Bref.

**Comment by PanierAvide** [comment]
On a progressé sur le modèle pour ce genre de cas (cf https://wiki.openstreetmap.org/wiki/FR:Key:opening_hours:covid19 ) :
* À emporter : `takeaway:covid19=yes/no`
* Livraison : `delivery:covid19=yes/no`
* Service drive : `drive_through:covid19=yes/no`
* Boutique dans laquelle on ne peut pas rentrer mais qui continue de fournir un service : `access:covid19=no` + tags ci-dessus

Il reste donc à prévoir :
* Appel/réservation obligatoire : `reservation:covid19=required` ?
* Contact uniquement par mail/téléphone : ... ?
* Service accessible uniquement pour personnel médical, pour les urgences : ... ?

Si vous avez des idées de tags, je suis preneur pour qu'on avance :wink:

**Comment by deuzeffe** [comment]
1. déjà prévu : `yes/no/only` pour avoir la totale ?

2. à prévoir : 
- `reservation:covid19=required` me semble correct (si je comprends ce que raconte le wiki à propos de la clé et de sa valeur) ;
- `email:covid19=only` ? `phone:covid19=only` ? (tant qu'on est dans la déclinaison de `*:covid19`...)
- plus largement réservé aux pro. : pas d'idée :/ `description:covid19=` ne suffit pas ?

**Comment by PanierAvide** [comment]
Pour `email/phone:covid19`, on s'attend plus à y trouver des adresses mail ou n° de téléphone (il y a déjà 43 valeurs pour le téléphone). Il y avait le terme de `call ahead` en anglais (appeler avant de s'y rendre) mais pas trouvé de tag associé hormis dans les descriptions.

Et peut-être que pour les accès réservés aux pros, effectivement on peut se dire que `description:covid19` est suffisant vu qu'on aura du mal à couvrir toutes les possibilités.

**Comment by vinber** [comment]
pour moi access:covid19=no sert vraiment à cela, oui le service est possible mais pas comme d'habitude en se rendant sur place.
Donc pour moi premier niveau la combinaison opening_hours:covid19=* (open, same; XX:XX) et acess:covid19=no -> signifie "Prendre contact pour en savoir plus entre telle heure et telle heure"

après on peut effectivement affiner avec d'autres clés mais le "principal est rempli", personne ne se retrouve devant une porte close car il n'a pas appelé avant ou envoyé un mail.


@deuzeffe 
> @vinber ce que tu appelles le champ description:covid19, c'est là où tu rajoutes des précisions (ça ne fait donc plus une note donne une valeur au dit champ ?).

je parle de la clé, pas de l'éditeur de CRO. L'éditeur ajoute toujours dans une note la partie précision, texte libre. à un contributeur soit de la basculer dans description:covid19=* soit d'adapter le texte avec les bons tags.

**Comment by deuzeffe** [comment]
@PanierAvide Pour contact uniquement par mail/tel, il y aurait bien `contact:covid19=*` mais 1/ ça impliquerait une valeur pour plusieurs moyen de contact (mail, tél) dans le champ, sauf à décliner `contact:covid19:email=` et `contact:covid19:phone=`avec yes/only comme valeur. Hum. 2/ contact: n'a pas forcément bonne presse hors de France :P 

In fine, à laisser dans `description:coved19=` ? (comme dans  Covid_enseignes/rules.csv quoi).

**Comment by PanierAvide** [comment]
Je ferme le ticket, on part donc sur `description:covid19`
