### ISSUE TITLE
Differentiate the "Still Open" from the "Currently closed but open later"

### ISSUE THREAD

**Issue by wadouk** [osmontrouge/caresteouvert#318]
**Is your feature request related to a problem? Please describe.**
On mobile in the street, yesterday (Saturday) I go to a bakery that I know was still open, but too late and it was closed, when I see the other bakery of neighbourhood, there was green spots but in the details, it was too late too. It's annoying to have to click on every point.

**Describe the solution you'd like**
It should be good differentiate the covid closed of too late closed. color, border dashed  ...

**Describe alternatives you've considered**
Button to toggle it but think it's harder ? Toggle closed, covid closed, soon open ...

**Comment by caugner** [comment]
I came across this as well and was thinking about a thinner red circle around the green circle for places that are *currently* closed.

Alternatively, a filterable list view (for the current viewport) would also solve this.

**Comment by francois2metz** [comment]
The text is carefully worded to make it clear that the place is open during the lockdown, but not open all the time. The opening hours solve this (and it's clear if it's open or not and when).

Not sure adding another visual think will make it usable.

**Comment by caugner** [comment]
A user story would be:

> It's Saturday at 10am and I want to find a bakery near me that is open right now.

The current approach is:

> 1. Select the "Food" category.
> 2. Now look for places near you that have a green circle and the bakery sign.
> 3. Click on each of these places and check the details until you find one saying "open until ...".

While 2. could be improved by #103 (e.g. [my proposal](https://github.com/osmontrouge/caresteouvert/issues/103#issuecomment-612961576)), this issue is about 3.

If I understand @wadouk correctly, this is not so much about the wording in the details panel (which is carefully worded, as you say), but about enabling users to find the places *open right now* in the map.

**Comment by vdct** [comment]
>  It should be good differentiate the covid closed of too late closed. color, border dashed ...
Not sure about a solution on this with a dedicated map style. How about the ability to filter the map POIs with a 'Show only shops open right now' checkbox ?

**Comment by wadouk** [comment]
I will try something : add a control on the map that could filter the really open or open to delivery like mentionned in #92 
hope the data are in the tiles ?

**Comment by PanierAvide** [comment]
Not yet, what do we want to embed ? `opening_hours:covid19` if set, otherwise `opening_hours` ? Or nothing ?

**Comment by wadouk** [comment]
Add some filter on opening_hours:* but maybe it's not that simple, I should parse and compute if it's really open.
having a delivery:*=yes or only should be easier to start

Maybe filtering from tiles is not the good option. Maybe I will have to loop on displayed POI and for each toggle a display suff ?

Not confortable in vue, i begin in pure JS for a first version. After, I will convert it to vue.

**Comment by wadouk** [comment]
I will try to see from where those info are displayed in the detail of POI and lookup the same way.

**Comment by PanierAvide** [comment]
Or you can add dummy values for testing, in order to see what we should bring in tiles. I think looping other POIs will take time + not be really efficient.

**Comment by wadouk** [comment]
that’s what I fear

**Comment by PanierAvide** [comment]
Or we can start with just `delivery` tag in tiles to make you able create dynamic filtering. So value true/false for this will be enough ?

**Comment by PanierAvide** [comment]
_Ça tombe bien_, it's already in the tiles : column `delivery`, with values `yes/no/unknown/only`. I think you can group together `yes/only` and `unknown/no` to keep filter simple.

**Comment by wadouk** [comment]
We can also disable the filtering by opening state by zoom level (<1km) or number of POI.
If there is too much POI to filter (>50 ?) it's only display a message : zoom more to filter ?

**Comment by PanierAvide** [comment]
I would have said the opposite : it's when you have plenty of POIs you want to filter. If there are only a few of them, filtering doesn't provide much.

**Comment by wadouk** [comment]
more than too or three to click to view detail is OK, more is already annoying so filtering in 50 points is already useful to me. And your not supposed to go to more than 1km so ... not so much points should be displayed. It's cumulative by filtering with categories/sub categories no it's not so difficult to reduce the number.

**Comment by caugner** [comment]
Please note that the 1km is only valid for France and not for grocery shopping (see attestation). Especially in the countryside, a 1km filter would make the map unusable, because shops are often more than 1km away, if your village doesn't have its own commercial area.

**Comment by wadouk** [comment]
So if there is no point in the view, there will not be slowing, and filtering only few points. But now I have to add data in tiles to continue to move forward. That's the number of points in the view that could be interesting and not the distance, geolocation should not be mandatory for this feature.

**Comment by wadouk** [comment]
I propose a design to have filters, categories (don't change what is already done)
Put all "search & filter" to top panel.
Add some labels to input text that remember that it's only address, in label at top, in place holder, when there is no result, remember that it's only address to be full clear that it's only addresses. Some wording to find.
I put categories in an elevator on right to keep the white panel not full screen to view the map moving when click but don't know
The bottom menu is like today but without categories.
When the search panel is closed, you have the "last" or "more frequent" categories #475 
The filters are exclusives (both same time doesn't make sens) opened #318, delivery #92, takeaway ...
When a filter is selected, even if the search panel is closed, you can view the filter applied and quickly remove it because it's convenient.
On my sketching, the logo are not always here but it could be different. I begin to have always here the address field but having logo could be interesting for the "brand caresteouvert" but wihtout french language. We could have the logo (small), text field, button always displayed. 

On desktop, the search panel is always keep opened on left. The search textfield is in the same panel, on left.

Hope this is full cleared but know it's not so let's argue.  

https://balsamiq.cloud/sm5kz3o/pwimg5c
![New Wireframe 1](https://user-images.githubusercontent.com/787448/80025663-4ba78800-84e1-11ea-97d6-a047dd686f96.png)

**Comment by overflorian** [comment]
Thank you very much for this detailed proposal. It makes a lot of sense to me.
My idea was to have approximately the same design in the bottom menu, but I quite like the idea of having it at the top too.

In my opinion, if we choose this way, we should not rely to user to click on the SEARCH field only. We might want to add an extra button : sandwich button as before? Filter button ?

Also I like the idea of "The filters are exclusives (both same time doesn't make sens)" because it's a simpler UI.
But we could consider that "extra filters" (delivery, takeaway, currently open ...) can be combined with "categories / sub-categories"
_Use case: display all pharmacies open right now._

Least but not last: we could also have the solution of having
* the "extra filters" at the top, with the search bar
* the categories / sub-categories remaining in the bottom bar

**Comment by wadouk** [comment]
+1 for an other point of interraction for opening the search panel, the sandwich button come back, maybe the logo, other path with a look and feel tricks in this zone. I heard/read that designer doesn't like so much the "burger menu" but don't remember the arguments.

Of course for the combination between categories and filters, both are filters but they make sens to work together : only cheese shops that deliver. 

About the categories at the bottom.
At technical point, I will argue if I have to do it that having a layout closest between desktop and mobile it will be easier to do/maintain. Maybe other one will have other idea ?
At user point, all are filters so why not putting all together ?

**Comment by PanierAvide** [comment]
Closing as this issue may be solved by recent changes in UI.
