### ISSUE TITLE
Bug d'affichage colonne de gauche

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#32]
Comme vous pouvez le voir sur cette superbe capture d'écran, mon interlocuteur a un bug d'affichage. 
![index](https://user-images.githubusercontent.com/11553211/77679542-f4220500-6f92-11ea-9c09-ed994070130c.jpeg)

Sa config : Chrome 68.6.0 (à priori la dernière) sur Android (One Plus)

**Comment by francois2metz** [comment]
Faut qu'il recharge la page.

**Comment by PanierAvide** [comment]
Pas plus d'infos, pas réussi à reproduire. Je ferme le ticket, c'était peut-être un problème temporaire de cache ou autre.
