### ISSUE TITLE
Add shop=books for AT/CH/DE

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#321]
**Is your feature request related to a problem? Please describe.**
In Germany, independent book shops are often still open, offering delivery and/or takeaway service. Therefore we would like to see them on the map.

**Describe the solution you'd like**
Add a `books` subcategories with `shop=books` to the `shop` category.

**Describe alternatives you've considered**
None.

**Additional context**
Downstream: https://github.com/bleibtoffen/bleibtoffen/issues/56

**Comment by PanierAvide** [comment]
This is integrated, thanks !
