### ISSUE TITLE
Closed restaurants that moved to delivery only?

### ISSUE THREAD

**Issue by Matthias84** [osmontrouge/caresteouvert#325]
**Describe the bug**
Here in Germany all restaurants / fastfoods are closed. So some started to setup a online-shop / registred at existing delivery providers / ... and you can now order food for contactless delivery. A good chance for OSM to get that newest information!

Unfortunately currently the webpages doesn't allow a user to edit a object with shop is closed and only delivery is offered. For now, you need to say the shop is open and then you reach the card, where you can edit delivery only service. 

**Expected behavior**
I want to edit a POI and mark the local store to be closed but only a delivery is offered and where you can reach the online store. This results in tags like
```
delivery:covid19=only
description:covid19=https://delivery.losteria.de
opening_hours:covid19=off
```

**Comment by wadouk** [comment]
The website URL should have to be set in website tag, or do you make an other meaning ?

**Comment by PanierAvide** [comment]
Note that as now, all restaurants are shown even if they don't offer delivery. So if you use website tag as suggested, nothing has to be changed to fulfil your proposal.

**Comment by pqhf5kd** [comment]
I came here looking for a similar answer. opening_hours:covid19=off implies that the business is closed completely. The wiki page isn't clear how to tag this.

**Comment by PanierAvide** [comment]
The wiki has been made clearer on this : https://wiki.openstreetmap.org/wiki/FR:Key:opening_hours:covid19#Livraison.2C_vente_.C3.A0_emporter.2C_drive

**Comment by caugner** [comment]
> Unfortunately currently the webpages doesn't allow a user to edit a object with shop is closed and only delivery is offered. For now, you need to say the shop is open and then you reach the card, where you can edit delivery only service.

**Solution**: Show a hint "Place is closed, but offers delivery or takeaway? Choose Yes." in step 1 or (if "Closed" was chosen) in step 3.

**Comment by PanierAvide** [comment]
Yes, we can change simply the label : "Is this place open or offering services during lockdown ?"

Then, in step 3, we can change inputs like :
* Offers delivery : yes/no/I don't know
* Offers take-away : yes/no/I don't know
* Offers drive-through : yes/no/I don't know
* Can public enter this place : yes/no/I don't know -> fills `access:covid19` tag

**Comment by caugner** [comment]
How does the value `only` relate to those options?

(So far it's actually a bit confusing to set `delivery=only` and `takeaway=only`, because they seem to contradict each other. Maybe you have addressed that already?)

**Comment by PanierAvide** [comment]
Well we could not use it anymore as it seems to confuse many people. I was thinking at start that if we have delivery or takeaway=only, then place is not accessible inside to public. But using `access:covid19=no` + `delivery/takeaway:covid19=yes` might be clearer.

**Comment by Matthias84** [comment]
From my perspective, a simple tagging scheme is usually prefered, even if you could use it to construct illogical features.

Personally I'm perfectly happy to adapt only the edit process and use existing tags.
Maybe it makes also sense to show this explicitly at the map markers? Your popup uses a blue color, so POI markers with delivery might become a blue tone as well?

**Comment by PanierAvide** [comment]
This has been implemented

**Comment by govvin** [comment]
In addition to yes/no/i don't know, can you re-consider "only" option.

> Yes, we can change simply the label : "Is this place open or offering services during lockdown ?"
> 
> Then, in step 3, we can change inputs like :
> 
>     * Offers delivery : yes/no/I don't know
> 
>     * Offers take-away : yes/no/I don't know
> 
>     * Offers drive-through : yes/no/I don't know
> 
>     * Can public enter this place : yes/no/I don't know -> fills `access:covid19` tag

**Comment by PanierAvide** [comment]
Well, having `only` value was confusing for both people using the form and OSM contributors. This 3 state system is quite clear, and makes each field/tag independent. In which use case would you find it useful to put `only` value back ?

**Comment by govvin** [comment]
Thank you. I re-considered how to frame the situation for local mappers and you are right that these options are enough.
