### ISSUE TITLE
Import existing restaurants with delivery

### ISSUE THREAD

**Issue by Matthias84** [osmontrouge/caresteouvert#327]
**Is your feature request related to a problem? Please describe.**
OSM already contains the delivery=* tag to indicate restaurants / fastfoods / ... where people can order food online.
It would be nice, if you could import that infos to present this restaurants also with available services.

**Comment by PanierAvide** [comment]
I'm not sure of what you are offering : is it to display if a restaurant offer delivery/takeaway in right sidebar ?

**Comment by Matthias84** [comment]
Yes, to indicate it in the same way, as it would be a covid19 related delivery only.

**Comment by PanierAvide** [comment]
It's already the case, you can add `delivery:covid19=yes/only` or `takeaway:covid19=yes/only` in OpenStreetMap. This is already supported on our side, for example (appears in blue info tip in right sidebar) :
https://www.caresteouvert.fr/eat@48.114289,-1.692083,15.99/place/n4807400822
https://www.openstreetmap.org/node/4807400822

If your proposal goes beyond this, please make sure to detail what you're looking for :wink:

**Comment by PanierAvide** [comment]
More details on preferred tagging scheme for delivery : https://wiki.openstreetmap.org/wiki/FR:Key:opening_hours:covid19#Livraison.2C_vente_.C3.A0_emporter.2C_drive

**Comment by Matthias84** [comment]
Hi, thanks for reply, but I guess my post caused a misunderstanding :wink: 

I refer to the normal `delivery=yes` tag, which indicate that a shop regulary offers to bring food to your home. Usually they have a custom online shop or use takeway.com, deliveroo.com, deliveryhero.com, ... etc.

So I recommend to display such POIs in the same way, as a POI with `delivery:covid19=yes/only`
