### ISSUE TITLE
German "Packstation" missing

### ISSUE THREAD

**Issue by Matthias84** [osmontrouge/caresteouvert#328]
**Describe the bug**
The german post  [vending machines "Packstation"](https://wiki.openstreetmap.org/wiki/DE:Packstation) are missed as POI. They are tagged as `vending=parcel_pickup;parcel_mail_in` but of course the list might contain a space.

**Expected behavior**
Show POIs with post icon, e.g. [Packstation 105 at Rostock](https://www.openstreetmap.org/node/2466446544)

**Comment by PanierAvide** [comment]
Thanks for your feedback, it is integrated and will be visible in ~1h on website.
