### ISSUE TITLE
Cultural POIs offering videostreams, webcams, ... online events instead?

### ISSUE THREAD

**Issue by Matthias84** [osmontrouge/caresteouvert#330]
**Is your feature request related to a problem? Please describe.**
There are some cultural POIs, which offer extra online-services, to support their audience during the pandemic. This includes livestreams, webcams, podcasts, ... which is unfortunately spread over a lot of media channels and hard to discover quickly.

**Describe the solution you'd like**
I recommend to also add cultural POIs, which are off during the pandemic. IMHO this includes
```
amenity=arts_centre
amenity=cinema
amenity=community_centre
amenity=library
amenity=theatre
amenity=museum
amenity=nightclub
amenity=zoo
```
We might want to enrich their POIs with one / multiple URLs for COVID19 related content to make it visible to the interested users?

**Additional context**
Here at Rostock our arts centre [offers VR tours](https://www.kunsthallerostock.de/de/aktuelles/news/virtueller-rundgang), nightclubs livestream DJ sets, the zoo offers [DIY material](https://www.zoo-rostock.de/kinder-familie/downloads.html) ...

**Comment by PanierAvide** [comment]
Thanks for your proposal. Even if I see the interest of easily find this kind of information, do you think this would fit in OSM tagging scheme ? If so, what tag could be used to link to such information ?

**Comment by caugner** [comment]
@Matthias You might also want to join the [bleibtoffen repositiory](https://github.com/bleibtoffen/bleibtoffen).

**Comment by Matthias84** [comment]
Thanks for your recommendation and trust, but to do real work, I currently lack of time (and skills).

I think this is pretty forward for the OSM tags:
```
opening_hours:covid19=off
access:covid19=no
description:covid19=They started a VR tour...
```

If useful, we can add `website:covid19=https://....` to flag that there is a page dedicated to the services of the pandemic (and use it as filter for map markers etc)?

**Comment by PanierAvide** [comment]
+1 for `website:covid19` is this is a __temporary__ website

**Comment by Matthias84** [comment]
Yes, for website articles / fb posts / ... which refer the services and limitations during the pandemic.

**Comment by caugner** [comment]
Since this would be an additional information recorded in OSM and there had already been criticism about the COVID19 opening hours, it would probably be wise to discuss this in the local, regional or national community before, e.g. talk-de.

**Comment by caugner** [comment]
In my opinion it doesn't really make sense to show it in CRO, because CRO is about finding amenities and shops near you, whereas distance doesn't really matter for the cultural POIs you mention.

A project that gathers a list of these offers per city, region or country would suffice in my point of view. You don't need to see them on a map. But surely you could extract a list of those places from OSM or Wikidata first and provide a feedback form afterwards.

You might also want to have a look at https://lokalwirkt.de/, which follows a category- and list-based approach to collecting current data. They might collect cultural infos already or be interested in doing so.

**Comment by PanierAvide** [comment]
So closing this issue as "ça reste ouvert" is not the most relevant place to display such information.

**Comment by Matthias84** [comment]
I understand and see your point :smile: My intention was, that locals also want to 'explorer' what their neighbourhood / city does during the pandemic.
