### ISSUE TITLE
How To Tag Takeaway and Delivery

### ISSUE THREAD

**Issue by pqhf5kd** [osmontrouge/caresteouvert#331]
Some businesses are offering both a delivery and a contactless collection service while not open for shopping/eating/drinking on the premises.

If tagged takeaway:covid19=yes and delivery:covid19=yes that doesn't specify that customers are unable to shop/eat/drink in the establishment.

If tagged takeaway:covid19=only and delivery:covid19=only then the tags conflict each other.

**Comment by PanierAvide** [comment]
See new wiki documentation on this, which may be clearer : https://wiki.openstreetmap.org/wiki/FR:Key:opening_hours:covid19#Livraison.2C_vente_.C3.A0_emporter.2C_drive
