### ISSUE TITLE
vending=pizza dans "Alimentation"

### ISSUE THREAD

**Issue by py-b** [osmontrouge/caresteouvert#333]
Bonjour,
Pourrait-on intégrer les distributeurs de pizza (amenity=vending_machine+vending=pizza) dans la catégorie "Alimentation" ?
(et si possible avoir une icône spécifique ?)

**Comment by PanierAvide** [comment]
Bonjour, les distributeurs de pizza sont normalement déjà intégrés, exemple : https://www.caresteouvert.fr/@48.121438,-1.700962,19.06/place/n6833909160

La recherche par type sera implémentée prochainement pour faciliter leur découverte #103
