### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#340]
**Is your feature request related to a problem? Please describe.**
You make a great job at improving CRO continuously. As a side effect, a lot is changing here and there, which makes it hard to keep track of everything that is happening.

**Describe the solution you'd like**
It would be great to have a `CHANGELOG.md` file that lists the most notable changes that happen, ideally directly as part of the feature commits, or at least updated daily.

**Describe alternatives you've considered**
None.

**Additional context**
None, but thank you template for the reminder.

**Comment by PanierAvide** [comment]
Right, we clearly lack a changelog as now. One problem I see to introduce it is that we don't have proper releases as now, everything is rolling out continuously. I usually use the [keep a changelog](https://keepachangelog.com/en/1.0.0/) format, which needs versions numbers.

@francois2metz do we want to have semantic versioning ? Or we use a changelog only based on date ?

**Comment by caugner** [comment]
A changelog based on date is probably appropriate, also given that the backend is in another repository.

**Comment by francois2metz** [comment]
To better understand the need, who will read this changelog?

**Comment by caugner** [comment]
> To better understand the need, who will read this changelog?

Primarly the CRO "representatives" "responsible" for the different countries, and those people that are in contact with their town halls or with users and can't read (or make sense of) the commit history.

**Comment by francois2metz** [comment]
> Primarly the CRO "representatives" "responsible" for the different countries, and those people that are in contact with their town halls or with users and can't read (or make sense of) the commit history.

Which things did you missed that would been useful to know?

**Comment by caugner** [comment]
Never mind.
