### ISSUE TITLE
Quelques tags manquants

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#346]
Il manque quelques tags;

**Alimentation :**
On a les boulangeries, les pâtisseries, les chocolateries, mais pas les confiseries ;-)
- Confiseries => **shop=confectionery**   (1116 en France)

**Santé :**
-  Audioprothésistes => **shop=hearing_aids**  (763 en France)

Vu d'ailleurs sur le site du syndicat national des audioprothésistes (https://www.unsaf.org) qu'il existe une carte où sont répertoriés les centres (+ 1150) assurant la continuité des soins 
Elle se trouve ici => https://www.permanence-audio.fr
Des données utiles ?

**Matériaux :**
Commerces autorisés => _Commerce de détail de matériaux de construction, quincaillerie, peintures et verres en magasin spécialisé._
- Magasin de peinture : **shop=paint**   (374 en France)
- Magasin de vitrerie : **shop=glaziery**  (87 en France)

**Comment by PanierAvide** [comment]
Intégré, ce sera visible d'ici ~1h.

**Comment by Cybereric** [comment]
Bonjour,

Il y a un problème avec les POIs shop=confectionery

Certains n'apparaîssent pas

Exemples :
Orvault
https://www.openstreetmap.org/node/1984227691
https://www.caresteouvert.fr/@47.245195,-1.600680,18.58

Pornic
https://www.openstreetmap.org/node/7178626268
https://www.caresteouvert.fr/@47.115324,-2.098875,18.47

https://www.openstreetmap.org/way/55149776
https://www.caresteouvert.fr/@47.114772,-2.103657,18.81

La Baule
https://www.openstreetmap.org/node/1801882915
https://www.caresteouvert.fr/@47.282079,-2.392331,17.96


Toujours le même tag et là c'est OK le POI est visible

Ancenis
https://www.openstreetmap.org/node/3429992631
https://www.caresteouvert.fr/@47.374733,-1.187739,18.74/place/n3429992631

Nantes
https://www.openstreetmap.org/node/2607658271
https://www.caresteouvert.fr/@47.217567,-1.551742,18.16/place/n2607658271

https://www.openstreetmap.org/node/2590489606
https://www.caresteouvert.fr/@47.217567,-1.551742,18.16/place/n2590489606


Remarque :
Lorsqu'on sélectionne les POIs visibles ils sont considérés comme "Autres établissements"

Chose curieuse lorsque j'active le filtre "Autres établissements" j'ai ça => https://www.caresteouvert.fr/other@47.219132,-1.558822,14.05
Seulement trois points qui apparaissent
Un traiteur => qui est aussi dans la catégorie "Autres établissements"
et les deux shop=confectionery cités plus haut

En me déplaçant sur Ancenis toujours avec le filtre.
Je retrouve mon POI de confiserie visible
https://www.caresteouvert.fr/other@47.372345,-1.177216,13.32/place/n2465163331
Plus la mairie :-/

J'ai systématiquement vidé le cache du navigateur à chaque fois
Le phénomène est le même avec les navigateurs Firefox et Chromium.

**Comment by francois2metz** [comment]
Effectivement, le tag `confectionery` n'avait pas été rajouté. C'est corrigé, et sera visible dans ~1 heure.
