### ISSUE TITLE
Alternative Transifex integration

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#348]
**Is your feature request related to a problem? Please describe.**
Locales are imported automatically from Transifex, however the integration seems to be buggy these days. This could be improved using a dedicated bot account.

**Describe the solution you'd like**
You could use the bot approach that I'm using for the @vue/cli and guijs locales:
* https://github.com/caugner/vue-cli-locales
* https://github.com/caugner/guijs-locales

I have copied that approach from Nextcloud's @nextcloud-bot (see [their commits](https://github.com/nextcloud/desktop/commits?author=nextcloud-bot)).

All you need is:
* Add the `.tx/config`, `requirements.txt` and `.travis.yml` files.
* Define the bot's github token (`GH_TOKEN`) and your transifex token (`TX_TOKEN`) as a secret environment variable in Travis.

**Describe alternatives you've considered**
Fix the transifex integration.

**Additional context**
See https://github.com/caugner/vue-cli-locales/commits/master for how that looks in action.

**Comment by PanierAvide** [comment]
As you are familiar with Transifex Integrations, is the problem we encounter recently is something regular ? If not, it seems too many machinery for a temporary problem. If yes, then could be worth it.

**Comment by caugner** [comment]
I'm not familiar with the specific Transifex Integration they offer now. When I setup `vue-cli-locales` they didn't offer that yet afaik (otherwise I would have tried it). But in general I have always had recurring issues with Transifex, yes.

The advantage of the bot approach is that you don't need to merge PRs, as the bot could push directly. On the other hand, Travis only supports daily cronjobs on the free Open Source plan.

So maybe running these commands every 5 minutes or so on a server setup with a bot account would be the safest approach (just don't `git push -f`):
https://github.com/caugner/vue-cli-locales/blob/89ea7b56296ee03a4fee20c9bf7d26d918085bc2/.travis.yml#L17-L22

**Comment by caugner** [comment]
Closing, since the integration seems to work again.
