### ISSUE TITLE
Bug d'affichage quand aucune couche n'est sélectionnée

### ISSUE THREAD

**Issue by ViolaineDo** [osmontrouge/caresteouvert#35]
On ne devrait rien voir d'affiché quand aucune couche n'est sélectionnée, ce qui n'est pas le cas : 
https://www.caresteouvert.fr/police=false&pharmacy=false&post_office=false&food=false&bakery=false&shop=false&bank=false&fuel=false&funeral_directors=false@-17.545042,-149.575043,14.90

**Comment by francois2metz** [comment]
Bonjour Violaine,

Merci pour ce retour. J'ai corrigé ça.

**Comment by ViolaineDo** [comment]
Hello,
En fait il reste des points qui se baladent ici.. (juste 3, on est sur du détail).
@+

**Comment by PanierAvide** [comment]
Peut-être pour que la base soit toujours raccord avec le site, je peux faire une catégorisation synthétique ? Garder le champ `cat` pour l'affichage et panneau de droit, et ajouter un `cat_normalized` pour panneau de gauche et icônes ?

**Comment by PanierAvide** [comment]
J'ai réalisé les modifications suivantes pour résoudre ce problème récurrent :
* Créé une colonne `normalized_cat` en base de données, qui reprend le logique des filtres de la colonne de gauche de la carte
* Ajouté une catégorie "other" (autres établissements) pour tout ce qui a une info `opening_hours:covid19` mais ne rentre dans aucune catégorie
