### ISSUE TITLE
Disable Matomo for bleibtoffen.{at,ch,de}

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#354]
**Is your feature request related to a problem? Please describe.**
We would like to disable Matomo completely for the German domains, since we don't need it (and don't want it).

**Describe the solution you'd like**
Add an option to the `config.json` to disable Matomo completely for a given brand/domain.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by caugner** [comment]
I created this issue quickly yesterday. The background is that the German association that sponsored the domain would like to advertise the app as privacy friendly in contrast to Google Maps. Therefore the cookie banner doesn't look good.

**Comment by overflorian** [comment]
Let discuss that at the phone as proposed

**Comment by overflorian** [comment]
As discussed we are in a process of looking for a long-term solution but we need the analytics for now.
