### ISSUE TITLE
Afficher la date de dernière modification

### ISSUE THREAD

**Issue by QuentinS33** [osmontrouge/caresteouvert#360]
Bonjour,
Il arrive que pour un magasin, les horaires changent en fonction de la semaine. Prenons en exemple mon bureau de poste d'où j'ai été surpris du changement des jours et horaires d'ouverture. C'est pourquoi je verrai bien une info concernant la dernière date de mise à jour, soit par le biais du changeset, soit par le biais d'un nouveau tag du style "survey-date-covid19".
Qu'en pensez-vous ?
NB1 : A cause de l'interprétation de github, bien entendu les tirets seront remplacés par des ":"
NB2 : J'en ai déjà parlé à Florian LAINEZ en off

**Comment by PanierAvide** [comment]
@vdct est-ce que la date de dernière modification peut être ajoutée par Imposm ?

**Comment by overflorian** [comment]
Je trouve que c'est une information importante et qui sera particulièrement utile lors de la phase de déconfinement qui durera plusieurs semaines.

**Comment by caugner** [comment]
I remember we talked about this, because I had requested the same feature about a week ago.

I think imposm doesn't import the last modification time, which makes this hard to implement.

**Comment by PanierAvide** [comment]
Otherwise, we could also ask dynamically when a POI is shown in sidebar its last edit date by calling OSM API. This avoid to have info in DB, but we can still display it on front-end.

**Comment by QuentinS33** [comment]
Vous ne pensez pas que ce serait plus simple de passer par la clé "survey-date-covid19" ?
(Remplacer "-" par ":" dans la clé)
Translation for @caugner : It wouldn't be easier to create a new key "survey-date-covid19" ?
(Replace "-" by ":" in the key)

**Comment by overflorian** [comment]
> Vous ne pensez pas que ce serait plus simple de passer par la clé "survey-date-covid19" ?
> (Remplacer "-" par ":" dans la clé)
> Translation for @caugner : It wouldn't be easier to create a new key "survey-date-covid19" ?
> (Replace "-" by ":" in the key)
+1

**Comment by PanierAvide** [comment]
Even if this could be a solution, I'm not sure this will be systematically defined. What we can do in that case is use `survey:date:covid19` if set, and if not call OSM API for last edit date. What do you think ?

**Comment by caugner** [comment]
> Even if this could be a solution, I'm not sure this will be systematically defined. What we can do in that case is use `survey:date:covid19` if set, and if not call OSM API for last edit date. What do you think ?

The argument against using that key is probably the same as the one recording `source:covid19`. Since it would only get updated by CRO, it wouldn't attribute for manual edits (e.g. edits following the created notes).

**Comment by vdct** [comment]
> 
> 
> @vdct est-ce que la date de dernière modification peut être ajoutée par Imposm ?

Unfortunately not. Apologies for the late answer

**Comment by QuentinS33** [comment]
Je relance le sujet, une décision a-t-elle été prise pour cette information ?

**Comment by vdct** [comment]
Pas de nouvelle décision non. L'information de date de dernière modif n'est pas disponible au travers des outils qu'on utilise pour traiter les données OSM, donc pas d'issue en l'état

**Comment by PanierAvide** [comment]
Si la solution c'est d'aller interroger OSM sur la base de l'identifiant, donc possible techniquement. Après je sais pas vraiment comment l'afficher pour que ce soit pertinent.

**Comment by QuentinS33** [comment]
Pour ce qui est question de l'affichage : Lorsque tu cliques sur le POI et que les informations sont affichées. A l'endroit où est inscrits "lieu ouvert durant le confinement", je verrai bien un petit encart indiquant "il y a 1 jour" si la modification date d"hier par exemple.
Voici un exemple de ce qui m'avait pensé à ce genre d'informations à afficher : https://apps.apple.com/fr/app/essence-gasoil-now/id681463839
(images 3 et 4 notamment)

**Comment by vdct** [comment]
> 
> 
> Si la solution c'est d'aller interroger OSM sur la base de l'identifiant, donc possible techniquement. Après je sais pas vraiment comment l'afficher pour que ce soit pertinent.

Oui mais ce qui compte ici (je pense) c'est la date de la dernière modif *que nous affichons* donc celle dont on dispose dans notre image locale d'OSM. Et c'est bien là que l'info manque hélas, du fait d'une [limitation d'imposm](https://github.com/omniscale/imposm3/issues/58)

**Comment by PanierAvide** [comment]
Certes :sweat_smile: On peut toujours récupérer la date depuis OSM, si la date est plus vieille qu'une heure on l'affiche, sinon on affiche un libellé type "il y a une heure (mise à jour en cours)" ?

**Comment by PanierAvide** [comment]
Cf #521

**Comment by PanierAvide** [comment]
C'est intégré et ce sera dispo sur le site dans quelques minutes.
