### ISSUE TITLE
Ajout d'une catégorie "Centre de consultations Covid19"

### ISSUE THREAD

**Issue by QuentinS33** [osmontrouge/caresteouvert#361]
Bonjour,
J'ai récemment ajouté un Centre de consultations covid19 dans ma commune. J'ai demandé sur le fil de disussion talk-fr [1] la meilleure façon de la tagguer.
Actuellement, mon POI est bien affiché grâce au tag "opening_hours:covid19" dans la catégorie "Autres établissements"
Je pense que cette information est de première ordre et pourrait avoir sa propre catégorie, tout comme les pharmacies.
[1] Prendre à partir d'ici : https://lists.openstreetmap.org/pipermail/talk-fr/2020-April/098075.html

**Comment by francois2metz** [comment]
Est ce que cela correspond à #196 ?

**Comment by QuentinS33** [comment]
Oui exactement, j'ai regardé pour la commune de Balma, on me montre bien l'établissement que j'ai réajouté. Attention par contre au POI, très mal placé, je soupçonne le centroide du polygone de la commune

**Comment by francois2metz** [comment]
Peut tu donner un lien vers ça reste ouvert pour que je regarde ?

**Comment by QuentinS33** [comment]
Ce point : https://www.caresteouvert.fr/@43.612662,1.485537,18.22

**Comment by francois2metz** [comment]
Comme c'est un point, il est placé exactement comme dans OSM, on n'a pas déterminer un quelconque centre.

**Comment by QuentinS33** [comment]
Je me suis mal exprimé. Je te prie de m'excuser
Sur la #196, le site indiqué mentionne tous ces centres. Or, le site en question place mal les POI.
Le lien que je t'ai envoyé sur mon dernier message correspond à la réalité du terrain, j'ai rajouté personnellement les informations du POI.
Ma demande correspond à intégrer ces POI faisant référence à des établissements de santé

**Comment by PanierAvide** [comment]
Si on ajoute une entrée "centre de consultation covid19" en sous-catégorie de santé, ça ferait le boulot ?

**Comment by QuentinS33** [comment]
Ce serait une bonne idée de détecter ce genre d'établissements en les regroupant dans "Santé". A ton avis, il faudrait que j'édite une page Wiki OSM pour bien tagguer ce genre d'établissements ?

**Comment by PanierAvide** [comment]
C'est ajouté, ce sera visible d'ici ~1h
