### ISSUE TITLE
petite correction de wording

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#363]
Je suggère de remplacer :
> Votre signalement a été enregistré, merci !
> Patientez, cela peut prendre un moment avant qu'il soit pris en compte.

par une mention plus courte et plus explicite :
> Votre signalement a été enregistré, merci !
> Il apparaîtra sur la carte d'ici peu.

**Comment by francois2metz** [comment]
C'est plus court mais pas plus explicite selon moi. Si une note est créée, on ne peut pas s'attendre a ce que cela soit  "d'ici peu".

**Comment by overflorian** [comment]
Il apparaîtra sur la carte d'ici un moment
?

**Comment by overflorian** [comment]
dans un moment
?

**Comment by caugner** [comment]
Maybe use two different messages depending on whether a note will be created. The short one if not, a longer one if yes. 

In the German locale, I added the info to the comment field title that this causes the report to be verified manually. It looks like this already reduced the number of irrelevant comments somehow.

**Comment by Bibi56** [comment]
> Il apparaîtra sur la carte d'ici peu.

"Il apparaitra après traitement par un contributeur OpenStreetMap."

Comme ça on voit qu'il y a des gens qui travaillent derrière (dont un^^).
C'est plus long et plus exact. Mais l'idée de Claas me plait bien.

**Comment by overflorian** [comment]
le mot "traitement" ne sera, il me semble, pas compris du grand public, ni même la mention "contributeur OpenStreetMap" : n'oubliez pas que les utilisateurs ne sont pas des geeks.

Ma proposition vise à simplifier le wording, pas l'alourdir. Je pense que créer deux version différentes est une erreur : du point de vue de l'utilisateur, 2 contributions, qu'elles aient pour conséquence de créer une note ou pas, c'est la même opération. Le wording devrait donc rester neutre sur les traitements à posteriori.
Le wording neutre "dans un moment" est assez flou pour pouvoir vouloir dire "d'ici 60 minutes" ou "dans quelques heures / jours".

**Comment by caugner** [comment]
Background: When I made my first contributions to CRO, I *always* put a note with the source in the comment field, not knowing that this information won't get recorded and not knowing that this slows down the workflow by requiring a manual edit. Had I known, I would have omitted the comment.
