### ISSUE TITLE
Tags associés à la catégorie "Épicerie"

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#366]
Lorsqu'on sélectionne un POI avec les tags suivants

- shop=chocolate
- shop=cofee
- shop=tea
- shop=dairy
- shop=confectionery

Le type de commerce qui s'affiche est "**Épicerie**" !

![epicerie](https://user-images.githubusercontent.com/7645549/79346596-dbbe5e00-7f32-11ea-89a5-96eec23c69cb.png)

Ces magasins ne correspondent pas vraiment à ce qu'on appelle de l'épicerie.

Je vois aussi que pour shop=pastry on a "Boulangerie" au lieu de "Pâtisserie"

Ces **6 tags** ne pourraient-ils avoir **leurs caractéristiques propres** ?
Comme on a déjà :
- "Poissonnerie" pour shop=seafood 
- "Boucherie" pour shop=butcher
- "Fromagerie" pour shop=cheese
- Etc.

Donc cela donnerait :

- shop=pastry       => **Pâtisserie**
- shop=chocolate    => **Chocolaterie**
- shop=confectionery => **Confiserie**

- shop=coffee => **Magasin de café** 
- shop=tea => **Magasin de thé**

- shop=dairy => **Crèmerie**

**Comment by francois2metz** [comment]
S'agit-il de la même issue #365 ?

**Comment by Cybereric** [comment]
Oui j'ai fermé #365
Désolé

**Comment by PanierAvide** [comment]
À noter que pour faciliter la prise en compte de nouvelles catégories (ou différenciation dans ce cas là), on est preneurs d'icônes SVG libres de droits aux dimensions 18x18px. Elles peuvent venir par exemple de https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/ mais doivent être redimensionnées.

**Comment by pyrog** [comment]
Pour `shop=dairy` ou `shop=cheese` il y a https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/dairy.svg

Je n'aime pas trop, mais c'est mieux que la pomme 😉

**Comment by PanierAvide** [comment]
La version Font Awesome sera sûrement celle qui ressortira le mieux une fois réduite à 18x18px :wink:

**Comment by pyrog** [comment]
Le redimensionnement est fait sur ma machine (on ne peux pas les uploader en svg dans un ticket).
Je t'envoi ça par mél 😉

**Comment by PanierAvide** [comment]
Au pire tu peux copier/coller le contenu texte du svg directement, si c'est fait avec Inkscape bien penser à enregistrer en "svg simple" (plus léger). C'est pour limiter le bus factor : si j'ai pas le temps de m'en occuper, quelqu'un d'autre aura déjà tout ce qu'il faut ici pour le faire ;-)

**Comment by pyrog** [comment]
> avec Inkscape bien penser à enregistrer en "svg simple" (plus léger)

Zut, pas pensé 🤒

**Comment by PanierAvide** [comment]
D'habitude ça pose pas de problèmes, mais là le script qui fusionne les SVG pour en faire un fichier de police d'écriture est un petit peu _tatillon_ si le fichier comporte trop de balises annexes :sweat_smile:

**Comment by pyrog** [comment]
Essaie stp avec les 3 versions que je t'ai envoyé par "courrier".
Je ferais le nettoyage et une PR 😄

**Comment by PanierAvide** [comment]
C'est ce que je disais dans un message précédent : la version Font Awesome me semble bien. Disponible en fichier brut ici : https://thenounproject.com/search/?q=cheese&i=2441110

(désolé j'ai assez peu de temps aujourd'hui :-/ )

**Comment by Cybereric** [comment]
Voici ma liste pour les 6 POIs :

**Ces premières icônes sont donc celles d'OpenStreetMap Carto**

**dairy** 
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/dairy.svg
![dairy](https://user-images.githubusercontent.com/7645549/79434438-ab2c0200-7fce-11ea-845a-5b4a27f3fde8.png)


**coffee**
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/coffee.svg
![coffee](https://user-images.githubusercontent.com/7645549/79434479-bda63b80-7fce-11ea-8e6d-11cacb8c0250.png)


**tea**
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/tea.svg
![tea](https://user-images.githubusercontent.com/7645549/79434730-137ae380-7fcf-11ea-9a95-ff6077492e4b.png)


**pastry** 
C'est en fait l'icône de confectionery dans le style "Carto" mais je trouve que ça "passe" mieux en pâtisserie.
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/confectionery.svg
![pastry](https://user-images.githubusercontent.com/7645549/79434821-34dbcf80-7fcf-11ea-8229-452ce47d3468.png)

========================================================

**Icônes suivantes venant de The Noun Project sous licence CC BY**

**chocolate**
https://thenounproject.com/term/chocolate/3058729/
CC BY Serhii Smirnov 
![chocolate](https://user-images.githubusercontent.com/7645549/79434879-458c4580-7fcf-11ea-8084-9ddf4eaac2f9.png)

Pour **confectionery** il faut choisir. 
La première icône est pas mal. On "voit" bien le bonbon je trouve.

**confectionery 1**
https://thenounproject.com/term/candy/1466991/
CC BY Hat-Tech  
![confectionery1](https://user-images.githubusercontent.com/7645549/79434934-59d04280-7fcf-11ea-8c0c-b4440965a6de.png)


**confectionery 2**
https://thenounproject.com/term/candy/2166537/
CC BY Vectors Market
![confectionery2](https://user-images.githubusercontent.com/7645549/79434948-5f2d8d00-7fcf-11ea-9591-ebf644c5a974.png)


**confectionery 3**
https://thenounproject.com/term/toffee/2713874/
CC BY Eucalyp 
![confectionery3](https://user-images.githubusercontent.com/7645549/79434968-65236e00-7fcf-11ea-8fd6-6d03cd436f16.png)

==============================================================

**Toutes les icônes** mises au **format SVG simple 18 px**  (fichier ZIP à télécharger)

=> https://covid19.framadrop.org/r/cUtM0fNxcv#XSjf6/k+GYvbeDzpXUaM6ILyFUXAe7rOjfXiDi90yP0=

**Comment by PanierAvide** [comment]
Merci, ce sera visible d'ici ~1h
