### ISSUE TITLE
Ajout lien page wiki dans l'interface

### ISSUE THREAD

**Issue by deuzeffe** [osmontrouge/caresteouvert#370]
Hello,

À défaut de mode d'emploi détaillé (pour osm-addicts ou simplement curieux), on pourrait avoir un lien vers la page du wiki (par ex. https://wiki.openstreetmap.org/wiki/France/Covid-19 ) dans l'interface de CRO ? Par exemple dans la bulle "En savoir plus" ?

Merci pour la réponse, quelle qu'elle soit.

**Comment by PanierAvide** [comment]
Salut :-) On a le lien vers cette page qui apparaît dans [la page à propos](https://blog.caresteouvert.fr/about/), dont le lien apparaît sur le site web. Et on est à la recherche de personnes motivées pour écrire du contenu sur le blog, notamment des ressources pour faciliter la contribution. Si c'est un sujet qui t'intèresse on peut en discuter :smiley:

**Comment by deuzeffe** [comment]
@PanierAvide Certes (moi ? intéressée par la doc. ? légende urbaine !) Je ne suis qu'utilisatrice du projet (en plus d'un manque de dispo. temporelle monstrueuse)...

Mais pour l'instant, juste un lien vers le wiki (dans la bulle à propos - visible d'emblée - ou dans le panneau de droite, en bas, dans le cartouche osm - moins user-compliant amha), ce n'est vraiment pas possible ?

**Comment by PanierAvide** [comment]
On peut le faire apparaître dans la popup "à propos" oui, @overflorian quel libellé on pourrait mettre pour l'y faire apparaître ?

**Comment by overflorian** [comment]
Bonne idée !
Je suggère "Documentation pour contributeur OpenStreetMap" en attendant le guide complet ;)

**Comment by PanierAvide** [comment]
Ajouté, ça sera visible dans quelques minutes sur le site. Merci du retour :+1

**Comment by deuzeffe** [comment]
@PanierAvide l'ouverture de la page dans un nouvel onglet serait ze chéri on ze kèïke :)

**Comment by PanierAvide** [comment]
Cherry on the cake is on its way :cherries: :smile:
