### ISSUE TITLE
Display fax number

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#373]
**Is your feature request related to a problem? Please describe.**
Display fax number

Example:
https://www.caresteouvert.fr/health@46.479371,0.368976,18.62/place/n2153404526

**Comment by PanierAvide** [comment]
Fax, that's a name I haven't heard in a long time :grin:

**Comment by PanierAvide** [comment]
Can you offer a PR for this feature ? That may be quite simple, as you can mimic the phone field, maybe also find an appropriate icon (SVG, 18x18px).

**Comment by pyrog** [comment]
There is a big usage in healthcare in France :
Doctors and nurses send prescriptions to pharmacies 😉

**Comment by PanierAvide** [comment]
Yes that's what I thought about, so it makes sense to show this info.

**Comment by overflorian** [comment]
![giphy](https://user-images.githubusercontent.com/11553211/79429973-86cd2700-7fc8-11ea-912d-2e42cb9593fb.gif)

**Comment by gendy54** [comment]
I can confirm that it is still widely used in hospitals. je reçois même des fax de bilans dans mon bureau des ressources humaines
