### ISSUE TITLE
Display every shops with direct link in URL

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#374]
**Describe the bug**
A direct link to an OSM object that is not yet handled display an invisible box.

**To Reproduce**
Example : this [pub](https://www.caresteouvert.fr/@46.673800,5.552386,18.12/place/n7409176494) ([n7409176494](https://www.openstreetmap.org/node/7409176494)) without `*:covid19` tags. 

**Expected behavior**
Display it's properties in the right panel as any "shops" with `*:covid19` tags.

I would like to give a link i.e. to **the owner shop** so he **could edit his shop** or at least display it.

**Screenshot**
<img width="1280" alt="Invisible right panel" src="https://user-images.githubusercontent.com/2158081/79415422-ae62c600-7fad-11ea-952a-3853236a7648.png">

**Comment by vinber** [comment]
i'm not sure to understand link with osmose ?

If i well understand,  you want to schow in CRO a shop which are not actually display.

It's easier perhaps to add amenity=pub in categorie eat ?

**Comment by pyrog** [comment]
osmose, just a typo 😆 

Adding `amenity=pub`, I'am not sure.
If I remember well, it happened for all "shops" without `*:covid19` tags.

**Comment by PanierAvide** [comment]
It's a bug for sure, but expected behaviour can't be the one specified : if sidebar doesn't appear, it's because we don't have kept feature in our filtered POI table. So we can't / don't want to display this. Expected + technically reasonable behaviour is to not try to open sidebar if we don't have the feature on our side.

**Comment by pyrog** [comment]
> reasonable behaviour is to not try to open sidebar

Better than invisible sidebar 😉 

Is it possible that the front or back-end download "on the fly" data directly to osm API for these "missing" POI ?

**Comment by PanierAvide** [comment]
It's _possible_, but when this will be used ? By who and for which kind of use ?

**Comment by pyrog** [comment]
I don't know exactly how, but for "newbies" to add a shop to CRO that is already in OSM.

How he could find it ?
When clicking on "Report a shop", we could display a "form" that suggest to find the POI inside OSM first :
- Search by name with Nominatim ?
- And/or by searching inside a circle centered  on the map ("like" OSM website) ?

The "form" (a sidebar ?) must also display the current [link to the blog](https://blog.caresteouvert.fr/que-faire-sil-manque-un-commerce-dans-ca-reste-ouvert/) 😄

**Comment by francois2metz** [comment]
I fixed the invisible sidebar.

About displaying any shops/features, I don't think we want that.

**Comment by PanierAvide** [comment]
Sure, we may instead look for being exhaustive on categories we display.
