### ISSUE TITLE
Expand to DRC

### ISSUE THREAD

**Issue by clairedelune** [osmontrouge/caresteouvert#377]
### Requirements:
- [X] You are a team of at least 2 people experienced with OpenStreetMap
- [X] Translate the app via transifex with your country languages
- [X] Translate some content of the blog to help newcomers (how to create a new shop, the about page, ...)
- [X] Start gathering data about shop open or closed nation wide in https://github.com/PanierAvide/Covid_enseignes/ 
- [ ] Once everything has been done and the data have been loaded, you should be busy getting media coverage. So the map will have a lot of contribution and be quickly useful.

### Team:
- @vick25
- @yongololo
- @clairedelune

### Localized domain name:
- ezosala.org

### Categories:
- We've started updating the category list although we are expecting new legal changes in the coming days.

**Comment by PanierAvide** [comment]
Hi, did you made some progress on various listed tasks ? Don't hesitate to ask us questions if you have any :wink:

**Comment by clairedelune** [comment]
> 
> 
> Hi, did you made some progress on various listed tasks ? Don't hesitate to ask us questions if you have any wink

Hi @PanierAvide, yes we did. Just submitted some issues for the legal rules csv. On a different matter, I'm hoping we could have roadblocks/police checkpoints displayed differently from shops and services at some point.

**Comment by PanierAvide** [comment]
For barriers, it is being done through #402

**Comment by PanierAvide** [comment]
@francois2metz @clairedelune was the configuration of domain name done ? I think it's the last missing piece to open in DRC ? As we have brand logos, info about legal rules, country geometry...

**Comment by clairedelune** [comment]
@PanierAvide, the configuration of domain name is done and the legal rules have been updated. The data isn't showing for DRC yet though and there are some adaptations still to do on the front page too.

**Comment by PanierAvide** [comment]
UI should appear as expected as now, and data is shown. Let us know if something is still missing before you start communicating about the project there.
