### ISSUE TITLE
Traduire le site en anglais

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/caresteouvert#38]
Pour les anglophones et les autres, on pourrais traduire le site en anglais.

**Comment by francois2metz** [comment]
Ça se passe dans le fichier `locales.json`.

**Comment by fbroussais** [comment]
Bonjour, j'ai un premier jet ici : https://github.com/fbroussais/covid19_map/blob/master/locales.json

**Comment by PanierAvide** [comment]
Merci, je viens d'intégrer une PR qui proposait la traduction. Au-delà de l'interface, il reste quelques éléments à rendre traductibles : page à propos, texte des notes...

**Comment by MatthieuOSM** [comment]
Bonjour, Ce n'est pas en rapport direct avec la traduction mais lié. Il m'a été rapporté que l'interface s'affichait en anglais déjà. Surement que cela détecte l'user agent et/ou les paramètres de langue du système ?

Est-il envisagé d'avoir une option pour changer la langue ?

**Comment by francois2metz** [comment]
J'ai rajouté un sélecteur de langue dans le menu qui sauvegarde la dernière valeur.

**Comment by PanierAvide** [comment]
On a le sélecteur de langues, la possibilité de traduire sur Transifex https://www.transifex.com/openlevelup/ca-reste-ouvert/dashboard/
Je ferme donc le ticket
