### ISSUE TITLE
Reopening and maximum capacity

### ISSUE THREAD

**Issue by gendy54** [osmontrouge/caresteouvert#389]
**Is your feature request related to a problem? Please describe.**
To accompany the gradual reopening of the stores, some will implement specific measures.

This is a specific tag to add information that doesn't fit in an existing tag, ie: max 10 people on the shop at the same time.

**Describe the solution you'd like**
I suggest **capacity:covid19** or **capacity_max:covid19** but I think the first tag is enough

**Comment by PanierAvide** [comment]
I approve `capacity:covid19` :+1: Should we document this right now, or is it too soon yet ?

**Comment by overflorian** [comment]
> I approve `capacity:covid19` +1 Should we document this right now, or is it too soon yet ?

+1

**Comment by PanierAvide** [comment]
@gendy54 You want to add documentation for this on OSM wiki, at least in French ?

**Comment by gendy54** [comment]
Yes

**Comment by gendy54** [comment]
I changed the wiki to French and English.

**Comment by PanierAvide** [comment]
Great ! So we can display this tag if set. When we will have more info on re-openings, we will think about best way to ask user this info : approximate value, `restricted`, exact value...

**Comment by PanierAvide** [comment]
Added display of this tag if set on a POI, will be online in a few minutes.

**Comment by PanierAvide** [comment]
I think we can close the issue for now, and re-open it when it will be clearer on how we can handle contribution on this topic (May 11th ?).
