### ISSUE TITLE
opening_hours : Les commentaires ne sont pas affichés

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#39]
Le [commentaire](https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification#Explanations)  n'est pas affiché `opening_hours=Tu-Sa 08:30-12:00 "Sur rendez-vous"`

Exemple:
- https://www.openstreetmap.org/way/123009543
- https://www.caresteouvert.fr/@46.576882,5.750625,18.75/place/w123009543

**Comment by PanierAvide** [comment]
Pour l'instant on a 9 `opening_hours:covid19` en base avec des commentaires, dont certains ayant juste un commentaire. Je suis d'avis plutôt de renseigner `description:covid19`. Si par la suite l'usage se généralise on pourra parser cette syntaxe.

**Comment by pyrog** [comment]
Je ne pige pas tout : tu ne l'analyses pas déjà ?
C'est une syntaxe `opening_hours` standard.

D'ailleurs, comment sont affichées les `opening_hours` avec des commentaires ?
(il doit y en avoir plus que 9 😆 )

**Comment by PanierAvide** [comment]
En fait il y a deux endroits où sont gérés les horaires :
* Dans le panneau latéral de droite sur la carte, l'ensemble des horaires qu'on peut dérouler : géré par la bibliothèque `opening_hours` (cf #40). Cette bibliothèque doit le gérer mais je ne sais pas si elle l'affiche directement
* Dans la base de données, pour déterminer le "statut d'ouverture" (couleur des marqueurs + information en haut du panneau latéral droit "c'est ouvert / c'est fermé" et les infos dans le bandeau bleu) : là c'est du code SQL maison. Ça me paraît galère de parser ça de manière fiable en SQL (s'il manque un guillemet, s'il y a deux commentaires, si on a des commentaires dans `opening_hours` + `opening_hours:covid19`...). Même si c'est standard, ça veut pas dire pour autant que c'est simple à gérer :sweat_smile: 

Là pour l'affichage, tu faisais référence à quel élément ?

**Comment by pyrog** [comment]
Je faisais référence à la liste dans le panneau de droite.

J'ai trouvé un autre exemple : [Pharmacie de l'Observatoire](https://www.caresteouvert.fr/@48.839671,2.337402,20.51/place/n788761911) ([n788761911](https://www.openstreetmap.org/node/788761911#map=18/48.83965/2.33644))

Et une requête overpass pour en trouver : https://overpass-turbo.eu/s/S2l

**Comment by PanierAvide** [comment]
OK, dans ce cas c'est bien `opening_hours.js` qui gère ça et son affichage n'est pas forcément évident non plus : https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2008%3A00-20%3A00%2C%20Sa%2009%3A00-20%3A00%2C%20PH%2008%3A00-21%3A00%20%7C%7C%2008%3A00-21%3A00%20%22Dimanches%20de%20garde%22&lat=48.7769&lon=9.1844&mode=0&DATE=1585479715964

**Comment by pyrog** [comment]
C'est retourné dans la chaine en vert:
_L'installation est indéterminée en ce moment, mais cela dépend de "Dimanches de garde"._

Tu la récupères comme ça :
```javascript
var unknown = oh.getUnknown(date);
```

**Comment by PanierAvide** [comment]
D'accord, tu aurais envie de faire une pull request pour intégrer ça ? On peut t'aider au besoin :wink:
