### ISSUE TITLE
Accept geographic coordinates in the search box

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#393]
**Is your feature request related to a problem? Please describe.**
Can't search i.e for "44.3877159,7.5453774" (it work's on many maps)

**Describe alternatives you've considered**
Must edit the url to paste the new coordinates.

**Additional context**
Sometime the search can't find some POI, so I need to paste the coordinates.
For testing the apps, I paste coordinates of POI founded with overpass.

**Comment by PanierAvide** [comment]
This is implemented, and will be online in a few minutes. Thanks for feedback :+1:

**Comment by pyrog** [comment]
Ok, thank you very much too 😃 

@Joxit This feedback could be useful too for Jawg as many of their users/customers could appreciate it 😉

**Comment by Joxit** [comment]
Hi,

This feature is named [`reverse geocoding`](https://www.jawg.io/docs/apidocs/places/reverse/) which is already a part of our API.
This is an integration issue, the input should be parsed and do a reverse geocoding when coordinates are in the search box.

Anyway, thank you for you use case, I will add it for our future integration kit ;)
