### ISSUE TITLE
Wording page "à propos"

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#394]
Je propose de remplacer le wording 

> « Ça reste ouvert », un outil de communication pour les mairies ! 

par 

> Solution de communication de crise pour les mairies

Je propose aussi de rajouter les bannières Play Store / F-droid / App Store / Github en bas

**Comment by francois2metz** [comment]
@overflorian tu peux changer le wording sur transifex directement

**Comment by PanierAvide** [comment]
Celui-là il faudrait plutôt le changer en anglais d'abord, comme il y a guillemets + `{brand}` transifex râle si c'est plus dans le texte en français.

**Comment by PanierAvide** [comment]
Fait, ça sera en ligne dans quelques instants
