### ISSUE TITLE
Icônes manquantes ... la suite

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#397]
Pour continuer avec les icônes manquantes pour les POIs

**Boissons**
shop=beverages
https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/shop/beverages.svg
![beverages svg](https://user-images.githubusercontent.com/7645549/79484139-86a64900-8013-11ea-92ec-231d2dafa5fb.png)

**Matériel de bricolage, équipement**
shop=doityourself - shop=hardware
https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/shop/diy.svg
![diy svg](https://user-images.githubusercontent.com/7645549/79484207-9a51af80-8013-11ea-8f4f-c4aede4a1c85.png)

**Électronique : vente / réparation**
shop=electronics
craft=electronics_repair
https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/shop/electronics.svg
![electronics svg](https://user-images.githubusercontent.com/7645549/79484249-a6d60800-8013-11ea-801b-857b7f63f7de.png)

**Matériel médical**
shop=medical_supply
https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/shop/medical_supply.svg
![medical_supply svg](https://user-images.githubusercontent.com/7645549/79484266-ac335280-8013-11ea-8319-50977e5ef1c5.png)

**Magasin de peinture**
shop=paint
https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/shop/paint.svg
![paint svg](https://user-images.githubusercontent.com/7645549/79484283-b1909d00-8013-11ea-9c63-11b20225a160.png)

**Papeterie - Équipement de bureau**
shop=stationery
https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/shop/stationery.svg
![stationery svg](https://user-images.githubusercontent.com/7645549/79484308-b9e8d800-8013-11ea-8d2b-898cfc7db1ed.png)

**Animalerie**
shop=pet
https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/shop/pet.svg
![pet svg](https://user-images.githubusercontent.com/7645549/79484316-bead8c00-8013-11ea-9dda-be51ab134283.png)

**Audioprothésiste - Audiologiste**
shop=hearing_aids

Il n' y a rien dans OpenStreetMap Carto. 
Voici quelques exemples ci-dessous.  À mon avis la première icône est la meilleure.

https://thenounproject.com/term/hearing-test/1050597/
CC BY Delwar Hossain
![hearing_aids1](https://user-images.githubusercontent.com/7645549/79484338-c836f400-8013-11ea-8c09-3b6d029121e5.png)

https://thenounproject.com/term/listening/793750/
CC BY ProSymbols
![hearing_aids2 svg](https://user-images.githubusercontent.com/7645549/79484393-dab12d80-8013-11ea-95c9-e6e5d80fd0d3.png)

https://thenounproject.com/term/hearing-aid/466188/
CC BY MRFA
![hearing_aids3 svg](https://user-images.githubusercontent.com/7645549/79484416-e270d200-8013-11ea-8273-47beda79daae.png)

============================================================

**Téléchargement :**  Icônes au format svg simple en 18 pixels 

Ici => https://covid19.framadrop.org/r/dQwVkC_7U5#F/74ZNcsAAUXQAWE8j6ahWz9GQ6te5wKDjzxdxE+pqE=

============================================================
Un  **bug ?** 

Lorsqu'une pharmacie ou un garage est sélectioné.e il n' y a pas d'icône dans le volet latéral droit (propriétés du POI) en haut dans la zone noire à côté du nom. Pourtant les icônes existent sur les POIs de la carte.

**Comment by Cybereric** [comment]
Bon les icônes suggérées pour **confectionery** et **chocolate** ça n'est pas terrible.
Il y a trop de blanc dans les icônes.

![choco](https://user-images.githubusercontent.com/7645549/79564715-7774d900-80af-11ea-852b-6a1019e43cc4.png)


Je pense que celles-ci sont mieux :

**confectionery**
https://thenounproject.com/term/candy/16713/
CC BY Bohdan Burmich
shop=confectionery
![18 px Bohdan Burmich CC BY](https://user-images.githubusercontent.com/7645549/79564269-9e7edb00-80ae-11ea-89ce-48440c65615d.png)

**chocolate**
https://thenounproject.com/term/chocolate/64149/
CC BY Amos Kofi Commey
shop=chocolate
![Amos Kofi Commey CC BY](https://user-images.githubusercontent.com/7645549/79564280-a3dc2580-80ae-11ea-834b-63ac97d725ba.png)


**pastry**  un oubli ? c'est toujours "boulangerie" qui s'affiche
shop=pastry
![pastry](https://user-images.githubusercontent.com/7645549/79564245-8e66fb80-80ae-11ea-90a1-f1f7d38e5408.png)

===============================================

Téléchargement des 3 fichiers (svg simple 18 px)
https://covid19.framadrop.org/r/XWgHV5ZLDb#Aocs0ZHwj6kAR9OwXOPHDCEfXP9uyTE/juOn9blfHjE=

===============================================

Pour le thé ou le café ok pour juste le nom du produit mais lorsqu'il y a un mot pour ça : 
chocolate => Chocolaterie non ?  ;-)

===============================================

Et pour les pharmacies l'icône n'apparaît toujours pas. 

![pharma](https://user-images.githubusercontent.com/7645549/79565006-0d106880-80b0-11ea-871d-8996325b41ea.png)

À présent c'est OK pour les garages.

**Comment by Cybereric** [comment]
Ça le fait aussi avec les assurances

![assurance](https://user-images.githubusercontent.com/7645549/79566899-983f2d80-80b3-11ea-9aff-082319bbcec7.png)


Et pour le matériel médical l'icône n'apparaît ni sur la carte ni dans le volet
![matmedic](https://user-images.githubusercontent.com/7645549/79567126-f1a75c80-80b3-11ea-9bb0-e2f4fd035a90.png)

![materiel medical](https://user-images.githubusercontent.com/7645549/79566918-9d03e180-80b3-11ea-9606-9ad0f856a398.png)

**Comment by francois2metz** [comment]
Je crois qu'on est bon pour les icones proposées. Merci ! Celles qui n'ont pas été intégré c'est parce qu'elles ne sont pas en CC0.

Si l'icone n'apparait pas dans le panneau de droite, c'est qu'il n'y pas d’icône associé à la sous catégorie. 
L'affichage de la carte permet d'essayer différentes possibilité, mais pas possible simplement dans la barre d'affichage des POIs.
