### ISSUE TITLE
amenity=fuel set as closed by brand rules

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#398]
**Describe the bug**
[w115897989](https://www.openstreetmap.org/way/115897989)
* `amenity=fuel`
* `name=Renault`

In [rules.csv](https://github.com/PanierAvide/Covid_enseignes/blob/master/rules.csv)
country|category|brand_name|wikidata_id|opening_rule|opening_hours|osm_additional_tags|description|source_url|opening_hours_url
--|--|--|--|--|--|--|--|--|--
FR|car_repair|Renault|Q6686|closed||||https://www.renault.fr/mesures-covid19.html|
FR|car_repair|Garage Renault|Q6686|closed||||https://www.renault.fr/mesures-covid19.html|

**To Reproduce**
Exemple: https://www.caresteouvert.fr/@46.858922,0.939394,18.33/place/w115897989

**Expected behavior**
This amenity shouldn't be closed automatically. We don't know it's status.
(Probably opened 24/7)

I seem that the **category** is not checked, only the **name**.
See [db/update_poi.sql#L183](https://github.com/osmontrouge/caresteouvert/blob/53f34cc11513ecf422b87939fb67531968a38623/db/update_poi.sql#L183) and [db/update_poi.sql#L198](https://github.com/osmontrouge/caresteouvert/blob/53f34cc11513ecf422b87939fb67531968a38623/db/update_poi.sql#L198)

**Comment by PanierAvide** [comment]
Only checking name of brand is intended behaviour, as brands usually have various kind of store/services associated (Carrefour = convenience, supermarket, bank, travel_agency, ...). For this example, Renault garages having a fuel station associated are usually using another brand like Total or Elan. Also, I can't find this station in prix-carburants.gouv.fr, which means it may not be open anymore.

**Comment by pyrog** [comment]
> Only checking name of brand is intended behaviour

So, remove category field 👅 (Je te taquine Adrien)

I just call the garage : the gas station is opened 24/7 (as stated in their website) and not affiliated especially with Renault.

But this **Renault** garage is **opened** but displayed as close 😞
So [rules.csv](https://github.com/PanierAvide/Covid_enseignes/blob/master/rules.csv) is not uptodate for this brand 😉

**Comment by PanierAvide** [comment]
I'm not using category field, but other users of CSV file are :wink: I just updated brand rule to make it adapted to recent changes, thanks for your feedback.

**Comment by pyrog** [comment]
Un grand merci 😎
