### ISSUE TITLE
Afficher "toute la journée" ?

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#40]
Quand un horaire n'est pas spécifié, affiche  **00:00-00:00**  au lieu de **00:00-24:00** ou **"Toute la journée"**
Exemple:
- https://www.openstreetmap.org/node/7339724950
- https://www.caresteouvert.fr/@46.576882,5.750625,18.75/place/n7339724950
- Voir sur [openingh.openstreetmap.de/evaluation_tool](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Tu-Sa%2008%3A30-12%3A00%2C15%3A00-18%3A00%3B%20Su%2009%3A00-12%3A00%3BMo%20%20%22Vous%20pouvez%20vous%20adresser%20au%20magasin%20de%20Pont-de-Poitte%22&lat=46.67573877990781&lon=5.5672473265760924&mode=0&DATE=1584957120000)

**Comment by PanierAvide** [comment]
On utilise directement la bibliothèque `opening_hours` pour cet affichage, le bug serait plutôt à reporter de leur côté : https://github.com/opening-hours/opening_hours.js/issues

Tu peux voir si tu arrives à reproduire le bug avec leur outil ? S'ils font un correctif on mettra à jour de notre côté ;-)

**Comment by francois2metz** [comment]
Je n'ai pas de doute que la bibliothèque `opening_hours` gère cela. Mais pour afficher tout cela, il y a toute une mécanique, et clairement, je n'ai jamais regardé les commentaires. J'ai géré les cas simples.
Il faut voir a quel point c'est compliqué

**Comment by francois2metz** [comment]
@pyrog Est ce que tu parle de ce point ? https://www.openstreetmap.org/node/7339724950

**Comment by pyrog** [comment]
Oui, c'est bien lui : je corrige mes liens 😄

Tient, il ne s'affiche plus (maintenant `shop=cheese`, avant `shop=deli`)

**Comment by francois2metz** [comment]
Je dois dire que je ne suis pas très au fait des commentaires. 
Je vois un bug dans l'affichage chez nous car avec `Mo off` ça devrait être indiqué fermé de ce que je comprend.
En suite, on peut mettre le commentaire dans la liste, tout en haut. Qu'en pense tu ?

**Comment by francois2metz** [comment]
Voila le résultat :
![Screenshot_2020-04-01 Ça reste ouvert](https://user-images.githubusercontent.com/86659/78121479-b9452480-740b-11ea-98d0-efe4b474b83f.png)

C'est très complexe cette histoire de commentaires. Clairement on ne gêre pas tout.

**Comment by pyrog** [comment]
Merci François, le résultat est très lisible 😄
Et pour les libellés trop longs il y a une popup.

> Clairement on ne gêre pas tout.

Oui, je n'ai pas encore eu le temps de m'y remettre. J'ai mis le code une seule fois à la fin de la journée, mais il faut le mettre pour chaque période de temps…

Je vais me faire une version où je peux saisir la valeur de `opening_hour` pour tester "tous" les cas…
