### ISSUE TITLE
Add a 404 error page

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#406]
**Is your feature request related to a problem? Please describe.**
This [newly created node](https://www.caresteouvert.fr/@46.858922,0.939394,18.33/place/n/7414289956) display a unfriendly (and ugly) error message.

<img width="331" alt="This page could not be found" src="https://user-images.githubusercontent.com/2158081/79564381-d4bc5a80-80ae-11ea-95c5-2a73751a6986.png">

**Describe the solution you'd like**
Could display a "funny" error 404 page displaying i.e. a map of the [Bermuda Triangle](https://en.wikipedia.org/wiki/Bermuda_Triangle) 🤣 , the 🌔  ?
with the message : **Lost ?**

**Describe alternatives you've considered**
Or at least the map with a brief warning message ?

**Additional context**

**Comment by PanierAvide** [comment]
As a mapper, I 100% approve the Bermuda triangle + lost message :grin: But I'm not sure this will not confuse general public. A simple redirect would do the trick too.

**Comment by francois2metz** [comment]
This URL is not a correct one: `https://www.caresteouvert.fr/@46.858922,0.939394,18.33/place/n/7414289956` should  `https://www.caresteouvert.fr/@46.858922,0.939394,18.33/place/n7414289956`

**Comment by pyrog** [comment]
> This URL is not a correct one

Thanks to open my eyes.

Thanks too for the map is displayed normally without the ugly warning 😃
