### ISSUE TITLE
Street Usability Evaluation

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#407]
I just took a (masked) walk to record data for almost all grey places around me. Here's my feedback:

1. Zoom level 19 seems to be most useful for mapping in the street (and I wish there was a shortcut).
2. In zoom level 17, some places don't show their icon in the circle yet. Is that intentional? Often there would be enough space.
3. In zoom level 18, it's hard to select places near other places, so you often end up opening the wrong place. It would be nice to zoom implicitly when the user touches on a place that is less than X pixels away from another place, rather than opening the one the user touched by chance.
4. The zoom buttons as well as the circles are rather small and hard to aim on high-resolution smartphones. I struggled a lot, *even though* I'm used to aiming carefully.
5. The map doesn't support the "double-tap and move up/down to zoom" gesture, which would be very useful.
6. For the "Is this place open during lockdown?" question, the answers "Open" and "Closed" would be more straightforward than "Yes" and "No" (and you could add "Partially open" as an alias for "Open" to prevent people chosing "No" for places offering deliery/takeaway).
7.  I reported a police station that is opened 24/7, which is not obvious to report. I have set opening and closing time to 00:00, whereas previously I would have tried to set it to 23:59 (but you only get one shot, see #338). However, 00:00 to 00:00 is bit confusing and it would help to show "24" instead of "00" in the closing time picker.
8. For places that don't require a comment, the comment field is a bit in the way. I saw that it has just been reduced in height, but maybe it could only appear after ticking a checkbox? (And then you could also show a field for phone number, website and email address.)
9. I stumbled upon several places that were either permanently closed (as in no sign of a shop or restaurant anymore) or renamed. It would be great to handle these cases (although the "closed" case should not be too prominent, otherwise it might be abused).
10. I came across several missing places and it would have been great to add a note directly from within CRO.
11. Right before submitting a report, I don't see what I chose in step 1 (ideally: "✅ Open" or "❌ Closed") or whether I provided anything in step 2 (e.g. "➖✅ ✅ ✅ ✅ ✅ ➖➖" for Tu-Sa) . It would be great to show that below the collapsed steps to allow the user to verify their input.
12. When giving feedback for a 🟢 green place (e.g. a bank office belonging to a bank whose offices are supposed to be open), the success message is hard to notice, because it has the same background color as the area above (with the place name and category) and there is no margin between.
13. After having sent a report, it would be useful to have a "close" button below, as the "✖️" at the top is far away from the previously pressed "Publish" button below.
14. It would be nice to count the number of reports by the current user to gamify the data gathering a bit. Every so and so many reports, a dialog with a tip or an encouraging message could appear.

**Comment by PanierAvide** [comment]
Just some thoughts on some points.
2. It's a Mapbox-styling related issue, I'm not sure we can change this behaviour (to be checked)
8. Details input field could be by default hidden and appear if click on some extendable panel like https://vuetifyjs.com/fr-FR/components/expansion-panels/
9. Isn't the closed during lockdown + permanently closed text in details input field enough to cover this one ?
10. Same, had this scenario during my last shopping trip, a wine shop was missing in OSM
14. Can be done, but as contribution is anonymous, this data would be kept only in local storage of browser (so not shared between PC / mobile). Maybe that's not an issue.

**Comment by PanierAvide** [comment]
It seems that most of points reported may have been fixed by recent changes. If necessary, can you open smaller issues for individual points which not be satisfying yet ? Thanks for this feedback.
