### ISSUE TITLE
Change style on selected POI for visibility

### ISSUE THREAD

**Issue by sygour** [osmontrouge/caresteouvert#408]
When selecting a POI, the right panel opens to show information about it but it might be interesting to change the display style on the map:

- When there are a lot of POIs, it's hard to see with one is selected
- If you come from another page (page shared on a site / by a friend / from a search engine), it's impossible to see which one was selected

for example on Qwant maps, you can see which POI I selected :
- https://www.qwant.com/maps/place/osm:node:6970262278@Tellor#map=17.17/45.7587547/4.8318278

**Comment by overflorian** [comment]
I agree and I think that, as a quick-win we can do like on Qwant Maps: display an extra indicator. But a proper highlight would be nicer ;)
