### ISSUE TITLE
Geojson management at the country level

### ISSUE THREAD

**Issue by vdct** [osmontrouge/caresteouvert#409]
A single countries_subcountries.geojson file is way too big for QGis.
Spliting the file by country is required to gain editing capabilities.
Nevertheless the whole file is required for imposm

**Comment by PanierAvide** [comment]
Maybe splitting by country + merging dynamically before calling imposm with ogr2ogr would do the trick ? Also avoid to store several large files in Git repository.

**Comment by vdct** [comment]
Yes, that's the purpose of the geojson directory (one geojson per country) and the build_countries_geojson.sh shell. You're right : the large worldwide file is not required since the process is available and the README up to date ;)

**Comment by vdct** [comment]
Closed by #524
