### ISSUE TITLE
Missing category: copyshop

### ISSUE THREAD

**Issue by Codain** [osmontrouge/caresteouvert#410]
**Name**: [copyshop](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcopyshop) (I suggest to place it under 'Amenities' in categories.json)

**Tagging**: shop=copyshop

**Country**: France

**Example in OpenStreetMap**: (https://www.openstreetmap.org/node/6308549503)

**Example in "Ca reste ouvert"**: (https://www.caresteouvert.fr/@48.970991,2.258714,18.33)

**Icon**: (https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/copyshop.svg)

**Comment by Cybereric** [comment]
I think this kind of shop is not in the list
=> https://www.legifrance.gouv.fr/affichTexte.do;jsessionid=0988773243DDED4434CBFE85C9B0A44A.tplgfr36s_2?cidTexte=JORFTEXT000041723302&dateTexte=&oldAction=rechJO&categorieLien=id&idJO=JORFCONT000041723291
They are mostly closed
An example with https://www.corep.fr/   All the shops are closed

**Comment by PanierAvide** [comment]
I would say it depends if it falls in `papeterie` category or not. @Codain do you have examples of open places ? In OSM as now, we only have 2 of them being open in France.

**Comment by PanierAvide** [comment]
Closing as we lack feedback.
