### ISSUE TITLE
Missing category: florist

### ISSUE THREAD

**Issue by bagage** [osmontrouge/caresteouvert#411]
**Name**: Florist

**Tagging**: `shop=florist`

**Country**: France

**Example in OpenStreetMap**: (link starting with https://www.openstreetmap.org/node/...)
https://www.openstreetmap.org/node/2675935244

**Example in "Ca reste ouvert"**: (link starting with https://www.caresteouvert.fr/...)
https://www.caresteouvert.fr/@45.036457,5.081756,19.25/place/n7359106854

**Icon**: (link starting with https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/...)
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/florist.svg

**Comment by Cybereric** [comment]
Florists are not open during confinement.
Only the garden centers are open for a few days

**Comment by Bibi56** [comment]
@Cybereric Inexact, les magasins en tant que tels sont fermés certes mais le réseau Interflora (ou un autre) a réouvert, simplement comme les magasins sont fermés il est possible de commander et de se faire livrer (n'importe où en France). `delivery:covid19=only` + `opening_hours:covid19=open` + `access:covid19=no`

**Comment by bagage** [comment]
Yes there are since they sell seeds too.

**Comment by Cybereric** [comment]
Il y a aussi une autre marque je ne sais plus laquelle (et pas tous les magasins il me semble) car ils vendent aussi des plants
Quel est le nombre de magasins ouverts en rapport des milliers de fleuristes "normaux" 
Mais bon je n'ai rien contre ;-)

**Comment by PanierAvide** [comment]
Si c'est un cas vraiment ambigu, vous pouvez commencer à ajouter des infos sur les fleuristes dans https://github.com/PanierAvide/Covid_enseignes avant qu'on les affiche. Comme ça on aura dès le départ des états d'ouvertures un peu plus fiables.

**Comment by Bibi56** [comment]
Le problème c'est qu'on n'entre pas l'info boutique Interflora ou pas dans OSM. Donc difficile d'utiliser Covid_enseignes ensuite. Après le principe, c'est qu'ils trouvent la boutique la plus proche... qui nous reste fermée : c'est de la vente par correspondance, certes en faisant travailler un fleuriste localement mais d'un point de vue achat, c'est de la VPC. Donc est-ce pertinent de le mettre dans caresteouvert ?
Le nombre de boutiques effectivement actives importe peut pour le client.
https://www.interflora.fr

**Comment by Bibi56** [comment]
Je viens de regarder un fleuriste, pas sur Interflora, commande par téléphone, mise à disposition sur parking (ou livraison).

**Comment by bagage** [comment]
Peut-être que le problème est plus global dans ce cas, et qu'il faudrait simplement afficher sur la carte tous les POI qui ont un tag `covid!=no` : plusieurs enseignes font soit de la livraison soit de la vente à emporter.

**Comment by PanierAvide** [comment]
Added florist in a common category with garden centres. Will be visible in ~1h.
