### ISSUE TITLE
Missing category: bar/pub

### ISSUE THREAD

**Issue by bagage** [osmontrouge/caresteouvert#412]
**Name**: bar and pub

**Tagging**: `amenity=bar` and `amenity=pub`

**Country**: France

**Example in OpenStreetMap**: (link starting with https://www.openstreetmap.org/node/...)
https://www.openstreetmap.org/node/7209064848
https://www.openstreetmap.org/node/530911106

**Example in "Ca reste ouvert"**: (link starting with https://www.caresteouvert.fr/...)
https://www.caresteouvert.fr/@45.043009,5.049429,19.62/place/n7359106854
https://www.caresteouvert.fr/@45.076850,4.958290,19.00/place/n7359106854

**Icon**: (link starting with https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/...)
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/amenity/bar.svg
https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/amenity/pub.svg

Since some bar/pub may suggest takeaway and/or delivery, I think it'd make sense to show them.

Or, even better, render all places with `covid19` tags (for instance `delivery:covid19=yes` tag here).

**Comment by Cybereric** [comment]
I did not see that there were a lot of pubs/bars that offered takeaway actually.
In normal times there are not many to offer real full meals.
So now...

**Comment by caugner** [comment]
This would be similar to `amenity=cafe` who are only shown in these cases:

https://github.com/osmontrouge/caresteouvert/blob/137560e3769c7fd0ffe8bf39d81df53fdf0be1be/categories.json#L242-L256

**Comment by PanierAvide** [comment]
+1, we may only show the ones with `covid19` tags to avoid having too many noise.

**Comment by PanierAvide** [comment]
This has been implemented and will be visible in ~1h.
