### ISSUE TITLE
Missing category: childcare, kindergarten

### ISSUE THREAD

**Issue by ViolaineDo** [osmontrouge/caresteouvert#414]
**Name**: in amenity add child care and kindergarten 

**Tagging**: amenity=childcare;kindergarten

**Country**: (country of category)France

**Example in OpenStreetMap**: (link starting with https://www.openstreetmap.org/node/...)
https://www.openstreetmap.org/node/7344532717

**Example in "Ca reste ouvert"**: (link starting with https://www.caresteouvert.fr/...)
https://www.caresteouvert.fr/other@-17.534220,-149.555871,15.00/place/n7344532717

**Icon**: (link starting with https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/...)
THERE IS NO ICON YET!! Need to be fixed... :( 

**Why adding this category":**
Many women are in the front line, see those statistics in french ; https://www.franceinter.fr/societe/coronavirus-cinq-chiffres-concrets-qui-montrent-que-les-femmes-sont-en-premiere-ligne
Those women might be on their own, and need a solution for their children...

**Comment by PanierAvide** [comment]
This has been implemented, and will be visible on website in ~1h. Thanks for this feedback :+1:

**Comment by ViolaineDo** [comment]
Thank you!
