### ISSUE TITLE
Mobile : le menu latéral se rétracte dès qu'on change les couches affichées

### ISSUE THREAD

**Issue by zorun** [osmontrouge/caresteouvert#42]
Pour reproduire, sur mobile (Android) :

- ouvrir le menu sur la gauche
- décocher un des types de POI, par exemple « Stations services »
- **le menu est immédiatement caché et on revient à la carte**
- idem si on coche un type de POI précédemment décoché

C'est vraiment pas pratique quand on veut décocher plusieurs types de POI...

Sur PC (firefox 74 sous Linux), le problème n'apparaît pas, le menu reste affiché.

**Comment by overflorian** [comment]
Je suis d'accord et pense également qu'il faudrait corriger cela

**Comment by francois2metz** [comment]
Fixé dans b3e6a904c79f5ce8b125639ac39f4277433c9226. C'était pas de la tarte pour faire ce truc :sweat:

**Comment by PanierAvide** [comment]
Tu m'étonnes, j'ai essayé deux fois de résoudre ce ticket sans succès :disappointed:
