### ISSUE TITLE
Icônes manquantes suite ... et fin ?

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#420]
En parcourant l'interface et le volet latéral je vois qu'il manque encore des icônes pour :
- Les épiceries
- Les assurances
- Le matériel et les fournitures agricoles
- Les distributeurs de préservatifs

**===== Épiceries =====================**

Les épiceries (**shop=deli**) utilisent la même icônes que les primeurs.
La pomme
![greengrocer](https://user-images.githubusercontent.com/7645549/79635020-8c647180-816e-11ea-8571-63afdae10383.png)

Ne serait-il pas plus judicieux d'utiliser l'icône présente dans OpenStreetMap Carto ?
La conserve.
![deli](https://user-images.githubusercontent.com/7645549/79635031-9edeab00-816e-11ea-8773-0daa3ceec860.png)

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/deli.svg

**===== Assurances ====================**

Pour les assurances (**office=insurance**) la métaphore du parapluie revient assez souvent. 
Je trouve qu'elle est intéressante.
Quelques exemples

![Yugudesign - Insurance3](https://user-images.githubusercontent.com/7645549/79635114-43f98380-816f-11ea-94a9-9525bdc01d7d.png)
CC BY Yugudesign
https://thenounproject.com/term/insurance/246855/

![Sandhi Priyasmoro - Insurance4](https://user-images.githubusercontent.com/7645549/79635137-6e4b4100-816f-11ea-9a24-d2119e8af73d.png)
CC BY Sandhi Priyasmoro
https://thenounproject.com/term/insurance/2076069/

![Adrien Coquet - Insurance1](https://user-images.githubusercontent.com/7645549/79635163-9e92df80-816f-11ea-842c-fc9b9a4c0d62.png)
CC BY Adrien Coquet
https://thenounproject.com/term/insurance/1339104/

![popcornarts - Insurance2](https://user-images.githubusercontent.com/7645549/79635174-b10d1900-816f-11ea-8c1f-289af93a6c59.png)
CC BY Popcornarts 
https://thenounproject.com/term/insurance/2469685/

Autres icônes
https://thenounproject.com/search/?q=insurance

 **===== Matériel et produits agricoles  ====================**
C'est assez explicite je pense. 

![Orin zuu - agrarian](https://user-images.githubusercontent.com/7645549/79635218-fdf0ef80-816f-11ea-98b5-59f6576795ba.png)
CC BY Orin zuu 
https://thenounproject.com/term/tractor/1109292/

 **===== Distributeurs de préservatifs  ====================**

![Hea Poh Lin - condoms svg](https://user-images.githubusercontent.com/7645549/79635244-2d076100-8170-11ea-95a1-6186d2839a97.png)
CC BY Hea Poh Lin
https://thenounproject.com/term/condom/582305/

![Baboon designs - condoms](https://user-images.githubusercontent.com/7645549/79635478-77d5a880-8171-11ea-9b09-3a62d786e987.png)
CC BY Baboon designs
https://thenounproject.com/term/condom/2342597/

Encore du choix sur le site The Noun Project.
https://thenounproject.com/search/?q=condom

**======== Téléchargement =========================**

Format svg simple 18 px

https://covid19.framadrop.org/r/RWkc5PXGmh#oJrbWm51/Zmc8i4jUJSYTlUusDQVFEjzg5pHVxtrWYA=

**Comment by francois2metz** [comment]
Hello. Merci pour ces propositions.

J'ai intégré l'icone grocery. Pour les autres ca risque d'être une galère d'intégrer les crédits, je préfére intégrer des icons en CC0 ou dans le domaine public pour s'éviter des ennuis.
