### ISSUE TITLE
Code de partage iframe

### ISSUE THREAD

**Issue by deuzeffe** [osmontrouge/caresteouvert#422]
Hello,

C'est juste une question, hein, pas forcément du boulot supplémentaire... Savoir si c'est possible/impossible en l'état, envisageable/inenvisageable, envisagé/énergiquement refusé ;)

**1. Is your feature request related to a problem? Please describe.**
Imaginons un monde merveilleux où les "Cartes interactives gg temporaires" seraient remplacées par des cartes CRO auxquelles tout le monde pourrait donc contribuer (plutôt que le proprio du site, surtout quand le site est celui d'une coll. terr.)

**2. Describe the solution you'd like**
Un bout de code (iframe ?) pour intégrer la carte.

**3. Describe alternatives you've considered**
TINA

**4. Additional context**
Cf 1. ;)

Merci pour la réponse, quelle qu'elle soit.

**Comment by PanierAvide** [comment]
C'est tout à fait possible, et en fait certains sites l'ont déjà fait, exemple : https://dinge.fr/fermetures-ouverture-des-services-durant-le-confinement/

Le code à minima c'est ça :
```html
<iframe style="width: 100%;" src="https://www.caresteouvert.fr/@48.357221,-1.715824,16.51" height="400" frameborder="0" scrolling="no"></iframe>
```

Avec l'URL qui peut être changée pour centrer sur la zone de ton choix. On devrait proposer une petite fonctionnalité dans le site pour générer le code directement, ça serait plus pratique.

**Comment by francois2metz** [comment]
Le code d'exemple, ca pourrait être rajouté dans l'article, après la mention de l'iframe: https://blog.caresteouvert.fr/un-outil-de-communication-des-mairies
Dans les faits les services techniques y arrivent très bien (ainsi que les sites de presses) sans rien nous demander (ce qui n'est pas très sympathique).

**Comment by PanierAvide** [comment]
Oui après le mettre dans l'article est peut-être suffisant.

**Comment by vinber** [comment]
déjà je mets le code, et si vous savez pas quoi faire, vous intégrez le truc qui génère le code centré, à la taille voulue, ...

**Comment by PanierAvide** [comment]
Merci d'avoir ajouté le code exemple, je ferme le ticket pour l'instant, à rouvrir si on veut intégrer le générateur de code dans le site.
