### ISSUE TITLE
Suggestions d'amélioration des boutons de filtrage du volet latéral

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#423]
Pour chacune des 3 rubriques citées du volet latéral j'ai fait un **"Avant/Après" visuel** 
donc ce qui existe actuellement et ce qui serait à améliorer.

Pour que cela soit plus réaliste j'ai ajouté des icônes proposées dans #397 et #420

**1/ Dans "Services pratiques"** 
Je vois un bouton "Banques & assurances" et un bouton "Assurance" 
Au vu des tags (amenity=bank + office=financial) ne devrait-on pas plutôt avoir "**Banque et finance**" 
puisqu'on a déjà un bouton "Assurance"

![volet lateral services](https://user-images.githubusercontent.com/7645549/79641520-4d4b1600-8198-11ea-8672-d6c4a724039b.png)

======================================================================

**2/ Dans "Alimentation"** 
Je pense qu'il est vous est possible de réorganiser les boutons comme vous le voulez.

J'ai donc réorganisé les boutons de manière plus thématique et renommé certaines étiquettes.

**- Pour shop=dairy**  
Utiliser plutôt "**Crèmerie**" que "Laiterie"  car ce dernier mot est (en français) plus utilisé pour le lieu de collecte et de transformation du lait que pour le lieu de vente des produits laitiers.
Mais bon ....

**- Pour shop=confectionery**
Écrire "**Confiserie**" au lieu de "Magasins de bonbons" serait plus correct. 
Les bonbons sont des confiseries parmi d'autres, toutes les confiseries ne sont pas des bonbons !
En plus le mot est moins long d'où un gain de place de 9 caractères !
Il y aurait aussi une meilleure icône à utiliser que l'actuelle. Voir #397
![bonbon](https://user-images.githubusercontent.com/7645549/79641043-5f778500-8195-11ea-89c3-cbbb65325a54.png)

**- Pour shop=chocolate**
Par souci de cohérence et d'uniformisation, sur le modèle de boucherie, poissonnerie, boulangerie, etc, utiliser "**Chocolaterie**" plutôt que le produit "chocolat"  
Voir #397 pour l'icône

**- Pour shop=pastry**
Il faudrait vraiment séparer "shop=bakery" de "shop=pastry"
S'il est vrai que les boulangeries font quelques pâtisseries les **pâtisseries** "exclusives" ne fabriquent elles pas de pain.
Il y a donc selon moi un intérêt à les séparer.
![pastry](https://user-images.githubusercontent.com/7645549/79641066-7cac5380-8195-11ea-8266-c3f1daced054.png)

Dans cette rubrique réécrire ces intitulés de boutons et réorganiser ceux-ci fait gagner une "ligne"dans le volet latéral

![volet lateral alimentation](https://user-images.githubusercontent.com/7645549/79641522-52a86080-8198-11ea-8e52-422d4b6cfa4a.png)

======================================================================

**3/ Dans "Mobilité"**

- "**Distributeur de chambre à air**"  suffit.  Avec l'icône c'est assez explicite je trouve.

- Pour faire plus court avec les tickets de transport  pourquoi ne pas utiliser l'expression "**titres de transport**"
C'est moins long et le texte n'est plus coupé.

![volet lateral mobilité](https://user-images.githubusercontent.com/7645549/79641529-5a680500-8198-11ea-83e1-dc38c2086d6d.png)

**Comment by PanierAvide** [comment]
À noter que pour les libellés en français, ceux-ci peuvent être changés sur transifex directement : https://www.transifex.com/openlevelup/ca-reste-ouvert/dashboard/

**Comment by Cybereric** [comment]
Ok j'en apprends tous les jours ;-)  
et les boutons se réorganisent en fonction de la longueur des libéllés ou pas ?

**Comment by Cybereric** [comment]
C'est fait 
Par contre "shop=pastry" n'existant pas (je ne l'ai en tout cas pas trouvé) je suppose qu'il faut que tu l'ajoutes dans le fichier source en anglais.  
Je te laisse faire ;-)

**Comment by francois2metz** [comment]
J'ai fait les changements de wording dans 5535670c7553bdc845dea0b357efecf6a2690534. 

Pour la séparation boulangerie / patisserie, aucune idée précisément. Ca n'a pas l'air d'être un tag très utilisé, en tout cas en france.

**Comment by overflorian** [comment]
Est-ce que quelqu'un a regardé les stats pour les catégories "Crémerie" & "distributeur de chambre à air" ? Je n'ai pas testé toute la France mais je ne trouve aucun point dans tout Paris, je ne suis donc pas certain que ces catégories soient vraiment pertinentes.

**Comment by PanierAvide** [comment]
70 `shop=dairy`, 5 `vending=bicycle_tube` en France. Je peux les désactiver en France si besoin.

**Comment by PanierAvide** [comment]
Ce que j'ai fait : ils sont toujours visibles sur la carte, mais le bouton de filter est masqué en France dans le volet de gauche.

**Comment by Cybereric** [comment]
[shop=dairy] Je ne les ai pas encore cartographiées c'est pour cela qu'il y en a si peu  **:-)**
Objectif Covid-20, Covid-21 etc.... **;-)** 
La suite.... suit

**Comment by PanierAvide** [comment]
On espère que le covid va rester == 19 sinon on est pas rendus :scream:

**Comment by Cybereric** [comment]
Ď'abord juste une précision.

Dans #420 François me dit :

>  Pour les autres ca risque d'être une galère d'intégrer les crédits, je préfére intégrer des icons en CC0 ou dans le domaine public pour s'éviter des ennuis."

**Mon avis :**
Utiliser des choses en CCO et/ou Domaine public ne dispense pas de citer les auteurs.
On peut même y être obligé.

En France avec le droit d'auteur il y a ce qu'on appelle le droit moral qui est inaliénable et imprescribtible. 
Une des 4 prérogatives qui le composent est le droit à la paternité.
Je cite : [Il] permet à l’auteur d’exiger et de revendiquer à tout moment la mention de
son nom et de ses qualités sur tout mode de publication de son œuvre. En outre, tout utilisateur de
l’œuvre a l'obligation d’indiquer le nom de l’auteur [...]

Source : note 2 sur https://fr.wikipedia.org/wiki/Licence_CC0

Donc même quand on utilise une licence la plus libre soit-elle, il est préférable de toujours citer ses sources.
Une simple page "Crédits" quelque part suffit...
Dans la pratique je ne pense pas qu'il y ait de soucis de ce côté là

Quoiqu'il en soit il faut supprimer les icônes actuelles de **shop=chocolate** et **shop=confectionery** qui sont sous CC BY

Cela tombe bien elle ne "rendent" pas bien et j'en ai d'autres en Domaine Public ! 

J'ai donc trouvé ce qui manquait en icônes et j'en ai créé moi-même deux !



**====================  **Icônes vraiment "libres"** =========================**


**Produits agricoles**   shop=agrarian
https://thenounproject.com/term/tractor/629
Public Domain
![agrarian60](https://user-images.githubusercontent.com/7645549/79747973-e00cc180-830c-11ea-8ab4-dc38836cc499.png)
*******************************************************
**Assurances**  office=insurance
https://thenounproject.com/term/umbrella/12312/
Public Domain
![insurance60](https://user-images.githubusercontent.com/7645549/79748099-24985d00-830d-11ea-814f-81ba238b3257.png)
Bon la métaphore du parapluie qui "couvre" est intéressante : je n'ai pas trouvé mieux
https://thenounproject.com/search/?q=insurance
*******************************************************
**Confiseries**  shop=confectionery
https://thenounproject.com/term/candy/12378/
Public Domain
![confectionery60](https://user-images.githubusercontent.com/7645549/79748171-45f94900-830d-11ea-941c-99adc80dee67.png)
Pour remplacer l'actuelle qui est en CC BY et ne rend pas bien

*******************************************************
**Pâtisseries**  shop=pastry

> Pour la séparation boulangerie / patisserie, aucune idée précisément. Ca n'a pas l'air d'être un tag très utilisé, en tout cas en france.

Alors les pâtisseries sont-elles assez nombreuses pour être distinguées ?
Suspense ....
Pour la France on a :

- **819 pâtisseries** avec TagInfo  (10 444 au niveau mondial)  => https://taginfo.openstreetmap.fr/tags/shop=pastry#overview  

- **846 pâtisseries** avec Overpass turbo  => http://overpass-turbo.eu/s/T3Z 
(Overpass ne compte pas tout à fait pareil il me semble)

C'est donc pas mal utilisé. Il y en a plus que les audioprothésistes !
Donc pour shop=pastry il y a une icône venant d'OpenStreetMap Carto
![pastry60](https://user-images.githubusercontent.com/7645549/79748303-7fca4f80-830d-11ea-9b55-14ff8653c7b8.png)
*******************************************************

**Chocolateries**  shop=chocolate
Je n'ai rien trouvé de bien intéressant sous licence Public Domain pour remplacer l'actuelle en CC BY 
J'en ai donc créé une.  Je la mets en WTFPL
Bon elle vaut ce qu'elle vaut hein.
![chocolate60](https://user-images.githubusercontent.com/7645549/79748357-95d81000-830d-11ea-8117-1f9524100974.png)
*******************************************************

**Distributeurs de préservatifs**
Là aussi pas de choses intéressantes sous licence Public Domain
Donc voici ma seconde icône créée.
Idem pour la licence :  WTFPL
![condom60](https://user-images.githubusercontent.com/7645549/79748432-b2744800-830d-11ea-9b41-0b53585d4b58.png)

============================================================

**Téléchargement**
Tout ceci au format svg simple 18 pixels
=> https://covid19.framadrop.org/r/M4aXSDn3R_#/+LMHsu0C05HZousRp2meiSxSUnL1oOwLj1WgAlupAk=

**Comment by Cybereric** [comment]
Il manquait une icône pour les centre de consultation covid-19
Un virus ? **;-)**
J'ai trouvé une icône (Licence domaine public)
![path925](https://user-images.githubusercontent.com/7645549/79779270-6986b880-833a-11ea-8051-494254f62e4e.png)


https://covid19.framadrop.org/r/GXjq_JKprR#It71gJgDqpg9pAaxLeXNtgpg658EDKYdBwxob3RqmMo=

**Comment by francois2metz** [comment]
Niquel les icones! Merci.
