### ISSUE TITLE
Pre-fill the minutes at 00 having added the hours in the editor.

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#424]
**Is your feature request related to a problem? Please describe.**
when you add opening_horus, it's usually XX:OO. When specifying the time, it would be simpler - quicker to fill in the 00 of minutes

**Describe the solution you'd like**

when you fill the hour the minutes are at 00

**Describe alternatives you've considered** 

the minutes are already with 00

**Additional context**

If we validate without define minute it make an bug, see picture 
![Capture d’écran de 2020-04-18 19-21-08](https://user-images.githubusercontent.com/890869/79644523-c868f800-81a9-11ea-94e8-ea7e644025ae.png)

**Comment by francois2metz** [comment]
I believe it was fixed in 5f56621ad1a588d237dd9e141faca2cc737d22ad.
