### ISSUE TITLE
Drop-down answers in step 3 remain in English instead of Filipino

### ISSUE THREAD

**Issue by govvin** [osmontrouge/caresteouvert#429]
**Describe the bug**
The local translation for the drop-down answers: Yes, No, I don't know is not used.

**To Reproduce**
1. Switch the language to Filipino, and look for any POI
2. Click on a POI and select "Report a change"
3. Scroll down to Step 3. (this is only possible if you answered yes in Step 1)
4. The first drop-down will show the translated option in Filipino. The other drop-downs are in English.

**Expected behavior**
The drop-down should use the Filipino translation

**Screenshots**

![image](https://user-images.githubusercontent.com/5821688/79685178-39231980-8269-11ea-80d8-0d3cc9fd8f15.png)

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Browser: Firefox
 - Version: 75

**Smartphone (please complete the following information):**

**Additional context**

**Comment by PanierAvide** [comment]
Thanks for your feedback, Transifex was stuck (again...), so this will be updated in a few minutes.
