### ISSUE TITLE
Interface web particulièrement lente / consommatrice en CPU

### ISSUE THREAD

**Issue by zorun** [osmontrouge/caresteouvert#43]
Je ne sais pas si c'est lié au nombre de POI affichés ou à du JS pas optimisé, mais l'interface est particulièrement lente, surtout sur un mobile pas très puissant...

Exemple d'action qui est difficile à réaliser à cause de cette lenteur :

- déplacement (« pan ») sur la map, surtout sur mobile : il y a un délai de quasi 1 seconde entre l'action et le déplacement effectif, c'est tout sauf fluide
- changement de couche à partir du menu : idem, il faut parfois plusieurs secondes pour que ça se mette à jour sur la carte (problème exacerbé sur mobile par #42 )

Si c'est lié au nombre de POI, peut-être voir à les agréger (« clustering ») tant qu'on reste à un zoom faible ? Un peu comme leaflet fait : https://github.com/Leaflet/Leaflet.markercluster

**Comment by francois2metz** [comment]
Je pense que c'est mapbox-gl qui fait ramer. Je ne pense pas que ce soit le nombre de POI. Il faudrait utiliser leur rendu android pour améliorer cela, mais c'est un sacré développement.

**Comment by PanierAvide** [comment]
Ça va être réglé par la disponibilité future d'applis mobiles (cf #110), je ferme donc ce ticket.
