### ISSUE TITLE
garde d'enfants, cas des écoles maternelles

### ISSUE THREAD

**Issue by py-b** [osmontrouge/caresteouvert#435]
Les objets **amenity=kindergarten + school:FR=maternelle** ne devraient pas apparaître.
Ils sont fermés par décision nationale au moins jusqu'au 11 mai.

**Comment by PanierAvide** [comment]
Ajoutés suite au ticket #414, @ViolaineDo tu as des précisions pour kindergarten de ce qui doit être affiché ou pas ?

**Comment by py-b** [comment]
Petite clarification, au cas où :
Cette combinaison de tags représente une école maternelle.
https://wiki.openstreetmap.org/wiki/FR:Tag:amenity=school
 Et les écoles maternelles sont toutes fermées.

**Comment by PanierAvide** [comment]
Donc `amenity=kindergarten + kindergarten:FR=*` est la bonne combinaison pour la garde d'enfants. Je modifie en ce sens.

**Comment by PanierAvide** [comment]
Corrigé, ce sera pris en compte d'ici ~1h.

**Comment by py-b** [comment]
Merci Adrien !

**Comment by ViolaineDo** [comment]
Hello, Dsl pour le laps de réponse je suis à 12h de décalage par rapport à vous ! En fait j'avais proposé d'ajouter les maternelles "au cas ou" (pour les autres pays) mais attendons de voir si le besoin se fait sentir effectivement. Donc OK pour moi de le retirer pour le moment, la demande était surtout au niveau des garderies. Merci Adrien et Pierre-Yves!
