### ISSUE TITLE
Split open data files per country

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#441]
The open data files published https://www.data.gouv.fr/fr/organizations/ca-reste-ouvert/ are becoming very big which is not very convenient.

Also the data should be more usable if sorted by country.
My proposal: create one file per country. Alternative solution: create a column COUNTRY

**Comment by PanierAvide** [comment]
Is it a feedback you got from data users ?

**Comment by overflorian** [comment]
Yes from a user that wanted to display only france's data.

**Comment by PanierAvide** [comment]
C'est fait : https://download.osmontrouge.fr/caresteouvert/

**Comment by overflorian** [comment]
coeur coeur love
