### ISSUE TITLE
Missing category: atm

### ISSUE THREAD

**Issue by govvin** [osmontrouge/caresteouvert#446]
**Name**: ATM / Cash machine
**Tagging**: [amenity=atm](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Datm)
**Country**: Philippines
**Example in OpenStreetMap**: (https://openstreetmap.org/node/6845652883)
**Example in "Ca reste ouvert"**: (https://www.caresteouvert.fr/@14.578208,121.057551,20.35)
**Icon**: (https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/amenity/atm.svg.)

**Comment by caugner** [comment]
Are there any ATMs that are closed? So far the map mainly shows places that could be closed due to COVID-19 (with vending machines being an exception though).

**Comment by govvin** [comment]
The ATM POIs are not visible on "Ca reste ouvert".

Some establishments inside malls are allowed to open  but some ATM machines inside are probably inaccessible while stand-alone machines outside branches are expected to work as normal.

**Comment by PanierAvide** [comment]
I'm not sure what is the best solution for this. I think if we display all ATMs directly, we will have too much noise.

@govvin would it be OK if we show ATMs only in Philippines ? Can you add most common brands/networks of ATMs in covid_enseigne repository ? Also, what tag do you use between operator/brand/network for ATMs ?

**Comment by PanierAvide** [comment]
Closing as we lack feedback. Don't hesitate to reopen if necessary.

**Comment by clairedelune** [comment]
In the DRC, we don't have many ATMs yet and it would be quite useful to display them, using brand tag. They are actually already visible in CRO, with a question mark icon, in the "Autres établissements" category while we'd like to have them in "Argent" with an actual icon.

**Example in OpenStreetMap (CD):** https://www.openstreetmap.org/node/7432750600

**Icon**: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/amenity/atm.svg
