### ISSUE TITLE
Missing category: cafe

### ISSUE THREAD

**Issue by govvin** [osmontrouge/caresteouvert#447]
**Name**: cafe
**Tagging**: [amenity=cafe](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcafe)
**Country**: Philippines
**Example in OpenStreetMap**: (https://www.openstreetmap.org/node/1943718056)
**Example in "Ca reste ouvert"**: (https://www.caresteouvert.fr/@14.597228,121.037673,20.10)
**Icon**: (https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/amenity/cafe.svg)

Cafes are allowed to open, but only for takeaway or deliveries.

**Comment by caugner** [comment]
I guess this line should be removed:

https://github.com/osmontrouge/caresteouvert/blob/95d32a9a052ed2af25c0d6a81caf36b07ea81907/categories.json#L268

**Comment by PanierAvide** [comment]
It's because only café with either `opening_hours:covid19` or `delivery/takeaway` information which are shown.

**Comment by PanierAvide** [comment]
Closing the issue as we show them, but feel free to reopen if rules should be changed for Philippines ;-)
