### ISSUE TITLE
fantome du volet de gauche sur mobile

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#448]
Sur mobile, lorsque l'on slide depuis la gauche _rapidement_, le volet de gauche apparaît puis disparaît instantanément.
Attendu : le volet de gauche ne doit plus apparaître.

**Comment by francois2metz** [comment]
Je crois que cela a été corrigé.

**Comment by overflorian** [comment]
Yes indeed. Merci
