### ISSUE TITLE
Increase the size of text / buttons

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#449]
I propose we increase slightly the size of the interface : the text, the buttons, the space between the objects... for a better accessibility.

I propose 34px for an upper case character and 111px for the geoloc + zoom buttons.
Here the benchmark I just made:
![applis](https://user-images.githubusercontent.com/11553211/79743649-3a098900-8305-11ea-9453-16012067edce.jpg)

This should apply to the mobile version first but I don't see why not implement it also on the desktop version.

**Comment by PanierAvide** [comment]
Fait

**Comment by overflorian** [comment]
Au nom de tous les HUMAINS, merci :D
On voit bien la différence, ça fait le taff
