### ISSUE TITLE
Importer les données sur les opticiens 

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#45]
Depuis https://www.urgenceopticien.fr

**Comment by francois2metz** [comment]
@overflorian t'a envoyé un email pour connaitre la licence de ces données ?

**Comment by overflorian** [comment]
Non pas du tout. Et je n'ai pas pris contact non plus. C'est juste une idée à ce stade

**Comment by francois2metz** [comment]
J'en ai envoyé un !

**Comment by francois2metz** [comment]
Pas de retour de leur part. Je clôt.
