### ISSUE TITLE
Split interface between categories and the rest for desktop version

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#450]
It could be tricky to differenciate the POI categories from the rest of the interface.

We could add a 10% grey background behind these lines:
* Commerce manquant ?
* En savoir plus
* Changer la langue

**Comment by francois2metz** [comment]
With the new space between the categories and the others links/settings, I believe this has been fixed.

**Comment by overflorian** [comment]
yes indeed! I like this solution, thanks
