### ISSUE TITLE
Intégrer données livraison à domicile de paris ?

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#452]
https://opendata.paris.fr/explore/dataset/coronavirus-commercants-parisiens-livraison-a-domicile
Licence ODbL, plein d'infos de contact croustillantes héhé -> OSMOSE ? Ou intégration plus directe ?
823 objets géolocalisés à ce jour, ça vaut peut-être un petit effort

**Comment by francois2metz** [comment]
En doublon de #120

**Comment by overflorian** [comment]
my bad
