### ISSUE TITLE
access:covid19 > opening_hours:covid19=*

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#459]
This office seem to be closed https://www.caresteouvert.fr/@43.832427,-0.809296,18.86/place/n1254995830
but it's open with access:covid19=no because it's only by phone https://www.openstreetmap.org/node/1254995830#map=19/43.83245/-0.80968

**Comment by francois2metz** [comment]
It seems to be open now.

**Comment by vinber** [comment]
j'aimerai tant vous dire merci à chaque fois, mais j'ai peur de noyer vos mentions :1st_place_medal:
