### ISSUE TITLE
MSP/centre covid apparaît dans "Autres établissement"

### ISSUE THREAD

**Issue by deuzeffe** [osmontrouge/caresteouvert#460]
Hello,

Une MSP+centre covid n'apparaît pas dans la catégorie _Santé_ mais _Autres établissements_ 

Soit le POI https://www.openstreetmap.org/way/681741178. Le sélecteur de catégorie le fait apparaître dans la catégorie _Autres établissements_ et non dans _Santé/Centre Covid_.

Une idée de quels tags manquent ou sont inappropriés ? Ou est-ce vraiment un bug de l'analyse ?

Merci d'avance pour la réponse, quelle qu'elle soit.

**Comment by francois2metz** [comment]
Hello,

C'est dans "Autre établissements" car aucune catégorie n'a été configuré pour ce type de centre. Il apparaît parce qu'il a le tag `opening_hours:covid19`.

Les centres covid doivent être taggé en `healthcare:speciality=covid19` ce qui n'est pas le cas ici.

**Comment by PanierAvide** [comment]
Il faudra sûrement modifier la manière dont on gère les tags multi-valeurs, car un centre médical pourra avoir plusieurs spécialités dont covid19.

Côté OSM : ajouter `covid19` en valeur de `healthcare:speciality` où c'est pertinent.

Côté CRO : supporter les tags à valeurs multiples

**Comment by deuzeffe** [comment]
Désolée, je ne comprends pas. 

C'est une MSP en temps "normal" (`healthcare=centre`) : c'est bien dans la catégorie "Santé" tout comme un `amenity/healthcare=pharmacy`, non (ex. https://www.openstreetmap.org/way/550144349). C'est parce que cette valeur de tag `healthcare=` n'est pas montrée dans les rendus les plus courants ?

Qu'il y ait un tag `:covid19 `ou pas, ne change rien à la catégorie initiale. S'il n'y est pas, seule la couleur change et non la catégorie.

C'est comme ça que j'avais compris la façon de CRO de catégoriser les établissements. 

Apparemment, j'ai tout faux.

Désolée pour le dérangement.

**Comment by PanierAvide** [comment]
En fait la catégorisation se fait sur la base du fichier ici : https://github.com/osmontrouge/caresteouvert/blob/master/categories.json

Si les tags d'un objet apparaissent dans ce fichier (sans compter la gestion des zones et filtres masqués), il aura une catégorie. Sinon, s'il a un tag `opening_hours:covid19`, il va dans "autres établissements".

Ici, il n'y a pas de catégorie "centre de santé", donc c'est pour ça qu'il ressort dans autres établissements.

**Comment by PanierAvide** [comment]
Ça a été intégré, tout ce qui est relatif à un établissement de soins sera noté "centre de santé".
