### ISSUE TITLE
Untranslated text: "Specified as open end. Closing time was guessed."

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#461]
**Describe the bug**
Untranslated text in the interface.

**To Reproduce**
1. Go to: https://www.bleibtoffen.de/@48.476958,11.964339,11.01/place/n822968861
2. Change language to German or French.
3. See untranslated text.

**Expected behavior**
The text should be translateable.

**Screenshots**
![image](https://user-images.githubusercontent.com/495429/79803537-6ef7f900-8362-11ea-89b2-4b48b62340c4.png)

**Additional context**
It appears that the object has an opening hour without ending time:
https://www.openstreetmap.org/node/822968861

**Comment by francois2metz** [comment]
The result:

![Screenshot_2020-04-22 Bleibt offen](https://user-images.githubusercontent.com/86659/79994112-d7a3ba80-84b5-11ea-83e5-bdf120c1046f.png)
