### ISSUE TITLE
Name change still not in map after 2 days

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#462]
**Describe the bug**
POI appears with old name.

**To Reproduce**
1. Go to https://www.caresteouvert.fr/@48.881219,2.324730,18.92/place/n3775262458
2. Go to https://www.openstreetmap.org/node/3775262458/history
3. See different name (updated two days ago)

**Expected behavior**
POI should appear with current name.

**Screenshots**

BO / CRO:
![image](https://user-images.githubusercontent.com/495429/79805324-27736c00-8366-11ea-8c61-b1ba7742f09a.png)

OSM:
![image](https://user-images.githubusercontent.com/495429/79805316-23474e80-8366-11ea-80fc-037630dbd9a2.png)

**Additional context**
None.

**Comment by PanierAvide** [comment]
I think it's related the DB update we trying to make to allow retrieving `tourism` features and have a wider range of supported tags. @vdct will confirm this.

**Comment by vdct** [comment]
Yes it will be fixed with the rollout of the new DB, expected tonight/tomorrow

**Comment by vdct** [comment]
POI is now up to date in our OSM db but not displayed on the map since it is an estate_agent
![image](https://user-images.githubusercontent.com/2237260/79925888-ce760780-843b-11ea-8e12-f1cc0f0d2ef0.png)
