### ISSUE TITLE
Hide POIs with access=customers restrictions

### ISSUE THREAD

**Issue by tbarthelet** [osmontrouge/caresteouvert#469]
Hello,
What should be the appropriate tag to hide a POI from caresteouvert ?
I have in mind the example of a shop=laundry with tag access=customers which is not publicly accessible (inside a campsite).
Do you support filtering out POIs according to access tag?
Thomas.

**Comment by francois2metz** [comment]
Hi Thomas,

That's a good point. There is something to do here.

**Comment by overflorian** [comment]
I guess we should implement this proposal as it is.

**Comment by PanierAvide** [comment]
This is done, and fix will be visible in ~1h.

**Comment by tbarthelet** [comment]
It works fine, thank you very much Adrien.
