### ISSUE TITLE
Order subcategories by localised name

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#473]
**Is your feature request related to a problem? Please describe.**
Subcategories are shown when a category has been selected. Some categories have several subcategories and the order is fixed, which makes it hard to spot a subcategory.

**Describe the solution you'd like**
It would be nice to sort the subcategories alphabetically by localised name.

**Describe alternatives you've considered**
Alternatively, the subcategories could be ordered by the number of places shown in the map, so that more important places like "supermarket" and "bakery" are shown first.

**Additional context**
![image](https://user-images.githubusercontent.com/495429/79852565-1c9cf380-83c7-11ea-80ba-31265b9106a2.png)

**Comment by overflorian** [comment]
I like the idea of sorting the objects by the number of places shown on a map for every country. But I don't know how difficult it is to implement ;)

**Comment by caugner** [comment]
> I like the idea of sorting the objects by the number of places shown on a map for every country.

This would also allow to fade out those not relevant for the current boundary box.
