### ISSUE TITLE
Create quick access to most popular categories

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#475]
Since the categories has been more and more enriched with sub-categories, it's been difficult to access to most popular categories of POIs.

I suggest to add several quick button for a instant access to the most useful categories (5 items max), the same way Gmaps does:
![image](https://user-images.githubusercontent.com/11553211/79840866-d049b780-83b6-11ea-8cfd-3a00eb6559fb.png)

In order to pick the good categories, here's a little benchmark of current popular categories:
* Google Maps: **vente à emporter / livraison / supermarchés / Carburant / Boulangerie / Pharmacies / Hôtels**

* Les pages jaunes ([source](https://twitter.com/PagesJaunes/status/1252259051649597440)): **primeurs / La Poste / supermarchés / pharmacies**

* Apple Plans ([source](https://www.usine-digitale.fr/article/google-maps-waze-apple-les-services-de-cartographie-repensent-leurs-fonctionnalites-avec-le-covid-19.N953691)) : **épiceries, livraison de nourriture, pharmacies, hopitaux**

Therefore for France I propose: **Boulangerie / Pharmacie / Supermarchés / Alimentation / La poste**

avec la catégorie "supermarchés" incluant les supérettes et "alimentation" incluant primeurs, fromagers, ... tous les petits commerces alimentaires.

**Comment by PanierAvide** [comment]
Are you talking of categories (alimentation, services, commerces) or subcategories (in services : police, poste, garde d'enfants...) ? We have also #473 which might overlap.

**Comment by overflorian** [comment]
Originally I was thinking about specific subcategories only but I guess now it's more like a mix.
The goal is to create a quick-access to the most useful places, no matter which categories/subcategories they belong to.

Let me be more specific:
Boulangerie -> shop=bakery
Pharmacie -> amenity=pharmacy
Supermarchés -> shop=convenience;supermarket
Alimentation -> shop=frozen food;greengrocer;butcher;seafood;pastry;wine;alcohol;cheese
La poste -> amenity=post office (and maybe amenity=post_box)

I think it's not a duplicate of https://github.com/osmontrouge/caresteouvert/issues/473 but it's definitely going in the same direction of a simpler selection of POIs.

**Comment by overflorian** [comment]
ok je vois que mon idée ne plaît à personne, dommage ! Je ferme
