### ISSUE TITLE
Icône pour les établissements médico-sociaux

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#48]
Affiche celui des magasins : [exemple](https://www.caresteouvert.fr/@46.675941,5.567138,18.58/place/n7331084100)

**Comment by PanierAvide** [comment]
À résoudre en même temps que #12

**Comment by PanierAvide** [comment]
En attendant, tout ce qui n'est pas dans les catégories identifiées a un symbole "marqueur" classique. Je ferme le ticket ici, quand on affichera ces établissements on leur associera directement un symbole plus parlant.
