### ISSUE TITLE
Refresh OSM replication db

### ISSUE THREAD

**Issue by vdct** [osmontrouge/caresteouvert#497]
Our OSM replication db has random replication failures and should be replaced with a new fresh import available on our backend.. 

Steps to switch :

- [x] turn replication crontab off 
- [x] rename cro db as cro_old
- [x] rename shadow_cro db to cro
- [x] rename diff and cache directory with '_old' suffix
- [x] rename diffs-shadow and cache-shadow directory by removing the -shadow suffix
- [x] check state.txt and configuration.txt in the diffs directory according to (minutely) hourly diffs
- [x] from /home/cro/caresteouvert commit new settings into master including updated import.yml 
- [x] drop (or better rename) tables imposm_osm_point@scalingo & imposm_osm_polygon@scalingo and related indexes, PK and sequences
- [x] from cro db dump imposm_osm_point & imposm_osm_polygon tables & transfert @scalingo PG
- [x] run db/indexes_post_import.sql on new tables
- [ ] turn crontab on on remote OSM-FR bridge VM with user cro

**Comment by francois2metz** [comment]
🎉
