### ISSUE TITLE
les fermetures définitives semblent ne pas être prise en compte

### ISSUE THREAD

**Issue by wadouk** [osmontrouge/caresteouvert#50]
https://www.caresteouvert.fr/@48.844310,2.389870,17.72/place/n1932388427
https://www.caresteouvert.fr/@48.844310,2.389870,17.72/place/n1423029028

alors que les deux sont marqué `closed` et que [opening_hours](https://yarnpkg.com/package/opening_hours) semble bien prendre en compte `off` et `closed`

Avant que je fasse mes modifs, je crois que ce n'était pas marqué ouvert 24/7 comme 
https://www.caresteouvert.fr/@48.843087,2.386914,17.36/place/n5083115253

je suis juste un peu trop pressé ?

**Comment by francois2metz** [comment]
Bonjour,
Il faut vraiment utiliser `off` lorsque c'est fermé pendant le confinement. Le code qui gère cela s'attend a cela ici: https://github.com/osmontrouge/caresteouvert/blob/eae6c424a82abdfb8de19095a1fff03b756a2bff/db/update_poi.sql#L41

**Comment by PanierAvide** [comment]
On peut au pire ajouter la valeur `closed` de notre côté

**Comment by wadouk** [comment]
je l'ai utilisé à la fois dans un `opening_hours` et un `opening_hours:covid19` aucun des deux n'a fonctionné

**Comment by francois2metz** [comment]
Nous avons un délai de maximum 1 heure avec la base OSM. C'est peut être pour cela que cela n'a pas fonctionné.

**Comment by wadouk** [comment]
Viens de modifier pour mettre `off` on va voir ce que ça donne

**Comment by francois2metz** [comment]
Pour le premier lien c'est passé. Pour le deuxième il manque le opening_hours:covid19.

**Comment by wadouk** [comment]
bah, le kiosque à journaux est définitivement fermé, bizarre de devoir le marquer en plus fermé pour le covid19 ... est c'est bien le soucis, c'est fermé mais il est marqué ouvert 24/7

**Comment by vinber** [comment]
mais si il est fermé définitivement, il faut effacer le point ?
j'ai ajouté disused:

**Comment by wadouk** [comment]
euh, joker, y a toujours physiquement une cahute qui a été un jour un kiosque à journaux, mais qui n'ouvre plus https://www.mapillary.com/app/?pKey=gUgJmNHT5xBjv8SmIFjYLw&lat=48.84389947166667&lng=2.3906790463888887&focus=photo&z=17

**Comment by vinber** [comment]
ok, merci, j'ai supprimé et mis un building=kiosk. Si cela convient, on peut fermer ?
