### ISSUE TITLE
Icône ne s'affichant pas

### ISSUE THREAD

**Issue by mgageo** [osmontrouge/caresteouvert#51]
Lorsque deux établissements sont côte à côte "horizontalement", l'icône de l'établissement de droite ne s'affiche pas dans le cercle vert.
Il faut fortement zoomer pour voir l'icône, boulangerie par exemple.

**Comment by francois2metz** [comment]
Bonjour

Merci de votre message. Malheureusement on ne peut rien faire. Mapbox-gl que nous utilisons fait des choix d'affichage car tout ne peut pas être rendu en même temps. Dans le cas contraire ce serait illisible. C'est pourquoi il y a tout de même le rond vert/gris.

**Comment by mgageo** [comment]
Merci pour votre réponse.
L'icône est à l'intérieur du rond vert.
Effectivement l'affichage de tous les labels n'est pas possible dans ce cas.
