### ISSUE TITLE
N'afficher la case "vente à emporter" que sur les lieux concernés

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#514]
L'implémentation de la possibilité d'indiquer des possibilité de vente à emporter https://github.com/osmontrouge/caresteouvert/issues/92 a un sens pour les restaurants, les bars et peut-être d'autres types de lieux (mais je n'arrive pas à trouver d'autres types).

Par contre peut-être souhaitons-nous ne l'afficher que sur les autres types de POIs ? 
Il ne me semble **pas** pertinent d'indiquer la vente à emporter (qui est implicite ou impossible) pour **tous** les autres lieux (mais je peux me tromper).
_Exemple : une boulangerie, une boucherie ou un commerçant de services funéraires._ 

Pour certains de ces lieux, à la limite, on pourrait rajouter une case "consommation sur place" mais c'est du bonus.

De plus, pour les lieux suivants, il ne me semble ni pertinent d'afficher la "vente à emporter" ni la "livraison pendant le confinement" :
* amenity=police 
* amenity=fuel 
* tourism=hotel 
* amenity=car rental 
* office=employment_agency 
* shop=laundry 
* shop=funeral_directors 
* amenity=bank 
* office=insurance

**Comment by PanierAvide** [comment]
Fait, c'est géré via un paramètre `form_details` dans le fichier `categories.json`.

**Comment by overflorian** [comment]
Quelle rapidité ! Merci, c'est parfait. Peut-être qu'on voudrait réfléchir à des cases spécifiques selon les POIs dans le futur.

**Comment by PanierAvide** [comment]
Déjà il faudrait ajouter `drive_through:covid19`.

**Comment by overflorian** [comment]
on peut considérer qu'il ne s'applique qu'à la restauration rapide et aux supermarchés, non ?

Aux USA j'aurai allongé la liste énormément ... mais ici ça me paraît limité

**Comment by PanierAvide** [comment]
Même si c'est limité ici, pour l'instant on ne le demande pas dans le formulaire, c'est ballot

**Comment by overflorian** [comment]
j'imagine que c'est juste un champ à ajouter ? je n'ai pas suivi les discussions pour en estimer la pertinence, je vous laisse avancer là-dessus. Tu as encore besoin de moi sur le sujet ?
