### ISSUE TITLE
Amazon Locker tagged as Postal Office

### ISSUE THREAD

**Issue by QuentinS33** [osmontrouge/caresteouvert#518]
En explorant la carte CRO, j'ai eu la surprise d'observer que le Amazon Locker était tagué comme étant un bureau de poste lorsqu'on clique sur le point.
Sur OSM, aucune mention indiquant que c'est un bureau de poste n'est affichée. Les tags utilisés sont les suivants :
amenity = vending_machine
operator = Amazon
vending = parcel_pickup
https://www.caresteouvert.fr/@43.609357,1.489041,17.49/place/n6465299823

Ce que je pense c'est que l'ensemble des points tagués comme "parcel_pickup" sont catégorisés comme des bureaux de poste, ce qui n'est absolument pas le cas

**Comment by vinber** [comment]
j'apprends à lire les trucs de geek, et je suis assez d'accord si j'en crois cela : https://github.com/osmontrouge/caresteouvert/blob/e3ac6b988cb018923dc5f7ec3e4f0fd25e113374/categories.json#L20

**Comment by PanierAvide** [comment]
C'est dans l'idée de regrouper, La Poste ou dépose de colis (amazon ou autre fournisseur peu importe) ça reste un service d'expédition/livraison de colis (aka pour envoyer/recevoir des _trucs_). Si on trouve un intitulé plus large ça pourrait aller ? Par exemple "services postaux" ?

**Comment by QuentinS33** [comment]
Oui "Services postaux" collerait déjà mieux que "Bureau de Poste", c'est vraiment le terme qui étai gênant, pas l'attribution de catégorie.

**Comment by PanierAvide** [comment]
OK, on part là-dessus dans ce as

**Comment by PanierAvide** [comment]
Fait, ce sera en ligne dans quelques minutes, merci du retour :+1:
