### ISSUE TITLE
horaires adaptés ne veut pas dire same !

### ISSUE THREAD

**Issue by Bibi56** [osmontrouge/caresteouvert#53]
Exemple de traitement :
https://www.openstreetmap.org/note/2133163

description:covid19 | horaires adaptés. Téléphoner avant (suivant pêche !)
-- | --
opening_hours:covid19 | same

Si les horaires sont adaptés ce n'est pas same.

Rien dans le wiki https://wiki.openstreetmap.org/wiki/FR:Key:opening_hours:covid19

Je propose `restricted` ou `different`.
Certaines fois (souvent) les horaires sont réduits, quelques fois différents (prolongation le soir par exemple).

Ici on pourrait dire
description:covid19 | horaires adaptés. Téléphoner avant (suivant pêche !)
-- | --
opening_hours:covid19 | restricted

Je ne sais si c'est à mettre ici ou  plutôt dans le wiki (https://wiki.openstreetmap.org/wiki/FR_talk:Key:opening_hours:covid19#Horaires_adapt.C3.A9s) pour la résolution des notes mais je pense que la bande des 4 aura son avis !

**Comment by pyrog** [comment]
Il suffit d'utiliser les commentaires 😉 
`opening_hours:covid19 = "horaires adaptés. Téléphoner avant (suivant pêche !)"`

**Comment by Bibi56** [comment]
Sauf que : c'est plutôt description:covid19 qui est fait pour ça. Et quand quelqu'un ajoute abusivement des `same`, après tu ne sais pas si l'information est valable ou pas. J'ajouterai bien aussi `open` : on sait qu'il est ouvert mais on ne sait pas les horaires (identiques à l'habitude ou pas ?).
Je me retrouve avec des `same` dont je ne sais que faire.

**Comment by pyrog** [comment]
> Sauf que : c'est plutôt `description:covid19` qui est fait pour ça

Oui et non 😉 
Si on utilise les commentaires dans `opening_hours:covid19`, le script affiche le message (en indiquant si c'est effectivement ouvert, fermé ou indéterminé).

J'interprète `opening_hours:covid19=same` comme c'est ouvert comme **AVANT**.

**Comment by pyrog** [comment]
Voir aussi #39

**Comment by PanierAvide** [comment]
Logiquement c'est aussi résolu par 6f9b11d : les valeurs `opening_hours:covid19=open/restricted/same/yes/off "commentaire"` sont gérées. Voir https://github.com/osmontrouge/caresteouvert/blob/master/db/update_poi.sql#L6 pour l'implémentation SQL.

**Comment by pyrog** [comment]
Oh le beau bleu. Merci 😄 

- https://www.caresteouvert.fr/@47.790006,-3.487664,21.20/place/n840334545
- https://www.openstreetmap.org/node/840334545
- https://www.openstreetmap.org/note/2133163#map=19/47.79002/-3.48756

**Comment by zorun** [comment]
@PanierAvide On est d'accord que `opening_hours:covid19=restricted` tombe dans le cas par défaut `status := 'ouvert_adapté';` ?

Pour résumer :

- `opening_hours:covid19=open` : on ne sait pas si les horaires sont adaptées ou non, mais c'est ouvert. En pratique sur caresteouvert, c'est affiché comme `opening_hours:covid19=same`
- `opening_hours:covid19=restricted` : les horaires sont adaptées mais difficiles à décrire avec la syntaxe opening_hours, des précisions sont dans `description:covid19`

C'est pour documenter dans le wiki (j'ai commencé mais en le faisant je me suis rendu compte qu'il y avait deux cas un peu différents)

**Comment by zorun** [comment]
Ou alors, pour le second cas (horaires adaptées difficiles à décrire) on peut simplement utiliser les commentaires comme le suggère @pyrog , par exemple `opening_hours:covid19="tous les jours sauf le lundi matin"` ?

**Comment by PanierAvide** [comment]
C'est exactement ça, ton aide sur le wiki est la bienvenue, merci :smiley:

**Comment by PanierAvide** [comment]
Les commentaires dans `opening_hours` à éviter, pas vraiment géré pour l'instant

**Comment by zorun** [comment]
Ok super !

**Comment by Bibi56** [comment]
Donc donc contrairement à ce que propose @pyrog il vaut mieux :
`description:covid19`|tous les jours sauf le lundi matin
--|--
`opening_hours:covid19`|`restricted`

Comme ça en plus l'appli peut dire quand c'est fermé et quand c'est peut-être ouvert (je parle de l'exemple initial, pas de celui de @pyrog).

On met à jour le wiki dans ce sens ? Cf. aussi https://wiki.openstreetmap.org/wiki/FR_talk:Key:opening_hours:covid19#Horaires_adapt.C3.A9s

**Comment by PanierAvide** [comment]
Oui c'est bien ça, la proposition de son 1er message ou celle que tu reprends ici sont OK.

**Comment by Bibi56** [comment]
@zorun 
> @PanierAvide On est d'accord que `opening_hours:covid19=restricted` tombe dans le cas par défaut `status := 'ouvert_adapté';` ?
> 
> Pour résumer :
> 
>     * `opening_hours:covid19=open` : on ne sait pas si les horaires sont adaptées ou non, mais c'est ouvert. En pratique sur caresteouvert, c'est affiché comme `opening_hours:covid19=same`
> 
>     * `opening_hours:covid19=restricted` : les horaires sont adaptées mais difficiles à décrire avec la syntaxe opening_hours, des précisions sont dans `description:covid19`

Pas tout à fait (voir mon message sur le wiki).
>     * `opening_hours:covid19=open` : on ne sait pas si les horaires sont adaptées ou non, mais c'est ouvert. En pratique sur caresteouvert, c'est affiché comme `opening_hours:covid19=same`

Idéalement affiche plutôt "horaires éventuellement adaptés Les horaires usuels sont :"

>     * `opening_hours:covid19=restricted` : les horaires sont adaptées mais difficiles à décrire avec la syntaxe opening_hours, des précisions sont dans `description:covid19`

Pas forcément difficiles, aussi partiellement inconnus. Cf le [nœud](https://www.openstreetmap.org/node/840334545) initialement cité, mis à jour entre temps et parfaitement affiché dans [CaResteOuvert](https://www.caresteouvert.fr/@47.789914,-3.487668,17.00/place/n840334545).

@zorun, je te laisse mettre à jour la version française, après j'attaquerai la version anglaise.
On pourra le signaler dans OSMHebdo.

**Comment by zorun** [comment]
@Bibi56 c'est bon pour le wiki FR

> > ```
> > * `opening_hours:covid19=restricted` : les horaires sont adaptées mais difficiles à décrire avec la syntaxe opening_hours, des précisions sont dans `description:covid19`
> > ```
> 
> Pas forcément difficiles, aussi partiellement inconnus. Cf le [nœud](https://www.openstreetmap.org/node/840334545) initialement cité, mis à jour entre temps et parfaitement affiché dans [CaResteOuvert](https://www.caresteouvert.fr/@47.789914,-3.487668,17.00/place/n840334545).

Oui dans le wiki j'ai décrit ça comme « horaires adaptés approximatifs », ça couvre les différents cas d'usage (horaires adaptés définis partiellement, horaires adaptés connus partiellement, horaires adaptés relatifs aux horaires normaux qui sont absents d'OSM)

Par contre pour ton exemple, il y a des horaires définis + des précisions dans la description, c'est un peu différent.

**Comment by pyrog** [comment]
Je ne voudrais pas être trop casse-pied par un si bel après-midi 😆 

Un tag `name:fr` doit se comporter comme un tag `name`.
C'est donc la même logique pour `opening_hours:covid19` et `opening_hours`, non ?

Bon, je me colle au _jaja_ script 😆
Si j'arrive à quelque chose je fais une belle PR 😄

**Comment by PanierAvide** [comment]
C'est _quasiment_ la même logique, avec quelques mots-clés en plus. L'idée était surtout de pouvoir rapidement partir sur un tag simple et explicite pour rapidement récolter des infos. Une fois qu'on a les infos, on peut améliorer la sémantique plus tard (ce qui est fait parfois avec les tags dépréciés ou autres).

C'est noté pour _jaja_, n'hésite pas si besoin ;-)

**Comment by pyrog** [comment]
@PanierAvide Comment faire tourner la page web en local ?

```shell
sudo npm install npm@latest -g
sudo npm install -g vue-cli
npm install
npm run start

```
Quand je vais sur http://127.0.0.1:8080, le message suivant s'affiche :

```
Error: ENOENT: no such file or directory, stat '/Users/yves/Documents/GitHub/covid19_map/dist/index.html'
```

**Comment by PanierAvide** [comment]
C'est ça dans l'ordre :
```
npm install
npm run icons
npm run sprites
npm run dev
```

Ou sinon possibilité de lancer `./script/server` pour utiliser un environnement Docker (cf https://github.com/osmontrouge/caresteouvert/blob/master/script/server ).

**Comment by pyrog** [comment]
Un grand merci 😄

**Comment by Bibi56** [comment]
@zorun c'est aussi bon pour la traduction même si on s'est marché sur les pieds.
> Par contre pour ton exemple, il y a des horaires définis + des précisions dans la description, c'est un peu différent.

Non, c'est qu'entre temps les horaires ont été définis. Avant c'était juste par demie-journée^^.

@pyrog tu me fais peur : j'ai des magasins dont je ne connais _que_ les horaires exceptionnels. Tu ne veux pas plutôt nous mettre une url /en ou ?lang=en ou autre pour changer de langue ? ;-) Ca se passe [ici](https://github.com/osmontrouge/caresteouvert/issues/38).

**Comment by pyrog** [comment]
[Agence AXA d'Audierne](https://www.caresteouvert.fr/@48.023997,-4.540365,19.81/place/n6282854719), ([serveur local](http://localhost:1234/@48.023997,-4.540365,19.81/place/n6282854719))

`opening_hours=Mo-Fr 09:00-12:00 || Mo,Fr 13:30-17:00 || Tu,Th 13:30-17:00 "Sur rendez-vous"`
[OH evaluation tool](https://openingh.openstreetmap.de/evaluation_tool/?EXP=Mo-Fr%2009%3A00-12%3A00%20%7C%7C%20Mo%2CFr%2013%3A30-17%3A00%20%7C%7C%20Tu%2CTh%2013%3A30-17%3A00%20%22Sur%20rendez-vous%22&lat=43576619459609645&lon=-5.750306361383313&mode=0&DATE=1585659180000)

Ça ne fonctionne pas dans tous les cas 😞 
Il faudrait afficher le commentaire pour la tranche horaire courante ?
