### ISSUE TITLE
Working offline

### ISSUE THREAD

**Issue by wadouk** [osmontrouge/caresteouvert#534]
**Describe the bug**
When showing the app to the pharmacist, clicking on POI do nothing.
Doesn't see that the network was disconnect (too far in the bulding).

**To Reproduce**
1. https://www.caresteouvert.fr/@48.845457,2.404328,19.51
3. Going offline
4. Clicking on "Pharmacie du rendez-vous"

**Expected behavior**
Opening the detail of the pharmacie or seeing something that tell there is a problem

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Lineage OS (Android)
 - Browser: App

**Workaround proposals**
- Having just a message telling that fetching the detail doesn't work
- Prefetching 10 pois details nearest from center at a certain levels
- Pre-displaying only datas that are available in tiles and when the datas are available displaying the precise datas

- Using a service worker to manage the cache of assets should be handy to implement a rich approch of that

**Comment by Bibi56** [comment]
@wadouk, workout for your use case: copy your screen (or your webpage) on your mobile. 2-3 screenshots are sufficient to show it to the pharmacist. But definitevely nice to have.

**Comment by PanierAvide** [comment]
Even if I understand the need, it's quite a corner case for advanced users, not a general need. Closing the issue as now.

**Comment by wadouk** [comment]
The workaround is for advanced users yes, because I try to make the publicity of the app, I have to think to prepare the showcase and make a screenshot before.
For normal user, without thinking it could go offline I see an app that no more work, without message or information whatever is the situation.

**Comment by PanierAvide** [comment]
Well maybe it's more related to the app and not the website, you can instead send this report to the Android dev team : https://github.com/osmontrouge/caresteouvert_android/
