### ISSUE TITLE
Préciser les règles de Covid_enseignes par type de POI ?

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#543]
Hey, on a un le siège du crédit agricole qui apparaît sur la carte : https://www.openstreetmap.org/node/2042118214
Ce lieu ne reçoit pas de public et ne devrait donc pas apparaître.

Je pense que c'est une règle de Covid-Enseignes qui s'applique sur ce office=financial car il est tagué brand:wikidata=Q590952.

Est-ce que l'on aurait envie de préciser sur quel type de tag s'applique les règles Covid-Enseignes ? Ou doit-on considérer que ce cas est vraiment trop exceptionnel pour se pencher sérieusement sur le sujet ?

**Comment by PanierAvide** [comment]
Ce sont des cas vraiment peu fréquents (cf #398), d'autant que `office=financial` est peu utilisé et sur des lieux à priori pas ouverts au grand public. Je vais donc plutôt les enlever des catégories.

**Comment by PanierAvide** [comment]
C'est fait, ce sera corrigé à la prochaine mise à jour ~1h.

**Comment by overflorian** [comment]
OK merci donc si je comprends bien on a une liste noire des types de POI à ne jamais afficher même si un tag Covid ou une règle covid-enseignes s'applique ?

**Comment by PanierAvide** [comment]
Non, c'est juste que les exceptions où les infos des enseignes ne s'appliquent pas sont rares, et souvent des bureaux pas ouverts au public. Donc retiré purement et simplement de la liste des POIs gérés

**Comment by overflorian** [comment]
OK merci
