### ISSUE TITLE
Clarifier l'usage de access=no

### ISSUE THREAD

**Issue by OcelotNat** [osmontrouge/caresteouvert#549]
Bonjour,

suite à l'intégration de nombreuses notes, je constate que l'usage du tag access=no n'est pas clair pour les utilisateurs, et il semble également y avoir une ambiguïté entre CRO et le wiki OSM.

Usage dans CRO : 
question : "les clients peuvent entrer ou rester à l'intérieur ?"
-> si non : affichage "L'intérieur n'est pas accessible au public"

Indications dans le wiki OSM : 
Lieu (commerce, salle de restaurant) non accessible au public : access:covid19=no

Dans les notes, je constate que les restaurants l'utilisent plutôt pour dire "pas de service en salle" (mais commande possible à l'accueil).
Les mairies l'utilisent plutôt en "pas d'accueil physique [uniquement téléphone/mail/...]".
Les commerces genre magasin de bricolage l'utilisent de manière variée (magasin/cours des matériaux/commande préalable/...)

Du coup je me retrouve à interpréter les notes selon les autres informations fournies, et il doit donc y avoir des différences de choix/sens entre les infos intégrées automatiquement et celles intégrées manuellement.

**Il me semble** que l'usage de access=no devrait être réservé aux établissement n'offrant aucun accueil physique (hors préalable appel/rendez-vous/commande), et donc il faudrait modifier en quelque chose comme : 

- "les clients peuvent entrer ou rester à l'intérieur ?" -> "La porte est-elle ouverte [aux heures indiquées] au public ?"

- "L'intérieur n'est pas accessible au public" -> "Pas d'accueil [physique] sur place"

Si les restaurants ont besoin d'une distinction salle ouverte/fermée, on pourrait imaginer un "access:inside=yes/no" (les pharmacies peuvent avoir le même distingo avec le service au comptoir et le service au guichet de garde, donc à l'extérieur)

**Comment by vinber** [comment]
Totalement d'accord, et cette formulation, voire un complément /
"L'intérieur n'est pas accessible au public" -> "Pas d'accueil [physique] sur place. Contactez nous pour en savoir plus."

Cela permet de couvrir en gros toutes les raisons (pour passer commande à un restaurant, pour un service de la mairie, pour des fleurs à faire livrer, ...).

**Comment by PanierAvide** [comment]
C'est corrigé, merci du retour ce sera effectivement plus clair comme ça ;-)
