### ISSUE TITLE
Intégrer les données des vente a la ferme de l'Indre et Loire

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/caresteouvert#55]
A faire peut être directement sur OSM ?

https://www.francebleu.fr/infos/agriculture-peche/la-carte-interactive-des-fermes-qui-font-de-la-vente-directe-en-indre-et-loire-1585319030

**Comment by vinber** [comment]
tu veux dire les contacter pour qu'ils le fassent sur caresteouvert ?

**Comment by PanierAvide** [comment]
Ce serait pas plus mal, les producteurs (de données ou de produits fermiers !) enrichissent par eux-même pour créer des contributeurs de long terme. Donc pourquoi pas les contacter voir s'ils sont réceptifs et intéressés

**Comment by vinber** [comment]
et on n'intègre pas de la donnée dont on n'a pas la license d'utilisation dans tous les cas :D

**Comment by vinber** [comment]
contact pris, je vous tient au jus

**Comment by vinber** [comment]
Réponse, je ne sais pas pourquoi il m'appelle Rodolphe :)
"Bonjour Rodolphe,
Merci pour votre message.
Je vais poser la question aux membres du bureau des Jeunes agriculteurs et reviendrais vers vous dans l’affirmative."

**Comment by vinber** [comment]
pas de réponse, on ferme et si j'ai des retours j'ouvre :)
