### ISSUE TITLE
Hôtel

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#551]
**Hébergements** in grays

With an opening_hours:covid19 it's ok, we can see red ou green dot.

but we don't have possibility to contribute to undetermined hotel (grays)

Severals activities start in few days-weeks and it's seems necessary to know where to host people (construction, ...). It's not tourism.

**tourism=hotel**

and perhaps others one, important in rural area : https://wiki.openstreetmap.org/wiki/Tag:tourism%3Dhotel#See_also

**France**

https://www.openstreetmap.org/way/139704042#map=19/44.78445/-0.58810

https://www.caresteouvert.fr/amenity@44.787129,-0.584251,14.51/place/w139675721

**Comment by vinber** [comment]
#315

**Comment by PanierAvide** [comment]
All hotels are now enabled in AT/DE/CH/FR. Will be online in ~1h.
