### ISSUE TITLE
Missing category: Hotels in Switzerland

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#556]
**Name**: Hotels

**Tagging**: `tourism=hotel|motel|hostel`

**Country**: Switzerland (CH)

**Example in OpenStreetMap**: (I don't have one)

**Example in "Ca reste ouvert"**: (I don't have one)

**Icon**: Already checked in as [hotel.svg](https://github.com/osmontrouge/caresteouvert/blob/master/icons/hotel.svg)

--

**Background**: We discussed this in https://github.com/osmontrouge/caresteouvert/issues/315 and consequently in https://github.com/bleibtoffen/bleibtoffen/issues/88.

**Result**: All hotels should be displayed in Switzerland, as already prepared in the `categories.json`:

https://github.com/osmontrouge/caresteouvert/blob/c0b852bba7ac033127f91448f10c650743aa831c/categories.json#L91-L99

**Comment by vinber** [comment]
#551

**Comment by caugner** [comment]
(#551 is not a duplicate, because it isn't about Switzerland.)

**Comment by vinber** [comment]
it's not as duplicate, it's to link interest of display of hotels

**Comment by PanierAvide** [comment]
@caugner I translated discussions on your repository, so how will be handled the fact that most hotels are open there ? If there are major brands, could be interesting to add them first to covid_enseignes.

**Comment by caugner** [comment]
I have requested a list now, but IMO this doesn't need to block adding them on the map. Or is there any technical work required apart from enabling them in the `categories.json`?

**Comment by caugner** [comment]
@PanierAvide Is there any easy way to compile a list of Swiss hotel operators and their number of hotels in OSM?

In theory, they would be in [stats_brand_count.csv](https://download.osmontrouge.fr/caresteouvert/stats_brand_count.csv) once they are in `categories.json`, but then again the brand statistic doesn't include the POI type, so couldn't be used for this.

**Comment by caugner** [comment]
@PanierAvide Just got the feedback that the most important chains would be `partial` in Switzerland, so the chain data wouldn't really help here.

**Comment by PanierAvide** [comment]
All hotels are now enabled in AT/DE/CH/FR. Will be online in ~1h.
