### ISSUE TITLE
Show all shops in Germany

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#558]
(**Current status** :arrow_right: https://github.com/osmontrouge/caresteouvert/issues/558#issuecomment-619889781)

**Name**: All shops not belonging to any other category.

**Tagging**: `shop=*`

**Country**: Germany

**Example in OpenStreetMap**: (Not relevant.)

**Example in "Ca reste ouvert"**: (Not relevant.)

**Icon**: Use [other.svg](https://github.com/osmontrouge/caresteouvert/blob/master/icons/other.svg).

--

**Background**: From Monday, 27th April, all shops with a surface of less than 800 sqm are allowed to open in most parts of Germany. Shops with a surface of more than 800 sqm may also open if they reduce the accessible surface to 800 sqm or less.

**Comment by PanierAvide** [comment]
If everything is open again, does it make sense to show them all ? Reverse proposal would be to remove every category related to shops in Germany, as we now they are open. So community focuses on categories of POI where there is uncertainty. I make this point to discuss and find best solution :wink:

**Comment by caugner** [comment]
Even if shops are allowed to open, this doesn't mean that they actually do, nor that their opening hours match their regular opening hours.

**Comment by PanierAvide** [comment]
OK, understood ;-)

**Comment by PanierAvide** [comment]
If we look back at what we've done until now:
- Every POI is part of category which make sense for user
- POIs which go into fallback are minority, and only for making `opening_hours:covid19` still visible

In the case of adding all remaining shop=* POI, we can't just let them go into a fallback category : it would be a huge mess. Instead, let's keep thing organized, and create appropriate categories which are now lacking. This will allow to keep UI coherent (filters, icons, appropriate contribution form for each type of POI...).

So to make this possible, would it be OK for you to list shop=* values which are not supported yet and having 100+ POIs in Germany ? That way, it will be easier to create categories/subcategories, and then we can share tasks to create icons, translations and so on.

**Comment by caugner** [comment]
Sounds good to me.

Any tips to determine which types of shops these are? Unfortunately the Geofabrik Taginfo is currently unavailable, otherwise it could answer this question.

**Comment by PanierAvide** [comment]
Yes that's every unfortunate for Taginfo, this is _the_ tool to do so. Hopefully we can do raw SQL analysis on our DB (unfiltered between supported/unsupported shop values):

```
        shop         |  cnt  
---------------------+-------
 storage_rental      |   103
 insurance           |   108
 health_food         |   111
 winery              |   112
 electrical          |   116
 wool                |   116
 appliance           |   129
 window_blind        |   132
 pet_grooming        |   134
 scuba_diving        |   136
 ice_cream           |   140
 pawnbroker          |   141
 chocolate           |   142
 rental              |   143
 weapons             |   146
 radiotechnics       |   153
 estate_agent        |   161
 sewing              |   172
 solarium            |   175
 photo_studio        |   177
 video_games         |   178
 cheese              |   186
 fireplace           |   190
 glaziery            |   195
 tiles               |   201
 frame               |   206
 general             |   225
 leather             |   230
 fishing             |   234
 watches             |   263
 agrarian            |   266
 bathroom_furnishing |   294
 baby_goods          |   296
 e-cigarette         |   304
 pastry              |   314
 carpet              |   373
 curtain             |   390
 charity             |   423
 erotic              |   426
 no                  |   435
 video               |   445
 lottery             |   455
 locksmith           |   465
 bag                 |   467
 fashion             |   477
 wholesale           |   496
 bookmaker           |   497
 music               |   501
 paint               |   643
 tea                 |   656
 perfumery           |   761
 coffee              |   788
 tobacco             |   796
 houseware           |   809
 musical_instrument  |   831
 hifi                |   865
 antiques            |   872
 seafood             |   891
 craft               |   904
 outdoor             |   932
 second_hand         |  1047
 confectionery       |  1056
 ticket              |  1058
 trade               |  1187
 cosmetics           |  1205
 bed                 |  1219
 newsagent           |  1236
 tattoo              |  1244
 fabric              |  1268
 copyshop            |  1321
 tyres               |  1343
 kitchen             |  1394
 photo               |  1423
 car_parts           |  1427
 boutique            |  1501
 art                 |  1502
 wine                |  1519
 hardware            |  1585
 laundry             |  1692
 department_store    |  1722
 motorcycle          |  1758
 mall                |  1788
 massage             |  1821
 deli                |  1882
 medical_supply      |  1889
 dry_cleaning        |  1929
 hearing_aids        |  2024
 toys                |  2055
 funeral_directors   |  2096
 greengrocer         |  2171
 tailor              |  2175
 alcohol             |  2199
 computer            |  2200
 pet                 |  2236
 interior_decoration |  2584
 variety_store       |  2746
 sports              |  2762
 stationery          |  3100
 garden_centre       |  3187
 gift                |  3197
 farm                |  3318
 mobile_phone        |  3916
 books               |  4385
 vacant              |  4808
 yes                 |  4896
 electronics         |  4967
 chemist             |  5355
 travel_agency       |  5416
 doityourself        |  5505
 jewelry             |  5569
 furniture           |  5795
 bicycle             |  6448
 beauty              |  7098
 optician            |  7119
 shoes               |  7784
 beverages           |  8280
 convenience         |  8752
 florist             | 10898
 kiosk               | 10975
 butcher             | 11397
 car                 | 17028
 car_repair          | 18199
 hairdresser         | 29645
 clothes             | 30547
 supermarket         | 33942
 bakery              | 36290
```

**Comment by caugner** [comment]
Thank you, I have now checked which shops are already defined in the `categories.json`:

- [x] bakery
- [x] supermarket
- [ ] clothes
- [ ] hairdresser
- [x] car_repair
- [ ] car
- [x] butcher
- [x] kiosk
- [x] florist
- [x] convenience
- [x] beverages
- [ ] shoes
- [x] optician
- [ ] beauty
- [x] bicycle
- [ ] furniture
- [ ] jewelry
- [ ] doityourself
- [ ] (travel_agency)
- [x] chemist
- [x] electronics
- [ ] ~~yes~~
- [ ] ~~vacant~~
- [x] books
- [x] mobile_phone
- [x] farm
- [ ] gift
- [x] garden_centre
- [x] stationery
- [ ] sports
- [ ] variety_store
- [ ] interior_decoration
- [x] pet
- [x] computer
- [x] alcohol
- [ ] tailor
- [x] greengrocer
- [x] funeral_directors
- [ ] toys
- [x] hearing_aids
- [x] dry_cleaning
- [x] medical_supply
- [ ] deli
- [ ] (massage)
- [ ] mall
- [ ] motorcycle
- [ ] department_store
- [x] laundry
- [x] hardware
- [x] wine
- [ ] art
- [ ] boutique
- [x] car_parts
- [ ] photo
- [ ] kitchen
- [ ] tyres
- [ ] copyshop
- [x] fabric
- [ ] tattoo
- [x] newsagent
- [ ] bed
- [ ] cosmetics
- [ ] trade
- [ ] ticket
- [x] confectionery
- [ ] second_hand

**Comment by PanierAvide** [comment]
So if we try to merge them.

## Amenity
copyshop

## Mobility
car
motorcycle
tyres
ticket

## Shops
boutique
photo
trade
furniture
gift
variety_store
interior_decoration
kitchen
bed
toys
mall
department_store
second_hand
art

## Clothing / personal care (new)
clothes
shoes
sports
jewelry
tailor
tattoo
hairdresser
beauty
cosmetics

**Comment by PanierAvide** [comment]
So if this categorization is OK for you, can you provide SVG icons (preferably under CC0 license) for each subcategory ? SVG icons must be 18px x 18px wide.

**Comment by nomeata** [comment]
Just wondering: Does this mean that work is underway to support `shop=shoes`?

**Comment by caugner** [comment]
@nomeata Would you be interested in contributing other shop categories, especially `clothes` and `hairdresser`?

**Comment by nomeata** [comment]
Not necessary, I scratched the itch I had, if that’s ok :-0

**Comment by caugner** [comment]
**Current status** :arrow_right: https://github.com/osmontrouge/caresteouvert/issues/558#issuecomment-619889781
