### ISSUE TITLE
Missing category: déchetterie

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#559]
Rajouter les déchetteries ? 
tagguées amenity=recycling et recycling_type=centre

Exemple : https://www.openstreetmap.org/way/615251186

Lieu dans CRO : https://www.caresteouvert.fr/@43.590315,1.299482,14.35/place/w615251186

Proposition d'icône : https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/amenity/recycling.svg

**Comment by PanierAvide** [comment]
Ajouté, ce sera en ligne dans ~1h.
