### ISSUE TITLE
Ajouter la possibilité d'afficher/renseigner un horaire "créneau réservé"

### ISSUE THREAD

**Issue by FlorentRICHARD44** [osmontrouge/caresteouvert#56]
Certains magasins ajoutent un horaire "créneau réservé" en plus de leurs horaires adaptés (par exemple pour les personnes de plus de 70 ans).
Il serait intéressant d'ajouter cette information, sans "sur-remplir" le champ description. donc un nouveau tag "opening_hours:covid19:xxxx" ou autre

**Comment by vinber** [comment]
cela me semble complexe par rapport aux cas réellement existants et à la possibilité de le renseigner dans description:covid19=*
Est-ce vraiment très fréquent ?

**Comment by Bibi56** [comment]
Très je ne sais, mais effectivement ça existe. Dans d'autres ce sont des caisses qui sont réservées.
`opening_hours:covid19:over70` ça va devenir ingérable car ça peut aussi être valables pour les personnes handicapées ou fragiles (celles ayant une Affectation Longue Durée leur permettant de poser un arrêt de travail sans avis médical.
Mettre un truc au format `opening_hours:covid19`  dans `description:covid19` serait illisible.
`opening_hours:covid19:specific` au format opening hours plus `specific:covid19`=description du public peut être.

**Comment by FlorentRICHARD44** [comment]
Ce n'est pas très fréquent, et principalement pratiqué par des supermarchés.
en attendant mieux, je le renseigne effectivement dans description:covid19.
Ce qui m'ennuie avec description:covid19, c'est que ça devient fourre-tout et que pour certains magasins ce champ s'allonge trop et devient illisible.

J'explique un cas que j'ai vu:
* le magasin est ouvert de 8h15 à 9h pour les + de 70 ans et de 9h à 19h pour tout le monde
* un précédent contributeur avait indiqué magasin ouvert de 8h15 à 19h, ce qui est à la fois vrai et faux
* j'ai donc indiqué dans les opening_hours:covid19 ouvert de 9h à 19h et dans description:covid19 ajouté l'ouverture de 8h15 à 9h réservée aux + de 70 ans.

Je comprend bien que ce genre de cas est aussi difficile à tagguer qu'à afficher.

**Comment by PanierAvide** [comment]
Même constat : ça va devenir complexe à structurer.

À minima ce qu'on va essayer de gérer ce sont les établissements proposant des livraisons ou de la vente à emporter. Pour les créneaux, si vous arrivez à un consensus assez simple pour les modéliser, on fera tout pour les intégrer.

**Comment by vinber** [comment]
à mon avis priorité sur les ouvertures à tout le monde, donc ce que tu proposes @FlorentRICHARD44 me semble trés pertinent (le "pour tout le monde" dans opening_hours:covid19 et le spécifique dans description:covid19).
