### ISSUE TITLE
Handle links without https/http

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#561]
**Describe the bug**
Some URLs in OSM omit the `https://`/`http://` prefix and therefore don't work.

**To Reproduce**
1. Open: https://www.caresteouvert.fr/food%2Fbakery@48.681651,6.153254,13.72/place/n2736141217
2. Click on website.
4. See that website doesn't open.

**Expected behavior**
Website should open despite missing protocol.

**Screenshots**
(None.)

**Additional context**
Downstream: https://github.com/bleibtoffen/bleibtoffen/issues/93

**Comment by PanierAvide** [comment]
This has been fixed and will be available in a few minutes, thanks for your feedback :+1:
