### ISSUE TITLE
Display the website in browser language

### ISSUE THREAD

**Issue by gnafron** [osmontrouge/caresteouvert#564]
Hello,

My browser is configured in Breton, however I have to manually select "Brezhoneg" in the menu ; the website is displayed in French by default.
Could be great if the UI was displayed in browser language when translation exists.

Thank you

**Comment by PanierAvide** [comment]
Hello, I think it's related to how language is found here :
https://github.com/osmontrouge/caresteouvert/blob/83e8875259bc5da8ebb45470283edd057ce104a5/modules/plugin.i18n.js#L14

Priority seems to be given to which website domain is used (caresteouvert.fr) and not language code sent by browser.

Solution could either be to add a domain name for Breton version, or change priority in code above.

**Comment by francois2metz** [comment]
Thanks for the report. It was the intended behavior.
