### ISSUE TITLE
Ajouter un lien vers le guide de contribution pour ajouter un lieu inexistant

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#57]
en dessus de "à propos" et "presse", ajouter, dans un bloc séparé (peut-être bien distinct avec un fond gris clair ?) la mention "Indiquer un commerce manquant" qui renvoie vers https://blog.caresteouvert.fr/que-faire-sil-manque-un-commerce-dans-ca-reste-ouvert/

**Comment by PanierAvide** [comment]
Je fais ça

**Comment by PanierAvide** [comment]
Fait ;-)
