### ISSUE TITLE
Warning pour un message trop long

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#572]
Lorsque l'on écrit un message texte trop long, le message d'erreur affiché devrait indiquer "Doit être vide ou compris entre 10 et 200 caractères.
Message actuel :
![image](https://user-images.githubusercontent.com/11553211/80378114-78bab880-889c-11ea-9d0a-c1ab8add47d3.png)

**Comment by PanierAvide** [comment]
Le wording c'est la vie ;-)

**Comment by overflorian** [comment]
ça y est, tu commences à réaliser A QUEL POINT les utilisateurs sont HUMAINS ;)
cool aussi la correction pour afficher la date et l'heure en format HUMAIN. Merci à toi ou @francois2metz, je ne sais pas
