### ISSUE TITLE
Intégrer les hackspaces / initiatives de makers qui répondent au covid

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#581]
Est-ce que l'on n'intégrerait pas les données de https://covid-initiatives.org ?
Elles sont là : https://www.data.gouv.fr/fr/datasets/inventaire-des-initiatives-de-la-societe-civile-visant-a-faire-face-a-la-pandemie-de-covid-19/

**Comment by PanierAvide** [comment]
À proposer à la communauté

**Comment by PanierAvide** [comment]
Pas de retour, je ferme le ticket.
