### ISSUE TITLE
Classement et/ou priorités entre marques, tags, ...

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#582]
**Describe the bug**

la station service et l'épicerie apparraissent dans la même catégorie : https://www.caresteouvert.fr/food%2Fconvenience@44.918876,-0.242191,18.84

**To Reproduce**
1. https://www.caresteouvert.fr/food%2Fconvenience@44.918876,-0.242191,18.84
2. le noeud au sud est une station service https://www.openstreetmap.org/node/1136060445
3. le way au nord est une épicerie https://www.openstreetmap.org/way/79358798

**Expected behavior**

la station service dans https://www.caresteouvert.fr/mobility%2Ffuel@44.918876,-0.242191,18.84

**Comment by PanierAvide** [comment]
Le double tagging shop=convenience / amenity=fuel est à l'origine de cette mauvaise classification. Comme ici la boutique est représentée par un point séparé, j'aurais tendance à enlever `shop=convenience` de la station.

**Comment by vinber** [comment]
bien sur, je n'avais pas vu le shop=convenience sur la station essence !
