### ISSUE TITLE
Display properly the search bar text for iOS

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#584]
The RECHERCHE text isn't displayed fully in the search bar on an iPhone (config iOS 13.3.1, @ossiannroux's phone)

![IMG_7174](https://user-images.githubusercontent.com/11553211/80498155-ad497580-896b-11ea-9cd1-4f3ce4eeb87d.PNG)

**Comment by overflorian** [comment]
Hi, this issue is still unfixed (checked yesterday). Any update?

**Comment by PanierAvide** [comment]
I reduced size of text to `1.5rem`, should solve the issue. Will be online in a few minutes.
