### ISSUE TITLE
Missing category: newsagent

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#587]
Add a "newsagent" category, including shop=kiosk and shop=newsagent

Associated icon: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/newsagent.svg

**Comment by francois2metz** [comment]
This one ? https://www.caresteouvert.fr/shop%2Fnewsagent

**Comment by overflorian** [comment]
Oops yes! Should we add shop=kiosk too to this category?

**Comment by francois2metz** [comment]
It's already there.
