### ISSUE TITLE
Afficher la police nationale ouverte par défaut

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#59]
J'ai trouvé un commissariat dont le statut est inconnu : https://www.caresteouvert.fr/@48.815536,2.312591,16.71/place/w83237134
Il faudrait je pense afficher tous les points POLICE ouverts

**Comment by overflorian** [comment]
Idem pour la police municipale https://www.caresteouvert.fr/@48.814993,2.320141,16.71/place/n2325918469

**Comment by PanierAvide** [comment]
On est sûr qu'ils accueillent le public partout ?

**Comment by vinber** [comment]
je ne suis pas sur et je ne sais pas si c'est un service trés recherché ?

**Comment by PanierAvide** [comment]
Après discussion téléphonique, on est pas certains de l'ouverture des postes de police partout, donc à gérer comme les autres lieux. Je ferme le ticket.
