### ISSUE TITLE
Display the titre of a category splitted

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#595]
While a category is open _e.g. https://www.caresteouvert.fr/health_ display its title differently from the rest of the page.

### Proposal 1
Create a banner: https://material.io/components/banners#anatomy 
  
![image](https://user-images.githubusercontent.com/11553211/80584336-cc9ade00-8a11-11ea-8c4a-39b5a272fe17.png)

### Proposal 2
Create a backtrop: https://material.io/components/backdrop
![image](https://user-images.githubusercontent.com/11553211/80584756-72e6e380-8a12-11ea-980b-6ef3bf3fcd53.png)
It his second proposal, the extra-categories filters (such as delivery) are in the top section.
A subheader displays the titre of the category. Only the bottom of the interface is scrollable.

I prefer proposal 2.

**Comment by overflorian** [comment]
Suite aux évolutions récentes de l'interface, on est plus qu'à deux doigts d'arriver à une banner telle que définie dans le material design :)
Ne reste qu'à ajouter une séparation claire (avec une ombre), à décaler un peu le titre vers la droite et d'en augmenter la taille :
![banner](https://user-images.githubusercontent.com/11553211/81962375-ed6b5200-9613-11ea-9208-e7b9d56b9c7d.png)

Comme ça la lisibilité sera top, merci par avance.

**Comment by PanierAvide** [comment]
Fait, ce sera en ligne dans quelques minutes
