### ISSUE TITLE
Change behaviour when clicking on a fax number

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#599]
What should happen when clicking on a fax number?

### Current behavior
1. Display a POI with a fax number, e.g. https://www.caresteouvert.fr/@48.816398,2.311360,22.00/place/n1911406628
2. Click on the fax number, e.g. https://www.caresteouvert.fr/@48.816398,2.311360,22.00/place/+33%201%2047%2035%2093%2055
3. The page reloads itself

### Proposed behavior
**Proposal 1.** A click on the fax number copies it in the clipboard. A [snackbar](https://material.io/components/snackbars) confirms the action: "Number copied"

**Proposal 2.** A click on the fax number displays a [menu](https://material.io/components/menus#usage) with a single option "copy the number in the clipboard. If clicked, a [snackbar](https://material.io/components/snackbars) confirms the action: "Number copied"

Honestly, it's just a proposal, I have no precise idea of what should happen when clicking on a fax number.

**Comment by PanierAvide** [comment]
There is the `fax:` prefix (same as `tel:`) which can be used at least. Supported software will handle it. And I don't know if we want to go further on this.

**Comment by overflorian** [comment]
OK, I didn't understood that, I think that's great for now and that we shouldn't invest more time on this.

**Comment by PanierAvide** [comment]
OK, so I added this `fax:` prefix to avoid reload + allow support by software.

**Comment by overflorian** [comment]
perfect, thanks
