### ISSUE TITLE
Corrections wording

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#6]
un peu de wording :
-le bouton de validation "signaler" -> publier
-Boutiques (dans la liste des POIs) -> Commerces
-Magasins d'alimentation (dans la liste des POIs) -> Alimentation
-Horaires susceptibles de changer pendant le confinement -> Horaires d'ouverture hors-confinement
-Cette enseigne a été déclaré ouverte -> Lieu ouvert durant le confinement. Bon plan partagé par un contributeur
(peut-être mettre la deuxième phrase à la ligne en plus petit ? A tester)

-Le wording pour les lieux fermés -> Lieu fermé durant le confinement. Bon plan partagé par un contributeur
(peut-être mettre la deuxième phrase à la ligne en plus petit ?)

-Nous ne savons pas si cette enseigne est ouverte ou non -> _Je n'ai pas trouvé mieux mais cela ne convient pas. A discuter de vive voix._

**Comment by vinber** [comment]
> Bon plan

me surprend ! Un peu trop réseau social pour moi mais je suis prèt à croire que je suis vieux jeu :)
sortir ces deuxième phrase ?

**Comment by PanierAvide** [comment]
Je suis parti là-dessus :
* Lieu ouvert durant le confinement
* Lieu ouvert durant le confinement avec des horaires adaptées
* Lieu potentiellement ouvert durant le confinement (à vérifier)
* Lieu dont l'état d'ouverture n'est pas connu

Je trouvais ça aussi bizarre de parler de "bon plan" dans un contexte de crise :thinking:

**Comment by overflorian** [comment]
ça me va, merci.
Sauf "Lieu dont l'état d'ouverture n'est pas connu" -> "l'état" n'est pas un mot très parlant.
Propositions :
-Lieu dont l'ouverture est inconnue ?
-Lieu ouvert ou fermé. À vous de le dire.
-Lieu autorisé à ouvrir durant le confinement. Ouvert ou fermé. À vous de dire.

**Comment by francois2metz** [comment]
C'est bon pour cette issue ?

**Comment by overflorian** [comment]
hey, je pense que ma dernière remarque tient toujours : "l'état" d'ouverture ne me semble pas très parlant. Je propose :
 "Lieu autorisé à ouvrir durant le confinement. Ouvert ou fermé ? À vous de le dire."
