### ISSUE TITLE
Faire figurer les boites aux lettres de la poste

### ISSUE THREAD

**Issue by JocelynDelalande** [osmontrouge/caresteouvert#60]
Les boites aux lettres de la poste sont pour une grande partie fermée, par ex :

![boite au lettre fermée et scochée pour cause de covid, avec mot explicatif](https://user-images.githubusercontent.com/429633/77831112-64648e00-712d-11ea-81db-782e7a525564.png)

**Comment by MatthieuOSM** [comment]
Pareil je l'ai constaté sur une boîte pas loin de mon domicile, peut-on imaginer un tag similaire aux autres pour cet usage ?
collection_times:covid19=off

**Comment by PanierAvide** [comment]
On peut imaginer les intégrer, il faut qu'on veille cependant à l'implémentation :
- Lire `collection_times:covid19` au lieu de `opening_hours:covid19` en base de données
- Utiliser ce même champ dans les affichages du site web
- Et surtout, utiliser ce tag __lors de la contribution à OSM__

**Comment by francois2metz** [comment]
j'ai un truc que j'avais fait sur OSMontrouge pour les horaires de collecte. La modification par contre va être plus pénible à implémenter.

**Comment by PanierAvide** [comment]
On a 18 boîtes aux lettres avec des infos, et peut-être que ce ne sera bientôt plus un sujet ? Je ferme le ticket, ne pas hésiter à réouvrir au besoin.
