### ISSUE TITLE
Missing category: parapharmacie

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#606]
Les parapharmacies, taguées shop=chemist avec [600 occurrences en France](https://taginfo.openstreetmap.fr/tags/shop=chemist) sont _à priori_ autorisées à vendre des masques ([source](https://sante.journaldesfemmes.fr/fiches-maladies/2609189-masque-coronavirus-covid-obligatoire-enfant-ecole-transport-commerce-entreprise-afnor-tissu-grand-public-pharmacie-prix-achat/), désolé, je n'ai pas mieux, pourtant j'ai cherché)

Est-ce qu'on les rajouterait pas ? Dans la catégorie /pharmacie direct ? Quitte à choquer un ou deux pharmaciens au passage mais que cela reste pratique à l'usage.

**Comment by PanierAvide** [comment]
`shop=chemist` est déjà affiché comme "droguerie" dans la catégorie "boutiques". C'est suffisant niveau catégorisation ou on le déplace ?

Sinon oui ça a du sens d'ajouter la question masques/gel sur ce type de POIs.

**Comment by overflorian** [comment]
Est-ce qu'on en l'afficherait pas également dans la catégorie pharmacies ? Il apparaîtrait en double, à la cool.

**Comment by PanierAvide** [comment]
Ça non ça marche pas, pour un même pays un tag ne peut être utilisé qu'une seule fois.

**Comment by overflorian** [comment]
OK, c'est bien dommage.

Je suis un peu partagé :
-en théorique ce sont des lieux lié au médical
-en pratique je retrouve pas mal de nocibé, marrionaud, occitanne en provence voir même un "anti-cafard 2000" qui sont vraiment mal taggués. Il y a aussi beaucoup de parapharmacies bien tagguées, notamment des parashop

Dans le doute on laisse à droguerie et on ouvre la contribution pour gel/masques ?

Pour moi la solution, c'est ce que j'ai proposé ce matin : des modes GEL / MASQUE / TESTS qui n'affichent que les lieux liés à ces thématiques.

**Comment by PanierAvide** [comment]
Je crois que c'était l'idée : une fois qu'on aura un peu plus de données, ajouter ces filtres comme on le fait pour la livraison et vente à emporter.

Je vais ajouter l'affichage des questions gel/masque sur ces POIs.

Et on a peut-être un travail de nettoyage à mener côté OSM du coup ?

**Comment by PanierAvide** [comment]
Les champs de contribution sont ajoutés. Je vais faire un peu de ménage côté OSM.

**Comment by overflorian** [comment]
ok, j'étais en train de regarder vite fait, et la page https://wiki.openstreetmap.org/wiki/FR:Tag:shop%3Dchemist n'est pas très explicite. A vrai dire, à ce stade, je ne sais pas comment mapper une parapharmacie. Je pense qu'un débat s'impose sur Talk-fr.

**Comment by Cybereric** [comment]
Je ne comprends pas le fonctionnement pour le gel et les masques.
Si on sélectionne un choix ce n'est pas mémorisé  à la réouverture du POI ou en revenant sur le site

Le site https://outrouverdugel.com utilise ce principe
Cela marche : si on clique sur une des icônes le choix est mémorisé

**Comment by PanierAvide** [comment]
Pour moi la définition est assez claire, c'est juste que c'est un joyeux vrac côté OSM. Je viens de corriger une centaine de points. Le wiki mériterait de clarifier la distinction entre salon de beauté, parfumerie, magasin de produits de beauté et droguerie/parapharmacie.

**Comment by PanierAvide** [comment]
@Cybereric on a le délai d'une heure qui s'applique, et ce n'est pas pris en compte dans le cache pour l'instant. Je fais un ticket dédié.

**Comment by PanierAvide** [comment]
Je ferme le ticket parapharmacie, on affiche les champs, c'est stocké en cache désormais.
