### ISSUE TITLE
Dans le menu, alimentation ne comprend pas les magasins à la ferme

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#61]
Un exemple ici: https://www.caresteouvert.fr/@43.525632,-1.375211,16.97/place/n6472153676

Je n'arrive pas à le désactiver

je ne sais pas si il est ouvert mais bientôt.

**Comment by francois2metz** [comment]
Merci de l'avoir signalé. C'est corrigé dans quelques minutes.

**Comment by vinber** [comment]
Trop fort, merci
