### ISSUE TITLE
Store in cache gel/masks contributions

### ISSUE THREAD

**Issue by PanierAvide** [osmontrouge/caresteouvert#610]
**Describe the bug**
When contributing to add info about gel/masks, if you click again on POI, info is not visible.

**Expected behavior**
Info is directly visible like other contributions.

**Additional context**
This should be put in local storage like status during 1h.

**Comment by francois2metz** [comment]
We may update the `poi_osm` once a new contribution is done.

**Comment by PanierAvide** [comment]
Sure, it allows a faster display for other users, but still need to be stored in cache for direct display to user.

**Comment by francois2metz** [comment]
The status is already updated once a contribution is done.

**Comment by PanierAvide** [comment]
Implemented. By updated you mean client-side ?
