### ISSUE TITLE
Aspect des boutons "Livraison" et "Vente à emporter"

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#611]
Les boutons **"Livraison"** et **"Vente à emporter"** ne se distinguent pas vraiment des autres boutons.
Pourtant à mons avis ils devraient car il ne s'agit pas de commerces à proprement parler mais de **modes de distribution**.

Il serait donc intéressant qu'il y ait un **séparateur** entre ces boutons et les autres. 
Ils pourraient aussi être **colorés** pour augmenter leur **visibilité**.

**Exemple :**       

![boutons](https://user-images.githubusercontent.com/7645549/80621598-d0495780-8a47-11ea-9b19-8836536fc432.png)

**Comment by PanierAvide** [comment]
Voir aussi #595

**Comment by Cybereric** [comment]
Et bien sûr les boutons sélectionnés peuvent rester en bleu 

![boutons2](https://user-images.githubusercontent.com/7645549/80624089-7a76ae80-8a4b-11ea-9778-ce0d142aca54.png)
