### ISSUE TITLE
Never liked that the project has "stays" in the domain name and title... And now?

### ISSUE THREAD

**Issue by sfkeller** [osmontrouge/caresteouvert#616]
I never liked that this nice project has "stays" in the domain name and title - and now, soon in many countries the lockdown will be loosened and business will pick up again. 

So what about at least adjust the tagline of "Places that remain open during lockdown"
to ...

EN: "Places that remain or re-open during lockdown"
FR: "Les lieux ouverts durant (à nouveaux apres) le confinement"
DE: "Alle Geschäfte, die weiterhin/wieder geöffnet sind"

or similar...?

**Comment by francois2metz** [comment]
That's a nice suggestion! Thanks for it. We need to think about it I guess.

**Comment by overflorian** [comment]
my english friend confirmed me that "stays" doesn't make a lot of sense in english so I guess we should change the wording accordingly.

**Comment by Bibi56** [comment]
`FR: "Lieux ouverts durant la pandémie"`
Comme ça, ça reste valable plus longtemps.
`EN: "Places open during the pandemic"`
`DE: "Geschäfte die während der Pandemie geöffnet sind"`
Alle : pourquoi pas. Mais il faut assumer. @sfkeller just do it :-).

**Comment by sfkeller** [comment]
> FR: "Lieux ouverts durant la pandémie"
> Comme ça, ça reste valable plus longtemps.

Je crains que non. Essaye de tois mettre dans la situation de ceux qui rouvrent (!) pendant et après la pandémie. 

> pourquoi pas. Mais il faut assumer. @sfkeller just do it :-).

Je ne comprends pas. En tout cas, il y a d'autres endroits où la nouvelle perspective de réouverture afflue. Voir par exemple https://www.bleibtoffen.ch/@47.411400,8.967291,19.90/place/n3949299948

> "Lieu ouvert durant le confinement avec des horaires adaptés"

Par exemple, il serait préférable d'être appelé 
> "Lieu (ré-)ouvert pendant ou après le confinement avec des horaires adaptés"

**Comment by Bibi56** [comment]
> Je crains que non. Essaye de tois mettre dans la situation de ceux qui rouvrent (!) pendant et après la pandémie.

Pour après non, mais pendant si. Et après, on n'a plus besoin des :covid19, or l'appli a pour but d'indiquer les lieux ouverts pendant la pandémie.

> Je ne comprends pas.
Je fais référence à "Alle", même si les Allemands ont en moyenne une très bonne carte, affirmer que tous les magasins d'Allemagne (Autriche et Suisse aussi) seront sur la carte et à jour, c'est assez audacieux d'autant que comme tu dis les status évoluent.

> "Lieu (ré-)ouvert pendant ou après le confinement avec des horaires adaptés"
En suisse peut-être, en français non.
"Ré-" n'apporte rien. Que le magasin soit resté ouvert ou pas, avec des horaires adaptés ou pas, on s'en contrefiche. Que les horaires soient actuellement adaptés ou pas, si (pour savoir si ce sont les horaires "connus" ou pas).

On peut mettre "Lieu ouvert pendant la pandémie" pour que ça reste valable après le déconfinement.
