### ISSUE TITLE
Ajouter l'option "dispo masque" aux bureaux de tabac

### ISSUE THREAD

**Issue by MediAtta** [osmontrouge/caresteouvert#617]
D'après les médias, les bureaux de tabacs sont autorisés à vendre des masques à partir du 30 avril. Pourriez-vous ajouter les boutons correspondant pour indiquer la disponibilité ?
Merci

**Comment by PanierAvide** [comment]
C'est implémenté via dc3dbf8, merci du retour :+1:  Ce sera en ligne d'ici quelques minutes
