### ISSUE TITLE
intégrer les tags contact:*

### ISSUE THREAD

**Issue by Kazing** [osmontrouge/caresteouvert#62]
Bonsoir,

Il me semble que le schéma contact:* (pour les n° de téléphone, site web...) n'est pas pris en compte.

Exemple ici où le site & le téléphone (indiqué avec contact:website & contact:phone), ne s'affichent pas : 
* https://www.openstreetmap.org/node/5325754299
* https://www.caresteouvert.fr/@50.626799,3.047820,18.57/place/n5325754299

Ce schéma n'est pas majoritaire mais il est très utilisé :  
https://taginfo.openstreetmap.org/compare/contact:website/website/contact:phone/phone

Cela me semble utile de prendre en charge ces tags.

**Comment by francois2metz** [comment]
Bien vu. Fait dans 13ed167a5eb33d237569f001dc419235c28485ea. Ca arrive en prod dans quelques minutes.
