### ISSUE TITLE
How to handle end of lockdown? (Switzerland)

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#621]
In Switzerland, the lockdown will end on 11th May 2020 and almost everything will open again.

How do we handle this case? Does it make sense to bulk-delete the ` :covid19` tags in OSM?

Source (en): https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/massnahmen-des-bundes.html#681391707

Downstream: https://github.com/bleibtoffen/bleibtoffen/issues/98

**Comment by PanierAvide** [comment]
Maybe we can wait a bit before deleting any `:covid19` tag. If lockdown is done and no more restrictions are taking place there, maybe we can display some popup message to make people use OSM ?

**Comment by caugner** [comment]
> Maybe we can wait a bit before deleting any `:covid19` tag.

That makes sense.

> If lockdown is done and no more restrictions are taking place there, maybe we can display some popup message to make people use OSM ?

I think the map could still be useful, as there is no other OSM POI map as good as CRO. 

Would it be possible to show all places in Switzerland as green (or grey) from May 11th and disable the report feature with a message?

On the other hand, it could be useful to have a simple yes/no question to whether this place is open again, because some places may stay closed permanently due to financial reasons.

**Comment by overflorian** [comment]
> Maybe we can wait a bit before deleting any :covid19 tag.

+1
I'm sure that QA tools will love to have Covid-related opening_hours data to improve opening_hours data.

> I think the map could still be useful, as there is no other OSM POI map as good as CRO.

+1
I think the reopening will be very progressive in France and that CRO will remain usefull for some extra weeks, maybe even months. That said, the situation may be different for Switzerland. 

> On the other hand, it could be useful to have a simple yes/no question to whether this place is open again, because some places may stay closed permanently due to financial reasons.

+1

**Comment by chnuessli** [comment]
Is there a way to show all businesses open in switzerland? What do we have to do as preparation for next week?

**Comment by PanierAvide** [comment]
We still lack some icons to cover all shops (see #558, you might help if you want), once done they will appear on the map.

**Comment by caugner** [comment]
> We still lack some icons to cover all shops (see #558, you might help if you want), once done they will appear on the map.

For most remaining shops, OpenStreetMap.org doesn't have a dedicated icon and instead just shows a thick dot. Would it be an option to use a similar fallback icon for those shops?

PS: Since there is a high number of shops, it might be worth reusing Nominatim's shop types systematically instead of duplicating it manually: https://github.com/openstreetmap/openstreetmap-website/blob/6f342c761672fca5149fd3b6422c90f2e22afd75/config/locales/en.yml#L879-L964

**Comment by PanierAvide** [comment]
I think we have solved this issue by adding shops icons, so I'm closing it.
