### ISSUE TITLE
Volet latéral : bouton d'accès aux filtres, boutons "Livraison" et "Vente à emporter", réorganisation des boutons

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#627]
Bonjour,

Quelques réflexions sur le volet latéral et les boutons.

**Bouton et liste des filtres**
=====================================
Je constate l'arrivée du "big bouton" de menu ;-)

Alors franchement je trouve que ce n'est pas terrible
- certains boutons sont "coupés"
- on n'a plus de vue d'ensemble de ce que contient la catégorie

**Exemple 1**
![0alim](https://user-images.githubusercontent.com/7645549/80716755-53c28180-8af8-11ea-9e57-a5d50d60ad32.png)

**Exemple 2**
![0sante](https://user-images.githubusercontent.com/7645549/80716767-57560880-8af8-11ea-993d-6fb7478df432.png)

Je crois qu'il serait judicieux de **faire apparaître deux ou trois "lignes" de boutons**
Pour des catégories où il y a très peu de filtres du genre "Tabac & alcool" (seulement 3 boutons) il faudrait tout afficher d'emblée 

Ne vaudrait-il pas mieux avoir ceci ?

![1alim](https://user-images.githubusercontent.com/7645549/80717099-bca9f980-8af8-11ea-844a-cce589efdf14.png)

![1tabac](https://user-images.githubusercontent.com/7645549/80717121-c3d10780-8af8-11ea-929d-a286095788ad.png)

**Boutons "Livraison" et "Vente à emporter"**
=====================================
La séparation des **boutons "Livraison" et "Vente à emporter"** avec les autres boutons par un trait est un minimum.
Si la couleur (comme je l'avais suggéré) ne va pas alors il faut trouver autre chose pour les démarquer visuellement.
Par exemple la forme (rectangle) une bordure ,...
Voir :

![boutons carres](https://user-images.githubusercontent.com/7645549/80717465-478af400-8af9-11ea-9f65-b8f6edd13c5e.png)

![boutons carres 2](https://user-images.githubusercontent.com/7645549/80717504-4f4a9880-8af9-11ea-89b6-60908f720f7d.png)

Réorganisation des boutons de filtres
=====================================
Je trouve que le gros problème des boutons est la façon dont ils s'affichent dans le volet.
Ils sont très "dispersés"
Cela fait apparaître comme des "trous"
J'ai mis un moment à m'apercevoir que c'était classé par ordre alphabétique. 
Est-ce bien indispensable ?  Il n' y a pas des centaines de boutons.
Je pense qu'il sera plus logique que **les boutons se regroupent automatiquement en fonction de la taille de chacun** afin de combler ces "trous"
Est-ce possible ?

Voilà ce que ça donne :

![2reorganisation boutiques](https://user-images.githubusercontent.com/7645549/80717717-7a34ec80-8af9-11ea-87ca-7b46628c749c.png)

![2reorganisation resto](https://user-images.githubusercontent.com/7645549/80717733-802acd80-8af9-11ea-9adf-c1773f56db96.png)

**Comment by overflorian** [comment]
Merci pour cette proposition très détaillée !
Je partage le constat des 2 problémes : une mauvaise présentation de l'information pour les catégories et une séparation nécessaire des filtres autres que des POIs.

1. Présentation des catégories.
Même si j'aime beaucoup la proposition d'afficher toutes les catégories, je pense qu'il serait plus efficace de les passer en onglets cf. https://material.io/components/tabs
La raison principale est une intuition : la majorité des personnes veulent afficher un nombre réduit de catégories. Si 3/4 catégories apparaissent à l'écran et que les autres restent accessibles facilement (et plus facilement qu'actuellement), on a tout gagné.

2. Séparer l'affichage des filtres : j'ai fait 2 propositions distinctes dans ce sens : https://github.com/osmontrouge/caresteouvert/issues/595

**Comment by Cybereric** [comment]
**Présentation des catégories.**

Ma proposition venait surtout du fait que le problème actuel est la "coupure" des boutons lorsqu'on consulte le site sur ordinateur.

Donc si on oublie la présentation de tous les boutons, serait-il possible de corriger ça ? 

Sur smartphone (site ou application) les boutons ne sont pas coupés. 

**Sur smartphone  avec l'application**  **|**   **Affichage OK**

![Alimentation smartphone appli](https://user-images.githubusercontent.com/7645549/80921427-9d200480-8d76-11ea-9638-cd1bb8966612.png)

**Sur smartphone sur le site web**       **|**       **Affichage OK**

![Alimentation smartphone site web](https://user-images.githubusercontent.com/7645549/80921449-b9bc3c80-8d76-11ea-8567-73a252facdd1.png)

**Sur ordinateur**    **|**    **"Coupure" des boutons**

![Alimentation Ordinateur OK](https://user-images.githubusercontent.com/7645549/80921464-d2c4ed80-8d76-11ea-8858-2b3cd65b59f4.png)

**Comment by Cybereric** [comment]
Pour répondre au reste

>  Présentation des catégories.
>     Même si j'aime beaucoup la proposition d'afficher toutes les catégories, je pense qu'il serait plus efficace de les passer en onglets cf. https://material.io/components/tabs

Comme ça ?
![tables](https://user-images.githubusercontent.com/7645549/80922306-795fbd00-8d7c-11ea-908a-c684dbf0f172.png)
Pourquoi pas ?

> La raison principale est une intuition : la majorité des personnes veulent afficher un nombre réduit de catégories. 

Il faudrait faire un test puis un sondage ;-)

> Séparer l'affichage des filtres : j'ai fait 2 propositions distinctes dans ce sens : #595


Alors je ne comprends pas trop #595  Je n'arrive pas à imaginer avec les exemples fournis.

Quant à la "séparation" que je préconisais elle est visuelle et pas physique
Je pense que les filtres doivent rester "proches" :
 - Filtrage thématique  (ex Alimentation) ou  "catégorie" plus précise 
-  Mode distribution

![choix filtres smartphone 2 ok](https://user-images.githubusercontent.com/7645549/80922663-e5dbbb80-8d7e-11ea-8b9e-1d4c85a09171.png)

**Comment by francois2metz** [comment]
L'espace avant les catégories sur desktop était un comportement bizarre de vuetify. J'ai corrigé cela.

J'ai aussi changé la forme des boutons livraison/a emporter. Je ne suis pas vraiment fan de cela, mais je tente. Cela pourra encore changer.

Quand à l'utilisation  de l'espace pour les sous catégories, on pourrait améliorer certainement des choses au prix de nombreux efforts. Si une PR améliore l'espace utilisé, je la prend.
