### ISSUE TITLE
Request for Irish OSM Community to join service

### ISSUE THREAD

**Issue by tadcan** [osmontrouge/caresteouvert#628]
The OSM community has an active userbase on ready to start adding business information for the island of Ireland. Members have already begun to look at the mapping requirements and are ready to start work.  We also have a local body to work through, you can contact us through the board@openstreetmap.ie and me at tadeusz.cantwell@openstreetmap.ie

Please read https://github.com/osmontrouge/caresteouvert/wiki/Expand-%22%C3%87a-reste-ouvert%22-to-another-country first.

Please check the following requirements:

- [ ] You are a team of at least 2 people experienced with OpenStreetMap
- [ ] Translate the app via transifex with your country languages
- [ ] Translate some content of the blog to help newcomers (how to create a new shop, the about page, ...)
- [ ] Start gathering data about chain stores open or closed nation wide, and legal opening rules in https://github.com/PanierAvide/Covid_enseignes/
- [ ] Once everything has been done and the data have been loaded, you should be busy getting media coverage. So the map will have a lot of contribution and be quickly useful.

Others questions:

- if you want a localized domain name, please tell us which one: 
- Each lockdown is different, what shops are open or closed in your country? What should be done in the category list?

**Comment by gendy54** [comment]
@overflorian French contact (Twitter) transmitted via Facebook

**Comment by vdct** [comment]
Hi @tadcan 
Welcome on board :)
We need for our backend POI database a polygon or set of polygons to manage POIs of each country according to the legal rules which apply in the country. Here is my request : can you provide me with a OSM relation number (or list of numbers) that best describe the Island of Ireland for our purpose ?
Thanks

**Comment by Bibi56** [comment]
@vdct:
https://www.openstreetmap.org/relation/62273 (Republic of Ireland)
https://www.openstreetmap.org/relation/156393 (Northern part, belongs to UK, so rules are probably different, but I think it's important to be able to display both on the same URL as the community act united). @PanierAvide a good test case for the management of France after the 11th of May.

@tadcan apparently some people use [umap](https://umap.openstreetmap.fr/fr/map/sligo-coronavirus-resources_436572#10/54.2171/-8.6765), probably a resource to look at:

**Comment by vdct** [comment]
Sure @Bibi56 I am aware of such relations. I don't want to _guess_ which one(s) fit for the need. That's the purpose of my question to @tadcan 🙂

**Comment by tadcan** [comment]
OSM Ireland and OSMUK have had an agreement from back when we were both mailing lists, that Northern Ireland and is a shared space where users can be a member of either or none of our organisations. When we joined the OSMF as a company, and it was announced on the main mailinglist members from OSMUK supported the position. The protocol is that I inform them it's happening and address any concerns they have, arranging an appropriate solution where needed.

**Comment by HeikkiVesanto** [comment]
@vdct:

We have confirmed with OSM UK that they no objections for us to proceed with an implementation for the Island of Ireland, so both outlines:

https://www.openstreetmap.org/relation/62273
https://www.openstreetmap.org/relation/156393 

We have also acquired two domains for this use:
StayingOpen.ie and TaimidOscailte.ie (which is Irish for "we are open").

**Comment by PanierAvide** [comment]
For domain names, you should either CNAME to caresteouvert.fr or add A entry to 5.104.101.30

**Comment by vdct** [comment]
Hi @HeikkiVesanto 
Thank you for the relation ids, that is perfect :+1:

**Comment by HeikkiVesanto** [comment]
Hi @PanierAvide 

Thanks. I have set up an ALIAS for StayingOpen.ie and TaimidOscailte.ie to caresteouvert.fr. Let me know if an A record for the IP is better.

The www. redirect to the base domain. Looks to be working.

**Comment by PanierAvide** [comment]
@HeikkiVesanto thanks, ALIAS seems to be working as expected, so no need for A record.

**Comment by tadcan** [comment]
Great news @PanierAvide. We also need to setup a translation for Irish translation since it is an official language.

**Comment by PanierAvide** [comment]
Just edited list of languages in Transifex, you may be able to start translating ;-)

Front-end : https://www.transifex.com/openlevelup/ca-reste-ouvert/languages/

Back-end : https://www.transifex.com/openlevelup/ca-reste-ouvert-backend/languages/

**Comment by PanierAvide** [comment]
Did you made some progress on your side ? As today, we have :
- Domain names working
- Country limits in database
- 80% of Irish translation

And we miss before opening :
- Complete Irish translation ?
- Add information about brand/legal opening status @ https://github.com/PanierAvide/Covid_enseignes/
- Activate in our config.json file Ireland to make POI appear on map

**Comment by HeikkiVesanto** [comment]
I have created a pull request for the legal rules.

https://github.com/PanierAvide/Covid_enseignes/pull/177

Will see what larger chains we want to include. Irish translation should be done shortly. But we are happy to go live with English first.

**Comment by HeikkiVesanto** [comment]
Rules update for Irish chain stores, and Irish translation completed.

**Comment by HeikkiVesanto** [comment]
Hi @PanierAvide what do we still have left to do for going live?

**Comment by PanierAvide** [comment]
I think it's all good, I enabled database so in ~1 hour POI should show up on map.

**Comment by HeikkiVesanto** [comment]
Excellent. We will start populating the businesses.

**Comment by donalhunt** [comment]
Two minor issues identified:

- [Translation correction for Irish language version](https://github.com/osmontrouge/caresteouvert/pull/804)
- [Irish language version defaulting to English](https://github.com/osmontrouge/caresteouvert/issues/805)
