### ISSUE TITLE
NoteReview alors que correction effectuée

### ISSUE THREAD

**Issue by gendy54** [osmontrouge/caresteouvert#63]
Hello,

Je suis passé sur une note, mais le compte générique de caresteouvert a crée une modif en base de sorte qu'il n'y avait rien à faire.
J'ai eu ce truc plusieurs fois. Un genre de note faux-positif.

Je laisse la note en place

![image](https://user-images.githubusercontent.com/10323517/77835553-29268700-714e-11ea-81b8-35e717374efa.png)

![image](https://user-images.githubusercontent.com/10323517/77835560-3e031a80-714e-11ea-8713-c00ef78f3887.png)

Changeset:
https://www.openstreetmap.org/changeset/82763009

**Comment by PanierAvide** [comment]
Normalement le fonctionnement est le suivant :
* Si le champ de détails est rempli, on créé une note
* Si pas de détails, on modifie directement

C'est possible que la personne ayant contribué au départ ait envoyé deux fois sa modif, une fois sans détails et une fois avec ? Et comme les horaires n'ont pas changé et qu'elles étaient renseignées, ça expliquerait le doublon et pourquoi il n'y a rien à faire.

**Comment by GeorgeKaplan** [comment]
Ce n'est pas un faux positif, au contraire. Par défaut, la modification automatique indique opneing_hours:covid19=same, que le champ opening_hours existe ou pas ou que la personne ait indiqué ou pas les horaires temporaires. On a souvent plus d'informations dans le commentaire que dans l'ajout auto de opening_hours:covid19=same. J'ai traité des dizaines de signalements par NoteReview, j'ai eu de nombreux cas comme ça.
Ici cet exemple est l'exception, cette note est effectivement inutile.

**Comment by PanierAvide** [comment]
En sachant qu'on a mis en ligne une nouvelle version du formulaire, qui suit le parcours suivant :
* Le commerce est-il ouvert : oui / non
* Si ouvert, quelles sont ses horaires d'ouvertures ? Est-ce que ce sont les mêmes que d'habitude ?
* Ajoutez plus de détails : champ texte libre

Toujours dans le même principe : si des détails en texte libre sont saisis, on créé une note. On ne peut pas juger de la nature du texte automatiquement, mieux vaut que ce soit un être humain qui l'interprète. Si le champ détail reste vide, on peut renseigner automatiquement désormais les horaires d'ouverture dans OSM, et donc apporter davantage d'information quand le contributeur la connaît.

**Comment by PanierAvide** [comment]
Pas de nouvelles, je ferme le ticket
