### ISSUE TITLE
Intégration données Grand Chambéry

### ISSUE THREAD

**Issue by Bibi56** [osmontrouge/caresteouvert#630]
**Is your feature request related to a problem? Please describe.**
Aucune frustration, juste une source de données en ODbL

**Describe the solution you'd like**
https://www.data.gouv.fr/fr/datasets/commercants-ouverts-pendant-le-confinement/
Ou encore :
https://donnees.grandchambery.fr/explore/dataset/ouvertureboutiqueschambery-tableaujulie3xlsx-feuil1/information/

**Describe alternatives you've considered**

- Avoir la possibilité d'avoir un "map compare" entre les cartes caresteouvert et ici https://donnees.grandchambery.fr/explore/dataset/ouvertureboutiqueschambery-tableaujulie3xlsx-feuil1/map/?location=18,45.61292,5.88821&basemap=jawg.streets pourrait faciliter l'intégration des données.

`<iframe src="https://donnees.grandchambery.fr/explore/embed/dataset/ouvertureboutiqueschambery-tableaujulie3xlsx-feuil1/map/?location=18,45.61292,5.88821&basemap=jawg.streets&static=false&datasetcard=false&scrollWheelZoom=false" width="400" height="300" frameborder="0"></iframe>`

- Contacter le producteur de données pour qu'il fasse le boulot^^

**Comment by francois2metz** [comment]
Personne n'a semble t'il regarder pour intégrer cela. Je ferme.
