### ISSUE TITLE
Horaires jour férié

### ISSUE THREAD

**Issue by lmagreault** [osmontrouge/caresteouvert#631]
J'ai constaté deux problèmes d'affichage sur un commerce avec opening_hours PH off pour signaler qu'il est fermé les jours fériés :
- Libellé "fermé jusqu'à demain 00:00" au lieu de "fermé jusqu'à samedi 9h30"
- "Tag der Arbeit" au lieu de "Fête du travail"

Lien vers le commerce  pour exemple :
https://www.caresteouvert.fr/@46.586535,5.693953,16.80/place/n4977420720
![Sans titre](https://user-images.githubusercontent.com/677071/80748845-e0376900-8b25-11ea-88bf-16435b362b30.png)

**Comment by PanierAvide** [comment]
Corrigé, merci du retour.
