### ISSUE TITLE
Unselect a POI when clicking on the map

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#632]
Current behaviour: when a POI is selected (and its window open) a click on the map (not on any POI) does nothing.
Expected behaviour: this click unselect the POI and close the window.

This behaviour seems pretty common among the other map apps.
I just tested all the apps I found on my smartphone: Google Maps, Vespucci, Maps.Me, City Mapper, RATP, Street Complete, City Scoot = 100% implemented this.

**Comment by francois2metz** [comment]
I see that our behavior is different. The question is: what is the problem solved when we click on the map and the currently selected POI is then unselected?

**Comment by PanierAvide** [comment]
Maybe getting rid more easily of sidebar ?

**Comment by francois2metz** [comment]
No update. Closing
