### ISSUE TITLE
Display wheelchair status in details

### ISSUE THREAD

**Issue by FlorentRICHARD44** [osmontrouge/caresteouvert#636]
It could be good to display the wheelchair status of the place  with an icon in the details:
https://wiki.openstreetmap.org/wiki/Key:wheelchair

It can permits to somebody to don't go to a shop if he/she can or can't access it due to handicap

If tag wheelchair is not set in OSM, display this icon with interrogation point, and allow permit to user to add this tag as other details.

In addition, add a filter to display only place accessible with wheelchair.

**Comment by PanierAvide** [comment]
Thanks for this feedback.

For display wheelchair info when set, I totally agree with it.

For asking wheelchair info in contribution form, I'm not sure, as this is quite technical and no propre survey could lead to wrong info in OSM.

**Comment by PanierAvide** [comment]
This is integrated, so if a shop has wheelchair=yes/limited access, a label is shown on right sidebar. This will be visible on website in a few minutes. Thanks for feedback :+1:
