### ISSUE TITLE
Add healthcare in health :)

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#637]
**Describe the bug**
https://www.caresteouvert.fr/@44.767434,-0.579872,16.43/place/n7282919238

displays in Others https://www.caresteouvert.fr/other@44.767434,-0.579872,16.43/place/n7282919238

better in health.

**Expected behavior**

Display  https://www.caresteouvert.fr/@44.767434,-0.579872,16.43/place/n7282919238

in Health

**Comment by PanierAvide** [comment]
This is related to #12 

I think we can at least show proper icon when an `healthcare=*` POI shows up, even if we do not display all of them as now.

**Comment by PanierAvide** [comment]
Technically that was already the case, just not for `laboratory`. So I added it to make it categorized, will appear at next DB update in ~1h. Furthermore, laboratories might have a central role in a near future if they offer tests, so they might be having their own subcategory if necessary.

**Comment by vinber** [comment]
thanks
