### ISSUE TITLE
same ne veut pas (forcément) dire ouvert

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#64]
Cas d'un [supermarché en travaux](https://www.openstreetmap.org/way/123009677) :

clé | valeur
-- | --
opening_hours | off "En travaux"
opening_hours:covid19 | same

Ça reste ouvert affiche ["Lieu ouvert durant le confinement"](https://www.caresteouvert.fr/@46.577966,5.746574,17.80/place/w123009677) 😉 

Voir aussi #39

**Comment by Bibi56** [comment]
Là tu mets off. Ce n'est pas same car il n'y a plus de travaux ;-)

**Comment by PanierAvide** [comment]
Vous êtes créatif, ça fait plaisir :smile: c'est mieux pris en compte désormais (voir 6f9b11d), ça sera actif d'ici ~1h.

**Comment by pyrog** [comment]
Nickel, merci 😄
