### ISSUE TITLE
Permanent closure of the store

### ISSUE THREAD

**Issue by gendy54** [osmontrouge/caresteouvert#640]
creation of a note or a tag for the contributors: definitive closure of the business

Il est encore un peu tôt, mais il faut malheureusement y penser.
Dans la perspective où certains commerces fassent faillite et dans l'optique de profiter d'effet levier de CRO, je pense qu'il peut être utile de prévoir la création d'une note ou d'un tag spécifique pour désigner les commerces qui ont définitivement baissé le rideau.
Je pense que la note est plus appropriée et permettra de ne pas faire de manip hasardeuse.

**Comment by PanierAvide** [comment]
C'est sûr que malheureusement des commerces feront faillite. On pourrait demander directement lors de la première partie du formulaire : Ce lieu est-il ouvert ? Oui / Non / Fermé définitivement. @overflorian un avis ?

**Comment by overflorian** [comment]
Je pense que le sujet est important mais qu'il faudrait éviter de surcharger le formulaire principal avec ça. Je pencherai plutôt pour un bouton dédié sur le pop-up "rajouter des infos sur ce lieu"

**Comment by overflorian** [comment]
J'ai eu le temps de dormir sur le sujet et voici ma proposition un peu plus détaillée.
En revoyant le formulaire, je ne pense finalement pas que ce serait surcharger l'interface de rajouter un bouton dédié. 
Use case : l'utilisateur clique sur NON à la question "Ce lieu reste-il ouvert pendant le confinement ?"
A ce moment là il me paraît opportun de rajouter la possibilité de mentionner que le lieu est définitivement fermé.

Ma proposition : ajouter un switch https://material.io/components/selection-controls#switches et qui fait apparaître un nouveau wording :

> Ce lieu a définitivement fermé ses portes. Qu'y a-t-il à ce jour à la place ? Donnez autant de détails que possible.
> _Exemple : bâtiment vide ou en travaux, nouveau commerce ..._

![image](https://user-images.githubusercontent.com/11553211/80908135-b6489700-8d1d-11ea-97a3-f7f6ec4f6ac0.png)

**Comment by overflorian** [comment]
Cool implémentation, merci. Du coup j'ai un bug mineur d'affichage de mon côté : le halo de la case sélectionné n'apparaît pas entier.
On est sur du fignolage...

**Comment by overflorian** [comment]
Le bug en question :

![Screenshot_20200509-183951](https://user-images.githubusercontent.com/11553211/81479671-e19f1a80-9224-11ea-8468-0a03f5201bd2.jpg)

**Comment by PanierAvide** [comment]
J'ai vu ça, mais je sais pas trop pourquoi. Si @francois2metz peut m'éclairer là-dessus comme je suis pas expert Vue.js :sweat_smile:

**Comment by PanierAvide** [comment]
Je sais pas trop pourquoi ça fait ça, et ça me semble suffisamment accessoire pour ne pas y passer des heures. Je ferme le ticket.

**Comment by overflorian** [comment]
ça me va, merci

**Comment by gendy54** [comment]
Tout à fait
