### ISSUE TITLE
Display phone:covid19

### ISSUE THREAD

**Issue by Bibi56** [osmontrouge/caresteouvert#641]
**Is your feature request related to a problem? Please describe.**
Some phone numbers are temporary, typically mobile numbers for reservation and/or orders. They are not intended for normal use and therefore not intended to be put in phone or mobile tag.

**Describe the solution you'd like**
Display the specific phone number.
https://www.caresteouvert.fr/@47.789385,-3.486717,17.02/place/n7398563042
BTW, some refer to a regional phone number not specific to the POI:
https://www.caresteouvert.fr/@47.797569,-3.477844,16.27/place/w70437860

**Describe alternatives you've considered**
Moving the data to mobile or phone is not always an option.

**Additional context**
Example: https://www.caresteouvert.fr/@47.789385,-3.486717,17.02/place/n7398563042

**Comment by PanierAvide** [comment]
This is integrated and will appear on website in a few minutes, thanks for feedback :+1:
