### ISSUE TITLE
Mettre en cohérence les données d'ouverture et de présence de gel / masque

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#643]
Aujourd'hui, les utilisateurs peuvent indiquer pour certains POIs l'ouverture, la vente de gel et de masque.
Afin d'éviter une situation où l'on indique la vente de gel / masque sur un lieu **fermé** au public, nous devrions mettre en place un mécanisme de détection d'erreur entre ces différentes données.

**Comment by PanierAvide** [comment]
Donc l'idée est plutôt d'avoir un avertissement / message dans l'interface ou lors de la contribution ? Ou sinon on peut juste cacher les champs masque/gel si le POI est noté comme fermé.

**Comment by overflorian** [comment]
> Ou sinon on peut juste cacher les champs masque/gel si le POI est noté comme fermé.

C'est peut être le plus cohérent oui.

**Comment by PanierAvide** [comment]
Intégré, ce sera en ligne dans quelques minutes.
