### ISSUE TITLE
Toujours les mêmes POIs listés avec l'application « Ça reste ouvert » sur smartphone

### ISSUE THREAD

**Issue by Cybereric** [osmontrouge/caresteouvert#644]
**Description :**
J'ai un truc bizarre avec l'application « Ça reste ouvert » sur smartphone.
Les filtres fonctionnent correctement : on voit bien plus ou moins de POIs en fonction des choix effectués.
Le truc bizarre c'est qu'**on ne voit pas les POIs correspondants au filtre** dans la liste sous les boutons des filtres.
Et ce qu'on ait sélectionné juste la catégorie mère (Alimentation, Santé, ...) ou un type de POI.
Plus exactement **on voit quelques POIs mais ils ne "correspondent" pas et ce sont toujours les mêmes !**
Il apparaît que **tous ces POIs sont situés en Andorre !**

**Tests :** 
J'ai vidé le cache et effacé les données de l'application.
Je l'ai désinstallée puis réinstallée.
C'est toujours pareil : j'ai toujours ces mêmes POIs.
Toujours sur smartphone, si je teste « Ça reste ouvert » avec un navigateur web pas de soucis ça fonctionne.

**Contexte logiciel :**
Application : "Ça reste ouvert" 1.0.4
Système : Android 6.01

**Copies d'écran :**

![pbme1](https://user-images.githubusercontent.com/7645549/80891129-4f49c480-8cc2-11ea-8c91-7e7421f0e949.png)
![pbme2](https://user-images.githubusercontent.com/7645549/80891132-5670d280-8cc2-11ea-8708-b9bf84aee559.png)
![pbme3](https://user-images.githubusercontent.com/7645549/80891134-5a9cf000-8cc2-11ea-9b54-c814d258b2be.png)
![pbme4](https://user-images.githubusercontent.com/7645549/80891135-5d97e080-8cc2-11ea-9963-23fc06120ad9.png)

**Comment by francois2metz** [comment]
On dirais un bug de webview. Si a un moyen de savoir quelle version du chrome ou de l'ancien navigateur est utilisé sur android 6, je suis preneur.

**Comment by Cybereric** [comment]
On fait comment ?

**Comment by PanierAvide** [comment]
On a prévenu l'équipe de développement de l'appli (cf https://github.com/osmontrouge/caresteouvert_android/ ) et ils vont regarder ça.

**Comment by francois2metz** [comment]
@Cybereric De ce que je vois de la doc: 
    Settings < Apps < Android System WebView and look at the version.

**Comment by ericafenyo** [comment]
Vous pouvez également obtenir la version du navigateur à partir de l'header "User-Agent". 
À partir d'Android 7, `Android System WebView` est désactivé par défaut en faveur de Chrome. 
https://support.google.com/nexus/forum/AAAANseOu18M5arThf0kag/?hl=en

De plus j'essaie de reproduire ce bug mais sans succès et comme je n'ai pas actuellement de Android 6 avec moi, ça va être difficile.

**Comment by Cybereric** [comment]
Android System WebView 55.0.2883.91

**Comment by ericafenyo** [comment]
@Cybereric Est-il possible de le mettre à jour stp? 
https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en

**Comment by Cybereric** [comment]
Via F-Droid et Aurora store (parce que je n'ai pas de compte Google) ça fonctionne :+1: 
Merci ;-)
