### ISSUE TITLE
L'icône osm-fuel apparait dans le panneau de droite mais pas sur la carte

### ISSUE THREAD

**Issue by pyrog** [osmontrouge/caresteouvert#65]
Exemple d'une [station service](https://www.caresteouvert.fr/@46.675332,5.523367,17.10/place/n4872777539).

<img width="449" alt="station service" src="https://user-images.githubusercontent.com/2158081/77843640-69622580-719f-11ea-8c77-b3113c0085a1.png">

**Comment by PanierAvide** [comment]
Corrigé, ça sera en ligne dans quelques minutes.

**Comment by pyrog** [comment]
C'est bon depuis un moment, merci 😄
