### ISSUE TITLE
Additional hygiene information (mask, hydroalcoolique gel): For more POIs and add 3rd option

### ISSUE THREAD

**Issue by georg-d** [osmontrouge/caresteouvert#651]
For a POI like a chemist, a question about additional hygiene information appears. 
1) Several other "untypical" shop types (even imbiss, florist etc.) do _currently_ sell these items but the question does not appear for them. As it's not an OSM tag, I can also not work around via JOSM. Suggestion: Offer these 2 questions for all POI types that appear.
2) For mask and for hydroalcoolique gel, users can currently only choose between "has" / "vorrätig" or "has no" / "ausverkauft". The latter one sounds like _when I was there, the shop did not have it in stock, but you can/shall try some days later_ - which makes no sens for a shop that is not just out of stock but does not sell these items at all. Hence, I'd suggest to add a 3rd option "not sold"/"nicht im Sortiment". Alternatively, e.g. because you'd stick with a DB column of type boolean, rename the GUI options such that they fit both variations, e.g. "currently or generally not" / "aktuell oder grundsätzlich nicht".

**Comment by PanierAvide** [comment]
Thanks for your feedback. Currently, we display gel/mask info based on our knowledge of situation in France. If it is different elsewhere, please give us a list of POIs where you have > 50% of chances to find gel or mask (both could be differenciated).

For answers, no technical issue to add a new kind of answer, but we want to keep the form as simple as possible. Difference between "there is none at the moment" and "they will never sell it" will be too subtle to display in a restricted space like there.

**Comment by georg-d** [comment]
> If it is different elsewhere, please give us a list of POIs where you have > 50% of chances to find gel or mask (both could be differenciated).

In Freiburg, the >50% chance does not apply to most POI types where gel/mask info is currently shown/asked, e.g. shop=supermarket (I estimate roughly 5% chance), shop=chemist (30%), amenity=vending_machine with vending=cigarettes (0%). Only amenity=pharmacy may reach 50-60%.

For masks, shop=medical_supply 30-50%, shop=tailor 30%, shop=fabric 30%, shop=clothes 10%, shop=outdoor 10-20%
For gel, shop=medical_supply 30%, shop=outdoor 10-20%, but like in most other shops, the vast majority of available gels are not certified against viruses but only bacteria, i.e. not reliably helping against Corona.

> For answers, no technical issue to add a new kind of answer, but we want to keep the form as simple as possible. Difference between "there is none at the moment" and "they will never sell it" will be too subtle to display in a restricted space like there.

OK.

**Comment by Cybereric** [comment]
Pourtant c'est une bonne idée je trouve.
Et il est possible il me semble de faire la différence entre "**_il n'y en a plus_**" et "_**pas de vente**_"
Cf ci-dessous

En tous cas **il faudrait réduire les boutons actuels beaucoup trop grands** (voir ceux du site _outrouverdugel_  ci-dessous)

**Les boutons actuels causent plusieurs problèmes**
J'ai rajouté des copies d'écran sur #615 

![comparaison gel masques taille boutons](https://user-images.githubusercontent.com/7645549/81282714-d947b380-905b-11ea-976a-0f6c79f125f6.png)

**Comment by overflorian** [comment]
I agree with @PanierAvide: I think we should keep only 2 buttons as adding an extra value would add confusion. I think we should keep in mind that these buttons are NOT in the main form where we can be very detailed but are quick buttons to use on the fly.

**Comment by PanierAvide** [comment]
I added mask/gel contribution form on more POIs as initially requested. It will be online in a few minutes. Thanks for your feedback :+1:

**Comment by georg-d** [comment]
@PanierAvide Thank you for adding them, works fine :) Today I observed that quite a lot of shoe shops/craftsmen also sell masks, e.g. 
shop=shoes e.g. https://www.openstreetmap.org/node/3903836866
craft=shoemaker https://www.openstreetmap.org/way/288583795
