### ISSUE TITLE
Missing category: money transfer & mobile money agents in CD

### ISSUE THREAD

**Issue by clairedelune** [osmontrouge/caresteouvert#655]
**Name**: money transfer & mobile money agents (to be added to a section called "Argent" also including banks and atm)

**Tagging**: amenity=money_transfer & amenity=mobile_money_agent

**Country**: DRC (CD)

**Example in OpenStreetMap**:
https://www.openstreetmap.org/node/6327282432 (display should include brand value)
https://www.openstreetmap.org/node/6327282430 (display should include network value)

**Example in "Ca reste ouvert"**: https://ezosala.org/@-4.323255,15.278694,20.57

**Icon**: These amenities are not yet displayed on OSM Carto but are very important especially during lockdown. Still looking for appropriate icons.

**Comment by clairedelune** [comment]
For money_transfer, I would suggest using this icon: https://github.com/hotosm/HDM-CartoCSS/blob/master/icons/poi/money_transfer.svg but it might need to be turned in black.

**Comment by PanierAvide** [comment]
This is integrated, and will be visible in ~1h. Note that all these features are in a single subcategory "Money", under "Services pratiques/amenity" category.

If you prefer a main category for money-related features in CD, please re-open the issue and let me know :wink:

**Comment by clairedelune** [comment]
Thank you !
And yes, please, we would like a main category for money-related features in CD.
It should be including the following amenities as subcategories: bank, atm, bureau_de_change, money_transfer and mobile_money_agent.

**Comment by PanierAvide** [comment]
Implemented with 0142f86, will be available in ~1h.
