### ISSUE TITLE
Gestion des amenity=atm

### ISSUE THREAD

**Issue by QuentinS33** [osmontrouge/caresteouvert#656]
Bonjour,
Ayant fait une petite mise à jour des banques dans ma ville, j'ai bien voulu dissocier l'établissement bancaire du distributeur automatique de billets.
En effet, il existe 3 cas rencontrés pendant le covid19
- Agences bancaires FERME + DAB à l'extérieur OUVERT
- Agences bancaires OUVERT + DAB à l'intérieur FERME + DAB à l'extérieur OUVERT (La Poste/La Banque Postale)
- Agences bancaires FERME + DAB à l'intérieur OUVERT

Dans le 1er cas, j'ai mis 2 POI en indiquant `opening_hours:covid19=off` pour l'agence et  pour le DAB `amenity=atm` + `opening_hours:covid19=24/7`. Actuellement, il n'y a aucun logo représentant le DAB, il s'affiche avec un "?" et est placé dans "Autres établissements". Un regroupement avec banque serait idéal en précisant qu'il s'agit d'un distributeur automatique de billets
Dans le 2ème cas, j'ai mis 2 POI en indiquant `opening_hours:covid19=open` pour La Poste avec un `atm=yes` et un autre POI avec `amenity=atm` + `opening_hours:covid19=24/7`
Pour le 3ème cas, je n'ai mis qu'un POI en `atm=yes` + `opening_hours:covid19=open`. Dans la plupart des cas, l'agence est fermé mais on peut accéder à l'intérieur pour retirer. A voir comment bien tagguer la clé "atm" car là je ne vois pas

**Comment by PanierAvide** [comment]
D'après le wiki, si les infos d'horaires d'ouverture du distributeur sont différentes de l'établissement "banque", c'est pertinent de représenter le distributeur via un point séparé (et mettre un `indoor=yes` ?), cf https://wiki.openstreetmap.org/wiki/Tag:amenity%3Datm

**Comment by PanierAvide** [comment]
J'ai ajouté la visualisation des distributeurs, regroupés dans une catégorie "Argent" dans "Services pratiques" avec les banques et prêteurs.
