### ISSUE TITLE
Intégrer les services essentiels aux routiers

### ISSUE THREAD

**Issue by krichtof** [osmontrouge/caresteouvert#66]
"Afin d’assurer la continuité du transport de marchandises, cruciale dans la gestion de la crise du Coronavirus, l’Etat s’emploie à maintenir l’ouverture des services essentiels aux conducteurs pour se reposer, se réapprovisionner en carburant, bénéficier de restauration à emporter et de sanitaires propres. Bison Futé met à disposition des transporteurs deux cartes pour référencer ces services"

https://www.bison-fute.gouv.fr/ouverture-des-aires-et-des-centres,11195.html

Je me dis que ces infos pourraient être pertinentes et auraient leur place sur caresteouvert

**Comment by PanierAvide** [comment]
Bien que ça aurait pu être intéressant, le sujet de l'intégration de ces données n'a pas trouvé d'écho. Je ferme donc le ticket.
