### ISSUE TITLE
Remove "Tabac et alcool" category in CD

### ISSUE THREAD

**Issue by clairedelune** [osmontrouge/caresteouvert#660]
As we currently don't have any shop=tobacco within lockdown area, we suggest the removal of the category "Tabac et alcool" in CD. "Alcool" could become a subcategory of "Alimentation" as there are few dedicated shops.

**Comment by PanierAvide** [comment]
This is integrated, filter should appear correctly in a few minutes and data will be updated accordingly in ~1h.
