### ISSUE TITLE
Missing category: Library

### ISSUE THREAD

**Issue by houtari** [osmontrouge/caresteouvert#667]
**Name**: Library

**Tagging**: amenity=library

**Country**: Finland

**Example in OpenStreetMap**: https://www.openstreetmap.org/node/1700615700

**Example in "Ca reste ouvert"**: https://www.caresteouvert.fr/@60.200836,24.935475,17.78

**Icon**: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/amenity/library.svg

**Comment by francois2metz** [comment]
@houtari In which category would you like this?

**Comment by houtari** [comment]
@francois2metz I would place it under Amenity as most other public services.
