### ISSUE TITLE
Note créée alors que le changement devrait être automatique

### ISSUE THREAD

**Issue by zorun** [osmontrouge/caresteouvert#67]
Il me semblait que depuis hier, les changements "simples" (pas de détails, juste ouvert/fermé) étaient générés directement dans OSM sans créer de note.

Pourtant j'ai ce groupe de 3 notes qui date d'aujourd'hui, et qui ne contiennent rien d'autre que "État: ouvert" :
https://www.openstreetmap.org/note/2139913#map=19/45.55560/5.07906&layers=N

**Comment by PanierAvide** [comment]
Toutes les nouvelles notes sont associées au compte `CaResteOuvert_visitor`. Celle-ci est anonyme, ce qui me fait penser que la personne doit avoir en cache dans son navigateur l'ancienne version du site web. Et comme avant c'est le client qui poussait les notes...

@francois2metz on a moyen de forcer l'invalidation du cache client ?

**Comment by francois2metz** [comment]
Si ils n'ont pas raffraichi la page c'est quasi impossible. Sinon en théorie ils devraient raffraichir le index.html et prendre les modifs.

**Comment by PanierAvide** [comment]
En tout cas la note ne vient pas de l'API : le format est légèrement différent dans la nouvelle version, et là c'est bien l'ancien format qu'on voit sur la note.

**Comment by francois2metz** [comment]
Il faudrait vérifier les headers HTTP qu'on envoie pour la page HTML pour être sur qu'on soit carré.

**Comment by PanierAvide** [comment]
Les en-têtes de réponse (idem HTML et JS) :
```
server: openresty
date: Sun, 29 Mar 2020 16:19:30 GMT
content-type: text/html; charset=UTF-8
content-length: 799
strict-transport-security: max-age=31536000
cache-control: public, max-age=0
last-modified: Sun, 29 Mar 2020 12:30:32 GMT
```

De ce que j'en comprends, on a bien indiqué de ne pas faire de cache sur la page, et le last modified semble coller.

**Comment by PanierAvide** [comment]
À priori il n'y a plus de notes anonymes de créées, on peut considérer le problème de cache résolu.
