### ISSUE TITLE
Évolutions marque blanche

### ISSUE THREAD

**Issue by PanierAvide** [osmontrouge/caresteouvert#671]
Les points techniques à adresser pour pouvoir avancer sur le sujet de la marque blanche pour Lyon.

- [x] Ajouter le contour de la ville de Lyon dans `country_subcountry` : https://www.openstreetmap.org/relation/120965 -> @vdct (ok)
- [x] Créer un sous-domaine `lyon.caresteouvert.fr` -> @PanierAvide 
- [ ] Augmenter la table `poi_cro` avec les données reçues -> en attente
- [x] Créer la sous-catégorie "grands chefs" -> @PanierAvide
- [ ] Afficher les images (s'il y en a) ? -> en attente
- [x] Page de CGV spécifique -> @overflorian 
- [x] Préparer le code d'iframe + le transmettre -> @PanierAvide et @overflorian 

N'hésitez pas à cocher la case une fois que la tâche est réalisée :wink:

**Comment by overflorian** [comment]
Il n'y aura pas de travail sur le visuel à réaliser;
je rajouterai 
- [ ] Page CGV custom

**Comment by PanierAvide** [comment]
Pas de logo spécifique à intégrer ?

**Comment by overflorian** [comment]
en effet, ils vont intégrer le site direct en iframe

**Comment by PanierAvide** [comment]
Le logo "ça reste ouvert" apparaît quand même dans une iframe, on le laisse tel quel ?

**Comment by overflorian** [comment]
on ne touche à rien coté logo, yes

**Comment by PanierAvide** [comment]
Le code pour l'iframe
```
<iframe style="width: 100%;" src="https://lyon.caresteouvert.fr/@45.756113,4.826931,13.76" height="400" frameborder="0" scrolling="no"></iframe>
```

**Comment by PanierAvide** [comment]
Système de gestion de POI personnalisés via CSV https://github.com/osmontrouge/caresteouvert/commit/45e2cdb1c587e03a15024c1087ab5f28819e9370

**Comment by PanierAvide** [comment]
Le POI exemple est ici, j'ai intégré les infos reçues donc à voir si OK à la prochaine màj : https://lyon.caresteouvert.fr/@45.771331,4.837202,18.33/place/n638214585

**Comment by PanierAvide** [comment]
Intégration des CGV en cours de déploiement via c02e2af

**Comment by francois2metz** [comment]
No news from them. Closing
