### ISSUE TITLE
Missing category: shop=outdoor

### ISSUE THREAD

**Issue by leonardehrenfried** [osmontrouge/caresteouvert#675]
**Name**: Outdoor shopt
**Tagging**: shop=outdoor
**Country**: Germany
**Example in OpenStreetMap**: https://www.openstreetmap.org/node/4789617810
**Example in "Ca reste ouvert"**: https://www.bleibtoffen.de/@52.502448,13.414417,19.74
**Icon**: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/outdoor.svg

**Comment by francois2metz** [comment]
Fixed in 98111ada2331cf35568ba44f98c61e590582a99e
