### ISSUE TITLE
Lien vers le blog

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#68]
Rajouter un URL vers https://blog.caresteouvert.fr depuis la homepage.
Wording : "Blog" calé entre "indiquer un commerce manquant" et "à propos"

**Comment by PanierAvide** [comment]
Ça été fait par François b1324631

**Comment by PanierAvide** [comment]
Ticket fermé trop vite : c'est le "à propos" qui a été déplacé

**Comment by PanierAvide** [comment]
Implémenté pour de vrai ce coup-ci :sweat_smile:
