### ISSUE TITLE
Translation feedback

### ISSUE THREAD

**Issue by RockyTV** [osmontrouge/caresteouvert#683]
There are some strings that appear in France but not other countries, such as:

- `Nous vous conseillons d’appeler votre agence avant de vous déplacer`
- `C'est votre établissement ? Complétez vos informations`
- `Vous avez votre propre établissement et vous avez besoin d'aide pour le rajouter :` (this one isn't exclusive to France)

The first 2 strings appear when you click on a POI, the last one appears when clicking the "missing place?" button. Even if they are exclusive to France, I think they should be translatable.

Also, I'd like to ask, where are these strings used:

```
  "directory": {
    "regions": {
      "title": "Regions list"
    },
    "departements": {
      "title": "Departments list"
    },
    "communes": {
      "title": "Counties list"
    },
    "categories": {
      "title": "Categories list"
    },
    "pois": {
      "title": "Places list",
      "link": {
        "previous": "Previous places",
        "next": "Next places"
      }
    }
  }
}
```

It'd help to know where they are used to check what are the limitations and the context where these strings are used.

**Comment by PanierAvide** [comment]
Thanks for your feedback :smiley: So to give you precise answers :
* `C'est votre établissement ? Complétez vos informations` + `Vous avez votre propre établissement et vous avez besoin d'aide pour le rajouter` where missing in translation files, I fixed it and should now appear on Transifex
* `Nous vous conseillons d’appeler votre agence avant de vous déplacer` : these kind of strings are coming from chain stores rules defined in [Covid enseignes repository](https://github.com/PanierAvide/Covid_enseignes). They can't be translated as now, but we consider that each store info is shown in country language so should not be an issue (yet).
* Directory strings are used in pages under development to make map information available as static HTML pages (for accessibility and SEO). Parts of code are [here](https://github.com/osmontrouge/caresteouvert_backend/tree/master/src/directory) and [here](https://github.com/osmontrouge/caresteouvert/tree/master/pages/annuaire)

I hope this helps.
