### ISSUE TITLE
App iOS simple

### ISSUE THREAD

**Issue by pat-tech** [osmontrouge/caresteouvert#69]
Bonjour 
Je me propose de mettre sur l'AppStore une appli très simple de ca reste ouvert.
Le but est que l'appli soit disponible rapidement. 
Par contre, j'utiliserais GG Maps (jc'est la seule méthode très rapide pour mettre en ligne l'appli (délai A pple pouvant être long pour l'acceptation)
L'appli est prete, il me faut juste votre accord pour le logo et le nom. Les données étant en open data.
Merci de cette initiative

Patrick

**Comment by francois2metz** [comment]
Bonjour Patrick,

Merci de cette proposition. Nous sommes très intéressé par faire une application mobile !

Il est important pour nous que l'application soit libre et qu'elle utilise un fond de carte OpenStreetMap (via mapbox ou autre). Est ce que c'est possible pour toi ?

J'ai également une question sur l'affichage des données. Tu utilise les données de data.gouv ? Quelle est leur délai de rafraîchissement ?

**Comment by pat-tech** [comment]
Bjr
L'application est terminée. Basique mais fonctionnelle.

L'appli sera gratuite, je pense à mettre des pubs dont les gains seront reversées à l'AP HP. Tous les moyens sont bons pour récolter des fonds (par expérience, il ne faudra pas s'attendre à des miracles non plus mais c'est mieux que rien).

Malheureusement c'est la solution la plus rapide et la technique que j'ai trouvée de mettre sur GG Maps.

Pour les données, ce sont les données de data gouv, mais elles sont mises à jour par moi tous les jours (action plus simple et plus rapide pour le moment).

Patrick

**Comment by PanierAvide** [comment]
Bonjour,

Merci pour ce retour. Nous sommes effectivement intéressés, mais faisant parti d'un écosystème de logiciels libres, nous avons besoin de garanties de votre part sur la solution publiée, en particulier :
* La publication __sous licence libre__ du code de l'application (de préférence licence AGPL, mais ça peut être une autre licence libre), par exemple sur GitHub ou Gitlab
* La __non-utilisation de la solution Google Maps__ : nous représentons la communauté OpenStreetMap, nous sommes pour le partage de l'information et les contributions collaboratives. C'est à l'opposé des valeurs de Google, nous ne voulons donc pas nous appuyer sur la solution Google Maps par principe. D'autant que des solutions alternatives (Mapbox, Mapzen...) sont de facilité d'utilisation équivalente et plus respectueuses de nos valeurs.

Comprenez bien notre démarche : nous sommes attachés aux valeurs d'ouverture et de partage. Nous souhaitons par ce projet également valoriser OpenStreetMap, en accord avec notre communauté de contributeurs. C'est grâce à eux que les données sont aussi détaillées et vivantes, nous ne pouvons pas bafouer les valeurs qui les animent au quotidien.

Si ces conditions sont inacceptables pour vous, nous serons contraint de décliner votre offre et de vous refuser l'utilisation du logo et de la marque "Ça reste ouvert". Par ailleurs, les données sur data.gouv.fr sont sous licence Open Database License : vous pouvez les utiliser sans notre accord, mais vous avez __l'obligation d'attribuer correctement la source de données__ ([voir détails ici](https://opendatacommons.org/licenses/odbl/summary/index.html)).

Merci de votre retour clair sur vos intentions afin de pouvoir travailler ensemble dans de bonnes conditions.

Cordialement.
