### ISSUE TITLE
Intégrer un formulaire spécifique pour les franchises

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#696]
Sur les POIs de franchises (avec un tag brand:wikidata), nous devrions indiquer une mention spécifique pour aider leurs propriétaires / gestionnaires à mettre en qualité leurs données.

Ma proposition : remplacer la mention actuelle sur la fiche POI "C'est votre établissement ? Compléter vos informations" par :
> C'est votre établissement ou celui de votre groupe ?
> Gagnez en visibilité après le confinement avec notre solution de promotion dédiée

Un popup s'ouvre et affiche :
> **Gestionnaire de points de vente**
> Vous êtes gestionnaire d'une franchise ou responsable d'un réseau franchisé.
> Gagnez en visibilité en référençant tous vos points de vente dans "Ça reste ouvert".

> En plus d'être mis en avant de manière personnalisée dans notre service, vous apparaîtrez également dans de très nombreux sites et applis mobiles.

-> Bouton "Contactez-nous" qui renvoie vers ce nouveau formulaire https://airtable.com/shrnIw9zsX9sYEVNI

@nlehuby je ne crois pas avoir configuré ce nouveau formulaire pour récupérer le bon ID OSM. Tu pourrai t'y pencher stp ?

**Comment by overflorian** [comment]
J'ai changé le formulaire, voici le nouveau https://airtable.com/shrfssuOhvXzVxtui

**Comment by vinber** [comment]
Je trouve la forme maladroite, trop commerciale "pour moi"
> notre solution de promotion dédiée
> en référençant dans Ca reste ouvert ou OSM ?
> dans notre service

mais sans doute qu eje suis vieux jeu !

**Comment by nlehuby** [comment]
> J'ai changé le formulaire, voici le nouveau https://airtable.com/shrfssuOhvXzVxtui

voici l'url à utiliser pour pré-renseigner l'id osm: `https://airtable.com/shrfssuOhvXzVxtui?prefill_osm_id=${osm}`

**Comment by overflorian** [comment]
merci Noémie. @PanierAvide sauf oubli tu as toutes les infos

**Comment by PanierAvide** [comment]
À priori oui

**Comment by PanierAvide** [comment]
Intégré, ce sera en ligne d'ici quelques minutes. J'ai aussi modifié le script en base pour bien récupérer le nom de l'enseigne systématiquement depuis Covid_enseigne, ce sera pris en compte d'ici ~1h.

**Comment by overflorian** [comment]
> Je trouve la forme maladroite, trop commerciale "pour moi"
> 
> > notre solution de promotion dédiée
> > en référençant dans Ca reste ouvert ou OSM ?
> > dans notre service
> 
> mais sans doute qu eje suis vieux jeu !

@vinber j'ai choisi le wording exprès pour qu'il soit adapté aux responsables de franchises. J'ai donc adapté la formule en conséquence pour capter leur attention. Je pense que si l'on est moins précis on risque justement de ne pas les intéresser. Tu avais quoi en tête sinon ?

**Comment by vinber** [comment]
la version du formulaire me convient plus que le premier message auquel j'ai répondu sans voir le tien entre !

J'ajouterai cependant :
"Gagnez en visibilité en référençant tous vos points de vente dans "Ça reste ouvert" (basé sur OpenStreetMap)."
J'imagine bien que c'est trop long mais je me dis qu'il doive savoir qu'ils sortent d'une logique de silo :)

**Comment by overflorian** [comment]
Tiens c'est marrant j'avais écrit un truc du genre au début et puis j'avais trouvé que c'était too much.
Du coup je propose :
> Vous êtes gestionnaire d'une franchise ou responsable d'un réseau franchisé.
> **[ALLER A LA LIGNE]**
> Gagnez en visibilité en référençant tous vos points de vente dans "Ça reste ouvert".
> **[ALLER A LA LIGNE]**
> En plus d'être mis en avant de manière personnalisée dans notre service, vous apparaîtrez également dans de très nombreux sites et applis mobiles grâce à OpenStreetMap.

ça te va @vinber ?

Concernant la mention sur le POI en lui-même, le texte est coupé :
![image](https://user-images.githubusercontent.com/11553211/81430349-8ce59c00-915f-11ea-8eb5-db24e07fd6c0.png)
Evidemment on pourrait revenir à la ligne pour qu'il rentre mais je propose plutôt de raccourcir le texte car ce n'est qu'un CTA :
> Gagnez en visibilité après le confinement

**Comment by PanierAvide** [comment]
C'est mis à jour
