### ISSUE TITLE
Les commerces fermés ne sont pas visibles

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#7]
exemple des shop=doityourself ou shop=electronics

il y a 1 leroy merlin, 1 darty et 1 boulanger ici (normalement tous fermés).

Si c'est un choix de ne pas afficher les enseignes fermées, cela rend difficile de se répérer sur la carte (du moins pour moi)

**Comment by PanierAvide** [comment]
Ça c'est une excellente question. Si une enseigne est notée fermée mais qu'un de ses magasins est ouvert, tant que c'est renseigné dans OSM ça arrivera sur la carte. Mais au-delà de ça, est-ce que l'on a envie d'afficher les commerces fermés (avec un symbole rouge ou noir) ?
* Si on les affiche, ça permet la contribution via le site, et met au clair qu'on est confiant sur le fait que ce soit fermé
* Mais au départ, on était sur la logique de ne montrer que ce qui est ouvert. Ça veut dire qu'il faut aussi aller tout les autres types de points hors ceux concernés ?

@overflorian ton avis là-dessus ?

**Comment by vinber** [comment]
Bon vous avez compris que moi j'ai surtout des questions :D

**Comment by overflorian** [comment]
Je pense qu'il faut rester sur l'idée de n'afficher que les commerces ouverts pour ne pas alourdir l'affichage.
Par contre on a toujours l'idée d'un bouton (+) pour permettre d'ajouter une note pour indiquer un POI avec ses infos temporaires du moment

**Comment by francois2metz** [comment]
Ce serait pas mal de rajouter une option pour voir les commerces fermé. Pas super prioritaire mais ca permettrait une contribution de A-Z dans caresteouvert a terme (si le commerce est déjà présent dans OSM).

**Comment by PanierAvide** [comment]
Si on part là-dessus, il faudra penser à modifier la vue SQL `poi_osm_light` qui les filtre automatiquement.

**Comment by PanierAvide** [comment]
C'est intégré !
