### ISSUE TITLE
ajouter une catégorie "tabac" ?

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#70]
Je réfléchis à séparer les commerces de tabac + e-cigarette dans une catégorie à part.
Selon tabac-info-service :
"La France compte près de 16 millions de fumeurs. Un tiers des personnes de 15 à 85 ans (32 %) fume ne serait-ce que de temps en temps (36% des hommes et 28% des femmes)."

Considérant donc que
1. 1/3 des français fument
2. Ce produit est de première nécessité pour ce public
3. Le stress de cette crise a sûrement un impact d'augmentation de la consommation
J'ai l'impression que nous avons une opportunité.

Quelle est la proposition de shop=tobacco et de shop=e-cigarette qui sont ouverts en base ? Ça nous aidera peut-être à prendre une décision.
Merci

**Comment by vinber** [comment]
shop=tobacco -> 2 295 http://taginfo.openstreetmap.fr/search?q=shop%3Dtobacco
shop=e-cigarette -> 549 http://taginfo.openstreetmap.fr/search?q=shop%3De-cigarette
tobacco=yes -> 1369 http://taginfo.openstreetmap.fr/keys/tobacco#overview

**Comment by PanierAvide** [comment]
J'y travaille ;-)

**Comment by PanierAvide** [comment]
C'est implémenté, ça va pas tarder à être en ligne.
