### ISSUE TITLE
Redirect guide to add a missing place to localized blog post

### ISSUE THREAD

**Issue by RockyTV** [osmontrouge/caresteouvert#705]
I've seen that some languages already redirect to the translated blog post with a guide to add a place in OSM. Would it be possible to make the link follow the selected language's code instead of being hardcoded?

For example, Brazilian Portuguese redirects to the original blog post, in French, but there's a translation available for that specific blog post.

**Comment by PanierAvide** [comment]
It's not hardcoded, it is configurable through this file : https://github.com/osmontrouge/caresteouvert/blob/master/config.json#L94

Which URL should we point to for pt_BR ?

**Comment by RockyTV** [comment]
Ah, thanks for pointing it out, I'll submit a pull request adding a config for the translated blog post.

**Comment by PanierAvide** [comment]
Great :wink:
