### ISSUE TITLE
"Suivez le guide" button in italian not working properly

### ISSUE THREAD

**Issue by Mannivu** [osmontrouge/caresteouvert#710]
**Describe the bug**
When using the map in italian, you can click on "Riporta/Segnala un negozio mancante" and then, after clicking on "Follow the guide" (or "Segui la guida, if you're reading after the tranlsation update) the site takes the user back to the map, instead of the blog entry on how to enter a missing shop.

**To Reproduce**
1. Go to https://www.caresteouvert.fr/ and set language to "Italiano"
2. Click on Riporta un negozio mancante (or Segnala un negozio mancante), then click to "Follow the guide" (or "Segui la guida")
3. See error

**Expected behavior**
The wanted link should be https://www.caresteouvert.fr/blog/it/come-posso-aggiungere-un-posto-mancante-su-RestiamoAperti/, but the user get back to https://www.caresteouvert.fr

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi
 - Version: 3.0.1874.38 (Stable channel) (64 bit)

**Additional context**
While there's no italian guida, it would be useful to redirect users on the english guide

**Comment by francois2metz** [comment]
Thanks for the report. The link was wrrong so I fixed it.

**Comment by Mannivu** [comment]
Thank you!
