### ISSUE TITLE
Missing category: Magasin de Magie

### ISSUE THREAD

**Issue by DarkYves** [osmontrouge/caresteouvert#716]
**Name**: Magasin de Magie

**Tagging**: shop=magic

**Country**: france

**Example in OpenStreetMap**: https://www.openstreetmap.org/node/2848150901

**Example in "Ca reste ouvert"**: https://www.caresteouvert.fr/@48.849615,2.347659,20.00

**Icon**: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/gift.svg

**Comment by PanierAvide** [comment]
Merci pour cette suggestion. Il y a 2 magasins avec ce tag `shop=magic` en France, et c'est peut-être pas le type de commerce que les utilisateurs recherchent sur ça reste ouvert. Je ferme le ticket pour l'instant.

**Comment by DarkYves** [comment]
Bonjour Adrien, 

C’est une réaction assez discriminatoire. En effet, pratiquer la magie en temps de confinement est un loisir qui correspond en de nombreux points aux normes COVID. 
D’autre part nous sommes ouverts en ces temps économiquement difficiles pour tous.
Pourquoi être mis de côté ? 
Il semble que ça reste ouvert s’adresse à tous et toutes tant qu’on reste ouvert.
Ce ne serai donc pas le cas?

Yves Doumergue 
Gérant abracadabra 

Envoyé de mon iPhone

**Comment by PanierAvide** [comment]
Bonjour,

Tout d'abord point essentiel : tous les commerces avec l'information d'ouverture `opening_hours:covid19=*` dans OpenStreetMap sont affichés, __même s'ils ne sont pas catégorisés__. Donc parler de discrimination me semble exagéré, s'il y a des données on les affiche, difficile de faire plus permissif. Si votre boutique n'apparaît pas, il suffit d'y ajouter les informations d'ouverture pendant/après le confinement dans OpenStreetMap pour qu'elle apparaisse. C'est l'objet de l'article de blog ici : https://blog.caresteouvert.fr/que-faire-sil-manque-un-commerce-dans-ca-reste-ouvert/

Deuxième point : le problème ne vient pas du _type de commerce_, mais de sa représentation dans OpenStreetMap. À ma connaissance, chaque grande ville de France doit avoir au moins un ou plusieurs magasins de magie (on pourrait dire au moins une bonne cinquantaine en France ?). On devrait donc pouvoir les retrouver grâce à l'attribut `shop=magic`, mais ce n'est pas le cas : 2 objets en France. L'exemple donné utilise d'ailleurs l'attribut `shop=hobby`, qui semble plutôt être utilisé pour les boutiques de modélisme. Soit l'attribut indiqué n'est pas le bon, soit il souffre d'un manque de représentation dans OpenStreetMap. Dans ce cas, avant de penser à faire apparaître une catégorie, il faut améliorer les données dans OpenStreetMap : retrouver les boutiques de magie, et leur donner un attribut approprié (que ce soit `shop=magic` ou un autre qui serait déjà utilisé par ailleurs). Si vous n'êtes pas familier de la contribution à OpenStreetMap, je vous invite à lire nos articles de blog qui sont prévus pour aider aux premières contributions : https://blog.caresteouvert.fr/

Dernier point : l''équipe qui travaille sur ce projet est entièrement bénévole. À titre personnel mon activité souffre également largement de la situation actuelle, je comprends donc tout à fait votre demande et souhaite vous aider au mieux. Mais comprenez aussi qu'il s'agit d'un projet _collaboratif_, c'est donc __ensemble__ qu'il faut construire un outil meilleur. En l'état les données ne sont pas de qualité suffisante pour être affichées, je vous invite donc à participer sur les deux points précédents pour rendre cela possible. Des données de meilleure qualité nous permettront de proposer un affichage pertinent des boutiques de magie aux utilisateurs. L'équipe reste à disposition pour vous aiguiller dans cette démarche.

Cordialement.
