### ISSUE TITLE
Restaurants and fast food with self service are all open

### ISSUE THREAD

**Issue by fansanelli** [osmontrouge/caresteouvert#718]
Hello,

Yesterday we've added Italian shops and today I started to play with CRO and go deeper into data.
I spotted that every restaurant or fast food with self service tag in Italy is open. It's not ok... Only takeaway is allowed.
Do you know what happened?

Many thanks
Best regards
Francesco

**Comment by PanierAvide** [comment]
Thanks for feedback, it was due to a too wide interpretation of `self_service` tag, which is mainly used in France for fuel stations. It's now fixed, data will be updated in ~1h.

**Comment by fansanelli** [comment]
> Thanks for feedback, it was due to a too wide interpretation of `self_service` tag, which is mainly used in France for fuel stations. It's now fixed, data will be updated in ~1h.

Thanks for the prompt fix!

Have a nice day
Francesco
