### ISSUE TITLE
Ouvert le mardi : le lundi ça reste fermé !

### ISSUE THREAD

**Issue by Bibi56** [osmontrouge/caresteouvert#72]
https://www.caresteouvert.fr/@47.790006,-3.487664,21.20/place/n840334545
Ouverture à 09:00. Exact mais mardi 09:00, pas lundi 09:00 or on est lundi.

Bon mercredi 1er avril, ça le fera : "on vous a dit que c'était fermé jusqu'à 09:00, on n'a pas dit quand c'était ouvert" ;-)

**Comment by francois2metz** [comment]
Bonjour,

Merci pour ce retour. Je n'ai pas compris le problème. L'affichage a l'air cohérent non ?

**Comment by Bibi56** [comment]
À cette heure-ci oui, quand j'ai écrit le message il n'était pas 09;00 on était lundi. Le commerce ouvre demain à 09:00 donc on aurait du voir "ouvre mardi à 09:00".

**Comment by francois2metz** [comment]
Ah, j'ai compris. C'était une feature je dois dire, mais on peut rendre cela plus explicite.

**Comment by francois2metz** [comment]
Fixé dans 3e58914419b7ab0df498cd6141edfd0e01815e03. Je clôt, mais si ça ne marche pas comme tu veux, n'hésite pas à réouvrir.
