### ISSUE TITLE
Last update time string looks weird on different locales

### ISSUE THREAD

**Issue by RockyTV** [osmontrouge/caresteouvert#721]
**Describe the bug**
The last update info box when clicking on a POI in the map displays a date string that lacks information on some locales.

For example, in English, the string is actually informative:
`Last update: Monday, June 17, 2019, 8 AM `

However, on languages like Portuguese, Spanish, Swedish, it takes some time to associate that the last number in the string refers to the hour of the last update:

`segunda-feira, 17 de junho de 2019 08`
`lunes, 17 de junio de 2019 8 `
`måndag 17 juni 2019 08`

**To Reproduce**
1. Change language to `Português (BR)`, `Español` or `Svenska`
2. Go to Paris
3. Click on Food
4. Click on [Franprix](https://www.caresteouvert.fr/@48.850684,2.348280,13.88/place/n6552384244)

**Screenshots**
![](https://cdn.discordapp.com/attachments/708036782826192959/709089181426778192/unknown.png)

**Additional context**
My idea at first was to change the date format to be universal, something like `YYYY-MM-dd HH:mm`, but I thought it wouldn't look good, and would require a custom date format in the code.

![](https://cdn.discordapp.com/attachments/708036782826192959/709090331324448788/unknown.png)

Another idea is to allow each language to choose their formatting for the date string, but it would require more or less the same effort as the idea above, but it would give languages more freedom to handle the string.

For simple changes, the date format object could include minutes, so it would reduce any misinterpretations like stated above:

![](https://cdn.discordapp.com/attachments/708036782826192959/709090667107713135/unknown.png)

**Comment by francois2metz** [comment]
I added the minutes to fix it. Tell me if it's works for you.
