### ISSUE TITLE
Evolution du wording post-confinement

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#728]
Faisons évoluer le wording suite à la levée du confinement :

### Sous titre du site :
- Les lieux ouverts durant et après le confinement > Les lieux ouverts durant la crise sanitaire

### Sur le volet des POIs :
- Lieu potentiellement ouvert pour proposer ses services habituels ou de nouveaux. Ouvert ou fermé ? À vous de le dire. > Lieu potentiellement ouvert avec services habituels ou adaptés. Ouvert ou fermé ? À vous de le dire.
- Ce lieu reste-il ouvert ? > Ce lieu reste-il ouvert durant la crise sanitaire ?
à adapter selon date de contribution (durant ou après confinement)
### Dans le formulaire :
- Horaires d'ouverture hors-confinement > Horaires d'ouverture avant la crise sanitaire
- Horaires d'ouverture > Horaires d'ouverture durant la crise sanitaire

### Dans la popup "commerce manquant" :
- « Ça reste ouvert » a pour but de n'afficher que les lieux qui sont autorisés à ouvrir pendant le confinement. > « Ça reste ouvert » n'affiche que les lieux potentiellement ouverts durant la crise sanitaire.

### Dans le bandeau "en savoir plus" :
« Ça reste ouvert » est l’outil indispensable pour éviter les déplacements infructueux autour de chez vous durant le confinement et limiter ainsi le risque de contagion. > « Ça reste ouvert » est l’outil indispensable pour éviter les déplacements infructueux autour de chez vous durant la crise sanitaire et limiter ainsi le risque de contagion.

**J'ai changé également le wording sur les pages :**
- https://blog.caresteouvert.fr/about/
- https://blog.caresteouvert.fr/presse/
- https://blog.caresteouvert.fr/mentions-legales/
- https://blog.caresteouvert.fr/mentions-legales-lyon/
- https://blog.caresteouvert.fr/que-faire-sil-manque-un-commerce-dans-ca-reste-ouvert/
- https://blog.caresteouvert.fr/un-outil-de-communication-des-mairies/
- https://wiki.openstreetmap.org/wiki/France/Covid-19

**Comment by gendy54** [comment]
> Dans le formulaire :
> Horaires d'ouverture hors-confinement > Horaires d'ouverture avant la crise sanitaire
> Horaires d'ouverture > Horaires d'ouverture durant la crise sanitaire

**Proposition**: Horaires d'ouverture hors-confinement > Horaires d'ouverture habituels hors crise sanitaire

> Ce lieu reste-il ouvert ? > Ce lieu reste-il ouvert durant la crise sanitaire ? 
> à adapter selon date de contribution (durant ou après confinement)

**Proposition**: Ce lieu reste-il ouvert actuellement ?

**Comment by overflorian** [comment]
pour moi c'est ok pour la première proposition.

pour la seconde, "actuellement" ne me paraît pas assez précis. -> certains lieux ont DEJA des infos d'ouverture. L'utilisateur en voyant cela pourrait s'il est légitime à modifier ces infos pre-existantes.

Or "durant la crise sanitaire" lève cette ambiguïté : on parle bien d'une situation perturbée (qui alimente le tag opening_hours:covid19) mais elle n'est pas limitée au temps du confinement.

**Comment by overflorian** [comment]
J'ai aussi changé le wording sur les pages
- https://twitter.com/caresteouvert
- https://www.facebook.com/pg/Ça-reste-ouvert-102510298066358/about
- https://github.com/osmontrouge/caresteouvert/blob/master/README.md

**Comment by overflorian** [comment]
Hello @francois2metz je vois qu'il manque pas mal de changement de wording.
Peux-tu stp expliquer la raison de la fermeture du ticket ?

On a discuté du wording approprié au post-confinement au téléphone avec @nlehuby et @PanierAvide  en choisissant soigneusement chaque mot.

Merci
