### ISSUE TITLE
Translate the website into more languages

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#73]
The website currently exists in French and English, what about the other languages?
Cf. request for catalan and castillan https://twitter.com/yopaseopor/status/1244419017672179712

**Comment by PanierAvide** [comment]
Best thing would be to put the `locales.json` file on Transifex or similar to allow crowd-sourced translation.

**Comment by PanierAvide** [comment]
Translation will be done there : https://www.transifex.com/openlevelup/ca-reste-ouvert/dashboard/

Still some things to setup before communicate this link

**Comment by PanierAvide** [comment]
This is now operational, everyone can translate Ça reste ouvert ;-)
