### ISSUE TITLE
Tag description:covid19 mis à jour en partie

### ISSUE THREAD

**Issue by deuzeffe** [osmontrouge/caresteouvert#730]
**Describe the bug**
Le tag `description:covid19`est mis à jour sans RàZ préalable (?).

**To Reproduce**
1. Go to https://www.openstreetmap.org/way/70704023 édité via iD (10/05 ~ 16:30)
![Screenshot_2020-05-11 OpenStreetMap](https://user-images.githubusercontent.com/36087963/81574688-6d8c8000-93a6-11ea-8752-856f2bcfb163.png)

2. Go to https://www.caresteouvert.fr/@45.794788,1.133240,15.81/place/w70704023
![Screenshot_2020-05-11 Ça reste ouvert](https://user-images.githubusercontent.com/36087963/81574820-93b22000-93a6-11ea-8da3-97fece37fcd4.png)

La première ligne de l'info/description n'est plus dans la base (c'était celle avant le 11/05) et ne devrait donc pas figurer dans CRO (?)

**Expected behavior**

Infos et contenu de `description:covid19` identiques ;)

Merci pour les remarques quelles qu'elles soient.

**Comment by PanierAvide** [comment]
La première ligne qui apparaît dans "Ça reste ouvert" est générée automatiquement à partir du tag `access:covid19=no`. Si cette info n'est plus d'actualité, il faut modifier ce tag soit dans iD, soit via le formulaire "signaler un changement" à la question sur l'accueil physique. J'espère que ça répond à la question, n'hésite pas si tu as besoin de plus d'infos :wink:

**Comment by deuzeffe** [comment]
Vu/compris. Merci !

J'ai modifié `access:covid19` en fonction (via iD, histoire de ne pas faire de note ?). J'attends la màj de CRO pour voir ce que ça donne ;)
