### ISSUE TITLE
Nouveau logo : changer toutes les images

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#736]
Changer les visuels pour faire apparaître le nouveau mag-ni-fi-que logo !
- [x] logo twitter
- [x] cover twitter
- [x] logo facebook
- [x] cover facebook
- [x] favicon site principal
- [x] favicon blog
- [x] cover blog
- [x] dossier de presse
- [x] https://github.com/osmontrouge/caresteouvert
- [ ] Logo app store
- [ ] Banners app store
- [x] Logo Play store
- [x] Banners play store
- [x] Logo F-droid
- [ ] Banners F-droid
- [ ] Animation en motion design
- [x] https://peertube.openstreetmap.fr/accounts/caresteouvert/video-channels
- [x] https://www.data.gouv.fr/fr/organizations/ca-reste-ouvert
- [x] Icone desktop site web Français - Ça reste ouvert
- [x] Icone mobile site web Français - Ça reste ouvert
- [x] Icone desktop site web Allemand - Bleibt offen
- [x] Icone mobile site web Allemand - Bleibt offen
- [x] Icone desktop site web Catalan - Es obert
- [x] Icone mobile site web Catalan - Es obert
- [x] Icone desktop site web Catalan - Espagne - Sigue abierto
- [x] Icone mobile site web Catalan - Espagne - Sigue abierto
- [x] Icone desktop site web Catalan - Finlandais - Ollaan auki
- [x] Icone mobile site web Catalan - Finlandais - Ollaan auki
- [x] Icone desktop site web Catalan - Galicia - Segue aberto
- [x] Icone mobile site web Catalan - Galicia - Segue aberto
- [x] Icone desktop site web Catalan - Philippines - Bukas pa rin
- [x] Icone mobile site web Catalan - Philippines - Bukas pa rin
- [x] Icone desktop site web Catalan - RDC - Ezo sala
- [x] Icone mobile site web Catalan - RDC - Ezo sala
- [x] Icone desktop site web Catalan - Staying open - Irlande
- [x] Icone mobile site web Catalan - Staying open - Irlande
- [x] Icone desktop site web Catalan - Taimid oscailte - Irlande gaélique
- [x] Icone mobile site web Catalan - Taimid oscailte - Irlande gaélique

Je crois que je n'oublie rien ...

Annonce :
- [x] [Tweet](https://twitter.com/caresteouvert/status/1259885114831654913)
- [x] [Message Facebook](https://www.facebook.com/102510298066358/photos/a.103956771255044/134150698235651/?type=3&notif_id=1589215231195428&notif_t=page_post_reaction)
- [x] [Article de blog](https://blog.caresteouvert.fr/nouveau-logo/)

Tous les visuels sont ici : https://ncloud.zaclys.com/index.php/s/GPqxzo3T946Gspq

Pour la vidéo de présentation, la personne qui a fait l'export n'est plus dispo : tout ré-export est donc impossible. Gardons donc là comme ceci ...

**Comment by naposm** [comment]
Aussi le photo de profil OpenStreetMap CaResteOuvert_visitor

**Comment by overflorian** [comment]
merci j'avais oublié celle-là. C'est fait

**Comment by PanierAvide** [comment]
Fait pour le site, c'est en cours de déploiement

**Comment by overflorian** [comment]
Pour le coup, je trouve qu'il prend beaucoup d'espace vertical. J'ai refait un export en gagnant un maximum de pixels verticaux, je pense que c'est mieux. Est-ce que de ton coté il y a moyen de bien le coller en haut ou est-il déjà au max ? merci

![logo-FR-laptop-narrow](https://user-images.githubusercontent.com/11553211/81690054-1eeced80-945b-11ea-99c5-0d84a567d0f3.png)

**Comment by PanierAvide** [comment]
Si modif doit être faite, ce ne sera pas en modifiant les logos à nouveau. Je vais jouer sur le style plutôt.

**Comment by overflorian** [comment]
j'ai remonté le texte dans l'image et rogné en haut et en bas, ça devrait tout de même aider. Si besoin, le svg est dans le drive cf. lien ci-dessus : logo-FR-laptop-narrow.svg

**Comment by overflorian** [comment]
@gendy54 tu peux changer le logo sur peertube stp ?

**Comment by gendy54** [comment]
Fait
