### ISSUE TITLE
Problème sur le géocodeur (nombre d'espace >3)

### ISSUE THREAD

**Issue by geostonemarten** [osmontrouge/caresteouvert#74]
Bonjour,
Le géocodeur ne retourne pas de résultat lors de la validation d'une adresse qui n'est pas proposé par l'autocomplétion. Le problème c'est que si plus de 3 espaces sont détectés il n'y a plus de proposition dans l'autocomplétion.

Je pense que seul les espaces de concaténation des chaines (numéro, rue, ville)

autre remarque mais peut-être à mettre sur un autre ticket c'est de limiter le domaine de recherche à la France.

**Comment by Joxit** [comment]
Bonjour,

Petite info, pour avoir uniquement les résultats en France, il y a [boundary.country=FRA](https://www.jawg.io/docs/apidocs/places/search/#prioritize-within-a-country) :smile:

**Comment by PanierAvide** [comment]
Merci pour la précision `boundary.country=FRA`, cela couvre bien France métropolitaine + DROM/COM ?

**Comment by PanierAvide** [comment]
Effectivement ça prend bien en compte les DROM/COM, donc impeccable.

J'ai mis en place le mécanisme suivant :
* Recherche à partir de 3 caractères
* Pas de recherche lancée si une est déjà en cours

À priori ça devrait être suffisant ?

**Comment by Joxit** [comment]
Pour les 3 caractères c'est OK.

Pour ne pas rechercher quand il y en a une en cours c'est un peu mieux, ça divise par 2 les requêtes quand je tape assez vite.

J'ai un peu peur du cas où la dernière lettre peut être importante lors de la recherche. Typiquement je cherche [`Gacé`](https://www.caresteouvert.fr/@48.794013,0.285950,11.64), je tape trop vite donc ça géocode `Gac` et ne trouve rien...
Mais j'avoue que c'est peu probable :smile:.

Peut-être vous pourrez faire [ceci](https://github.com/Joxit/pelias-mapbox-gl-js/blob/6f5532f430961e8581e624a7511d112f0cb40857/pelias-geocoder.js#L356-L370) dans un second temps (timeout de 350ms avant de valider une recherche c'est parfait, on ne se rend presque pas compte quand on tape déjà vite)
