### ISSUE TITLE
Expand to Brazil 🇧🇷

### ISSUE THREAD

**Issue by RockyTV** [osmontrouge/caresteouvert#741]
Please read https://github.com/osmontrouge/caresteouvert/wiki/Expand-%22%C3%87a-reste-ouvert%22-to-another-country first.

Please check the following requirements:

- [ ] You are a team of at least 2 people experienced with OpenStreetMap
- [x] Translate the app via transifex with your country languages
- [x] Translate some content of the blog to help newcomers (how to create a new shop, the about page, ...) (WIP)
- [ ] Start gathering data about chain stores open or closed nation wide, and legal opening rules in https://github.com/PanierAvide/Covid_enseignes/
- [ ] Once everything has been done and the data have been loaded, you should be busy getting media coverage. So the map will have a lot of contribution and be quickly useful.

Others questions:

- if you want a localized domain name, please tell us which one: 
- Each lockdown is different, what shops are open or closed in your country? What should be done in the category list?

----

I decided to open this issue to keep track of what's missing to expand to the country. I'm also talking to members of the community to figure out the best way to enable the service for Brazil.

**Comment by francois2metz** [comment]
You have been doing a good job already. Can you shoot me an email to francois [at] 2metz [dot] fr or send me a twitter DM https://twitter.com/francois2metz/ so I can send you a link to join our mattermost instance?

**Comment by francois2metz** [comment]
Hi there, I there is any news about this?

**Comment by RockyTV** [comment]
Yes, there is. I asked on Mattermost but got no answer: what type of work load should I expect from a project like this? Not press related, but with regards to maintaining the project for my country. What should I expect?

**Comment by francois2metz** [comment]
Outside of communication, there is at least 2 differents things to do:

- maintaining the list of shops/brand status via Covid_enseigne
- reading and closing the notes created by the users via caresteouvert.

Depending of the country, you may also have to update the categories list to match it against the law.

**Comment by RockyTV** [comment]
Alright. I've asked last month if members of the community had information about their states' policies on the lockdown. I'm already gathering more data and will look forward to updating the `Covid_enseigne` repository with more shops and brands, and update the legal rules.

Is there anything you need from our part?

**Comment by francois2metz** [comment]
That's look good. 

I looked at the boundary of the Brazil, is this relation ok? https://www.openstreetmap.org/relation/59470

**Comment by RockyTV** [comment]
Yes, it is!

**Comment by francois2metz** [comment]
Ok, it'll take a look to add it in our config file.

**Comment by RockyTV** [comment]
I was keeping track of how the social isolation was going here in Brazil for about a week and I have some bad news.

Brazil has 27 states, each one with a different policy on what services/stores should open, which ones are considered essential and should stay open, along with a nation-wide policy that considers beauty saloons and barber shops as "essential services". State governors are lifting up these policies because they think it's all good (check Rio de Janeiro for example, both the city mayor and state governor are opening up everything throughout the state). We also have chain stores finding ways to bypass the states' restrictions so they can remain open.

I was really excited to get this working in Brazil but I don't think it's going to be worth it. We're the 2nd country with most infected and we still aren't nowhere near the infection peak. I don't think it's worth expanding "ça reste ouvert" to Brazil now that almost no one respects social isolation.

Just to be clear, it's not because of the amount of work that has to be done. It's just that, at least for me, it doesn't make sense to track open/closed stores in a country where almost everything is open and the infection rate is still high, while no one cares about the disease or following the health protocols anymore.

I'll still be committed to sending feedback and helping translate text and pages to Brazilian Portuguese, but with things the way they are in my country, I don't think it's a good idea to expand to Brazil.
