### ISSUE TITLE
Missing category: Museum

### ISSUE THREAD

**Issue by MatthieuOSM** [osmontrouge/caresteouvert#749]
**Name**: Museum
**Tagging**: tourism=museum
**Country**: France
**Example in OpenStreetMap**: https://www.openstreetmap.org/way/84081121
**Example in "Ca reste ouvert"**: https://www.caresteouvert.fr/@47.855080,-3.746490,19.00
**Icon**: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/tourism/museum.svg

**Comment by francois2metz** [comment]
Added in e5e82410a5fa06861a3f30da1189aac67d8e33a2
