### ISSUE TITLE
Afficher l'URL d'info des horaires d'ouverture sur tous les POIs

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#760]
Sur ce POI https://www.caresteouvert.fr/@48.822985,2.324153,17.48/place/n2219848300 je vois l'info "La prise de rendez-vous en ligne est conseillée."
Cool.

Par contre il n'y a pas l'affichage du lien cliquable https://www.fabiosalsa.com/onvaprendresoindevous/ qui est le champ "opening_hours_url"
Je n'arrive pas à comprendre pour quelle raison cela n'affiche pas alors que c'est bien présent sur d'autres POIs (exemple https://www.caresteouvert.fr/@48.824315,2.325178,16.94/place/n2273162705)

Autre cas un peu différent avec les caisses d'épargne https://www.caresteouvert.fr/@48.830287,2.328458,17.46/place/n3282330163 pour lesquels cette fois il serait pertinent d'afficher l'URL depuis Wikidata https://www.wikidata.org/wiki/Q1547738
Est-ce qu'on veut importer cet URL dans les données OSM ou plutôt aller le chercher direct depuis CRO ? That is ze question.

**Comment by vinber** [comment]
> Est-ce qu'on veut importer cet URL dans les données OSM ou plutôt aller le chercher direct depuis CRO ? That is ze question.

Ma réponse / l'ajout de brand:wikidata est fait pour éviter de mettre l'url générique du groupe sur chaque caisse d'épargne, donc mon avis "non pour importer l'url dans OSM"

**Comment by vinber** [comment]
> Je n'arrive pas à comprendre pour quelle raison cela n'affiche pas alors que c'est bien présent sur d'autres POIs (exemple https://www.caresteouvert.fr/@48.824315,2.325178,16.94/place/n2273162705)

c'est troublant de sortir du site. il me semble que lorsqu'il y a un lien sortant, d'avoir l'url souligné serait un plus. On s'attend à avoir un menu qui se déroule avec la flèche.

**Comment by overflorian** [comment]
Oui, sur la forme je suis d'accord qu'on peut faire mieux.

@vinber tu as évidemment raison pour l'URL générique, ça doit être géré par Wikidata. Du coup l'évolution de CRO devrait être d'afficher ces données depuis Wikidata. @PanierAvide @francois2metz ?

En parallèle on devrait je pense bosser à ajouter les URLs spécifiques pour chaque point de vente cf. https://lists.openstreetmap.org/pipermail/talk-fr/2020-May/099075.html

**Comment by PanierAvide** [comment]
À minima, on affiche le lien défini dans `opening_hours_url` si on n'a pas de site web plus précis renseigné sur le POI.

**Comment by overflorian** [comment]
Super, merci pour cette évol @PanierAvide 
du coup je ferme ce ticket car le sujet d'aller chercher des données depuis Wikidata est plus large que l'URL seul.
Je précise mon idée ici https://github.com/osmontrouge/caresteouvert/issues/765
