### ISSUE TITLE
Humaniser l'affichage des infos de contact

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#761]
Je propose de rendre plus lisibles les infos de contact pour les HUMAINS :
### Numéro de téléphone
Ne jamais afficher le format international, toujours séparer les numéros par blocs de 2.
_Exemple : "+33 1 43220904" devient "01 43 22 09 04"_
Il y a sûrement des subtilités à l'étranger ...

### URL
Ne jamais afficher le HTTP et le slash de fin.
_Exemple : "https://www.sushishop.fr/" devient "www.sushishop.fr"

### Page Facebook
Afficher le nom de la page
_Exemple : "https://www.facebook.com/Little-italy-Lyon-2%C3%A8me-1570496759855502/" devient "Little Italy Lyon 2ème"

En cliquant, les numéros de téléphone et URL originaux sont bien chargés.

**Comment by PanierAvide** [comment]
Pour les numéros de téléphone, c'est un peu tout le problème de comment ça se gère à l'étranger... On peut changer l'affichage à minima en France mais ce sera pas exhaustif.

**Comment by PanierAvide** [comment]
Fait, ce sera en ligne dans quelques minutes.
