### ISSUE TITLE
Display all activities/services proposed by a shop

### ISSUE THREAD

**Issue by FlorentRICHARD44** [osmontrouge/caresteouvert#764]
Some shops have several activies or services, in addition to the main one, but only the main one is displayed currently.

It should be better to display all in the shop details.
For example, in French for the "bar-tabac", with this node as example in OSM https://www.openstreetmap.org/node/3300604788  and in caresteouvert https://www.caresteouvert.fr/@47.517673,-1.295289,15.94/place/n3300604788 :
* it is displayed as "Café" in French "amenity=cafe" OK
* it is not displayed it sells tobacco ("shop=tobacco")
* it is not displayed it sells newspapers ("newsagent=yes")

With such information, people could know that they can do all their shoppings in the same shop and wouldn't have to go in several shops before to finally discover the second or third one propose everything they wanted. 

Note: I listed newsagent, tobacco, bar/restaurant, "salon de thé + épicerie fine", amenity=bar+ shop=beverages/alcohol, but they are maybe other activities and services I don't think about now. Maybe it is possible to detect "automatically" all key=value already used in filters.

**Comment by francois2metz** [comment]
I added support for `newagent=yes` in f5e0a8f328efeff65306f035ddc3a2b7f6141084.
