### ISSUE TITLE
Mettre le status "open" plutôt que "same" par défaut

### ISSUE THREAD

**Issue by zorun** [osmontrouge/caresteouvert#77]
On dispose maintenant d'une distinction entre "ouvert mais on ne sait pas si les horaires sont adaptés" (`opening_hours:covid19=open`) et "ouvert avec les mêmes horaires qu'avant le confinement" (`opening_hours:covid19=same`), cf. #64

Je propose que si l'utilisateur répond « Oui » à « ce lieu est-il ouvert », sans plus de précision, on utilise `opening_hours:covid19=open`. Actuellement on taggue avec `opening_hours:covid19=same` mais c'est trompeur.

L'intérêt serait ensuite de différencier ces deux tags sur l'interface de çaresteouvert, par exemple en encourageant d'avantage la contribution si le POI est actuellement taggué `opening_hours:covid19=open` (par exemple « ce lieu a-t-il des horaires adaptés ? »).

Ça permet aussi de visibiliser ces POI dans la base OSM et éventuellement de repasser derrière pour préciser.

**Comment by PanierAvide** [comment]
C'est implémenté, et ça va bientôt arriver en production : https://github.com/osmontrouge/caresteouvert_backend/commit/e5b0889a31c25b071da2731aaf62ff746ed9041b

**Comment by zorun** [comment]
Super :+1:
