### ISSUE TITLE
Missing category: (voyance et cartomancie)

### ISSUE THREAD

**Issue by Arianne-G-Voyance** [osmontrouge/caresteouvert#771]
**Name**: (voyance et cartomancie)

**Tagging**: (office=company)

**Country**: (country=FR)

**Example in OpenStreetMap**: (link starting with https://www.openstreetmap.org/node/...)

**Example in "Ca reste ouvert"**: (link starting with https://www.caresteouvert.fr/...)

**Icon**: (link starting with https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/...)

**Comment by francois2metz** [comment]
Bonjour.

Je vois que nous n'avez pas correctement rentré les informations pour nous permettre de rajouter cette catégorie (pour autant qu'on la veuille vraiment). Pouvez vous compléter la demande ?

**Comment by francois2metz** [comment]
Pas de nouvelles. Je ferme.

**Comment by Arianne-G-Voyance** [comment]
Bonjour Mr. François Metz,
Vos mails étaient dans mes Spam de Gmail, je viens de mettre en liste
blanche et indiqué NON SPAM dans Gmail (cela améliorera la réception de vos
mails pour la suite je pense).
Veuillez m'excuser, je n'avais pas bien comprise le système de validation.
Voici la fiche OSM :
https://www.caresteouvert.fr/@43.914460,2.129328,15.92/place/n6537124285
Je souhaitais attendre pour vous envoyer un mail pour connaitre la marche a
suivre n'ayant pas bien comprise le système (pas très forte en
informatique).
Je relance la demande dès le début de semaine.
Merci pour votre compréhension, votre patience et votre ouverture d'esprit
car je viens de comprendre que la catégorie va être créé suite de ma
demande et je vous en remercie par avance.

Cordialement,

*Arianne .G Voyance*
36, rue du 18 Août 1944, 81000 Albi
Tél : 05 67 34 13 43
Mon Cabinet : www.arianne-g-voyance.fr
Mon Blog : www.monastromag.fr


Le sam. 16 mai 2020 à 23:34, François de Metz <notifications@github.com> a
écrit :

**Comment by Arianne-G-Voyance** [comment]
Je n'y arrive pas ;-(, 
La catégorie "Autres établissements" est tout à fait suffisante.
Merci
