### ISSUE TITLE
Expand "Ça reste ouvert" data to Colombia

### ISSUE THREAD

**Issue by angoca** [osmontrouge/caresteouvert#772]
Please read https://github.com/osmontrouge/caresteouvert/wiki/Expand-%22%C3%87a-reste-ouvert%22-to-another-country first.

Please check the following requirements:

- [ ] You are a team of at least 2 people experienced with OpenStreetMap
- [X] Translate the app via transifex with your country languages
- [x] Translate some content of the blog to help newcomers (how to create a new shop, the about page, ...)
- [x] Start gathering data about chain stores open or closed nation wide, and legal opening rules in https://github.com/PanierAvide/Covid_enseignes/
- [ ] Once everything has been done and the data have been loaded, you should be busy getting media coverage. So the map will have a lot of contribution and be quickly useful.

Others questions:

- if you want a localized domain name, please tell us which one: 
- Each lockdown is different, what shops are open or closed in your country? What should be done in the category list?

**Comment by angoca** [comment]
It would be interesting to have a dedicated domain for each country, like [sigueabierto.co](sigueabierto.co)

Many supermarkets have access to pregnant women and old people starting the day. That means, the opening_hours tag is not enough to differenciate this.
Also, many cities have restrictions to go out of the house depending:

- Genre (Women even days, Men odd days)
- Last digit of the national ID

**Comment by francois2metz** [comment]
Hi there!

Thanks for reaching out! I hope you are well.

> It would be interesting to have a dedicated domain for each country, like [sigueabierto.co](sigueabierto.co)

It's possible.

> Many supermarkets have access to pregnant women and old people starting the day. That means, the opening_hours tag is not enough to differenciate this.

For this, we use the tag `description:covid19`.

> Also, many cities have restrictions to go out of the house depending:
> 
>     * Genre (Women even days, Men odd days)
> 
>     * Last digit of the national ID

Not sure this is something we want to support. "Ça reste ouvert" only display places that are allowed to open, it's a not a global information tool about a specific lockdown.

**Comment by francois2metz** [comment]
Hi there, I there is any news about this?
