### ISSUE TITLE
Display facebook links with correct chars and not encoded chars

### ISSUE THREAD

**Issue by FlorentRICHARD44** [osmontrouge/caresteouvert#778]
Facebook links with non ascii chars are displayed with encoded chars. This is not easy to read by user.
Example: "Nature-de-Ch%C3%AAne" instead of "Nature-de-Chêne"
![image](https://user-images.githubusercontent.com/12184477/82195181-424ee700-98f8-11ea-9fef-672270f20250.png)

https://www.caresteouvert.fr/@47.299387,-1.491755,16.22/place/w129163238
https://www.openstreetmap.org/way/129163238

Note that:
* the link is functionnal
* the tag contact:facebook in OSM is written with the encoded char (not with the proper accentuated char)

**Comment by PanierAvide** [comment]
À mon avis on peut résoudre ça avec un `decodeURIComponent` au niveau de l'affichage, pourrais-tu proposer une pull request pour corriger ça ?
