### ISSUE TITLE
Add specific icon for library

### ISSUE THREAD

**Issue by FlorentRICHARD44** [osmontrouge/caresteouvert#779]
Current icon for amenity=library is a "generic" icon. 
Please show a specific icon, such as a book.

**Comment by francois2metz** [comment]
Bonjour. Je peux bien voir une icone pourtant: 
![Screenshot_2020-05-18 Ça reste ouvert](https://user-images.githubusercontent.com/86659/82244785-0e98af00-9942-11ea-98bd-cd36868cb583.png)

Pouvez vous en dire plus ?

**Comment by FlorentRICHARD44** [comment]
L'icone n'est pas la même sur la carte 
![image](https://user-images.githubusercontent.com/12184477/82245969-31c45e00-9944-11ea-8033-9a06b57f70e8.png)

ainsi que sur les détails
![image](https://user-images.githubusercontent.com/12184477/82246007-3f79e380-9944-11ea-9699-297d2527b521.png)
https://www.caresteouvert.fr/@47.364979,-1.182421,18.06/place/w171445974

**Comment by francois2metz** [comment]
Ok, c'est que la catégorie n'est pas affiché pour la france, du coup aucun traitement n'est fait.
