### ISSUE TITLE
Ajouter la possibilité des horaires habituels "Hors confinement"

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#78]
à voir comment ->  pertinent pour l'amélioration à long terme d'OSM et pour pouvoir afficher les opening_hours:covid19=same qui n'ont pas d'horaires.

**Comment by PanierAvide** [comment]
Ça peut être dans un premier juste en demandant "est-ce que ce sont les horaires habituels" après la saisie des horaires de confinement ?

**Comment by PanierAvide** [comment]
Ça a été intégré avec le formulaire #79
