### ISSUE TITLE
Les liens doivent changer quand on change la langue

### ISSUE THREAD

**Issue by angoca** [osmontrouge/caresteouvert#780]
**Describe the bug**

**To Reproduce**
1. Changer la langue à Espagnol
2. Cliquer sur "Commerce manquant" ou "En Savoir plus"
3. Sur la nouvelle fenêtre, les liens pointent sur le site en Français uniquement. 

**Expected behavior**

Ces liens doivent pointer vers le site de la propre langue ou en Anglais eventuellement.

Les traductions doivent avoir les articles importants, où au moins ces que viennent du site principal.

**Desktop (please complete the following information):**
 - Windows
 - Chrome

**Comment by francois2metz** [comment]
Seulement certains liens ne sont pas disponibles en espagnol. Le lien pour rajouter un commerce manquant est bien fonctionnel: https://www.caresteouvert.fr/es/que-hacer-si-falta-un-comercio-en-sigue-abierto/

Pour les autres, je vous encourage a contribuer à la traduction: https://github.com/osmontrouge/caresteouvert_blog

**Comment by angoca** [comment]
Mais sur le site en francais, quand je fais changer la langue par example Anglais, il continue à pointer sur les sites en francais.

**Comment by PanierAvide** [comment]
Certains liens sont liés à la zone géographique affichés (donc dans la langue du pays), d'autres liens sont liés à la langue à condition d'être traduits. Le nom de domaine par lequel on arrive peut aussi avoir un impact (https://www.sigueabierto.es/ pour l'Espagne).

**Comment by francois2metz** [comment]
> Mais sur le site en francais, quand je fais changer la langue par example Anglais, il continue à pointer sur les sites en francais.

Pour la même raison que pour l'espagnol, le contenu de base est en français, et il n'a pas été systématiquement traduit.
Nous sommes preneur aussi de contribution pour l'anglais.
