### ISSUE TITLE
How to translate https://airtable.com/shrwKi4g2nJu0rwUK

### ISSUE THREAD

**Issue by angoca** [osmontrouge/caresteouvert#785]
**Is your feature request related to a problem? Please describe.**
When clicking on "Report a missing shop", the last item says "Vous avez votre propre établissement et vous avez besoin d'aide pour le rajouter :" and it points to a only french site. This sentence should be in Transifex, and there should be a way to translate that other page.

**Describe the solution you'd like**
Different languages for the site to add.

**Describe alternatives you've considered**
Currently, the Google translator for the browser, but this is not always the best thing.

**Additional context**
This happens for English, Spanish, and I think for all proposed language from the main site.

**Comment by francois2metz** [comment]
This is only displayed when the current country displayed is France, and we expect that the visitor can read French as it's an French speaking only service. We have no intend to internationalize it for now. So no need to translate it.
