### ISSUE TITLE
lieu culturel

### ISSUE THREAD

**Issue by promeneur** [osmontrouge/caresteouvert#794]
Bonjour

Des lieux culturels 'musées, monuments etc.) ouvrent à nouveau.
Voir
https://www.culture.gouv.fr/Aides-demarches/Covid-19-le-ministere-informe/Deconfinement-carte-des-lieux-culturels-rouverts

Il serait bon de les signaler dans caresteouvert. Non ?

**Comment by fansanelli** [comment]
Bonjour,

This have been fixed today... Can you please check?

Cheers
Francesco

**Comment by promeneur** [comment]
I do not see any change.
Can you provide a screenshot, please ?

Thanks

**Comment by fansanelli** [comment]
> I do not see any change.
> Can you provide a screenshot, please ?
> 
> Thanks
Please see:

https://github.com/fansanelli/caresteouvert/blob/b7869c38f1062578686e65e3c9abfe5cc848ed90/categories.json#L115

**Comment by promeneur** [comment]
Ah ok it is in "Autres établissements".

Perhaps we need to add a new category as "Culture" because it is drowned in many things.

Thanks

**Comment by francois2metz** [comment]
Museums are displayed in France. See https://www.caresteouvert.fr/amenity%2Fmuseum@48.855045,2.345070,16.28
