### ISSUE TITLE
The text from the "buttons" should not be forced to be in capitals

### ISSUE THREAD

**Issue by angoca** [osmontrouge/caresteouvert#795]
Les buttons de commence manquant (Suivez le guide et Demande l'ajout) et du Changer la langue, ne doivent pas entre en majuscule. Dans des certains langues ca peut etre considere comme crier ou offensive.

**Comment by francois2metz** [comment]
C'est le comportement par défaut des boutons dans material design. 
Quel ce qui fait que certains boutons ne paraissent pas offensif ?
