### ISSUE TITLE
Beaucoup de blanc autour des icones dans les picto

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#8]
Et donc les icônes paraissent petits ?

**Comment by francois2metz** [comment]
A tout hasard tu connaitrais une personne qui connait bien les style mapbox ? Sur l'affichage il y a un truc que j'aimerais bien faire comme cacher les labels sur les zoom bas.

**Comment by PanierAvide** [comment]
Je peux essayer de bricoler ça, pour les icônes je soupçonne que ce soit les SVG de départ qui sont à des tailles différentes qui provoquent ça, mais la modif de leur taille pose des soucis dans le fichier sprite.

**Comment by pyrog** [comment]
>  je soupçonne que ce soit les SVG de départ qui sont à des tailles différentes qui provoquent ça

Je vois ça aussi. 

Il faut probablement homogénéiser les tailles des SVG.

**Comment by PanierAvide** [comment]
C'est fait, les SVG sont désormais en taille 18px.
