### ISSUE TITLE
Problèmes sur la recherche d'adresses / de lieux

### ISSUE THREAD

**Issue by fbroussais** [osmontrouge/caresteouvert#80]
Bonjour,
La recherche d'adresse fonctionne très mal (i.e. qu'elle marche environ 1 fois sur 5)  sur certaines villes, notamment celles dont les N° de rue sont peu renseigner dans OSM. Elle est également peu permissive sur la saisie des noms.
Exemples sur Nancy, France :
```
Adresses:
13 Rue Saint Dizier : OK
14 Rue Saint Dizier : rien
rue Saint Dizier, nancy : OK

1 Rue Saint Georges : OK
rue saint-georges : OK
1 Rue Saint-Georges : rien
(donc tiret sans n° de rue, mais espace si n° de rue)

cour des arts : non répertoriée
```
Sur ces éléments, https://adresse.data.gouv.fr/ s'en tire mieux
(sauf que cette API ne recense pas les lieux...)

**Comment by PanierAvide** [comment]
C'est probablement lié à #74

**Comment by fbroussais** [comment]
Pour le tiret dans les noms, peut-être.
Pour le résultat non retourné si le n° n'existe pas, c'est peut-être dans l'API jawg (même pb sur leur géocodeur https://www.jawg.io/fr/geocoding/)

**Comment by gendy54** [comment]
Et pourquoi pas https://demo.addok.xyz/#12/48.8500/2.3500
Ca cherche très les adresses et les POI.

**Comment by wadouk** [comment]
il faudrait changer de géocodeur ? quelqu'un de jawg pourrait dire en quoi le géocodeur est mal utilisé ?

y en a pleins des géocodeurs, jamais essayé addok, nominatim ou geonames c'est assez laborieux aussi ...

sinon, au moins enlever le champs de recherche ? dire que juste les villes fonctionnent ?

**Comment by fbroussais** [comment]
Sujet pas si simple en effet.

"Addok+POI" ne propose qu'une démo, il faut a priori l'installer sur son serveur, mais le mieux est de voir avec leurs auteurs https://github.com/osm-fr/osmpoi4addok 

A ma connaissance, jawg utilise Pelias, il a peut-être des paramètres à ajouter lors de l'appel pour avoir des résultats plus larges, car pour avoir testé un peu Pelias, il me semble capable de faire mieux en terme de recherche. Jawg a donc peut-être la solution.

**Comment by wadouk** [comment]
kiki a un contact chez jawg ? je vois qu'il y a 2 personnes dans la compagnie https://github.com/jawg, on ping directement ?

**Comment by fbroussais** [comment]
Je me demande si ça ne serait pas juste une erreur du côté de l'IHM.
La recherche de "1 rue saint-georges, nancy" renvoie bien quelque chose depuis jawg, mais pas de résultat sur l'appli web.
https://api.jawg.io/places/v1/search?boundary.country=FRA&text=1%20rue%20saint-georges%2C%20nancy&access-token=QRajeAKRBSKrFYnU1InkHcNJUZtcArA5xDOetW0CqQzmy9XVRF0IX1sGQ7oHrjaD

![image](https://user-images.githubusercontent.com/360608/78255592-c50e1500-74f7-11ea-83c4-09fc981b259d.png)

**Comment by wadouk** [comment]
effectivement, et il y a le dernier caractère frappé qui est ignoré aussi, rajouté une temporalité sur la complétion fera le taf.

**Comment by wadouk** [comment]
très bizarre, et je pense que je vais arriver à mon niveau d'incompétence sur vue ... l'api retourne plusieurs résultats et la complétion n'affiche aucune proposition, et quand l'api me donne 1 résultats, j'ai 19 proposition dans la complétion.
![image](https://user-images.githubusercontent.com/787448/78292886-08807780-7528-11ea-8351-2176339bb780.png)

**Comment by francois2metz** [comment]
Je pense que c'est du au `cache-items` de l'autocomplete. Je vais le supprimer.

Et je vais mettre un debounce sur la requête pour être sur de choper le dernier caractères en évitant de trop taper sur l'api.

**Comment by wadouk** [comment]
J'arrive à la même conclusion, mais il va falloir de toute façon annuler les requêtes parties et pas encore revenu si on reprends la frappe. Un fetch s'annule avec un signal et AbortController (je découvre).

**Comment by francois2metz** [comment]
@wadouk Tu veux le faire ?

**Comment by wadouk** [comment]
@francois2metz pas assez compétent pour l'instant sur vue. ça m’intéresse de regarder et c'était au cas où mais là me sens pas assez sùr. Je pense que tu iras plus vite.

**Comment by wadouk** [comment]
ps : j'ai juste joué à supprimer le cache (en gros le commit précédent sur le fichier geocoder.vue) et l'ihm rame énorme.

**Comment by francois2metz** [comment]
Il y avait un filtre supplémentaire dans le composant :/ Du coup on n'affichait rien des fois. J'ai corrigé tout cela.

**Comment by Joxit** [comment]
Bonjour, vous pouvez me ping si vous avez des soucis sur notre geocodeur, je suis plutôt actif sur GitHub :)

@wadouk les autres membre ont caché leur appartenance à l'orga GitHub ^^
