### ISSUE TITLE
https://taimidoscailte.ie/ defaulting to "en" locale (config says "ga")

### ISSUE THREAD

**Issue by donalhunt** [osmontrouge/caresteouvert#805]
**Describe the bug**
The Irish language portal for caresteouvert which was turned on is appearing in English, not Irish.

**To Reproduce**
1. Go to https://taimidoscailte.ie/
2. Lock at the left hand nav.
3. Nav will be in english.

**Expected behavior**
Expect the text to be in Irish (Gaeilge).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (Debian 10)
 - Browser: Chrome
 - Version: 

**Smartphone (please complete the following information):**
 - Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by donalhunt** [comment]
Screenshot: ![Screenshot from 2020-05-29 16-35-05](https://user-images.githubusercontent.com/5854402/83277769-6fd64300-a1ca-11ea-8dbb-c2828b1b6d11.png)

**Comment by francois2metz** [comment]
Hi!

When putting irish locale first in my browser, it works.

Also with curl: 

> curl https://taimidoscailte.ie/ | htmlq 'title'
> <title>Tá sé fós ar oscailt</title>

Can you try using a browser configured with Irish as the preferred language please?

**Comment by donalhunt** [comment]
Is there a way we can have the page default to "ga" locale even if the browser locale is not set to gaeilge (irish)? It would be common for many Irish speakers to use english as a browser locale (and Microsoft have just announced they are dropping support for Irish in some of their products).

**Comment by francois2metz** [comment]
Right now there is no way to force the locale, we respect the user choice.

As far as I know, the browser locale and Microsoft products is not related.

**Comment by Bibi56** [comment]
By default the browser use the OS language, but you can change the browser options, about:preferences in FireFox for instance to set `ga` first, then `en`. I used it to demonstrate Nominatim in Swahili. The next time I logged on my Microsoft web account I was a bit surprised ;-).
I guess if your favorite language is Irish it's safe to set the default language to Irish, the second to English. that's how I got the texts in French ;-).

**Comment by donalhunt** [comment]
No worries. Thanks for the explanation.
