### ISSUE TITLE
Missing "laboratoire d'analyse médical", healthcare=laboratory

### ISSUE THREAD

**Issue by promeneur** [osmontrouge/caresteouvert#807]
missing "laboratoire d'analyse médicale"

healthcare=laboratory

EXALAB Caudéran Leclerc
113 Avenue du Général Leclerc
33200 Bordeaux
France

laboratoire.exalab.fr/cauderan-leclerc-1.html

thanks

**Comment by overflorian** [comment]
Bonjour @promeneur,
Pour ajouter un lieu aujourd'hui inexistant, il suffit de suivre ce guide https://blog.caresteouvert.fr/que-faire-sil-manque-un-commerce-dans-ca-reste-ouvert
Je vous laisse donc le faire par vous-même, au plaisir

**Comment by promeneur** [comment]
Je me suis mal exprimé. Le lieu existe depuis longtemps. caresteouvert ne l'affiche pas.

**Comment by promeneur** [comment]
ni qwant/maps ni osm d'ailleurs

**Comment by overflorian** [comment]
ok. peux-tu stp fournir l'URL ?

**Comment by promeneur** [comment]
https://www.openstreetmap.org/?mlat=44.85394&mlon=-0.61076#map=19/44.85394/-0.61076

**Comment by vinber** [comment]
Un laboratoire qui remonte https://www.caresteouvert.fr/@44.767646,-0.580849,16.72/place/n7282919238

est-ce parce que le labo dont parle @promeneur n'a pas de tag covid:19 ?
