### ISSUE TITLE
facebook tag, url is badly interpreted

### ISSUE THREAD

**Issue by promeneur** [osmontrouge/caresteouvert#809]
In case of facebook=www.facebook.com/BAR-Le-cerey-490974291235545/
then careste ouvert tries to open
https://facebook.com/www.facebook.com/BAR-Le-cerey-490974291235545/

facebook=www.facebook.com/BAR-Le-cerey-490974291235545/ is a valid expression among several others .

**Comment by francois2metz** [comment]
Il manque la partie `https://` sinon ce n'est pas une URL valide. A corriger directement dans OSM.
