### ISSUE TITLE
What's next?

### ISSUE THREAD

**Issue by sfkeller** [osmontrouge/caresteouvert#812]
As was to be expected, the lockdown will soon be lifted, and "stay open!" makes no sense anymore at all. 

But there would be a purpose of this nicely done webapp - to show which shops are "open again" [1] - as I already suggested in #616 46 days ago.

So: What's next with this nice project?

[1] See for example for Basel https://telebasel.ch/2020/05/08/raus-aus-dem-lockdown-wer-in-basel-wann-oeffnet/

**Comment by francois2metz** [comment]
Hi,

Right now there is no ongoing work to adapt the code to the post-pandemic state. Here is the quick list of the thing that need to be done:

- the import and update the of the tables would need to be updated to be simpler and avoid doubling the size of the data
- we need to find long terms partners to host the multiple services and provides the basemap and the geocoder
- The POI editor and the API needs at least a small overhaul. (FIY I contributed several patches to https://gitlab.com/geometalab/osmybiz)
- as always, there is a gazillions of things to do and improve

**Comment by lud-bmgrt** [comment]
we would be happy with ongoing work in this nicely done webapp , perhaps in a more general direction "is open"  to show opening_hours-Data in our  osm.org-Database.
