### ISSUE TITLE
Adding Wikimedia Italia's logo on the Italian version of "Ca reste ouvert"

### ISSUE THREAD

**Issue by anisakuci** [osmontrouge/caresteouvert#814]
Hello "Ca reste ouvert" team!

As you know the OSM Italy community has translated and adapted the project for the Italian users since a while (https://restiamoaperti.it/) and it is still active at the moment.

OSM Italy is a local chapter under the [Wikimedia Italia](https://www.wikimedia.it/) (WMI) association, so I was wondering whether it would be possible to add the WMI logo on the Italian version of the website.
I currently work for Wikimedia Italia and we want to promote the project in our channels, so, we would really like to be visually present hopefully on the main page of the Italian website.

If you agree with this idea, we can either add the logo separately or modify the Italian one.
But this can be further discussed depending on the feedback.

Please let me know your thoughts on this!

Thank you very much in advance,

Anisa Kuci

**Comment by francois2metz** [comment]
Hi,

As we do not include any logo in the homepage (except "Ça reste ouvert" and their localized variants), I'm not very keen to accept this request. Others team members may have another opinion!

**Comment by francois2metz** [comment]
Without any comments from the team, I'm closing.

**Comment by anisakuci** [comment]
Thank you very much for the feedback @francois2metz !
