### ISSUE TITLE
Import updated translations for Irish (gaeilge).

### ISSUE THREAD

**Issue by donalhunt** [osmontrouge/caresteouvert#815]
**Describe the bug**

**To Reproduce**
1. Go to https://stayingopen.ie/
2. Click on "Change language"
3. Scroll down to 'Béarla'
4. See error (should be 'Gaeilge.)

**Expected behavior**
The option to switch to Irish should be labelled "Gaeilge".

**Screenshots**
![Screenshot from 2020-06-27 11-48-42](https://user-images.githubusercontent.com/5854402/85920496-30078780-b86c-11ea-998f-9ba853ad40ac.png)
![Screenshot from 2020-06-27 11-50-06](https://user-images.githubusercontent.com/5854402/85920528-6218e980-b86c-11ea-9efa-22ef97fdab2b.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: Version 81.0.4044.129 (Official Build) (64-bit)

**Additional context**
The string was updated in transifex over 1 month ago but has not made it to the production instance yet.

**Comment by francois2metz** [comment]
Hi there,

It seems that there is some missing translation. That's why the update has not been done. Could you translate the 4 remaining strings? Transifex will then create the pull request.

**Comment by donalhunt** [comment]
The 4 remaining strings have been added.

**Comment by francois2metz** [comment]
Thanks. With the PR merged this should be live in a minute.
