### ISSUE TITLE
English language corrections...

### ISSUE THREAD

**Issue by donalhunt** [osmontrouge/caresteouvert#818]
Some of the (english) source strings in transfix could be improved...

> This place has definitely closed. What's there now instead ? Give as many details as possible, for example: under construction building, new business...
This place has permanently closed. What's there now instead? Give as many details as possible, for example: under construction building, vacant, new business...

> Definite closing
Closed permanently

**Comment by francois2metz** [comment]
Hi! Your suggestions are looking good. Could you submit a PR?
