### ISSUE TITLE
Ca Reste Ouvert future: Closing operations Septembre 30.

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/caresteouvert#823]
We (the "Ca Reste Ouvert" team) plan  to close the website and cease operations Septembre 30 2020.

Here is the things to do:

- [x] Display a message on the website with the announce
- [x] Create a simple webpage once everything has been taken down
- [x] Stop the API
- [x] Stop the planet update
- [x] Stop tiles and features services
- [x] Stop the geoip service
- [x] Stop the matomo service
- [x] Stop the cron

**Comment by francois2metz** [comment]
We will need to keep one service on scalingo so localized domains will still works.

**Comment by francois2metz** [comment]
@vdct Tu pourrait stopper la réplication du serveur osm-fr ?

**Comment by vdct** [comment]
@francois2metz oui volontiers, j'ai juste un souci d'accès à la machine, je vais me rapprocher de la team OSM-Fr

**Comment by francois2metz** [comment]
I closed all the related services. Once the planet replication is stopped, we can release the osm-fr vm.

**Comment by francois2metz** [comment]
@PanierAvide Tu pourra enlever les enregistrements DNS `geo`, `tiles`, `features` et `s` ? Ca permettra de supprimer les applications scalingo en toute sécurité.

**Comment by PanierAvide** [comment]
C'est fait :wink:

**Comment by francois2metz** [comment]
Je ne vois pas de nettoyage restant a faire. Quelqu'un pense a quelque chose qui manquerait ?

**Comment by overflorian** [comment]
Je propose de rajouter sur la home la mention "La communauté OpenStreetMap se retrouve maintenant sur ProjetDuMois.fr" en rajoutant le logo de pdm.
à part ça, on est bons.

**Comment by vdct** [comment]
On est d'accord sur le shutdown de la VM mise à dispo par OSM-FR ?

**Comment by francois2metz** [comment]
> On est d'accord sur le shutdown de la VM mise à dispo par OSM-FR ?

Oui

**Comment by vdct** [comment]
> On est d'accord sur le shutdown de la VM mise à dispo par OSM-FR ?

C'est comme fait, cf mon mail @tech

**Comment by francois2metz** [comment]
🔥 🔥 Ça reste ouvert is closed 🔥 🔥
