### ISSUE TITLE
Affichage des restaurants proposant un service takeaway

### ISSUE THREAD

**Issue by QuentinS33** [osmontrouge/caresteouvert#83]
Bonjour,
Dans ma commune, certains restaurants restent ouverts mais les commandes peuvent être récupérés sur une plage d'horaire donnée. Est-il possible de les afficher si le tag "takeway:covid19" est présent sur le restaurant ?

Merci d'avance pour votre retour

PS: Super boulot aux développeurs et contributeurs de l'application

**Comment by PanierAvide** [comment]
Bonjour Quentin,

Merci de ce retour. En pratique, si le tag `opening_hours:covid19` est renseigné, on affiche le restaurant. On a dans les tuyaux de mieux gérer les tags takeaway/delivery.

**Comment by QuentinS33** [comment]
Bonjour Adrien,

Merci pour ton retour. D'accord, j'attends que cela soit bien mis en place car en effet je ne peux pas mettre opening_hours:covid19=open/same sur un établissement fermé. Même si on peut récupérer des commandes

**Comment by PanierAvide** [comment]
Le mieux pour gérer ces cas là serait sûrement d'indiquer `opening_hours:covid19=open + takeaway:covid19=only` non ?

**Comment by QuentinS33** [comment]
Je t'avoue que je ne sais pas trop. Avec du recul, je pense que tu as raison. Je vais les tagguer comme ça.
J'ai fait une contribution il y a quelques heures sur des restaurants fermés et l'icone du restaurant s'est bien affiché avec un contour rouge.

**Comment by PanierAvide** [comment]
Ça marche, de mon côté je suis en train d'ajouter l'affichage de ces infos

**Comment by PanierAvide** [comment]
C'est intégré via 81df862 (dispo dans quelques minutes sur le site) : si un lieu est affiché (tag `opening_hours:covid19` renseigné ou catégorie affichées par défaut) et qu'il dispose de tags delivery/takeaway:covid19, alors ce sera affiché dans le panneau de droite (bandeau bleu d'infos).
