### ISSUE TITLE
osmmotrouge ?

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#830]
je me doute que c'est l'histoire qui fait cela mais le dépot osmmontrouge/caresteouvert est difficile à renommer je suppose ?
on perd les actuelles personnes qui suivent ce dépot ?

**Comment by overflorian** [comment]
je crois que techniquement c'est possible mais en effet si des personnes ont le lien peut-être perdront-ils le lien. Je n'ai jamais essayé. Mais bon tu vois un autre repo plus légitime toi ? Jungle Bus ? OSM-Fr ? Il y a toujours des inconvénients, je trouve.

**Comment by vdct** [comment]
Personnellement ça me semble un faux problème. Par exemple oe rendu carto d'osm.org est ici : https://github.com/gravitystorm/openstreetmap-carto est-ce que ça gêne quoi que ce soit ? Peu importe l'URL (et encore plus son changement) si la gouvernance est ok je pense

**Comment by vinber** [comment]
ok, faux problème et pas simple, on ferme :)

**Comment by vinber** [comment]
j'imaginais une "organisation" ca reste ouvert au sens github
