### ISSUE TITLE
Permettre de préciser dans le formulaire si l'endroit permet la livraison ou la vente a emporter

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/caresteouvert#85]
Pour continuer a diminuer le nombre de notes et avoir la meilleure information sur les commerces, rajouter dans le formulaire la possiblité de spécifier si:

- le lieu fait de la vente a emporter (cela veut-il dire inclure les restaurants ?) (yes/only)
- le lieu fait la livraison (yes/only)

Il faut filtrer au minimum les catégories pour éviter de demande cela sur la police.

**Comment by glyo-rb1** [comment]
je suis pour l'ajout des restaurants faisant de la vente à emporté

**Comment by francois2metz** [comment]
L'entrée de formulaire a été rajouté.

![Screenshot_2020-04-02 Ça reste ouvert](https://user-images.githubusercontent.com/86659/78235238-9e8cb180-74d8-11ea-9b24-d336f9fa50cb.png)
