### ISSUE TITLE
Ajouter un lien pour éditer avec iD/JOSM

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/caresteouvert#86]
Quelques contraintes que nous nous sommes fixé

- Sur les lieux seulement.
- N'afficher que sur desktop.
- rester discret

**Comment by caugner** [comment]
Un lien vers l'objet OSM serait une première étape.

**Comment by francois2metz** [comment]
Fait dans d3d4c8e3b454e0c479ec59d9b5e9bb66c7f31311
