### ISSUE TITLE
Se souvenir de la localisation utilisée entre les sessions

### ISSUE THREAD

**Issue by GarenKreiz** [osmontrouge/caresteouvert#91]
Actuellement le site s'ouvre par défaut avec un zoom sur Paris. Il pourrait être intéressant d'utiliser un cookie pour mémoriser la position de la dernière consultation.

Paris étant riche en POI cela pourrait peut-être aussi réduire un peu le charge sur le serveur.

**Comment by francois2metz** [comment]
Merci de la suggestion.

C'est implémenté dans bb8bc97e99036f9f211f99a72e7dab356a33b63f et en live dans quelques minutes.

**Comment by GarenKreiz** [comment]
Merci, ça marche effectivement. Bravo pour la réactivité.
