### ISSUE TITLE
German version does not work anymore

### ISSUE THREAD

**Issue by aletsch** [osmontrouge/caresteouvert#914]
**Describe the bug**
The bug is that the version for germany isn't working anymore. Maybe it worked before some time but now it doesn't anymore.

The german website "bleibtoffen.de" is inacessible and the sections "blog" etc. in the Android app will direct you to a different site "bleibtoffen.org" which is mostly in french

When you zoom into the map (android app) anywhere beyond france the map will just not load anymore.

**To Reproduce**
Open the android app an zoom to any place in germany or click on the links.

**Expected behavior**
The map should load and the server should be accessible.

**Desktop (please complete the following information):**
 - OS: Android 11
 - Browser: Firefox/App

**Comment by overflorian** [comment]
Hi, thank you for bringing that up.
This German version was deployed by a local contributor see https://github.com/caresteouvert/caresteouvert/issues/149
As our tool is not really in use anymore, I guess the domain name has been deactivated by him.

To be honest, we are considering switching down the whole platform, therefore if you are interested into maintaining it, please let us know.
Regards
