### ISSUE TITLE
Avoir un filtre pour connaitre les magasins ouvert a la livraison

### ISSUE THREAD

**Issue by francois2metz** [osmontrouge/caresteouvert#92]
Sur une suggestion https://twitter.com/JulienDamelet/status/1244897058076712970

**Comment by francois2metz** [comment]
@PanierAvide Que pense tu de rajouter l'information `delivery:covid19` directement dans les tuiles ?

**Comment by PanierAvide** [comment]
Pourquoi pas oui, si on en a besoin pour les filtres. Il faudrait que l'info soit disponible comme colonne dans la table poi_osm pour une récupération plus rapide que la lecture du hstore `tags`

**Comment by PanierAvide** [comment]
Je t'ai ajouté ça dans la vue poi_osm_light, ce sera dispo à la prochaine màj de la base

**Comment by fbroussais** [comment]
J'allais faire la même demande. On a des restau qui font de la livraison à domicile.
