### ISSUE TITLE
takeway=only est affiché, alors que c'est fermé

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#93]
Si on regarde cela on imagine pouvoir y aller : https://www.caresteouvert.fr/@44.842083,-0.574326,17.47/place/n1741692437 au moins pour emporter.

Or le takeway=only est le fonctionnement habituel hors confinement (https://www.openstreetmap.org/node/1741692437/history) et les bricohes dorées semblent toutes fermées https://www.briochedoree.fr/restaurants/107-bordeaux-intendance

**Comment by PanierAvide** [comment]
C'est corrigé, on affiche les tags `delivery/takeaway` si le lieu est déclaré ouvert et s'il n'y a pas de tag spécial covid19.
