### ISSUE TITLE
Enable for all Spain and Andorra

### ISSUE THREAD

**Issue by yopaseopor** [osmontrouge/caresteouvert#94]
Your map is awesome, and we will translate it. But would be able to edit for all Spain? I think is silly to try to reinvent the wheel. For Spanish community would be more interesting to start editing points in Spain instead of trying to create something similar in Spain.

**Comment by francois2metz** [comment]
Hi thanks for reaching us about this.

There is at least 2 solutions for this:

- you deploy the code yourself (we need to document how to do it in english), if you have the resources to do it, or;
- we do it for you. Here are the few things I'm thinking about:

- [ ] Have a localized domain name
- [ ] Have the data loaded and updated alongside the french one
- [ ] Have a spanish translation
- [ ] Start gathering data about spanish shop open or closed nation wide, similar to https://github.com/PanierAvide/Covid_enseignes/blob/master/regles.csv.

**Comment by francois2metz** [comment]
@yopaseopor Can you tell us more about what is open and closed in Spain and which categories of POI should be displayed ?

**Comment by yopaseopor** [comment]
In Spain we open only essential services, said by the law. 
You can see in https://boe.es/boe/dias/2020/03/29/pdfs/BOE-A-2020-4166.pdf
If we read that we can find in OSM words these terminology:

amenity=fuel
amenity=atm

amenity=pharmacy

amenity=post_office

amenity=hospital
amenity=doctors
amenity=clinic

shop=convenience
shop=supermarket

shop=bakery
shop=car_repair
shop=kiosk
shop=optician
shop=greengrocer
shop=funeral_directors
shop=medical_supply
shop=gas
shop=butcher
shop=grocery
shop=seafood

 Also these are the specific restauration places they have to be open (https://boe.es/boe/dias/2020/03/30/pdfs/BOE-A-2020-4194.pdf )

Other places are opened but only in take away or delivery home only mode

amenity=restaurant
amenity=cafe
amenity=pub

Other are opened but only by phone attention.

**Comment by francois2metz** [comment]
@yopaseopor Hi there. Thanks for your patience.

We are almost ready. Could you take a look at the requirements listed there https://github.com/osmontrouge/caresteouvert/blob/master/.github/ISSUE_TEMPLATE/expand-data-to-my-country.md and update this issue?

**Comment by yopaseopor** [comment]
Update to day: 2020-04-06

- [x]     You are a team of at least 2 people experienced with OpenStreetMap
OSM Spain and Catalan community are aware of that
- [x]    Translate the app via transifex with your country languages
We have translated in Catalan, Galician and Spanish
- [ ]    Translate some content of the blog to help newcomers (how to create a new shop, the about page, ...) 
We will do soon as we have the code of these articles in transifex or What would be the better way to translate it?
- [x]     Start gathering data about shop open or closed nation wide in https://github.com/PanierAvide/Covid_enseignes/
Done by Spanish community
    Once everything has been done and the data have been loaded, you should be busy getting media coverage. So the map will have a lot of contribution and be quickly useful.

I will talk with Spanish  community to activate something like http://sigueabierto.openstreetmap.es

**Comment by francois2metz** [comment]
@alejandroscf you can point to the international name with a CNAME `aperta.fr`.

**Comment by alejandroscf** [comment]
I've just set up the CNAME

**Comment by francois2metz** [comment]
@yopaseopor it's live on caresteouvert.fr. Could you send me an email to francois [at] 2metz [dot] fr or a tweet to @francois2metz so I can send you an invitation link to our internal discussion board ?

**Comment by PanierAvide** [comment]
Closing the issue as it is now live.

**Comment by jibix2256** [comment]
> 
> 
> In Spain we open only essential services, said by the law.
> You can see in https://boe.es/boe/dias/2020/03/29/pdfs/BOE-A-2020-4166.pdf
> If we read that we can find in OSM words these terminology:
> 
> amenity=fuel
> amenity=atm
> 
> amenity=pharmacy
> 
> amenity=post_office
> 
> amenity=hospital
> amenity=doctors
> amenity=clinic
> 
> shop=convenience
> shop=supermarket
> 
> shop=bakery
> shop=car_repair
> shop=kiosk
> shop=optician
> shop=greengrocer
> shop=funeral_directors
> shop=medical_supply
> shop=gas
> shop=butcher
> shop=grocery
> shop=seafood
> 
> Also these are the specific restauration places they have to be open (https://boe.es/boe/dias/2020/03/30/pdfs/BOE-A-2020-4194.pdf )
> 
> Other places are opened but only in take away or delivery home only mode
> 
> amenity=restaurant
> amenity=cafe
> amenity=pub
> 
> Other are opened but only by phone attention.
> Also we can redirect something similar to http://sigueabierto.openstreetmap.es
> 
> Thanks for your help

Bonjour/Hola

Jean-Baptiste here, French (Breton) currently living in Spain.

As just discussed yesterday/today with the Spanish community:
-> shop=chemist is missing. Could you please add it?
-> I just placed an order for sigueabierto.es. I plan/hope to make CNAME redirect later today.

Yopaseopor also invited me to the framateam, I'll have a look later today

Merci.
-JB
