### ISSUE TITLE
Ajouter les mairies/offices du tourisme

### ISSUE THREAD

**Issue by vinber** [osmontrouge/caresteouvert#95]
dans beaucoup de cas, les informations sont centralisées par les mairies, concernant les services, commerces ouverts au public.
Les mairies ont elle même des horaires adapatées (exemple ici de l'ajout dans la description https://www.openstreetmap.org/node/369314978#map=19/44.85010/0.48535).

Je pense que les mairies pourraient avoir leur place ici

**Comment by PanierAvide** [comment]
À priori c'est assez complexe :
* Les services d'état civil sont d'astreinte probablement partout
* D'autres services peuvent être sur rendez-vous
* Les agents répondent au téléphone/courriel mais n'accueillent pas forcément le public

**Comment by francois2metz** [comment]
On a eu le même retour sur Montrouge. C'est fermé au public.

**Comment by PanierAvide** [comment]
Même constat que #12 :
- C'est pertinent d'afficher les mairies et surtout les infos de contact
- Mais en aucun cas on ne doit _inciter_ à s'y rendre. On doit bien au contraire afficher un message d'avertissement clair pour recommander le contact téléphonique avant tout déplacement.

@overflorian Quel message peut-on donc afficher pour rendre ça clair ?

**Comment by OcelotNat** [comment]
avec le même amenity=townhall sur une surface, certaines s'affichent mais pas d'autres :

- apparait : Sazos : https://www.caresteouvert.fr/@42.883693,-0.024343,19.11

- n'apparait pas : Rouen : https://www.caresteouvert.fr/@49.443278,1.099938,17.95

J'ai l'impression que s'il y a un autre POI dans la surface, ça bloque. Le problème est connu ?

**Comment by PanierAvide** [comment]
Pour l'instant les mairies ne sont pas affichées par défaut. Mais comme il est prévu que les objets ayant `opening_hours:covid19=*` apparaissent, les mairies qui ont ce tag sont affichées. D'où la différence entre Rouen et Sazos.

**Comment by OcelotNat** [comment]
Merci pour le retour !

**Comment by PanierAvide** [comment]
Tant qu'on a pas résolu #317 ça me paraît compliqué d'afficher une info pertinente sur les mairies. Je ferme le ticket.

**Comment by vinber** [comment]
Les mairies et les office de tourisme avec qui nous travaillons sont pour la plupart non accessible au public mais ouverte, dans le sens de permanences téléphoniques. Donc on se retrouve avec le cas : opening_hours:covid19=* et access:covid19=no.

Dans le cas des mairies (amenity=townhall), cela semble apparaitre si il y a le tag opening_hours:covid19

mais pas pour les office de tourisme (tourism=information) comme celui ci https://www.openstreetmap.org/node/1254995830#map=20/43.83243/-0.80895
il ne remonte pas : https://www.caresteouvert.fr/@43.832686,-0.808847,18.00

Cela peut-être un facteur d'utilisation par ces structures de se voir sur ca reste ovuert et donc de participer !

De là à les faire apparaitre en gris par défaut pour les pousser à l'usage, j'y suis favorable oui :)

**Comment by PanierAvide** [comment]
Pour les offices de tourisme, on a besoin du tag `tourism` qui n'est pas importé dans notre base pour l'instant (voir #401), mais on va régler ça ;-)

Donc on part sur un affichage en l'état, ou on a moyen d'avoir un peu de données en amont dans OSM, sur la base d'un référentiel ou jeu de données qui aurait été ouvert ?

**Comment by vinber** [comment]
non pas à ma connaissance, je me renseigne cependant en // auprès des mairies et OT

**Comment by vinber** [comment]
il y a cela https://www.collectivites-locales.gouv.fr/files/files/dgcl_v2/covid19/recommandation_ministres_continuite_des_services_publics_21032020.pdf

on y trouve 

> dans les services pour lesquels un accueil physique est jugé indispensable: restriction des plages horaires d’accueil et réception sur rendez-vous, mise en place  de  gestion  des  flux  pour  assurer  le  respect  des  gestes  barrières  et notamment la distance physique d’un mètre entre chaque personne;

> accueil téléphonique renforcéà la place de l’accueil physique;3.organisation  d’un  suivi  à  distance  pour  les  rendez-vousindividuels,par téléphone, courriel

> Maintenir le fonctionnement des services de soutien économique aux entreprises.

Donc oui, je pense que majoritairement les mairies ont à minima des services d'accueil téléphonique et quelques services au public en fonctionnement (état civil mais aussi CCAS par exemple et aides !)

**Comment by PanierAvide** [comment]
Les mairies ont été ajoutées, ce sera dispo dans environ 1h.

**Comment by PanierAvide** [comment]
Pour les offices du tourisme, continuent-ils d'avoir une activité à destination du public "pertinente" durant le confinement ? Parce que niveau tourisme en ce moment ça me paraît un peu compliqué... Mais si des infos à la population sont fournies, ou que des services temporaires sont proposés et pertinents, pourquoi pas.

**Comment by vinber** [comment]
ils connaissent souvent trés bien le territoire et tous les commerces, donc des initiatives de cartographie partent d'eux (j'ai certainement un biais de lecture). Dans les régions touristiques ceux sont, j'ai l'impression, des interlocuteurs pour beaucoup de services et commerces.

**Comment by PanierAvide** [comment]
Donc il faut les mettre dans la boucle de ce que l'on fait (mais ça tu le fais déjà :smile: ), mais pas forcément les afficher en tant que telle sur "ça reste ouvert" ?

**Comment by vinber** [comment]
sur la base de si tag covid19 alors affichée c'est déja bien

**Comment by PanierAvide** [comment]
Je suis parti sur cette proposition, les offices du tourisme qui ont un tag covid19 sont affichés avec le bon libellé et une icône appropriée. Ce sera visible dans ~1h.
