### ISSUE TITLE
Ajouter un lien à l'attention des mairies sur la page d'accueil

### ISSUE THREAD

**Issue by overflorian** [osmontrouge/caresteouvert#98]
Je suggère le wording "Mairies"
l'URL : https://blog.caresteouvert.fr/un-outil-de-communication-des-mairies/

**Comment by PanierAvide** [comment]
Sur l'article, la première image est cassée. Et sinon on peut suggérer d'embarquer une iframe sur leur page ?

**Comment by PanierAvide** [comment]
Et accessoirement on commence à avoir beaucoup de lien sur le panneau de gauche, on aurait moyen d'améliorer ça ? (ou pas si c'est pas nécessaire)

**Comment by overflorian** [comment]
iframe rajouté, je ne vois pas l'image cassée (est-ce encore le cas maitenant ?)
je travaille avec le graphiste en ce moment-même à l'amélioration du bandeau

**Comment by PanierAvide** [comment]
C'est moi, bloqueur de pub avec l'image 'decor-facebook' il aime pas donc il affiche le symbole d'image cassée...

**Comment by PanierAvide** [comment]
Intégré

**Comment by overflorian** [comment]
merci
